photon: nars.entity.Item Class Reference
nars.entity.Item Class Reference abstract
An item is an object that can be put into a Bag, to participate in the resource competition of the system.
Public Member Functions
String getKey ()
The key of the Item, unique in a Bag.
BudgetValue getBudget ()
The budget of the Item, consisting of 3 numbers.
float getPriority ()
Get priority value.
void setPriority (float v)
Set priority value.
float getDurability ()
Get durability value.
void setDurability (float v)
Set durability value.
float getQuality ()
Get quality value.
void setQuality (float v)
Set quality value.
String toString ()
Return a String representation of the Item.
void setKey (String key)
Static Public Member Functions
static void incPriority (BudgetValue budget, float v)
Increase priority value.
static void decPriority (BudgetValue budget, float v)
Decrease priority value.
static void incDurability (BudgetValue budget, float v)
Increase durability value.
static void decDurability (BudgetValue budget, float v)
Decrease durability value.
static void merge (BudgetValue budget, Item that)
Merge with another Item with identical key.
static String toStringBrief (BudgetValue budget, String key)
Return a String representation of the Item after simplification.
static String toStringLong (Item item)
Protected Member Functions
Item ()
The default constructor.
Item (String key)
Constructor with default budget.
Item (String key, BudgetValue budget)
Constructor with initial budget.
void setBudget (BudgetValue budget)
Constructor with initial budget.
Private Attributes
String key
BudgetValue budget
Detailed Description
An item is an object that can be put into a Bag, to participate in the resource competition of the system.
It has a key and a budget. Cannot be cloned
Definition at line 31 of file Item.java.
Constructor & Destructor Documentation
Item() [1/3]
nars.entity.Item.Item () protected
The default constructor.
Definition at line 39 of file Item.java.
 {}
Item() [2/3]
nars.entity.Item.Item (String key) protected
Constructor with default budget.
Parameters
key The key value
Definition at line 45 of file Item.java.
References nars.entity.Item.setBudget(), and nars.entity.Item.setKey().
{
         this.setKey(key);
         this.setBudget(new BudgetValue());
      }
Item() [3/3]
nars.entity.Item.Item (String key, BudgetValue budget) protected
Constructor with initial budget.
Parameters
key The key value
budget The initial budget
Definition at line 55 of file Item.java.
References nars.entity.Item.budget, nars.entity.Item.setBudget(), and nars.entity.Item.setKey().
{
         this.setKey(key);
         this.setBudget(new BudgetValue(budget));  // clone, not assignment
     }
Member Function Documentation
decDurability()
static void nars.entity.Item.decDurability (BudgetValue budget, float v) static
Decrease durability value.
Parameters
budget
v The amount of decrease
Definition at line 148 of file Item.java.
References nars.entity.Item.budget, and nars.entity.BudgetValue.decDurability().
Referenced by nars.inference.LocalRules.revise().
{
         budget.decDurability(v);
     }
decPriority()
static void nars.entity.Item.decPriority (BudgetValue budget, float v) static
Decrease priority value.
Parameters
budget
v The amount of decrease
Definition at line 114 of file Item.java.
References nars.entity.Item.budget, and nars.entity.BudgetValue.decPriority().
Referenced by nars.inference.LocalRules.revise().
{
         budget.decPriority(v);
     }
getBudget()
BudgetValue nars.entity.Item.getBudget ()
The budget of the Item, consisting of 3 numbers.
Get BudgetValue
Returns
Current BudgetValue
Definition at line 80 of file Item.java.
References nars.entity.Item.budget.
Referenced by nars.storage.Memory.activatedTask(), nars.inference.BudgetFunctions.budgetInference(), nars.storage.Memory.derivedTask(), nars.entity.Concept.directProcess(), nars.entity.Item.getDurability(), nars.entity.Item.getPriority(), nars.entity.Item.getQuality(), nars.storage.Memory.inputTask(), nars.entity.Concept.insertTaskLink(), nars.entity.Concept.linkToTask(), nars.entity.Task.merge(), nars.entity.Item.merge(), nars.entity.Concept.processJudgment(), nars.inference.LocalRules.revise(), nars.entity.Item.setDurability(), nars.entity.Item.setPriority(), nars.entity.Item.setQuality(), nars.inference.LocalRules.solutionEval(), nars.entity.Item.toString(), nars.entity.Task.toString(), nars.entity.Concept.toString(), and nars.entity.Concept.toStringLong().
{
         return budget;
     }
getDurability()
float nars.entity.Item.getDurability ()
Get durability value.
Returns
Current durability value
Definition at line 122 of file Item.java.
References nars.entity.Item.getBudget(), and nars.entity.BudgetValue.getDurability().
Referenced by nars.inference.BudgetFunctions.activate(), nars.inference.BudgetFunctions.budgetInference(), nars.inference.LocalRules.revise(), nars.inference.LocalRules.solutionEval(), and nars.inference.BudgetFunctions.update().
{
         return getBudget().getDurability();
     }
getKey()
String nars.entity.Item.getKey ()
The key of the Item, unique in a Bag.
Get the current key
Returns
Current key value
Definition at line 72 of file Item.java.
References nars.entity.Item.key.
Referenced by nars.storage.Memory.activateConcept(), nars.entity.TaskLink.novel(), nars.entity.TermLink.setKey(), nars.entity.TaskLink.TaskLink(), nars.entity.Item.toString(), nars.entity.Task.toString(), nars.entity.Concept.toString(), and nars.entity.Concept.toStringLong().
{
         return key;
     }
getPriority()
float nars.entity.Item.getPriority ()
Get priority value.
Returns
Current priority value
Definition at line 88 of file Item.java.
References nars.entity.Item.getBudget(), and nars.entity.BudgetValue.getPriority().
Referenced by nars.inference.BudgetFunctions.activate(), nars.inference.BudgetFunctions.budgetInference(), nars.inference.LocalRules.revise(), nars.inference.LocalRules.solutionEval(), and nars.inference.BudgetFunctions.update().
{
         return getBudget().getPriority();
     }
getQuality()
float nars.entity.Item.getQuality ()
Get quality value.
Returns
The quality value
Definition at line 156 of file Item.java.
References nars.entity.Item.getBudget(), and nars.entity.BudgetValue.getQuality().
{
         return getBudget().getQuality();
     }
incDurability()
static void nars.entity.Item.incDurability (BudgetValue budget, float v) static
Increase durability value.
Parameters
budget
v The amount of increase
Definition at line 139 of file Item.java.
References nars.entity.Item.budget, and nars.entity.BudgetValue.incDurability().
{
         budget.incDurability(v);
     }
incPriority()
static void nars.entity.Item.incPriority (BudgetValue budget, float v) static
Increase priority value.
Parameters
budget
v The amount of increase
Definition at line 105 of file Item.java.
References nars.entity.Item.budget, and nars.entity.BudgetValue.incPriority().
Referenced by nars.inference.BudgetFunctions.budgetInference(), and nars.inference.LocalRules.solutionEval().
{
         budget.incPriority(v);
     }
merge()
static void nars.entity.Item.merge (BudgetValue budget, Item that) static
Merge with another Item with identical key.
Parameters
budget
that The Item to be merged
Definition at line 173 of file Item.java.
References nars.entity.Item.budget, nars.entity.Item.getBudget(), and nars.entity.BudgetValue.merge().
Referenced by nars.entity.Task.merge(), and nars.storage.Bag< Concept >.putIn().
{
         budget.merge(that.getBudget());
     }
setBudget()
void nars.entity.Item.setBudget (BudgetValue budget) protected
Constructor with initial budget.
Parameters
budget The initial budget
Definition at line 64 of file Item.java.
References nars.entity.Item.budget.
Referenced by nars.entity.Item.Item().
{
         this.budget = budget;
     }
setDurability()
void nars.entity.Item.setDurability (float v)
Set durability value.
Parameters
v The new durability value
Definition at line 130 of file Item.java.
References nars.entity.Item.getBudget(), and nars.entity.BudgetValue.setDurability().
Referenced by nars.inference.BudgetFunctions.activate().
{
         getBudget().setDurability(v);
     }
setKey()
void nars.entity.Item.setKey (String key)
Definition at line 200 of file Item.java.
References nars.entity.Item.key.
Referenced by nars.entity.Item.Item(), and nars.entity.Task.Task().
{
         this.key = key;
     }
setPriority()
void nars.entity.Item.setPriority (float v)
Set priority value.
Parameters
v Set a new priority value
Definition at line 96 of file Item.java.
References nars.entity.Item.getBudget(), and nars.entity.BudgetValue.setPriority().
Referenced by nars.inference.BudgetFunctions.activate(), and nars.inference.LocalRules.solutionEval().
{
         getBudget().setPriority(v);
     }
setQuality()
void nars.entity.Item.setQuality (float v)
Set quality value.
Parameters
v The new quality value
Definition at line 164 of file Item.java.
References nars.entity.Item.getBudget(), and nars.entity.BudgetValue.setQuality().
Referenced by nars.inference.BudgetFunctions.activate().
{
         getBudget().setQuality(v);
     }
toString()
String nars.entity.Item.toString ()
Return a String representation of the Item.
Returns
The String representation of the full content
Definition at line 182 of file Item.java.
References nars.entity.Item.getBudget(), and nars.entity.Item.getKey().
Referenced by nars.entity.Item.toStringLong().
{
         return getBudget() + " " + getKey();
     }
toStringBrief()
static String nars.entity.Item.toStringBrief (BudgetValue budget, String key) static
Return a String representation of the Item after simplification.
Returns
A simplified String representation of the content
Parameters
budget
key
Definition at line 192 of file Item.java.
References nars.entity.Item.budget, nars.entity.Item.key, and nars.entity.BudgetValue.toStringBrief().
Referenced by nars.entity.Task.toString(), nars.storage.Bag< Concept >.toString(), and nars.entity.Concept.toStringLong().
{
         return budget.toStringBrief() + " " + key;
     }
toStringLong()
static String nars.entity.Item.toStringLong (Item item) static
Definition at line 196 of file Item.java.
References nars.entity.Item.toString().
Referenced by nars.storage.Bag< Concept >.toStringLong(), and nars.storage.Memory.toStringLongIfNotNull().
{
         return item.toString();
     }
Member Data Documentation
budget
BudgetValue nars.entity.Item.budget private
Definition at line 34 of file Item.java.
Referenced by nars.entity.Item.decDurability(), nars.entity.Item.decPriority(), nars.entity.Item.getBudget(), nars.entity.Item.incDurability(), nars.entity.Item.incPriority(), nars.entity.Item.Item(), nars.entity.Item.merge(), nars.entity.Item.setBudget(), and nars.entity.Item.toStringBrief().
key
String nars.entity.Item.key private
Definition at line 33 of file Item.java.
Referenced by nars.entity.Item.getKey(), nars.entity.Item.setKey(), and nars.entity.Item.toStringBrief().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/entity/Item.java