photon: nars.storage.ReasonerBatch Class Reference
nars.storage.ReasonerBatch Class Reference
Created by jim on 1/12/16.
Public Member Functions
ReasonerBatch ()
Memory getMemory ()
The memory of the reasoner.
boolean isFinishedInputs ()
determines the end of NARSBatch program (set but not accessed in this class)
String toString ()
long getTimer ()
System clock - number of cycles since last output.
AtomicInteger getSilenceValue ()
long getClock ()
System clock, relatively defined to guarantee the repeatability of behaviors.
void setClock (long clock)
String getName ()
The name of the reasoner.
void setName (String name)
void setMemory (Memory memory)
Collection< InputChannel > getInputChannels ()
The input channels of the reasoner.
void setInputChannels (List< InputChannel > inputChannels)
Collection< OutputChannel > getOutputChannels ()
The output channels of the reasoner.
void setOutputChannels (List< OutputChannel > outputChannels)
boolean isRunning ()
Flag for running continuously.
void setRunning (boolean running)
int getWalkingSteps ()
The remaining number of steps to be carried out (walk mode)
void setWalkingSteps (int walkingSteps)
void setFinishedInputs (boolean finishedInputs)
Static Public Member Functions
static Task parseExperience (StringBuffer buffer, Memory memory, long time)
Parse a line of input experience.
static void reset (ReasonerBatch reasonerBatch)
Reset the system with an empty memory and reset clock.
static boolean isDEBUG ()
global DEBUG print switch
static void addInputChannel (ReasonerBatch reasonerBatch, InputChannel channel)
static void removeInputChannel (ReasonerBatch reasonerBatch, InputChannel channel)
static void addOutputChannel (ReasonerBatch reasonerBatch, OutputChannel channel)
static void removeOutputChannel (ReasonerBatch reasonerBatch, OutputChannel channel)
static long getTime (long clock)
Get the current time from the clock Called in nars.entity.Stamp.
static void run (ReasonerBatch reasonerBatch)
Start the inference process.
static void walk (ReasonerBatch reasonerBatch, int n)
Will carry the inference process for a certain number of steps.
static void stop (ReasonerBatch reasonerBatch)
Stop the inference process.
static void tick (ReasonerBatch reasonerBatch)
A clock tick.
static void doTick (ReasonerBatch reasonerBatch)
static void textInputLine (ReasonerBatch reasonerBatch, String text)
To process a line of input text.
static AtomicInteger getSilenceValue (AtomicInteger silenceValue)
Report Silence Level.
static long updateTimer (ReasonerBatch reasonerBatch)
To get the timer value and then to reset it.
static void initTimer (ReasonerBatch reasonerBatch)
static void tickTimer (ReasonerBatch reasonerBatch)
Update timer.
Private Member Functions
void setTimer (long timer)
Static Private Member Functions
static String asString (ReasonerBatch reasonerBatch)
Private Attributes
String name
Memory memory
List< InputChannel > inputChannels
List< OutputChannel > outputChannels
long clock
boolean running
int walkingSteps
boolean finishedInputs
long timer
final AtomicInteger silenceValue = new AtomicInteger(Parameters.SILENT_LEVEL)
Static Private Attributes
static final boolean DEBUG = false
Detailed Description
Created by jim on 1/12/16.
Definition at line 18 of file ReasonerBatch.java.
Constructor & Destructor Documentation
ReasonerBatch()
nars.storage.ReasonerBatch.ReasonerBatch ()
Definition at line 32 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.setInputChannels(), nars.storage.ReasonerBatch.setMemory(), and nars.storage.ReasonerBatch.setOutputChannels().
{
         setMemory(new Memory(this));
         setInputChannels(new ArrayList<InputChannel>());
         setOutputChannels(new ArrayList<OutputChannel>());
     }
Member Function Documentation
addInputChannel()
static void nars.storage.ReasonerBatch.addInputChannel (ReasonerBatch reasonerBatch, InputChannel channel) static
Definition at line 94 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.getInputChannels().
Referenced by nars.io.ExperienceReader.openLoadFile(), and nars.io.ExperienceReader.setBufferedReader().
{
         reasonerBatch.getInputChannels().add(channel);
     }
addOutputChannel()
static void nars.storage.ReasonerBatch.addOutputChannel (ReasonerBatch reasonerBatch, OutputChannel channel) static
Definition at line 102 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.getOutputChannels().
Referenced by nars.storage.NARSBatch.init(), and nars.io.ExperienceWriter.openSaveFile().
{
         reasonerBatch.getOutputChannels().add(channel);
     }
asString()
static String nars.storage.ReasonerBatch.asString (ReasonerBatch reasonerBatch) static private
Definition at line 243 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.getMemory(), and nars.storage.Memory.toString().
Referenced by nars.storage.ReasonerBatch.toString().
{
         return Memory.toString(reasonerBatch.getMemory());
     }
doTick()
static void nars.storage.ReasonerBatch.doTick (ReasonerBatch reasonerBatch) static
Definition at line 158 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.getClock(), nars.storage.Memory.getExportStrings(), nars.storage.ReasonerBatch.getInputChannels(), nars.storage.ReasonerBatch.getMemory(), nars.storage.ReasonerBatch.getOutputChannels(), nars.storage.ReasonerBatch.getTimer(), nars.storage.ReasonerBatch.getWalkingSteps(), nars.storage.ReasonerBatch.isDEBUG(), nars.storage.ReasonerBatch.isFinishedInputs(), nars.storage.ReasonerBatch.isRunning(), nars.storage.ReasonerBatch.setClock(), nars.storage.ReasonerBatch.setFinishedInputs(), nars.storage.ReasonerBatch.setWalkingSteps(), nars.storage.ReasonerBatch.tickTimer(), and nars.storage.Memory.workCycle().
Referenced by nars.storage.ReasonerBatch.tick().
{
         if (isDEBUG() && (reasonerBatch.isRunning() || 0 < reasonerBatch.getWalkingSteps() || !reasonerBatch.isFinishedInputs())) {
             System.out.println("// doTick: "
                     + "walkingSteps " + reasonerBatch.getWalkingSteps()
                     + ", clock " + reasonerBatch.getClock()
                     + ", getTimer " + reasonerBatch.getTimer()
                     + "\n//    memory.getExportStrings() " + reasonerBatch.getMemory().getExportStrings()
             );
             System.out.flush();
         }
         switch (reasonerBatch.getWalkingSteps()) {
             case 0:
                 boolean reasonerShouldRun = false;
                 for (InputChannel channelIn : reasonerBatch.getInputChannels()) {
                     reasonerShouldRun = reasonerShouldRun ||
                             channelIn.nextInput();
                 }
                 reasonerBatch.setFinishedInputs(!reasonerShouldRun);
                 break;
         }
         // forward to output Channels
         List<String> output = reasonerBatch.getMemory().getExportStrings();
         if (!output.isEmpty()) {
             for (OutputChannel channelOut : reasonerBatch.getOutputChannels()) {
                 channelOut.nextOutput(output);
             }
             output.clear();    // this will trigger display the current value of timer in Memory.report()
         }
         if (reasonerBatch.isRunning() || 0 < reasonerBatch.getWalkingSteps()) {
             reasonerBatch.setClock(reasonerBatch.getClock() + 1);
             ReasonerBatch.tickTimer(reasonerBatch);
             Memory.workCycle(reasonerBatch.getMemory(), reasonerBatch.getClock());
             if (0 < reasonerBatch.getWalkingSteps()) {
                 reasonerBatch.setWalkingSteps(reasonerBatch.getWalkingSteps() - 1);
             }
         }
     }
getClock()
long nars.storage.ReasonerBatch.getClock ()
System clock, relatively defined to guarantee the repeatability of behaviors.
Definition at line 298 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.clock.
Referenced by nars.storage.ReasonerBatch.doTick(), nars.storage.Memory.getTime(), nars.storage.Memory.report(), nars.storage.NARSBatch.run(), and nars.storage.ReasonerBatch.textInputLine().
{
         return clock;
     }
getInputChannels()
Collection<InputChannel> nars.storage.ReasonerBatch.getInputChannels ()
The input channels of the reasoner.
Definition at line 324 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.inputChannels.
Referenced by nars.storage.ReasonerBatch.addInputChannel(), nars.storage.ReasonerBatch.doTick(), and nars.storage.ReasonerBatch.removeInputChannel().
{
         return inputChannels;
     }
getMemory()
Memory nars.storage.ReasonerBatch.getMemory ()
The memory of the reasoner.
Definition at line 90 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.memory.
Referenced by nars.storage.ReasonerBatch.asString(), nars.storage.ReasonerBatch.doTick(), nars.storage.ReasonerBatch.reset(), and nars.storage.ReasonerBatch.textInputLine().
{
         return memory;
     }
getName()
String nars.storage.ReasonerBatch.getName ()
The name of the reasoner.
Definition at line 309 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.name.
{
         return name;
     }
getOutputChannels()
Collection<OutputChannel> nars.storage.ReasonerBatch.getOutputChannels ()
The output channels of the reasoner.
Definition at line 335 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.outputChannels.
Referenced by nars.storage.ReasonerBatch.addOutputChannel(), nars.storage.ReasonerBatch.doTick(), and nars.storage.ReasonerBatch.removeOutputChannel().
{
         return outputChannels;
     }
getSilenceValue() [1/2]
static AtomicInteger nars.storage.ReasonerBatch.getSilenceValue (AtomicInteger silenceValue) static
Report Silence Level.
Parameters
silenceValue
Definition at line 252 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.silenceValue.
Referenced by nars.storage.Memory.activatedTask(), nars.main_nogui.CommandLineParameters.decode(), and nars.storage.Memory.derivedTask().
{
         return silenceValue;
     }
getSilenceValue() [2/2]
AtomicInteger nars.storage.ReasonerBatch.getSilenceValue ()
Definition at line 291 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.silenceValue.
{
         return silenceValue;
     }
getTime()
static long nars.storage.ReasonerBatch.getTime (long clock) static
Get the current time from the clock Called in nars.entity.Stamp.
Parameters
clock
Returns
The current time
Definition at line 117 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.clock.
Referenced by nars.storage.Memory.getTime(), nars.storage.Memory.report(), and nars.storage.NARSBatch.run().
{
         return clock;
     }
getTimer()
long nars.storage.ReasonerBatch.getTimer ()
System clock - number of cycles since last output.
Definition at line 283 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.timer.
Referenced by nars.storage.ReasonerBatch.doTick(), nars.storage.Memory.report(), nars.storage.ReasonerBatch.tickTimer(), and nars.storage.ReasonerBatch.updateTimer().
{
         return timer;
     }
getWalkingSteps()
int nars.storage.ReasonerBatch.getWalkingSteps ()
The remaining number of steps to be carried out (walk mode)
Definition at line 357 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.walkingSteps.
Referenced by nars.storage.ReasonerBatch.doTick().
{
         return walkingSteps;
     }
initTimer()
static void nars.storage.ReasonerBatch.initTimer (ReasonerBatch reasonerBatch) static
Definition at line 268 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.setTimer().
Referenced by nars.storage.Memory.init(), and nars.storage.ReasonerBatch.updateTimer().
{
         reasonerBatch.setTimer(0);
     }
isDEBUG()
static boolean nars.storage.ReasonerBatch.isDEBUG () static
global DEBUG print switch
Definition at line 83 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.DEBUG.
Referenced by nars.storage.ReasonerBatch.doTick(), and nars.storage.Memory.report().
{
         return DEBUG;
     }
isFinishedInputs()
boolean nars.storage.ReasonerBatch.isFinishedInputs ()
determines the end of NARSBatch program (set but not accessed in this class)
determines the end of NARSBatch program
Definition at line 202 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.finishedInputs.
Referenced by nars.storage.ReasonerBatch.doTick(), and nars.storage.NARSBatch.run().
{
         return finishedInputs;
     }
isRunning()
boolean nars.storage.ReasonerBatch.isRunning ()
Flag for running continuously.
Definition at line 346 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.running.
Referenced by nars.storage.ReasonerBatch.doTick().
{
         return running;
     }
parseExperience()
static Task nars.storage.ReasonerBatch.parseExperience (StringBuffer buffer, Memory memory, long time) static
Parse a line of input experience.
called from ExperienceIO.loadLine
Parameters
buffer The line to be parsed
memory Reference to the memory
time The current time
Returns
An experienced task
Definition at line 48 of file ReasonerBatch.java.
References nars.io.Symbols.INPUT_LINE, nars.storage.ReasonerBatch.memory, nars.io.Symbols.OUTPUT_LINE, nars.io.StringParser.parseTask(), nars.io.Symbols.PREFIX_MARK, nars.io.Symbols.STAMP_CLOSER, and nars.io.Symbols.STAMP_OPENER.
Referenced by nars.storage.ReasonerBatch.textInputLine().
{
         int i = buffer.indexOf(Symbols.PREFIX_MARK + "");
         if (0 < i) {
             String prefix = buffer.substring(0, i).trim();
             if (prefix.equals(Symbols.OUTPUT_LINE)) {
                 return null;
             } else if (prefix.equals(Symbols.INPUT_LINE)) {
                 buffer.delete(0, i + 1);
             }
         }
         char c = buffer.charAt(buffer.length() - 1);
         if (Symbols.STAMP_CLOSER == c) {
             int j = buffer.lastIndexOf(Symbols.STAMP_OPENER + "");
             buffer.delete(j - 1, buffer.length());
         }
         return StringParser.parseTask(buffer.toString().trim(), memory, time);
     }
removeInputChannel()
static void nars.storage.ReasonerBatch.removeInputChannel (ReasonerBatch reasonerBatch, InputChannel channel) static
Definition at line 98 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.getInputChannels().
Referenced by nars.io.ExperienceReader.closeLoadFile().
{
         reasonerBatch.getInputChannels().remove(channel);
     }
removeOutputChannel()
static void nars.storage.ReasonerBatch.removeOutputChannel (ReasonerBatch reasonerBatch, OutputChannel channel) static
Definition at line 106 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.getOutputChannels().
Referenced by nars.io.ExperienceWriter.closeSaveFile().
{
         reasonerBatch.getOutputChannels().remove(channel);
     }
reset()
static void nars.storage.ReasonerBatch.reset (ReasonerBatch reasonerBatch) static
Reset the system with an empty memory and reset clock.
Called locally and from MainWindow.
Parameters
reasonerBatch
Definition at line 71 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.getMemory(), nars.storage.Memory.init(), nars.entity.Stamp.init(), nars.storage.ReasonerBatch.setClock(), nars.storage.ReasonerBatch.setRunning(), and nars.storage.ReasonerBatch.setWalkingSteps().
Referenced by nars.storage.ReasonerBatch.textInputLine().
{
         reasonerBatch.setRunning(false);
         reasonerBatch.setWalkingSteps(0);
         reasonerBatch.setClock(0);
         Memory.init(reasonerBatch.getMemory());
         Stamp.init();
         //      timer = 0;
     }
run()
static void nars.storage.ReasonerBatch.run (ReasonerBatch reasonerBatch) static
Start the inference process.
Parameters
reasonerBatch
Definition at line 126 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.setRunning().
{
         reasonerBatch.setRunning(true);
     }
setClock()
void nars.storage.ReasonerBatch.setClock (long clock)
Definition at line 302 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.clock.
Referenced by nars.storage.ReasonerBatch.doTick(), and nars.storage.ReasonerBatch.reset().
{
         this.clock = clock;
     }
setFinishedInputs()
void nars.storage.ReasonerBatch.setFinishedInputs (boolean finishedInputs)
Definition at line 365 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.finishedInputs.
Referenced by nars.storage.ReasonerBatch.doTick().
{
         this.finishedInputs = finishedInputs;
     }
setInputChannels()
void nars.storage.ReasonerBatch.setInputChannels (List< InputChannel > inputChannels)
Definition at line 328 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.inputChannels.
Referenced by nars.storage.ReasonerBatch.ReasonerBatch().
{
         this.inputChannels = inputChannels;
     }
setMemory()
void nars.storage.ReasonerBatch.setMemory (Memory memory)
Definition at line 317 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.memory.
Referenced by nars.storage.ReasonerBatch.ReasonerBatch().
{
         this.memory = memory;
     }
setName()
void nars.storage.ReasonerBatch.setName (String name)
Definition at line 313 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.name.
{
         this.name = name;
     }
setOutputChannels()
void nars.storage.ReasonerBatch.setOutputChannels (List< OutputChannel > outputChannels)
Definition at line 339 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.outputChannels.
Referenced by nars.storage.ReasonerBatch.ReasonerBatch().
{
         this.outputChannels = outputChannels;
     }
setRunning()
void nars.storage.ReasonerBatch.setRunning (boolean running)
Definition at line 350 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.running.
Referenced by nars.storage.ReasonerBatch.reset(), nars.storage.ReasonerBatch.run(), and nars.storage.ReasonerBatch.stop().
{
         this.running = running;
     }
setTimer()
void nars.storage.ReasonerBatch.setTimer (long timer) private
Definition at line 287 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.timer.
Referenced by nars.storage.ReasonerBatch.initTimer(), and nars.storage.ReasonerBatch.tickTimer().
{
         this.timer = timer;
     }
setWalkingSteps()
void nars.storage.ReasonerBatch.setWalkingSteps (int walkingSteps)
Definition at line 361 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.walkingSteps.
Referenced by nars.storage.ReasonerBatch.doTick(), nars.storage.ReasonerBatch.reset(), and nars.storage.ReasonerBatch.walk().
{
         this.walkingSteps = walkingSteps;
     }
stop()
static void nars.storage.ReasonerBatch.stop (ReasonerBatch reasonerBatch) static
Stop the inference process.
Parameters
reasonerBatch
Definition at line 145 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.setRunning().
{
         reasonerBatch.setRunning(false);
     }
textInputLine()
static void nars.storage.ReasonerBatch.textInputLine (ReasonerBatch reasonerBatch, String text) static
To process a line of input text.
Parameters
reasonerBatch
text
Definition at line 212 of file ReasonerBatch.java.
References nars.io.Symbols.COMMENT_MARK, nars.storage.ReasonerBatch.getClock(), nars.storage.Memory.getExportStrings(), nars.storage.ReasonerBatch.getMemory(), nars.storage.Memory.inputTask(), nars.storage.ReasonerBatch.parseExperience(), nars.storage.ReasonerBatch.reset(), nars.io.Symbols.RESET_MARK, and nars.storage.ReasonerBatch.walk().
Referenced by nars.io.ExperienceReader.nextInput().
{
         if (!text.isEmpty()) {
             char c = text.charAt(0);
             switch (c) {
                 case Symbols.RESET_MARK:
                     reset(reasonerBatch);
                     reasonerBatch.getMemory().getExportStrings().add(text);
                     break;
                 case Symbols.COMMENT_MARK:
                     return;
                 default:
                     // read NARS language or an integer : TODO duplicated code
                     try {
                         int i = Integer.parseInt(text);
                         walk(reasonerBatch, i);
                     } catch (NumberFormatException e) {
                         Task task = parseExperience(new StringBuffer(text), reasonerBatch.getMemory(), reasonerBatch.getClock());
                         if (null != task) {
                             Memory.inputTask(reasonerBatch.getMemory(), task);
                         }
                     }
                     break;
             }
         }
     }
tick()
static void nars.storage.ReasonerBatch.tick (ReasonerBatch reasonerBatch) static
A clock tick.
Run one working workCycle or read input. Called from NARS only.
Parameters
reasonerBatch
Definition at line 154 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.doTick().
Referenced by nars.storage.NARSBatch.run().
{
         doTick(reasonerBatch);
     }
tickTimer()
static void nars.storage.ReasonerBatch.tickTimer (ReasonerBatch reasonerBatch) static
Update timer.
Parameters
reasonerBatch
Definition at line 276 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.getTimer(), and nars.storage.ReasonerBatch.setTimer().
Referenced by nars.storage.ReasonerBatch.doTick().
{
         reasonerBatch.setTimer(reasonerBatch.getTimer() + 1);
     }
toString()
String nars.storage.ReasonerBatch.toString ()
Definition at line 239 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.asString().
{
         return asString(this);
     }
updateTimer()
static long nars.storage.ReasonerBatch.updateTimer (ReasonerBatch reasonerBatch) static
To get the timer value and then to reset it.
Returns
The previous timer value
Parameters
reasonerBatch
Definition at line 262 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.getTimer(), and nars.storage.ReasonerBatch.initTimer().
Referenced by nars.storage.Memory.report().
{
         long i = reasonerBatch.getTimer();
         initTimer(reasonerBatch);
         return i;
     }
walk()
static void nars.storage.ReasonerBatch.walk (ReasonerBatch reasonerBatch, int n) static
Will carry the inference process for a certain number of steps.
Parameters
reasonerBatch
n The number of inference steps to be carried
Definition at line 136 of file ReasonerBatch.java.
References nars.storage.ReasonerBatch.setWalkingSteps().
Referenced by nars.io.ExperienceReader.nextInput(), and nars.storage.ReasonerBatch.textInputLine().
{
         reasonerBatch.setWalkingSteps(n);
     }
Member Data Documentation
clock
long nars.storage.ReasonerBatch.clock private
Definition at line 24 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.getClock(), nars.storage.ReasonerBatch.getTime(), and nars.storage.ReasonerBatch.setClock().
DEBUG
final boolean nars.storage.ReasonerBatch.DEBUG = false static private
Definition at line 19 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.isDEBUG().
finishedInputs
boolean nars.storage.ReasonerBatch.finishedInputs private
Definition at line 27 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.isFinishedInputs(), and nars.storage.ReasonerBatch.setFinishedInputs().
inputChannels
List<InputChannel> nars.storage.ReasonerBatch.inputChannels private
Definition at line 22 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.getInputChannels(), and nars.storage.ReasonerBatch.setInputChannels().
memory
Memory nars.storage.ReasonerBatch.memory private
Definition at line 21 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.getMemory(), nars.storage.ReasonerBatch.parseExperience(), and nars.storage.ReasonerBatch.setMemory().
name
String nars.storage.ReasonerBatch.name private
Definition at line 20 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.getName(), and nars.storage.ReasonerBatch.setName().
outputChannels
List<OutputChannel> nars.storage.ReasonerBatch.outputChannels private
Definition at line 23 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.getOutputChannels(), and nars.storage.ReasonerBatch.setOutputChannels().
running
boolean nars.storage.ReasonerBatch.running private
Definition at line 25 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.isRunning(), and nars.storage.ReasonerBatch.setRunning().
silenceValue
final AtomicInteger nars.storage.ReasonerBatch.silenceValue = new AtomicInteger(Parameters.SILENT_LEVEL) private
Definition at line 30 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.getSilenceValue().
timer
long nars.storage.ReasonerBatch.timer private
Definition at line 28 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.getTimer(), and nars.storage.ReasonerBatch.setTimer().
walkingSteps
int nars.storage.ReasonerBatch.walkingSteps private
Definition at line 26 of file ReasonerBatch.java.
Referenced by nars.storage.ReasonerBatch.getWalkingSteps(), and nars.storage.ReasonerBatch.setWalkingSteps().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/storage/ReasonerBatch.java