photon: nars.entity.Task Class Reference
nars.entity.Task Class Reference
A task to be processed, consists of a Sentence and a BudgetValue.
Public Member Functions
Task (Sentence s, BudgetValue b)
Constructor for input task.
Task (Sentence s, BudgetValue b, Task parentTask, Sentence parentBelief)
Constructor for a derived task.
Task (Sentence s, BudgetValue b, Task parentTask, Sentence parentBelief, Sentence solution)
Constructor for an activated task.
Sentence getSentence ()
The sentence of the Task.
Term getContent ()
Directly get the content of the sentence.
void setContent (TermStruct $content$)
boolean getInput ()
void setInput (boolean $input$)
boolean getStructural ()
void setStructural (boolean $structural$)
long getCreationTime ()
Directly get the creation time of the sentence.
void setCreationTime (long $creationTime$)
boolean isInput ()
Check if a Task is a direct input.
boolean isStructural ()
Check if a Task is derived by a StructuralRule.
Sentence getBestSolution ()
For Question and Goal: best solution found so far.
void setBestSolution (Sentence judg)
Set the best-so-far solution for a Question or Goal, and report answer for input question.
Sentence getParentBelief ()
Belief from which the Task is derived, or null if derived from a theorem.
String toString ()
Get a String representation of the Task.
void setSentence (Sentence sentence)
Task getParentTask ()
Task from which the Task is derived, or null if input.
void setParentTask (Task parentTask)
void setParentBelief (Sentence parentBelief)
Public Member Functions inherited from nars.entity.Item
String getKey ()
The key of the Item, unique in a Bag.
BudgetValue getBudget ()
The budget of the Item, consisting of 3 numbers.
float getPriority ()
Get priority value.
void setPriority (float v)
Set priority value.
float getDurability ()
Get durability value.
void setDurability (float v)
Set durability value.
float getQuality ()
Get quality value.
void setQuality (float v)
Set quality value.
String toString ()
Return a String representation of the Item.
void setKey (String key)
Static Public Member Functions
static void merge (Task task, Item that)
Merge one Task into another.
Static Public Member Functions inherited from nars.entity.Item
static void incPriority (BudgetValue budget, float v)
Increase priority value.
static void decPriority (BudgetValue budget, float v)
Decrease priority value.
static void incDurability (BudgetValue budget, float v)
Increase durability value.
static void decDurability (BudgetValue budget, float v)
Decrease durability value.
static void merge (BudgetValue budget, Item that)
Merge with another Item with identical key.
static String toStringBrief (BudgetValue budget, String key)
Return a String representation of the Item after simplification.
static String toStringLong (Item item)
Private Attributes
Sentence sentence
Sentence parentBelief
Sentence bestSolution
Task parentTask
Additional Inherited Members
Protected Member Functions inherited from nars.entity.Item
Item ()
The default constructor.
Item (String key)
Constructor with default budget.
Item (String key, BudgetValue budget)
Constructor with initial budget.
void setBudget (BudgetValue budget)
Constructor with initial budget.
Detailed Description
A task to be processed, consists of a Sentence and a BudgetValue.
Definition at line 31 of file Task.java.
Constructor & Destructor Documentation
Task() [1/3]
nars.entity.Task.Task (Sentence s, BudgetValue b)
Constructor for input task.
Parameters
s The sentence
b The budget
Definition at line 43 of file Task.java.
References nars.entity.Task.getSentence(), nars.entity.Item.setKey(), nars.entity.Task.setSentence(), and nars.entity.Sentence.toKey().
{
         super(Sentence.toKey(s), b); // change to toKey()
         setSentence(s);
         setKey(Sentence.toKey(getSentence()));
     }
Task() [2/3]
nars.entity.Task.Task (Sentence s, BudgetValue b, Task parentTask, Sentence parentBelief)
Constructor for a derived task.
Parameters
s The sentence
b The budget
parentTask The task from which this new task is derived
parentBelief The belief from which this new task is derived
Definition at line 57 of file Task.java.
References nars.entity.Task.parentBelief, nars.entity.Task.parentTask, nars.entity.Task.setParentBelief(), and nars.entity.Task.setParentTask().
{
         this(s, b);
         setParentTask(parentTask);
         setParentBelief(parentBelief);
     }
Task() [3/3]
nars.entity.Task.Task (Sentence s, BudgetValue b, Task parentTask, Sentence parentBelief, Sentence solution)
Constructor for an activated task.
Parameters
s The sentence
b The budget
parentTask The task from which this new task is derived
parentBelief The belief from which this new task is derived
solution The belief to be used in future inference
Definition at line 72 of file Task.java.
References nars.entity.Task.parentBelief, nars.entity.Task.parentTask, and nars.entity.Task.setBestSolution().
{
         this(s, b, parentTask, parentBelief);
         setBestSolution(solution);
     }
Member Function Documentation
getBestSolution()
Sentence nars.entity.Task.getBestSolution ()
For Question and Goal: best solution found so far.
Get the best-so-far solution for a Question or Goal
Returns
The stored Sentence or null
Definition at line 181 of file Task.java.
References nars.entity.Task.bestSolution.
Referenced by nars.entity.Task.toString(), and nars.inference.LocalRules.trySolution().
{
         return bestSolution;
     }
getContent()
Term nars.entity.Task.getContent ()
Directly get the content of the sentence.
Returns
The content of the sentence
Definition at line 95 of file Task.java.
References nars.entity.Sentence.getContent(), and nars.entity.Task.getSentence().
Referenced by nars.inference.LocalRules.convertedJudgment(), nars.inference.LocalRules.convertRelation(), nars.inference.CompositionalRules.decomposeCompound(), nars.storage.Memory.immediateProcess(), nars.storage.Memory.processNewTask(), nars.inference.StructuralRules.structuralStatement(), and nars.inference.RuleTables.transformTask().
{
         return getSentence().getContent();
     }
getCreationTime()
long nars.entity.Task.getCreationTime ()
Directly get the creation time of the sentence.
Returns
The creation time of the sentence
Definition at line 128 of file Task.java.
References nars.entity.Stamp.getCreationTime(), nars.entity.Task.getSentence(), and nars.entity.Sentence.getStamp().
Referenced by nars.entity.Task.merge().
{
         return getSentence().getStamp().getCreationTime();
     }
getInput()
boolean nars.entity.Task.getInput ()
Definition at line 104 of file Task.java.
{
         return false;
     }
getParentBelief()
Sentence nars.entity.Task.getParentBelief ()
Belief from which the Task is derived, or null if derived from a theorem.
Get the parent belief of a task
Returns
The belief from which the task is derived
Definition at line 202 of file Task.java.
References nars.entity.Task.parentBelief.
Referenced by nars.entity.Task.isStructural(), nars.entity.Task.toString(), and nars.inference.LocalRules.trySolution().
{
         return parentBelief;
     }
getParentTask()
Task nars.entity.Task.getParentTask ()
Task from which the Task is derived, or null if input.
Definition at line 238 of file Task.java.
References nars.entity.Task.parentTask.
Referenced by nars.entity.Task.isInput(), nars.entity.Task.isStructural(), and nars.entity.Task.toString().
{
         return parentTask;
     }
getSentence()
Sentence nars.entity.Task.getSentence ()
The sentence of the Task.
Get the sentence
Returns
The sentence
Definition at line 85 of file Task.java.
References nars.entity.Task.sentence.
Referenced by nars.storage.Memory.activatedTask(), nars.inference.SyllogisticRules.analogy(), nars.inference.CompositionalRules.composeCompound(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.RuleTables.conditionalAbd(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.RuleTables.contraposition(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.decomposeStatement(), nars.storage.Memory.derivedTask(), nars.inference.RuleTables.detachmentWithVar(), nars.entity.Concept.directProcess(), nars.storage.Memory.doublePremiseTask(), nars.inference.RuleTables.elimiVarDep(), nars.inference.RuleTables.functionBeggingToBeAsync(), nars.entity.Concept.getBelief(), nars.entity.Task.getContent(), nars.entity.Task.getCreationTime(), nars.storage.Memory.inputTask(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.inference.LocalRules.match(), nars.inference.LocalRules.matchAsymSym(), nars.inference.LocalRules.matchReverse(), nars.entity.Concept.processJudgment(), nars.storage.Memory.processNewTask(), nars.entity.Concept.processQuestion(), nars.inference.RuleTables.reason(), nars.storage.Memory.singlePremiseTask(), nars.inference.LocalRules.solutionEval(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralCompound(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.RuleTables.syllogisms(), nars.entity.Task.Task(), nars.entity.TaskLink.toString(), nars.entity.Task.toString(), nars.inference.RuleTables.transformNegation(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.StructuralRules.transformProductImage(), nars.inference.RuleTables.transformSetRelation(), nars.inference.StructuralRules.transformSubjectPI(), nars.inference.LocalRules.trySolution(), and nars.inference.BudgetFunctions.update().
{
         return sentence;
     }
getStructural()
boolean nars.entity.Task.getStructural ()
Definition at line 113 of file Task.java.
{
         return false;
     }
isInput()
boolean nars.entity.Task.isInput ()
Check if a Task is a direct input.
Returns
Whether the Task is derived from another task
Definition at line 144 of file Task.java.
References nars.entity.Task.getParentTask().
Referenced by nars.storage.Memory.processNewTask(), and nars.inference.LocalRules.trySolution().
{
         return null == getParentTask();
     }
isStructural()
boolean nars.entity.Task.isStructural ()
Check if a Task is derived by a StructuralRule.
Returns
Whether the Task is derived by a StructuralRule
Definition at line 155 of file Task.java.
References nars.entity.Task.getParentBelief(), and nars.entity.Task.getParentTask().
Referenced by nars.inference.RuleTables.componentAndStatement(), nars.inference.RuleTables.compoundAndSelf(), nars.inference.RuleTables.compoundAndStatement(), and nars.inference.StructuralRules.structuralCompound().
{
         return null == getParentBelief() && null != getParentTask();
     }
merge()
static void nars.entity.Task.merge (Task task, Item that) static
Merge one Task into another.
Parameters
task
that The other Task
Definition at line 165 of file Task.java.
References nars.entity.Item.getBudget(), nars.entity.Task.getCreationTime(), and nars.entity.Item.merge().
{
         if (task.getCreationTime() >= ((TaskStruct) that).getCreationTime()) {
             merge(task.getBudget(), that);
         } else {
             Item.merge(that.getBudget(), task);
         }
     }
setBestSolution()
void nars.entity.Task.setBestSolution (Sentence judg)
Set the best-so-far solution for a Question or Goal, and report answer for input question.
Parameters
judg The solution to be remembered
Definition at line 191 of file Task.java.
References nars.entity.Task.bestSolution.
Referenced by nars.entity.Task.Task(), and nars.inference.LocalRules.trySolution().
{
         bestSolution = judg;
     }
setContent()
void nars.entity.Task.setContent (TermStruct $content$)
Definition at line 100 of file Task.java.
{
     }
setCreationTime()
void nars.entity.Task.setCreationTime (long $creationTime$)
Definition at line 133 of file Task.java.
{
     }
setInput()
void nars.entity.Task.setInput (boolean $input$)
Definition at line 109 of file Task.java.
{
     }
setParentBelief()
void nars.entity.Task.setParentBelief (Sentence parentBelief)
Definition at line 246 of file Task.java.
References nars.entity.Task.parentBelief.
Referenced by nars.entity.Task.Task().
{
         this.parentBelief = parentBelief;
     }
setParentTask()
void nars.entity.Task.setParentTask (Task parentTask)
Definition at line 242 of file Task.java.
References nars.entity.Task.parentTask.
Referenced by nars.entity.Task.Task().
{
         this.parentTask = parentTask;
     }
setSentence()
void nars.entity.Task.setSentence (Sentence sentence)
Definition at line 231 of file Task.java.
References nars.entity.Task.sentence.
Referenced by nars.entity.Task.Task().
{
         this.sentence = sentence;
     }
setStructural()
void nars.entity.Task.setStructural (boolean $structural$)
Definition at line 118 of file Task.java.
{
     }
toString()
String nars.entity.Task.toString ()
Get a String representation of the Task.
Returns
The Task as a String
Definition at line 212 of file Task.java.
References nars.entity.Task.getBestSolution(), nars.entity.Item.getBudget(), nars.entity.Item.getKey(), nars.entity.Task.getParentBelief(), nars.entity.Task.getParentTask(), nars.entity.Task.getSentence(), nars.entity.Item.toStringBrief(), and nars.entity.Sentence.toStringBrief().
{
         StringBuffer s = new StringBuffer();
         s.append(super.toString() + " ");
         s.append(getSentence().getStamp());
         if (null != getParentTask()) {
             s.append("  \n from task: " + Item.toStringBrief(getParentTask().getBudget(), getParentTask().getKey()));
             if (null != getParentBelief()) {
                 s.append("  \n from belief: " + Sentence.toStringBrief(getParentBelief()));
             }
         }
         if (null != getBestSolution()) {
             s.append("  \n solution: " + Sentence.toStringBrief(getBestSolution()));
         }
 //        s.append("\n>>>> end of Task");
         return s.toString();
     }
Member Data Documentation
bestSolution
Sentence nars.entity.Task.bestSolution private
Definition at line 34 of file Task.java.
Referenced by nars.entity.Task.getBestSolution(), and nars.entity.Task.setBestSolution().
parentBelief
Sentence nars.entity.Task.parentBelief private
Definition at line 33 of file Task.java.
Referenced by nars.entity.Task.getParentBelief(), nars.entity.Task.setParentBelief(), and nars.entity.Task.Task().
parentTask
Task nars.entity.Task.parentTask private
Definition at line 35 of file Task.java.
Referenced by nars.entity.Task.getParentTask(), nars.entity.Task.setParentTask(), and nars.entity.Task.Task().
sentence
Sentence nars.entity.Task.sentence private
Definition at line 32 of file Task.java.
Referenced by nars.entity.Task.getSentence(), and nars.entity.Task.setSentence().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/entity/Task.java