photon: nars.io.ExperienceReader Class Reference
nars.io.ExperienceReader Class Reference
To read and write experience as Task streams.
Public Member Functions
ExperienceReader (ReasonerBatch reasoner)
Default constructor.
void openLoadFile ()
Open an input experience file with a FileDialog.
void openLoadFile (String filePath)
Open an input experience file from given file Path.
void closeLoadFile ()
Close an input experience file (close the reader in fact)
void setBufferedReader (BufferedReader inExp)
boolean nextInput ()
Process the next chunk of input data TODO duplicated code with InputWindow#nextInput().
Private Attributes
ReasonerBatch reasoner
Reference to the reasoner.
BufferedReader inExp
Input experience from a file.
int timer
Remaining working cycles before reading the next line.
Detailed Description
To read and write experience as Task streams.
Definition at line 31 of file ExperienceReader.java.
Constructor & Destructor Documentation
ExperienceReader()
nars.io.ExperienceReader.ExperienceReader (ReasonerBatch reasoner)
Default constructor.
Parameters
reasoner Backward link to the reasoner
Definition at line 47 of file ExperienceReader.java.
References nars.io.ExperienceReader.inExp, and nars.io.ExperienceReader.reasoner.
{
         this.reasoner = reasoner;
         inExp = null;
     }
Member Function Documentation
closeLoadFile()
void nars.io.ExperienceReader.closeLoadFile ()
Close an input experience file (close the reader in fact)
Definition at line 81 of file ExperienceReader.java.
References nars.io.ExperienceReader.inExp, nars.io.ExperienceReader.reasoner, and nars.storage.ReasonerBatch.removeInputChannel().
{
         try {
             inExp.close();
         } catch (IOException ex) {
             System.out.println("i/o error: " + ex.getMessage());
         }
         ReasonerBatch.removeInputChannel(reasoner, this);
     }
nextInput()
boolean nars.io.ExperienceReader.nextInput ()
Process the next chunk of input data TODO duplicated code with InputWindow#nextInput().
Returns
Whether the input channel should be checked again
Implements nars.io.InputChannel.
Definition at line 101 of file ExperienceReader.java.
References nars.io.ExperienceReader.inExp, nars.io.ExperienceReader.reasoner, nars.storage.ReasonerBatch.textInputLine(), nars.io.ExperienceReader.timer, and nars.storage.ReasonerBatch.walk().
{
         if (timer > 0) {
             timer--;
             return true;
         }
         if (inExp == null) {
             return false;
         }
         String line = null;
         while (timer == 0) {
             try {
                 line = inExp.readLine();
                 if (line == null) {
                     inExp.close();
                     inExp = null;
                     return false;
                 }
             } catch (IOException ex) {
                 System.out.println("i/o error: " + ex.getMessage());
             }
             line = line.trim();
             // read NARS language or an integer
             if (line.length() > 0) {
                 try {
                     timer = Integer.parseInt(line);
                     ReasonerBatch.walk(reasoner, timer);
                 } catch (NumberFormatException e) {
                     ReasonerBatch.textInputLine(reasoner, line);
                 }
             }
         }
         return true;
     }
openLoadFile() [1/2]
void nars.io.ExperienceReader.openLoadFile ()
Open an input experience file with a FileDialog.
Definition at line 53 of file ExperienceReader.java.
Referenced by nars.storage.NARSBatch.init().
{
         FileDialog dialog = new FileDialog((FileDialog) null,
                 "Load experience", FileDialog.LOAD);
         dialog.setVisible(true);
         String directoryName = dialog.getDirectory();
         String fileName = dialog.getFile();
         String filePath = directoryName + fileName;
         openLoadFile(filePath);
     }
openLoadFile() [2/2]
void nars.io.ExperienceReader.openLoadFile (String filePath)
Open an input experience file from given file Path.
Parameters
filePath File to be read as experience
Definition at line 69 of file ExperienceReader.java.
References nars.storage.ReasonerBatch.addInputChannel(), nars.io.ExperienceReader.inExp, and nars.io.ExperienceReader.reasoner.
{
         try {
             inExp = new BufferedReader(new FileReader(filePath));
         } catch (IOException ex) {
             System.out.println("i/o error: " + ex.getMessage());
         }
         ReasonerBatch.addInputChannel(reasoner, this);
     }
setBufferedReader()
void nars.io.ExperienceReader.setBufferedReader (BufferedReader inExp)
Definition at line 90 of file ExperienceReader.java.
References nars.storage.ReasonerBatch.addInputChannel(), nars.io.ExperienceReader.inExp, and nars.io.ExperienceReader.reasoner.
Referenced by nars.storage.NARSBatch.init().
{
         this.inExp = inExp;
         ReasonerBatch.addInputChannel(reasoner, this);
     }
Member Data Documentation
inExp
BufferedReader nars.io.ExperienceReader.inExp private
Input experience from a file.
Definition at line 36 of file ExperienceReader.java.
Referenced by nars.io.ExperienceReader.closeLoadFile(), nars.io.ExperienceReader.ExperienceReader(), nars.io.ExperienceReader.nextInput(), nars.io.ExperienceReader.openLoadFile(), and nars.io.ExperienceReader.setBufferedReader().
reasoner
ReasonerBatch nars.io.ExperienceReader.reasoner private
Reference to the reasoner.
Definition at line 34 of file ExperienceReader.java.
Referenced by nars.io.ExperienceReader.closeLoadFile(), nars.io.ExperienceReader.ExperienceReader(), nars.io.ExperienceReader.nextInput(), nars.io.ExperienceReader.openLoadFile(), and nars.io.ExperienceReader.setBufferedReader().
timer
int nars.io.ExperienceReader.timer private
Remaining working cycles before reading the next line.
Definition at line 39 of file ExperienceReader.java.
Referenced by nars.io.ExperienceReader.nextInput().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/io/ExperienceReader.java