photon: nars.inference.TruthFunctions Class Reference
nars.inference.TruthFunctions Class Reference
All truth-value (and desire-value) functions used in inference rules.
Static Public Member Functions
static float c2w (float c)
A function to convert confidence to weight.
Static Public Member Functions inherited from nars.inference.UtilityFunctions
static float and (float... arr)
A function where the output is conjunctively determined by the inputs.
static float or (float... arr)
A function where the output is disjunctively determined by the inputs.
static float aveGeo (float... arr)
A function where the output is the geometric average the inputs.
static float w2c (float w)
A function to convert weight to confidence.
Static Package Functions
static TruthValue conversion (TruthHandle v1)
{<A ==> B>} |- <B ==> A>
static TruthValue negation (TruthHandle v1)
{A} |- (–A)
static TruthValue revision (TruthHandle v1, TruthHandle v2)
{<S ==> P>, <S ==> P>} |- <S ==> P>
static TruthValue deduction (TruthHandle v1, TruthHandle v2)
{<S ==> M>, <M ==> P>} |- <S ==> P>
static TruthValue deduction (TruthHandle v1, float reliance)
{M, <M ==> P>} |- P
static TruthValue analogy (TruthHandle v1, TruthHandle v2)
{<S ==> M>, <M <=> P>} |- <S ==> P>
static TruthValue resemblance (TruthHandle v1, TruthHandle v2)
{<S <=> M>, <M <=> P>} |- <S <=> P>
static TruthValue abduction (TruthHandle v1, TruthHandle v2)
{<S ==> M>,
static TruthValue abduction (TruthHandle v1, float reliance)
{M,
static TruthValue induction (TruthHandle v1, TruthHandle v2)
{<M ==> S>, <M ==> P>} |- <S ==> P>
static TruthValue comparison (TruthHandle v1, TruthHandle v2)
{<M ==> S>, <M ==> P>} |- <S <=> P>
static TruthValue desireStrong (TruthHandle v1, TruthHandle v2)
A function specially designed for desire value [To be refined].
static TruthValue desireWeak (TruthHandle v1, TruthHandle v2)
A function specially designed for desire value [To be refined].
static TruthValue desireDed (TruthHandle v1, TruthHandle v2)
A function specially designed for desire value [To be refined].
static TruthValue desireInd (TruthHandle v1, TruthHandle v2)
A function specially designed for desire value [To be refined].
static TruthValue union (TruthHandle v1, TruthHandle v2)
{<M --> S>, <M <-> P>} |- <M --> (S|P)>
static TruthValue intersection (TruthHandle v1, TruthHandle v2)
{<M --> S>, <M <-> P>} |- <M --> (S&P)>
static TruthValue reduceConjunction (TruthHandle v1, TruthHandle v2)
{(–, (&&, A, B)), B} |- (–, A)
Detailed Description
All truth-value (and desire-value) functions used in inference rules.
Definition at line 30 of file TruthFunctions.java.
Member Function Documentation
abduction() [1/2]
static TruthValue nars.inference.TruthFunctions.abduction (TruthHandle v1, TruthHandle v2) static package
{<S ==> M>,
<P ==> M>} |- <S ==> P>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 170 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.entity.TruthValue.getFrequency(), and nars.inference.UtilityFunctions.w2c().
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.RuleTables.conditionalAbd(), nars.inference.LocalRules.convertRelation(), nars.inference.RuleTables.functionBeggingToBeAsync(), and nars.inference.TruthFunctions.induction().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float w = and(f2, c1, c2);
         float c = w2c(w);
         return new TruthValue(f1, c);
     }
abduction() [2/2]
static TruthValue nars.inference.TruthFunctions.abduction (TruthHandle v1, float reliance) static package
{M,
<P ==> M>} |- P
Parameters
v1 Truth value of the first premise
reliance Confidence of the second (analytical) premise
Returns
Truth value of the conclusion
Definition at line 191 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.entity.TruthValue.getFrequency(), and nars.inference.UtilityFunctions.w2c().
{
         float f1 = v1.getFrequency();
         float c1 = v1.getConfidence();
         float w = and(c1, reliance);
         float c = w2c(w);
         return new TruthValue(f1, c);
     }
analogy()
static TruthValue nars.inference.TruthFunctions.analogy (TruthHandle v1, TruthHandle v2) static package
{<S ==> M>, <M <=> P>} |- <S ==> P>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 130 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), and nars.entity.TruthValue.getFrequency().
Referenced by nars.inference.SyllogisticRules.analogy(), nars.inference.RuleTables.anonymousAnalogy(), nars.inference.RuleTables.conditionalAna(), and nars.inference.RuleTables.functionBeggingToBeAsync().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f = and(f1, f2);
         float c = and(c1, c2, f2);
         return new TruthValue(f, c);
     }
c2w()
static float nars.inference.TruthFunctions.c2w (float c) static
A function to convert confidence to weight.
Parameters
c confidence, in [0, 1)
Returns
The corresponding weight of evidence, a non-negative real number
Definition at line 371 of file TruthFunctions.java.
References nars.storage.Parameters.HORIZON.
Referenced by nars.inference.TruthFunctions.revision().
{
         return Parameters.HORIZON * c / (1 - c);
     }
comparison()
static TruthValue nars.inference.TruthFunctions.comparison (TruthHandle v1, TruthHandle v2) static package
{<M ==> S>, <M ==> P>} |- <S <=> P>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 221 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.entity.TruthValue.getFrequency(), nars.inference.UtilityFunctions.or(), and nars.inference.UtilityFunctions.w2c().
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.RuleTables.conditionalAna(), and nars.inference.CompositionalRules.introVarOuter().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f0 = or(f1, f2);
         float f = (f0 == 0) ? 0 : (and(f1, f2) / f0);
         float w = and(f0, c1, c2);
         float c = w2c(w);
         return new TruthValue(f, c);
     }
conversion()
static TruthValue nars.inference.TruthFunctions.conversion (TruthHandle v1) static package
{<A ==> B>} |- <B ==> A>
Parameters
v1 Truth value of the premise
Returns
Truth value of the conclusion
Definition at line 40 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.entity.TruthValue.getFrequency(), and nars.inference.UtilityFunctions.w2c().
Referenced by nars.inference.LocalRules.conversion().
{
         float f1 = v1.getFrequency();
         float c1 = v1.getConfidence();
         float w = and(f1, c1);
         float c = w2c(w);
         return new TruthValue(1, c);
     }
deduction() [1/2]
static TruthValue nars.inference.TruthFunctions.deduction (TruthHandle v1, TruthHandle v2) static package
{<S ==> M>, <M ==> P>} |- <S ==> P>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 95 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), and nars.entity.TruthValue.getFrequency().
Referenced by nars.inference.RuleTables.conditionalDedInd(), nars.inference.LocalRules.convertRelation(), nars.inference.RuleTables.dedExe(), nars.inference.RuleTables.functionBeggingToBeAsync(), nars.inference.TruthFunctions.reduceConjunction(), nars.inference.CompositionalRules.reduceDisjunction(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralCompound(), and nars.inference.StructuralRules.structuralDecompose1().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f = and(f1, f2);
         float c = and(c1, c2, f);
         return new TruthValue(f, c);
     }
deduction() [2/2]
static TruthValue nars.inference.TruthFunctions.deduction (TruthHandle v1, float reliance) static package
{M, <M ==> P>} |- P
Parameters
v1 Truth value of the first premise
reliance Confidence of the second (analytical) premise
Returns
Truth value of the conclusion
Definition at line 114 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), and nars.entity.TruthValue.getFrequency().
{
         float f1 = v1.getFrequency();
         float c1 = v1.getConfidence();
         float c = and(f1, c1, reliance);
         return new TruthValue(f1, c);
     }
desireDed()
static TruthValue nars.inference.TruthFunctions.desireDed (TruthHandle v1, TruthHandle v2) static package
A function specially designed for desire value [To be refined].
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 281 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), and nars.entity.TruthValue.getFrequency().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f = and(f1, f2);
         float c = and(c1, c2);
         return new TruthValue(f, c);
     }
desireInd()
static TruthValue nars.inference.TruthFunctions.desireInd (TruthHandle v1, TruthHandle v2) static package
A function specially designed for desire value [To be refined].
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 300 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.entity.TruthValue.getFrequency(), and nars.inference.UtilityFunctions.w2c().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float w = and(f2, c1, c2);
         float c = w2c(w);
         return new TruthValue(f1, c);
     }
desireStrong()
static TruthValue nars.inference.TruthFunctions.desireStrong (TruthHandle v1, TruthHandle v2) static package
A function specially designed for desire value [To be refined].
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 243 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), and nars.entity.TruthValue.getFrequency().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f = and(f1, f2);
         float c = and(c1, c2, f2);
         return new TruthValue(f, c);
     }
desireWeak()
static TruthValue nars.inference.TruthFunctions.desireWeak (TruthHandle v1, TruthHandle v2) static package
A function specially designed for desire value [To be refined].
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 262 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.entity.TruthValue.getFrequency(), and nars.inference.UtilityFunctions.w2c().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f = and(f1, f2);
         float c = and(c1, c2, f2, w2c(1.0f));
         return new TruthValue(f, c);
     }
induction()
static TruthValue nars.inference.TruthFunctions.induction (TruthHandle v1, TruthHandle v2) static package
{<M ==> S>, <M ==> P>} |- <S ==> P>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 208 of file TruthFunctions.java.
References nars.inference.TruthFunctions.abduction().
Referenced by nars.inference.RuleTables.conditionalDedInd(), nars.inference.CompositionalRules.introVarInner(), and nars.inference.CompositionalRules.introVarOuter().
{
         return abduction(v2, v1);
     }
intersection()
static TruthValue nars.inference.TruthFunctions.intersection (TruthHandle v1, TruthHandle v2) static package
{<M --> S>, <M <-> P>} |- <M --> (S&P)>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 340 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), and nars.entity.TruthValue.getFrequency().
Referenced by nars.inference.CompositionalRules.composeCompound(), nars.inference.LocalRules.inferToSym(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.inference.TruthFunctions.reduceConjunction(), and nars.inference.CompositionalRules.reduceDisjunction().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f = and(f1, f2);
         float c = and(c1, c2);
         return new TruthValue(f, c);
     }
negation()
static TruthValue nars.inference.TruthFunctions.negation (TruthHandle v1) static package
{A} |- (–A)
Parameters
v1 Truth value of the premise
Returns
Truth value of the conclusion
Definition at line 56 of file TruthFunctions.java.
References nars.entity.TruthValue.getFrequency().
Referenced by nars.inference.CompositionalRules.composeCompound(), nars.inference.TruthFunctions.reduceConjunction(), nars.inference.CompositionalRules.reduceConjunctionNeg(), nars.inference.CompositionalRules.reduceDisjunction(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralDecompose1(), and nars.inference.RuleTables.transformNegation().
{
         float f = 1 - v1.getFrequency();
         float c = v1.getConfidence();
         return new TruthValue(f, c);
     }
reduceConjunction()
static TruthValue nars.inference.TruthFunctions.reduceConjunction (TruthHandle v1, TruthHandle v2) static package
{(–, (&&, A, B)), B} |- (–, A)
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 359 of file TruthFunctions.java.
References nars.inference.TruthFunctions.deduction(), nars.inference.TruthFunctions.intersection(), and nars.inference.TruthFunctions.negation().
Referenced by nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.decomposeStatement(), nars.inference.LocalRules.inferToAsym(), and nars.inference.CompositionalRules.reduceConjunctionNeg().
{
         TruthValue v0 = intersection(negation(v1), v2);
         return negation(deduction(v0, 1f));
     }
resemblance()
static TruthValue nars.inference.TruthFunctions.resemblance (TruthHandle v1, TruthHandle v2) static package
{<S <=> M>, <M <=> P>} |- <S <=> P>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 149 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.entity.TruthValue.getFrequency(), and nars.inference.UtilityFunctions.or().
Referenced by nars.inference.SyllogisticRules.resemblance().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f = and(f1, f2);
         float c = and(c1, c2, or(f1, f2));
         return new TruthValue(f, c);
     }
revision()
static TruthValue nars.inference.TruthFunctions.revision (TruthHandle v1, TruthHandle v2) static package
{<S ==> P>, <S ==> P>} |- <S ==> P>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 72 of file TruthFunctions.java.
References nars.inference.TruthFunctions.c2w(), nars.entity.TruthValue.getFrequency(), and nars.inference.UtilityFunctions.w2c().
Referenced by nars.inference.LocalRules.revision().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float w1 = c2w(c1);
         float w2 = c2w(c2);
         float w = w1 + w2;
         float f = (w1 * f1 + w2 * f2) / w;
         float c = w2c(w);
         return new TruthValue(f, c);
     }
union()
static TruthValue nars.inference.TruthFunctions.union (TruthHandle v1, TruthHandle v2) static package
{<M --> S>, <M <-> P>} |- <M --> (S|P)>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 320 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.entity.TruthValue.getFrequency(), and nars.inference.UtilityFunctions.or().
Referenced by nars.inference.CompositionalRules.composeCompound().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f = or(f1, f2);
         // float c = or(and(f1, c1), and(f2, c2)) + and(1 - f1, 1 - f2, c1, c2);
         float c = and(c1, c2);
         return new TruthValue(f, c);
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/inference/TruthFunctions.java