photon: nars.storage.Bag< Type extends Item > Class Template Reference
nars.storage.Bag< Type extends Item > Class Template Reference abstract
A Bag is a storage with a constant capacity and maintains an internal priority distribution for retrieval.
Public Member Functions
void init ()
float averagePriority ()
Get the average priority of Items.
boolean contains (Type it)
Check if an item is in the bag.
Type get (String key)
Get an Item by key.
boolean putIn (Type newItem)
Add a new Item into the Bag.
boolean putBack (Type oldItem)
Put an item back into the itemTable.
Type takeOut ()
Choose an Item according to priority distribution and take it out of the Bag.
Type pickOut (String key)
Pick an item by key, then remove it from the bag.
void addBagObserver (BagObserver bagObserver, String title)
To start displaying the Bag in a BagWindow.
void play ()
Resume display.
void stop ()
Stop display.
void refresh ()
Refresh display.
String toString ()
Collect Bag content into a String for display.
String toStringLong ()
TODO bad paste from preceding.
void setShowLevel (int showLevel)
Protected Member Functions
Bag (WorkSpace memory)
constructor, called from subclasses
abstract int capacity ()
To get the capacity of the concrete subclass.
abstract int forgetRate ()
Get the item decay rate, which differs in difference subclass, and can be changed in run time by the user, so not a constant.
boolean emptyLevel (int n)
Check whether a level is empty.
void outOfBase (Type oldItem)
Remove an item from itemTable, then adjust mass.
Protected Attributes
WorkSpace memory
whether this bag has an active window
Package Functions
String showSizes ()
Private Member Functions
int getLevel (Type item)
Decide the put-in level according to priority.
Type intoBase (Type newItem)
Insert an item into the itemTable, and return the overflow.
Type takeOutFirst (int level)
Take out the first or last Type in a level from the itemTable.
Private Attributes
Map< String, Type > nameTable
mapping from key to item
List< ArrayList< Type > > itemTable
array of lists of items, for items on different level
int capacity
defined in different bags
int mass
current sum of occupied level
int levelIndex
index to get next level, kept in individual objects
int currentLevel
current take out level
int currentCounter
maximum number of items to be taken out at current level
BagObserver bagObserver = new NullBagObserver<Type>()
int showLevel = Parameters.BAG_THRESHOLD
The lowest display level.
Static Private Attributes
static final int TOTAL_LEVEL = Parameters.BAG_LEVEL
priority levels
static final int THRESHOLD = Parameters.BAG_THRESHOLD
firing threshold
static final float RELATIVE_THRESHOLD = (float) THRESHOLD / (float) TOTAL_LEVEL
relative threshold, only calculate once
static final float LOAD_FACTOR = Parameters.LOAD_FACTOR
hashtable load factor
static final Distributor DISTRIBUTOR = new Distributor(TOTAL_LEVEL)
shared DISTRIBUTOR that produce the probability distribution
Detailed Description
A Bag is a storage with a constant capacity and maintains an internal priority distribution for retrieval.
Each entity in a bag must extend Item, which has a BudgetValue and a key.
A name table is used to merge duplicate items that have the same key.
The bag space is divided by a threshold, above which is mainly time management, and below, space management. Differences: (1) level selection vs. item selection, (2) decay rate
Parameters
<Type> The type of the Item in the Bag
Definition at line 44 of file Bag.java.
Constructor & Destructor Documentation
Bag()
nars.storage.Bag< Type extends Item >.Bag (WorkSpace memory) protected
constructor, called from subclasses
Parameters
memory The reference to memory
Definition at line 87 of file Bag.java.
{
         this.memory = memory;
 //        showing = false;
         capacity = capacity();
         init();
     }
Member Function Documentation
addBagObserver()
void nars.storage.Bag< Type extends Item >.addBagObserver (BagObserver bagObserver, String title)
To start displaying the Bag in a BagWindow.
TODO startPlay should be renamed addBagObserver(BagObserver bagObserver, String title) and BagWindow will implement new interface BagObserver;
Parameters
bagObserver TODO
title The title of the window
Definition at line 306 of file Bag.java.
Referenced by nars.storage.Memory.conceptsStartPlay(), nars.entity.Concept.startPlay(), and nars.storage.Memory.taskBuffersStartPlay().
{
         this.bagObserver = bagObserver;
         bagObserver.post(toString());
         bagObserver.setTitle(title);
 //        window = new BagWindow(this, title);
 //        showing = true;
 //        window.post(toString());
     }
averagePriority()
float nars.storage.Bag< Type extends Item >.averagePriority ()
Get the average priority of Items.
Returns
The average priority of Items in the bag
Definition at line 123 of file Bag.java.
Referenced by nars.entity.Concept.getQuality().
{
         if (nameTable.size() == 0) {
             return 0.01f;
         }
         float f = (float) mass / (nameTable.size() * TOTAL_LEVEL);
         if (f > 1) {
             return 1.0f;
         }
         return f;
     }
capacity()
abstract int nars.storage.Bag< Type extends Item >.capacity () abstract protected
To get the capacity of the concrete subclass.
Returns
Bag capacity, in number of Items allowed
Referenced by nars.storage.Bag< Concept >.Bag(), nars.storage.Bag< Concept >.init(), and nars.storage.Bag< Concept >.intoBase().
contains()
boolean nars.storage.Bag< Type extends Item >.contains (Type it)
Check if an item is in the bag.
Parameters
it An item
Returns
Whether the Item is in the Bag
Definition at line 139 of file Bag.java.
{
         return nameTable.containsValue(it);
     }
emptyLevel()
boolean nars.storage.Bag< Type extends Item >.emptyLevel (int n) protected
Check whether a level is empty.
Parameters
n The level index
Returns
Whether that level is empty
Definition at line 233 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.intoBase(), nars.storage.Bag< Concept >.takeOut(), nars.storage.Bag< Concept >.toString(), and nars.storage.Bag< Concept >.toStringLong().
{
         return ((itemTable.get(n) == null) || itemTable.get(n).isEmpty());
     }
forgetRate()
abstract int nars.storage.Bag< Type extends Item >.forgetRate () abstract protected
Get the item decay rate, which differs in difference subclass, and can be changed in run time by the user, so not a constant.
Returns
The number of times for a decay factor to be fully applied
Referenced by nars.storage.Bag< Concept >.putBack().
get()
Type nars.storage.Bag< Type extends Item >.get (String key)
Get an Item by key.
Parameters
key The key of the Item
Returns
The Item with the given key
Definition at line 148 of file Bag.java.
Referenced by nars.storage.Memory.getConcept(), nars.storage.Memory.nameToConcept(), and nars.storage.Memory.nameToListedTerm().
{
         return nameTable.get(key);
     }
getLevel()
int nars.storage.Bag< Type extends Item >.getLevel (Type item) private
Decide the put-in level according to priority.
Parameters
item The Item to put in
Returns
The put-in level
Definition at line 242 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.intoBase(), and nars.storage.Bag< Concept >.outOfBase().
{
         float fl = item.getPriority() * TOTAL_LEVEL;
         int level = (int) Math.ceil(fl) - 1;
         return (level < 0) ? 0 : level;     // cannot be -1
     }
init()
void nars.storage.Bag< Type extends Item >.init ()
Definition at line 94 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.Bag(), and nars.storage.Memory.init().
{
         itemTable = new ArrayList<ArrayList<Type>>(TOTAL_LEVEL);
         for (int i = 0; i < TOTAL_LEVEL; i++) {
             itemTable.add(new ArrayList<Type>());
         }
         nameTable = new HashMap<String, Type>((int) (capacity / LOAD_FACTOR), LOAD_FACTOR);
         currentLevel = TOTAL_LEVEL - 1;
         levelIndex = capacity % TOTAL_LEVEL; // so that different bags start at different point
         mass = 0;
         currentCounter = 0;
     }
intoBase()
Type nars.storage.Bag< Type extends Item >.intoBase (Type newItem) private
Insert an item into the itemTable, and return the overflow.
Parameters
newItem The Item to put in
Returns
The overflow Item
Definition at line 253 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.putIn().
{
         Type oldItem = null;
         int inLevel = getLevel(newItem);
         if (nameTable.size() > capacity) {      // the bag is full
             int outLevel = 0;
             while (emptyLevel(outLevel)) {
                 outLevel++;
             }
             if (outLevel > inLevel) {           // ignore the item and exit
                 return newItem;
             } else {                            // remove an old item in the lowest non-empty level
                 oldItem = takeOutFirst(outLevel);
             }
         }
         itemTable.get(inLevel).add(newItem);        // FIFO
         mass += (inLevel + 1);                  // increase total mass
         refresh();                              // refresh the window
         return oldItem;     // TODO return null is a bad smell
     }
outOfBase()
void nars.storage.Bag< Type extends Item >.outOfBase (Type oldItem) protected
Remove an item from itemTable, then adjust mass.
Parameters
oldItem The Item to be removed
Definition at line 290 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.pickOut(), and nars.storage.Bag< Concept >.putIn().
{
         int level = getLevel(oldItem);
         itemTable.get(level).remove(oldItem);
         mass -= (level + 1);
         refresh();
     }
pickOut()
Type nars.storage.Bag< Type extends Item >.pickOut (String key)
Pick an item by key, then remove it from the bag.
Parameters
key The given key
Returns
The Item with the key
Definition at line 219 of file Bag.java.
Referenced by nars.storage.Memory.activateConcept().
{
         Type picked = nameTable.get(key);
         if (picked != null) {
             outOfBase(picked);
             nameTable.remove(key);
         }
         return picked;
     }
play()
void nars.storage.Bag< Type extends Item >.play ()
Resume display.
Definition at line 318 of file Bag.java.
{
         bagObserver.post(toString());
 //        showing = true;
 //        window.post(toString());
     }
putBack()
boolean nars.storage.Bag< Type extends Item >.putBack (Type oldItem)
Put an item back into the itemTable.
The only place where the forgetting rate is applied
Parameters
oldItem The Item to put back
Returns
Whether the new Item is added into the Bag
Definition at line 181 of file Bag.java.
Referenced by nars.storage.Memory.activateConcept(), nars.entity.Concept.fireFromProcessConcept(), and nars.storage.Memory.processConcept().
{
         BudgetFunctions.forget(oldItem.getBudget(), forgetRate(), RELATIVE_THRESHOLD);
         return putIn(oldItem);
     }
putIn()
boolean nars.storage.Bag< Type extends Item >.putIn (Type newItem)
Add a new Item into the Bag.
Parameters
newItem The new Item
Returns
Whether the new Item is added into the Bag
Definition at line 157 of file Bag.java.
Referenced by nars.storage.Memory.getConcept(), nars.entity.Concept.insertTaskLink(), nars.entity.Concept.insertTermLink(), nars.storage.Memory.processNewTask(), and nars.storage.Bag< Concept >.putBack().
{
         String newKey = newItem.getKey();
         Type oldItem = nameTable.put(newKey, newItem);
         if (oldItem != null) {                  // merge duplications
             outOfBase(oldItem);
             Item.merge(newItem.getBudget(), oldItem);
         }
         Type overflowItem = intoBase(newItem);  // put the (new or merged) item into itemTable
         if (overflowItem != null) {             // remove overflow
             String overflowKey = overflowItem.getKey();
             nameTable.remove(overflowKey);
             return (overflowItem != newItem);
         } else {
             return true;
         }
     }
refresh()
void nars.storage.Bag< Type extends Item >.refresh ()
Refresh display.
Definition at line 335 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.intoBase(), nars.storage.Bag< Concept >.outOfBase(), nars.storage.Bag< Concept >.takeOut(), nars.storage.Bag< Concept >.takeOutFirst(), and nars.storage.Memory.workCycle().
{
         bagObserver.refresh(toString());
 //        if (showing) {
 //            window.post(toString());
 //        }
     }
setShowLevel()
void nars.storage.Bag< Type extends Item >.setShowLevel (int showLevel)
Definition at line 388 of file Bag.java.
{
         this.showLevel = showLevel;
     }
showSizes()
String nars.storage.Bag< Type extends Item >.showSizes () package
Definition at line 376 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.toStringLong().
{
         StringBuilder buf = new StringBuilder(" ");
         int levels = 0;
         for ( List<Type> items : itemTable) {
             if ((items != null) && ! items.isEmpty()) {
                 levels++;
                 buf.append( items.size() ).append( " " );
             }
         }
         return "Levels: " + Integer.toString( levels ) + ", sizes: " + buf;
     }
stop()
void nars.storage.Bag< Type extends Item >.stop ()
Stop display.
Definition at line 327 of file Bag.java.
{
         bagObserver.stop();
 //        showing = false;
     }
takeOut()
Type nars.storage.Bag< Type extends Item >.takeOut ()
Choose an Item according to priority distribution and take it out of the Bag.
Returns
The selected Item
Definition at line 190 of file Bag.java.
Referenced by nars.entity.Concept.fireFromProcessConcept(), nars.storage.Memory.processConcept(), and nars.storage.Memory.processNovelTask().
{
         if (nameTable.isEmpty()) { // empty bag
             return null;
         }
         if (emptyLevel(currentLevel) || (currentCounter == 0)) { // done with the current level
             currentLevel = DISTRIBUTOR.pick(levelIndex);
             levelIndex = DISTRIBUTOR.next(levelIndex);
             while (emptyLevel(currentLevel)) {          // look for a non-empty level
                 currentLevel = DISTRIBUTOR.pick(levelIndex);
                 levelIndex = DISTRIBUTOR.next(levelIndex);
             }
             if (currentLevel < THRESHOLD) { // for dormant levels, take one item
                 currentCounter = 1;
             } else {                  // for active levels, take all current items
                 currentCounter = itemTable.get(currentLevel).size();
             }
         }
         Type selected = takeOutFirst(currentLevel); // take out the first item in the level
         currentCounter--;
         nameTable.remove(selected.getKey());
         refresh();
         return selected;
     }
takeOutFirst()
Type nars.storage.Bag< Type extends Item >.takeOutFirst (int level) private
Take out the first or last Type in a level from the itemTable.
Parameters
level The current level
Returns
The first Item
Definition at line 278 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.intoBase(), and nars.storage.Bag< Concept >.takeOut().
{
         Type selected = itemTable.get(level).get(0);
         itemTable.get(level).remove(0);
         mass -= (level + 1);
         refresh();
         return selected;
     }
toString()
String nars.storage.Bag< Type extends Item >.toString ()
Collect Bag content into a String for display.
Definition at line 346 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.addBagObserver(), nars.storage.Bag< Concept >.play(), and nars.storage.Bag< Concept >.refresh().
{
         StringBuffer buf = new StringBuffer(" ");
 //        int showLevel = window == null ? 1 : window.showLevel();
         for (int i = TOTAL_LEVEL; i >= showLevel ; i--) {
             if (!emptyLevel(i - 1)) {
                 buf = buf.append("\n --- Level " + i + ":\n ");
                 for (int j = 0; j < itemTable.get(i - 1).size(); j++) {
                     buf = buf.append(Item.toStringBrief(itemTable.get(i - 1).get(j).getBudget(), itemTable.get(i - 1).get(j).getKey()) + "\n ");
                 }
             }
         }
         return buf.toString();
     }
toStringLong()
String nars.storage.Bag< Type extends Item >.toStringLong ()
TODO bad paste from preceding.
Definition at line 361 of file Bag.java.
Referenced by nars.storage.Memory.toStringLongIfNotNull().
{
         StringBuffer buf = new StringBuffer(" BAG " + getClass().getSimpleName() );
         buf.append(" ").append( showSizes() );
         for (int i = TOTAL_LEVEL; i >= showLevel; i--) {
             if (!emptyLevel(i - 1)) {
                 buf = buf.append("\n --- LEVEL " + i + ":\n ");
                 for (int j = 0; j < itemTable.get(i - 1).size(); j++) {
                     buf = buf.append(Item.toStringLong(itemTable.get(i - 1).get(j)) + "\n ");
                 }
             }
         }
         buf.append(">>>> end of Bag").append( getClass().getSimpleName() );
         return buf.toString();
     }
Member Data Documentation
bagObserver
BagObserver nars.storage.Bag< Type extends Item >.bagObserver = new NullBagObserver<Type>() private
Definition at line 79 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.addBagObserver(), nars.storage.Bag< Concept >.play(), nars.storage.Bag< Concept >.refresh(), and nars.storage.Bag< Concept >.stop().
capacity
int nars.storage.Bag< Type extends Item >.capacity private
defined in different bags
Definition at line 62 of file Bag.java.
currentCounter
int nars.storage.Bag< Type extends Item >.currentCounter private
maximum number of items to be taken out at current level
Definition at line 70 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.init(), and nars.storage.Bag< Concept >.takeOut().
currentLevel
int nars.storage.Bag< Type extends Item >.currentLevel private
current take out level
Definition at line 68 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.init(), and nars.storage.Bag< Concept >.takeOut().
DISTRIBUTOR
final Distributor nars.storage.Bag< Type extends Item >.DISTRIBUTOR = new Distributor(TOTAL_LEVEL) static private
shared DISTRIBUTOR that produce the probability distribution
Definition at line 55 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.takeOut().
itemTable
List<ArrayList<Type> > nars.storage.Bag< Type extends Item >.itemTable private
array of lists of items, for items on different level
Definition at line 60 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.emptyLevel(), nars.storage.Bag< Concept >.init(), nars.storage.Bag< Concept >.intoBase(), nars.storage.Bag< Concept >.outOfBase(), nars.storage.Bag< Concept >.showSizes(), nars.storage.Bag< Concept >.takeOut(), nars.storage.Bag< Concept >.takeOutFirst(), nars.storage.Bag< Concept >.toString(), and nars.storage.Bag< Concept >.toStringLong().
levelIndex
int nars.storage.Bag< Type extends Item >.levelIndex private
index to get next level, kept in individual objects
Definition at line 66 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.init(), and nars.storage.Bag< Concept >.takeOut().
LOAD_FACTOR
final float nars.storage.Bag< Type extends Item >.LOAD_FACTOR = Parameters.LOAD_FACTOR static private
hashtable load factor
Definition at line 53 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.init().
mass
int nars.storage.Bag< Type extends Item >.mass private
current sum of occupied level
Definition at line 64 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.averagePriority(), nars.storage.Bag< Concept >.init(), nars.storage.Bag< Concept >.intoBase(), nars.storage.Bag< Concept >.outOfBase(), and nars.storage.Bag< Concept >.takeOutFirst().
memory
WorkSpace nars.storage.Bag< Type extends Item >.memory protected
whether this bag has an active window
display window : remove GUI dependency reference to memory
Definition at line 78 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.Bag().
nameTable
Map<String, Type> nars.storage.Bag< Type extends Item >.nameTable private
mapping from key to item
Definition at line 58 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.averagePriority(), nars.storage.Bag< Concept >.contains(), nars.storage.Bag< Concept >.get(), nars.storage.Bag< Concept >.init(), nars.storage.Bag< Concept >.intoBase(), nars.storage.Bag< Concept >.pickOut(), nars.storage.Bag< Concept >.putIn(), and nars.storage.Bag< Concept >.takeOut().
RELATIVE_THRESHOLD
final float nars.storage.Bag< Type extends Item >.RELATIVE_THRESHOLD = (float) THRESHOLD / (float) TOTAL_LEVEL static private
relative threshold, only calculate once
Definition at line 51 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.putBack().
showLevel
int nars.storage.Bag< Type extends Item >.showLevel = Parameters.BAG_THRESHOLD private
The lowest display level.
Definition at line 81 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.setShowLevel(), nars.storage.Bag< Concept >.toString(), and nars.storage.Bag< Concept >.toStringLong().
THRESHOLD
final int nars.storage.Bag< Type extends Item >.THRESHOLD = Parameters.BAG_THRESHOLD static private
firing threshold
Definition at line 49 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.takeOut().
TOTAL_LEVEL
final int nars.storage.Bag< Type extends Item >.TOTAL_LEVEL = Parameters.BAG_LEVEL static private
priority levels
Definition at line 47 of file Bag.java.
Referenced by nars.storage.Bag< Concept >.averagePriority(), nars.storage.Bag< Concept >.getLevel(), nars.storage.Bag< Concept >.init(), nars.storage.Bag< Concept >.toString(), and nars.storage.Bag< Concept >.toStringLong().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/storage/Bag.java