photon: nars.inference.UtilityFunctions Class Reference
nars.inference.UtilityFunctions Class Reference
Common functions on real numbers, mostly in [0,1].
Static Public Member Functions
static float and (float... arr)
A function where the output is conjunctively determined by the inputs.
static float or (float... arr)
A function where the output is disjunctively determined by the inputs.
static float aveGeo (float... arr)
A function where the output is the geometric average the inputs.
static float w2c (float w)
A function to convert weight to confidence.
Detailed Description
Common functions on real numbers, mostly in [0,1].
Definition at line 28 of file UtilityFunctions.java.
Member Function Documentation
and()
static float nars.inference.UtilityFunctions.and (float... arr) static
A function where the output is conjunctively determined by the inputs.
Parameters
arr The inputs, each in [0, 1]
Returns
The output that is no larger than each input
Definition at line 35 of file UtilityFunctions.java.
Referenced by nars.inference.TruthFunctions.abduction(), nars.inference.TruthFunctions.analogy(), nars.inference.BudgetFunctions.budgetInference(), nars.inference.TruthFunctions.comparison(), nars.inference.RuleTables.contraposition(), nars.inference.TruthFunctions.conversion(), nars.entity.BudgetValue.decDurability(), nars.entity.BudgetValue.decPriority(), nars.entity.BudgetValue.decQuality(), nars.inference.TruthFunctions.deduction(), nars.inference.TruthFunctions.desireDed(), nars.inference.TruthFunctions.desireInd(), nars.inference.TruthFunctions.desireStrong(), nars.inference.TruthFunctions.desireWeak(), nars.inference.RuleTables.exemplification(), nars.inference.TruthFunctions.intersection(), nars.inference.TruthFunctions.resemblance(), and nars.inference.TruthFunctions.union().
{
         float product = 1;
         for (float f : arr) {
             product *= f;
         }
         return product;
     }
aveGeo()
static float nars.inference.UtilityFunctions.aveGeo (float... arr) static
A function where the output is the geometric average the inputs.
Parameters
arr The inputs, each in [0, 1]
Returns
The geometric average the inputs
Definition at line 61 of file UtilityFunctions.java.
Referenced by nars.entity.BudgetValue.summary(), and nars.inference.BudgetFunctions.truthToQuality().
{
         float product = 1;
         for (float f : arr) {
             product *= f;
         }
         return (float) Math.pow(product, 1.00 / arr.length);
     }
or()
static float nars.inference.UtilityFunctions.or (float... arr) static
A function where the output is disjunctively determined by the inputs.
Parameters
arr The inputs, each in [0, 1]
Returns
The output that is no smaller than each input
Definition at line 48 of file UtilityFunctions.java.
Referenced by nars.inference.BudgetFunctions.activate(), nars.inference.TruthFunctions.comparison(), nars.entity.Concept.getQuality(), nars.entity.BudgetValue.incDurability(), nars.entity.BudgetValue.incPriority(), nars.entity.BudgetValue.incQuality(), nars.entity.Concept.rankBelief(), nars.inference.TruthFunctions.resemblance(), nars.inference.LocalRules.revise(), nars.inference.TruthFunctions.union(), and nars.inference.BudgetFunctions.update().
{
         float product = 1;
         for (float f : arr) {
             product *= (1 - f);
         }
         return 1 - product;
     }
w2c()
static float nars.inference.UtilityFunctions.w2c (float w) static
A function to convert weight to confidence.
Parameters
w Weight of evidence, a non-negative real number
Returns
The corresponding confidence, in [0, 1)
Definition at line 74 of file UtilityFunctions.java.
References nars.storage.Parameters.HORIZON.
Referenced by nars.inference.TruthFunctions.abduction(), nars.inference.RuleTables.anonymousAnalogy(), nars.inference.BudgetFunctions.backwardWeak(), nars.inference.TruthFunctions.comparison(), nars.inference.BudgetFunctions.compoundBackwardWeak(), nars.inference.RuleTables.contraposition(), nars.inference.TruthFunctions.conversion(), nars.inference.TruthFunctions.desireInd(), nars.inference.TruthFunctions.desireWeak(), nars.inference.RuleTables.exemplification(), and nars.inference.TruthFunctions.revision().
{
         return w / (w + Parameters.HORIZON);
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/inference/UtilityFunctions.java