photon: nars.entity.Sentence Class Reference
nars.entity.Sentence Class Reference
A Sentence is an abstract class, mainly containing a Term, a TruthValue, and a Stamp.
Public Member Functions
Sentence (TermStruct content, int punctuation, TruthValue truth, Stamp stamp)
Create a Sentence with the given fields.
Sentence (TermStruct content, int punctuation, TruthValue truth, Stamp stamp, boolean revisible)
Create a Sentence with the given fields.
boolean equals (Object that)
To check whether two sentences are equal.
int hashCode ()
To produce the hashcode of a sentence.
boolean equivalentTo (SentenceStruct that)
Check whether the judgment is equivalent to another one.
Object clone ()
Clone the Sentence.
Term getContent ()
The content of a Sentence is a Term.
int getPunctuation ()
The punctuation also indicates the type of the Sentence: Judgment, Question, or Goal.
void setPunctuation (int $punctuation$)
Term cloneContent ()
Clone the content of the sentence.
void setContent (TermStruct t)
Set the content Term of the Sentence.
TruthValue getTruth ()
The truth value of Judgment.
void setTruth (TruthHandle $truth$)
Stamp getStamp ()
Partial record of the derivation path.
void setStamp (StampStruct $stamp$)
boolean isJudgment ()
Distinguish Judgment from Goal ("instanceof Judgment" doesn't work)
boolean isQuestion ()
Distinguish Question from Quest ("instanceof Question" doesn't work)
void setQuestion (boolean $question$)
boolean getRevisible ()
void setRevisible (boolean b)
String toString ()
Get a String representation of the sentence.
void setPunctuation (char punctuation)
void setTruth (TruthValue truth)
void setStamp (Stamp stamp)
boolean isRevisible ()
Whether the sentence can be revised.
Static Public Member Functions
static boolean containQueryVar (SentenceStruct sentence)
static String toStringBrief (Sentence sentence)
Get a String representation of the sentence, with 2-digit accuracy.
static String toKey (Sentence sentence)
Get a String representation of the sentence for key of Task and TaskLink.
Static Private Member Functions
static String asString (Sentence sentence)
Private Attributes
Term content
char punctuation
TruthValue truth
Stamp stamp
boolean revisible
Detailed Description
A Sentence is an abstract class, mainly containing a Term, a TruthValue, and a Stamp.
It is used as the premises and conclusions of all inference rules.
Definition at line 36 of file Sentence.java.
Constructor & Destructor Documentation
Sentence() [1/2]
nars.entity.Sentence.Sentence (TermStruct content, int punctuation, TruthValue truth, Stamp stamp)
Create a Sentence with the given fields.
Parameters
content The Term that forms the content of the sentence
punctuation The punctuation indicating the type of the sentence
truth The truth value of the sentence, null for question
stamp The stamp of the sentence indicating its derivation time and base
Definition at line 51 of file Sentence.java.
References nars.entity.Sentence.content, nars.entity.Sentence.getContent(), nars.entity.Sentence.punctuation, nars.language.Term.renameVariables(), nars.entity.Sentence.setContent(), nars.entity.Sentence.setPunctuation(), nars.entity.Sentence.setRevisible(), nars.entity.Sentence.setStamp(), nars.entity.Sentence.setTruth(), nars.entity.Sentence.stamp, and nars.entity.Sentence.truth.
Referenced by nars.entity.Sentence.clone(), and nars.entity.Sentence.equals().
{
         setContent(content);
         getContent().renameVariables();
         setPunctuation(punctuation);
         setTruth(truth);
         setStamp(stamp);
         setRevisible(true);
     }
Sentence() [2/2]
nars.entity.Sentence.Sentence (TermStruct content, int punctuation, TruthValue truth, Stamp stamp, boolean revisible)
Create a Sentence with the given fields.
Parameters
content The Term that forms the content of the sentence
punctuation The punctuation indicating the type of the sentence
truth The truth value of the sentence, null for question
stamp The stamp of the sentence indicating its derivation time and base
revisible Whether the sentence can be revised
Definition at line 68 of file Sentence.java.
References nars.entity.Sentence.content, nars.entity.Sentence.getContent(), nars.entity.Sentence.punctuation, nars.language.Term.renameVariables(), nars.entity.Sentence.revisible, nars.entity.Sentence.setContent(), nars.entity.Sentence.setPunctuation(), nars.entity.Sentence.setRevisible(), nars.entity.Sentence.setStamp(), nars.entity.Sentence.setTruth(), nars.entity.Sentence.stamp, and nars.entity.Sentence.truth.
{
         setContent(content);
         getContent().renameVariables();
         setPunctuation(punctuation);
         setTruth(truth);
         setStamp(stamp);
         setRevisible(revisible);
     }
Member Function Documentation
asString()
static String nars.entity.Sentence.asString (Sentence sentence) static private
Definition at line 246 of file Sentence.java.
References nars.entity.Sentence.getContent(), nars.entity.Sentence.getPunctuation(), nars.entity.Sentence.getStamp(), and nars.entity.Sentence.getTruth().
Referenced by nars.entity.Sentence.toString().
{
         StringBuffer s = new StringBuffer();
         s.append(sentence.getContent());
         s.append(sentence.getPunctuation() + " ");
         if (sentence.getTruth() != null) {
             s.append(sentence.getTruth());
         }
         s.append(sentence.getStamp());
         return s.toString();
     }
clone()
Object nars.entity.Sentence.clone ()
Clone the Sentence.
Returns
The clone
Definition at line 122 of file Sentence.java.
References nars.entity.Sentence.getContent(), nars.entity.Sentence.getPunctuation(), nars.entity.Sentence.getStamp(), nars.entity.Sentence.getTruth(), nars.entity.Sentence.isRevisible(), and nars.entity.Sentence.Sentence().
Referenced by nars.inference.RuleTables.detachmentWithVar(), nars.entity.Concept.getBelief(), and nars.inference.LocalRules.match().
{
         if (getTruth() == null) {
             return new Sentence((Term) getContent().clone(), getPunctuation(), null, (Stamp) getStamp().clone());
         }
         return new Sentence((Term) getContent().clone(), getPunctuation(), new TruthValue(getTruth()), (Stamp) getStamp().clone(), isRevisible());
     }
cloneContent()
Term nars.entity.Sentence.cloneContent ()
Clone the content of the sentence.
Returns
A clone of the content Term
Definition at line 156 of file Sentence.java.
References nars.language.Term.clone(), and nars.entity.Sentence.getContent().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric(), nars.inference.RuleTables.asymmetricSymmetric(), and nars.inference.RuleTables.symmetricSymmetric().
{
         return (Term) getContent().clone();
     }
containQueryVar()
static boolean nars.entity.Sentence.containQueryVar (SentenceStruct sentence) static
Definition at line 217 of file Sentence.java.
References nars.io.Symbols.VAR_QUERY.
Referenced by nars.inference.LocalRules.solutionQuality().
{
         return 0 <= sentence.getContent().getName().indexOf(Symbols.VAR_QUERY);
     }
equals()
boolean nars.entity.Sentence.equals (Object that)
To check whether two sentences are equal.
Parameters
that The other sentence
Returns
Whether the two sentences have the same content
Definition at line 83 of file Sentence.java.
References nars.language.Term.equals(), nars.entity.TruthValue.equals(), nars.entity.Stamp.equals(), nars.entity.Sentence.getContent(), nars.entity.Sentence.getPunctuation(), nars.entity.Sentence.getStamp(), nars.entity.Sentence.getTruth(), and nars.entity.Sentence.Sentence().
{
         if (that instanceof Sentence) {
             SentenceStruct t = (Sentence) that;
             return getContent().equals(t.getContent()) && getPunctuation() == t.getPunctuation() && getTruth().equals(t.getTruth()) && getStamp().equals(t.getStamp());
         }
         return false;
     }
equivalentTo()
boolean nars.entity.Sentence.equivalentTo (SentenceStruct that)
Check whether the judgment is equivalent to another one.
The two may have different keys
Parameters
that The other judgment
Returns
Whether the two are equivalent
Definition at line 112 of file Sentence.java.
References nars.language.Term.equals(), nars.entity.TruthValue.equals(), nars.entity.Stamp.equals(), nars.entity.Sentence.getContent(), nars.entity.Sentence.getPunctuation(), nars.entity.Sentence.getStamp(), and nars.entity.Sentence.getTruth().
Referenced by nars.entity.Concept.addToTable().
{
         assert getContent().equals(that.getContent()) && getPunctuation() == that.getPunctuation();
         return getTruth().equals(that.getTruth()) && getStamp().equals(that.getStamp());
     }
getContent()
Term nars.entity.Sentence.getContent ()
The content of a Sentence is a Term.
Get the content of the sentence
Returns
The content Term
Definition at line 134 of file Sentence.java.
References nars.entity.Sentence.content.
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.entity.Sentence.asString(), nars.entity.Sentence.clone(), nars.entity.Sentence.cloneContent(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.LocalRules.convertedJudgment(), nars.inference.RuleTables.dedExe(), nars.inference.RuleTables.detachment(), nars.inference.RuleTables.detachmentWithVar(), nars.entity.Sentence.equals(), nars.entity.Sentence.equivalentTo(), nars.entity.Task.getContent(), nars.entity.Sentence.hashCode(), nars.inference.LocalRules.inferToAsym(), nars.inference.LocalRules.inferToSym(), nars.inference.CompositionalRules.introVarInner(), nars.inference.LocalRules.match(), nars.inference.CompositionalRules.processComposed(), nars.entity.Concept.processQuestion(), nars.inference.RuleTables.reason(), nars.inference.SyllogisticRules.resemblance(), nars.inference.LocalRules.revisible(), nars.entity.Sentence.Sentence(), and nars.entity.Sentence.toKey().
{
         return content;
     }
getPunctuation()
int nars.entity.Sentence.getPunctuation ()
The punctuation also indicates the type of the Sentence: Judgment, Question, or Goal.
Get the punctuation of the sentence
Returns
The character '.' or '?'
Definition at line 143 of file Sentence.java.
References nars.entity.Sentence.punctuation.
Referenced by nars.entity.Sentence.asString(), nars.entity.Sentence.clone(), nars.storage.Memory.doublePremiseTask(), nars.entity.Sentence.equals(), nars.entity.Sentence.equivalentTo(), nars.entity.Sentence.hashCode(), nars.entity.Sentence.isJudgment(), nars.entity.Sentence.isQuestion(), nars.storage.Memory.singlePremiseTask(), and nars.entity.Sentence.toKey().
{
         return punctuation;
     }
getRevisible()
boolean nars.entity.Sentence.getRevisible ()
Definition at line 227 of file Sentence.java.
References nars.entity.Sentence.isRevisible().
Referenced by nars.inference.LocalRules.revisible(), and nars.storage.Memory.singlePremiseTask().
{
         return isRevisible();
     }
getStamp()
Stamp nars.entity.Sentence.getStamp ()
Partial record of the derivation path.
Get the stamp of the sentence
Returns
The stamp
Definition at line 190 of file Sentence.java.
References nars.entity.Sentence.stamp.
Referenced by nars.entity.Sentence.asString(), nars.entity.Sentence.clone(), nars.entity.Sentence.equals(), nars.entity.Sentence.equivalentTo(), nars.entity.Concept.getBelief(), nars.entity.Task.getCreationTime(), nars.entity.Sentence.hashCode(), nars.entity.Concept.processJudgment(), nars.storage.Memory.singlePremiseTask(), nars.entity.TaskLink.toString(), and nars.entity.Sentence.toStringBrief().
{
         return stamp;
     }
getTruth()
TruthValue nars.entity.Sentence.getTruth ()
The truth value of Judgment.
Get the truth value of the sentence
Returns
Truth value, null for question
Definition at line 174 of file Sentence.java.
References nars.entity.Sentence.truth.
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.entity.Sentence.asString(), nars.entity.Sentence.clone(), nars.inference.CompositionalRules.composeCompound(), nars.inference.RuleTables.conditionalAbd(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.RuleTables.contraposition(), nars.inference.LocalRules.conversion(), nars.inference.LocalRules.convertRelation(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.decomposeStatement(), nars.inference.RuleTables.dedExe(), nars.inference.RuleTables.elimiVarDep(), nars.entity.Sentence.equals(), nars.entity.Sentence.equivalentTo(), nars.inference.RuleTables.functionBeggingToBeAsync(), nars.entity.Sentence.hashCode(), nars.inference.LocalRules.inferToAsym(), nars.inference.LocalRules.inferToSym(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.storage.Memory.processNewTask(), nars.entity.Concept.processQuestion(), nars.inference.SyllogisticRules.resemblance(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralCompound(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), nars.entity.Sentence.toKey(), nars.inference.RuleTables.transformNegation(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.StructuralRules.transformProductImage(), nars.inference.RuleTables.transformSetRelation(), nars.inference.StructuralRules.transformSubjectPI(), and nars.inference.BudgetFunctions.update().
{
         return truth;
     }
hashCode()
int nars.entity.Sentence.hashCode ()
To produce the hashcode of a sentence.
Returns
A hashcode
Definition at line 96 of file Sentence.java.
References nars.entity.Sentence.getContent(), nars.entity.Sentence.getPunctuation(), nars.entity.Sentence.getStamp(), nars.entity.Sentence.getTruth(), nars.language.Term.hashCode(), nars.entity.TruthValue.hashCode(), and nars.entity.Stamp.hashCode().
{
         int hash = 5;
         hash = 67 * hash + (getContent() != null ? getContent().hashCode() : 0);
         hash = 67 * hash + getPunctuation();
         hash = 67 * hash + (getTruth() != null ? getTruth().hashCode() : 0);
         hash = 67 * hash + (getStamp() != null ? getStamp().hashCode() : 0);
         return hash;
     }
isJudgment()
boolean nars.entity.Sentence.isJudgment ()
Distinguish Judgment from Goal ("instanceof Judgment" doesn't work)
Returns
Whether the object is a Judgment
Definition at line 204 of file Sentence.java.
References nars.entity.Sentence.getPunctuation(), and nars.io.Symbols.JUDGMENT_MARK.
Referenced by nars.inference.CompositionalRules.composeCompound(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.RuleTables.detachmentWithVar(), nars.entity.Concept.directProcess(), nars.inference.CompositionalRules.introVarInner(), nars.inference.LocalRules.match(), nars.inference.LocalRules.matchAsymSym(), nars.inference.LocalRules.matchReverse(), nars.storage.Memory.processNewTask(), nars.storage.Memory.singlePremiseTask(), nars.inference.LocalRules.solutionEval(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralCompound(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), and nars.inference.RuleTables.transformNegation().
{
         return getPunctuation() == Symbols.JUDGMENT_MARK;
     }
isQuestion()
boolean nars.entity.Sentence.isQuestion ()
Distinguish Question from Quest ("instanceof Question" doesn't work)
Returns
Whether the object is a Question
Definition at line 213 of file Sentence.java.
References nars.entity.Sentence.getPunctuation(), and nars.io.Symbols.QUESTION_MARK.
Referenced by nars.inference.RuleTables.abdIndCom(), nars.storage.Memory.activatedTask(), nars.inference.SyllogisticRules.analogy(), nars.inference.RuleTables.conditionalAbd(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.RuleTables.contraposition(), nars.inference.RuleTables.decomposeStatement(), nars.inference.RuleTables.dedExe(), nars.inference.RuleTables.elimiVarDep(), nars.inference.RuleTables.functionBeggingToBeAsync(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralCompound(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.RuleTables.transformNegation(), nars.inference.StructuralRules.transformProductImage(), and nars.inference.RuleTables.transformSetRelation().
{
         return getPunctuation() == Symbols.QUESTION_MARK;
     }
isRevisible()
boolean nars.entity.Sentence.isRevisible ()
Whether the sentence can be revised.
Definition at line 298 of file Sentence.java.
References nars.entity.Sentence.revisible.
Referenced by nars.entity.Sentence.clone(), and nars.entity.Sentence.getRevisible().
{
         return revisible;
     }
setContent()
void nars.entity.Sentence.setContent (TermStruct t)
Set the content Term of the Sentence.
Parameters
t The new content
Definition at line 165 of file Sentence.java.
References nars.entity.Sentence.content.
Referenced by nars.entity.Sentence.Sentence().
{
         content = (Term) t;
     }
setPunctuation() [1/2]
void nars.entity.Sentence.setPunctuation (int $punctuation$)
Definition at line 148 of file Sentence.java.
References nars.entity.Sentence.punctuation.
Referenced by nars.entity.Sentence.Sentence().
{
         punctuation = (char) ((char) $punctuation$&0xffff);
     }
setPunctuation() [2/2]
void nars.entity.Sentence.setPunctuation (char punctuation)
Definition at line 282 of file Sentence.java.
References nars.entity.Sentence.punctuation.
{
         this.punctuation = punctuation;
     }
setQuestion()
void nars.entity.Sentence.setQuestion (boolean $question$)
Definition at line 223 of file Sentence.java.
{
     }
setRevisible()
void nars.entity.Sentence.setRevisible (boolean b)
Definition at line 232 of file Sentence.java.
References nars.entity.Sentence.revisible.
Referenced by nars.entity.Sentence.Sentence().
{
         revisible = b;
     }
setStamp() [1/2]
void nars.entity.Sentence.setStamp (StampStruct $stamp$)
Definition at line 195 of file Sentence.java.
Referenced by nars.entity.Sentence.Sentence().
{
     }
setStamp() [2/2]
void nars.entity.Sentence.setStamp (Stamp stamp)
Definition at line 292 of file Sentence.java.
References nars.entity.Sentence.stamp.
{
         this.stamp = stamp;
     }
setTruth() [1/2]
void nars.entity.Sentence.setTruth (TruthHandle $truth$)
Definition at line 179 of file Sentence.java.
References nars.entity.Sentence.truth.
Referenced by nars.entity.Sentence.Sentence().
{
         truth = (TruthValue) $truth$;
     }
setTruth() [2/2]
void nars.entity.Sentence.setTruth (TruthValue truth)
Definition at line 287 of file Sentence.java.
References nars.entity.Sentence.truth.
{
         this.truth = truth;
     }
toKey()
static String nars.entity.Sentence.toKey (Sentence sentence) static
Get a String representation of the sentence for key of Task and TaskLink.
Returns
The String
Parameters
sentence
Definition at line 271 of file Sentence.java.
References nars.entity.Sentence.getContent(), nars.entity.Sentence.getPunctuation(), nars.entity.Sentence.getTruth(), and nars.entity.TruthValue.toStringBrief().
Referenced by nars.entity.Task.Task(), and nars.entity.Sentence.toStringBrief().
{
         StringBuffer s = new StringBuffer();
         s.append(sentence.getContent());
         s.append(sentence.getPunctuation() + " ");
         if (sentence.getTruth() != null) {
             s.append(sentence.getTruth().toStringBrief());
         }
         return s.toString();
     }
toString()
String nars.entity.Sentence.toString ()
Get a String representation of the sentence.
Returns
The String
Definition at line 241 of file Sentence.java.
References nars.entity.Sentence.asString().
{
         return asString(this);
     }
toStringBrief()
static String nars.entity.Sentence.toStringBrief (Sentence sentence) static
Get a String representation of the sentence, with 2-digit accuracy.
Returns
The String
Parameters
sentence
Definition at line 262 of file Sentence.java.
References nars.entity.Sentence.getStamp(), and nars.entity.Sentence.toKey().
Referenced by nars.storage.Memory.report(), and nars.entity.Task.toString().
{
         return Sentence.toKey(sentence) + sentence.getStamp();
     }
Member Data Documentation
content
Term nars.entity.Sentence.content private
Definition at line 38 of file Sentence.java.
Referenced by nars.entity.Sentence.getContent(), nars.entity.Sentence.Sentence(), and nars.entity.Sentence.setContent().
punctuation
char nars.entity.Sentence.punctuation private
Definition at line 39 of file Sentence.java.
Referenced by nars.entity.Sentence.getPunctuation(), nars.entity.Sentence.Sentence(), and nars.entity.Sentence.setPunctuation().
revisible
boolean nars.entity.Sentence.revisible private
Definition at line 42 of file Sentence.java.
Referenced by nars.entity.Sentence.isRevisible(), nars.entity.Sentence.Sentence(), and nars.entity.Sentence.setRevisible().
stamp
Stamp nars.entity.Sentence.stamp private
Definition at line 41 of file Sentence.java.
Referenced by nars.entity.Sentence.getStamp(), nars.entity.Sentence.Sentence(), and nars.entity.Sentence.setStamp().
truth
TruthValue nars.entity.Sentence.truth private
Definition at line 40 of file Sentence.java.
Referenced by nars.entity.Sentence.getTruth(), nars.entity.Sentence.Sentence(), and nars.entity.Sentence.setTruth().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/entity/Sentence.java