photon: nars.storage.NARSBatch Class Reference
nars.storage.NARSBatch Class Reference
The main class of the project.
Public Member Functions
NARSBatch ()
ReasonerBatch getReasoner ()
The reasoner.
boolean isDumpLastState ()
void setDumpLastState (boolean dumpLastState)
void setReasoner (ReasonerBatch reasoner)
boolean isLogging ()
void setLogging (boolean logging)
PrintStream getOut ()
void setOut (PrintStream out)
Static Public Member Functions
static void main (String args[])
The entry point of the standalone application.
static void runInference (NARSBatch narsBatch, String args[])
non-static equivalent to main(String[]) : run to completion from an input file
static void init (PrintStream out, ReasonerBatch reasoner, String[] args)
initialize from an input file
static void runInference (NARSBatch narsBatch, BufferedReader r, BufferedWriter w)
non-static equivalent to main(String[]) : run to completion from a BufferedReader
static void init (NARSBatch narsBatch)
Initialize the system at the control center.
static void run (NARSBatch narsBatch)
Run to completion: repeatedly execute NARS working cycle, until Inputs are Finished, or 1000 steps.
static void setPrintStream (NARSBatch narsBatch, PrintStream out)
static boolean isStandAlone ()
Flag to distinguish the two running modes of the project.
static void setStandAlone (boolean standAlone)
Private Member Functions
void log (String mess)
Static Private Member Functions
static void init (ReasonerBatch reasoner, BufferedReader r, BufferedWriter w)
Private Attributes
ReasonerBatch reasoner
transient boolean logging
PrintStream out = System.out
transient boolean dumpLastState = true
Static Private Attributes
static boolean standAlone
Detailed Description
The main class of the project.
Define an application with batch functionality; TODO check duplicated code
Manage the internal working thread. Communicate with Reasoner only.
Definition at line 20 of file NARSBatch.java.
Constructor & Destructor Documentation
NARSBatch()
nars.storage.NARSBatch.NARSBatch ()
Definition at line 47 of file NARSBatch.java.
References nars.storage.NARSBatch.init().
Referenced by nars.storage.NARSBatch.main().
{
         init(this);
     }
Member Function Documentation
getOut()
PrintStream nars.storage.NARSBatch.getOut ()
Definition at line 173 of file NARSBatch.java.
References nars.storage.NARSBatch.out.
Referenced by nars.storage.NARSBatch.runInference().
{
         return out;
     }
getReasoner()
ReasonerBatch nars.storage.NARSBatch.getReasoner ()
The reasoner.
Definition at line 133 of file NARSBatch.java.
References nars.storage.NARSBatch.reasoner.
Referenced by nars.storage.NARSBatch.run(), and nars.storage.NARSBatch.runInference().
{
         return reasoner;
     }
init() [1/3]
static void nars.storage.NARSBatch.init (PrintStream out, ReasonerBatch reasoner, String [] args) static
initialize from an input file
Definition at line 61 of file NARSBatch.java.
References nars.storage.ReasonerBatch.addOutputChannel(), nars.io.ExperienceReader.openLoadFile(), nars.storage.NARSBatch.out, and nars.storage.NARSBatch.reasoner.
Referenced by nars.storage.NARSBatch.NARSBatch(), and nars.storage.NARSBatch.runInference().
{
         if (0 < args.length) {
             ExperienceReader experienceReader = new ExperienceReader(reasoner);
             experienceReader.openLoadFile(args[0]);
         }
         ReasonerBatch.addOutputChannel(reasoner, new ExperienceWriter(reasoner,
                 new PrintWriter(out, true)));
     }
init() [2/3]
static void nars.storage.NARSBatch.init (ReasonerBatch reasoner, BufferedReader r, BufferedWriter w) static private
Definition at line 81 of file NARSBatch.java.
References nars.storage.ReasonerBatch.addOutputChannel(), nars.storage.NARSBatch.reasoner, and nars.io.ExperienceReader.setBufferedReader().
{
         ExperienceReader experienceReader = new ExperienceReader(reasoner);
         experienceReader.setBufferedReader(r);
         ReasonerBatch.addOutputChannel(reasoner, new ExperienceWriter(reasoner,
                 new PrintWriter(w, true)));
     }
init() [3/3]
static void nars.storage.NARSBatch.init (NARSBatch narsBatch) static
Initialize the system at the control center.
Can instantiate multiple reasoners
Parameters
narsBatch
Definition at line 96 of file NARSBatch.java.
References nars.storage.NARSBatch.setReasoner().
{
         narsBatch.setReasoner(new ReasonerBatchBuilder().createReasonerBatch());
     }
isDumpLastState()
boolean nars.storage.NARSBatch.isDumpLastState ()
Definition at line 153 of file NARSBatch.java.
References nars.storage.NARSBatch.dumpLastState.
{
         return dumpLastState;
     }
isLogging()
boolean nars.storage.NARSBatch.isLogging ()
Definition at line 165 of file NARSBatch.java.
References nars.storage.NARSBatch.logging.
Referenced by nars.storage.NARSBatch.log().
{
         return logging;
     }
isStandAlone()
static boolean nars.storage.NARSBatch.isStandAlone () static
Flag to distinguish the two running modes of the project.
Whether the project running as an application.
Returns
true for application; false for applet.
Definition at line 145 of file NARSBatch.java.
References nars.storage.NARSBatch.standAlone.
Referenced by nars.entity.Concept.toString().
{
         return standAlone;
     }
log()
void nars.storage.NARSBatch.log (String mess) private
Definition at line 127 of file NARSBatch.java.
References nars.storage.NARSBatch.isLogging().
Referenced by nars.storage.NARSBatch.run().
{
         if (isLogging())
             System.out.println("/ " + mess);
     }
main()
static void nars.storage.NARSBatch.main (String args[]) static
The entry point of the standalone application.
Create an instance of the class, then run the init(String[]) and run() methods.
Parameters
args optional argument used : one input file
Definition at line 36 of file NARSBatch.java.
References nars.main_nogui.CommandLineParameters.decode(), nars.storage.NARSBatch.NARSBatch(), nars.storage.NARSBatch.runInference(), and nars.storage.NARSBatch.setStandAlone().
{
         NARSBatch nars = new NARSBatch();
         setStandAlone(true);
         CommandLineParameters.decode(args, nars.getReasoner());
         runInference(nars, args);
         // TODO only if single run ( no reset in between )
         if (nars.isDumpLastState())
             System.out.println("\n==== Dump Last State ====\n"
                     + nars.getReasoner());
     }
run()
static void nars.storage.NARSBatch.run (NARSBatch narsBatch) static
Run to completion: repeatedly execute NARS working cycle, until Inputs are Finished, or 1000 steps.
This method is called when the Runnable's thread is started.
Parameters
narsBatch
Definition at line 107 of file NARSBatch.java.
References nars.storage.ReasonerBatch.getClock(), nars.storage.NARSBatch.getReasoner(), nars.storage.ReasonerBatch.getTime(), nars.storage.ReasonerBatch.isFinishedInputs(), nars.storage.NARSBatch.log(), and nars.storage.ReasonerBatch.tick().
Referenced by nars.storage.NARSBatch.runInference().
{
         while (true) {
             narsBatch.log("NARSBatch.run():" + " step "
                     + ReasonerBatch.getTime(narsBatch.getReasoner().getClock())
                     + " " + narsBatch.getReasoner().isFinishedInputs());
             ReasonerBatch.tick(narsBatch.getReasoner());
             narsBatch.log("NARSBatch.run(): after tick" + " step "
                     + ReasonerBatch.getTime(narsBatch.getReasoner().getClock())
                     + " " + narsBatch.getReasoner().isFinishedInputs());
             if (narsBatch.getReasoner().isFinishedInputs()
                     || 1000 == ReasonerBatch.getTime(narsBatch.getReasoner()
                             .getClock()))
                 break;
         }
     }
runInference() [1/2]
static void nars.storage.NARSBatch.runInference (NARSBatch narsBatch, String args[]) static
non-static equivalent to main(String[]) : run to completion from an input file
Definition at line 55 of file NARSBatch.java.
References nars.storage.NARSBatch.getOut(), nars.storage.NARSBatch.getReasoner(), nars.storage.NARSBatch.init(), and nars.storage.NARSBatch.run().
Referenced by nars.storage.NARSBatch.main().
{
         init(narsBatch.getOut(), narsBatch.getReasoner(), args);
         run(narsBatch);
     }
runInference() [2/2]
static void nars.storage.NARSBatch.runInference (NARSBatch narsBatch, BufferedReader r, BufferedWriter w) static
non-static equivalent to main(String[]) : run to completion from a BufferedReader
Definition at line 75 of file NARSBatch.java.
References nars.storage.NARSBatch.getReasoner(), nars.storage.NARSBatch.init(), and nars.storage.NARSBatch.run().
{
         init(narsBatch.getReasoner(), r, w);
         run(narsBatch);
     }
setDumpLastState()
void nars.storage.NARSBatch.setDumpLastState (boolean dumpLastState)
Definition at line 157 of file NARSBatch.java.
References nars.storage.NARSBatch.dumpLastState.
{
         this.dumpLastState = dumpLastState;
     }
setLogging()
void nars.storage.NARSBatch.setLogging (boolean logging)
Definition at line 169 of file NARSBatch.java.
References nars.storage.NARSBatch.logging.
{
         this.logging = logging;
     }
setOut()
void nars.storage.NARSBatch.setOut (PrintStream out)
Definition at line 177 of file NARSBatch.java.
References nars.storage.NARSBatch.out.
Referenced by nars.storage.NARSBatch.setPrintStream().
{
         this.out = out;
     }
setPrintStream()
static void nars.storage.NARSBatch.setPrintStream (NARSBatch narsBatch, PrintStream out) static
Definition at line 123 of file NARSBatch.java.
References nars.storage.NARSBatch.out, and nars.storage.NARSBatch.setOut().
{
         narsBatch.setOut(out);
     }
setReasoner()
void nars.storage.NARSBatch.setReasoner (ReasonerBatch reasoner)
Definition at line 161 of file NARSBatch.java.
References nars.storage.NARSBatch.reasoner.
Referenced by nars.storage.NARSBatch.init().
{
         this.reasoner = reasoner;
     }
setStandAlone()
static void nars.storage.NARSBatch.setStandAlone (boolean standAlone) static
Definition at line 149 of file NARSBatch.java.
References nars.storage.NARSBatch.standAlone.
Referenced by nars.storage.NARSBatch.main().
{
         NARSBatch.standAlone = standAlone;
     }
Member Data Documentation
dumpLastState
transient boolean nars.storage.NARSBatch.dumpLastState = true private
Definition at line 24 of file NARSBatch.java.
Referenced by nars.storage.NARSBatch.isDumpLastState(), and nars.storage.NARSBatch.setDumpLastState().
logging
transient boolean nars.storage.NARSBatch.logging private
Definition at line 22 of file NARSBatch.java.
Referenced by nars.storage.NARSBatch.isLogging(), and nars.storage.NARSBatch.setLogging().
out
PrintStream nars.storage.NARSBatch.out = System.out private
Definition at line 23 of file NARSBatch.java.
Referenced by nars.storage.NARSBatch.getOut(), nars.storage.NARSBatch.init(), nars.storage.NARSBatch.setOut(), and nars.storage.NARSBatch.setPrintStream().
reasoner
ReasonerBatch nars.storage.NARSBatch.reasoner private
Definition at line 21 of file NARSBatch.java.
Referenced by nars.storage.NARSBatch.getReasoner(), nars.storage.NARSBatch.init(), and nars.storage.NARSBatch.setReasoner().
standAlone
boolean nars.storage.NARSBatch.standAlone static private
Definition at line 25 of file NARSBatch.java.
Referenced by nars.storage.NARSBatch.isStandAlone(), and nars.storage.NARSBatch.setStandAlone().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/storage/NARSBatch.java