photon: nars.storage.WorkSpace Interface Reference
nars.storage.WorkSpace Interface Reference
Created by jim on 1/14/16.
Public Member Functions
List< String > getExportStrings ()
AtomicInteger getTaskForgettingRate ()
AtomicInteger getBeliefForgettingRate ()
AtomicInteger getConceptForgettingRate ()
void setBeliefForgettingRate (AtomicInteger beliefForgettingRate)
void setTaskForgettingRate (AtomicInteger taskForgettingRate)
void setConceptForgettingRate (AtomicInteger conceptForgettingRate)
List< Task > getNewTasks ()
void setNewTasks (List< Task > newTasks)
void setExportStrings (List< String > exportStrings)
Term getCurrentTerm ()
void setCurrentTerm (Term currentTerm)
TaskLink getCurrentTaskLink ()
void setCurrentTaskLink (TaskLink currentTaskLink)
Task getCurrentTask ()
void setCurrentTask (Task currentTask)
TermLink getCurrentBeliefLink ()
void setCurrentBeliefLink (TermLink currentBeliefLink)
Sentence getCurrentBelief ()
void setCurrentBelief (Sentence currentBelief)
Stamp getNewStamp ()
void setNewStamp (Stamp newStamp)
Detailed Description
Created by jim on 1/14/16.
Definition at line 12 of file WorkSpace.java.
Member Function Documentation
getBeliefForgettingRate()
AtomicInteger nars.storage.WorkSpace.getBeliefForgettingRate ()
Implemented in nars.storage.Memory.
Referenced by nars.storage.TermLinkBag.forgetRate().
getConceptForgettingRate()
AtomicInteger nars.storage.WorkSpace.getConceptForgettingRate ()
Implemented in nars.storage.Memory.
Referenced by nars.storage.ConceptBag.forgetRate().
getCurrentBelief()
Sentence nars.storage.WorkSpace.getCurrentBelief ()
Implemented in nars.storage.Memory.
getCurrentBeliefLink()
TermLink nars.storage.WorkSpace.getCurrentBeliefLink ()
Implemented in nars.storage.Memory.
Referenced by nars.inference.BudgetFunctions.budgetInference(), nars.inference.LocalRules.revise(), and nars.inference.LocalRules.solutionEval().
getCurrentTask()
Task nars.storage.WorkSpace.getCurrentTask ()
Implemented in nars.storage.Memory.
Referenced by nars.inference.BudgetFunctions.budgetInference(), nars.inference.LocalRules.revise(), and nars.inference.LocalRules.solutionEval().
getCurrentTaskLink()
TaskLink nars.storage.WorkSpace.getCurrentTaskLink ()
Implemented in nars.storage.Memory.
Referenced by nars.inference.BudgetFunctions.budgetInference(), nars.inference.LocalRules.revise(), and nars.inference.LocalRules.solutionEval().
getCurrentTerm()
Term nars.storage.WorkSpace.getCurrentTerm ()
Implemented in nars.storage.Memory.
getExportStrings()
List<String> nars.storage.WorkSpace.getExportStrings ()
Implemented in nars.storage.Memory.
getNewStamp()
Stamp nars.storage.WorkSpace.getNewStamp ()
Implemented in nars.storage.Memory.
getNewTasks()
List<Task> nars.storage.WorkSpace.getNewTasks ()
Implemented in nars.storage.Memory.
Referenced by nars.storage.Memory.noResult().
getTaskForgettingRate()
AtomicInteger nars.storage.WorkSpace.getTaskForgettingRate ()
Implemented in nars.storage.Memory.
Referenced by nars.storage.TaskLinkBag.forgetRate().
setBeliefForgettingRate()
void nars.storage.WorkSpace.setBeliefForgettingRate (AtomicInteger beliefForgettingRate)
Implemented in nars.storage.Memory.
setConceptForgettingRate()
void nars.storage.WorkSpace.setConceptForgettingRate (AtomicInteger conceptForgettingRate)
Implemented in nars.storage.Memory.
setCurrentBelief()
void nars.storage.WorkSpace.setCurrentBelief (Sentence currentBelief)
Implemented in nars.storage.Memory.
setCurrentBeliefLink()
void nars.storage.WorkSpace.setCurrentBeliefLink (TermLink currentBeliefLink)
Implemented in nars.storage.Memory.
setCurrentTask()
void nars.storage.WorkSpace.setCurrentTask (Task currentTask)
Implemented in nars.storage.Memory.
setCurrentTaskLink()
void nars.storage.WorkSpace.setCurrentTaskLink (TaskLink currentTaskLink)
Implemented in nars.storage.Memory.
setCurrentTerm()
void nars.storage.WorkSpace.setCurrentTerm (Term currentTerm)
Implemented in nars.storage.Memory.
setExportStrings()
void nars.storage.WorkSpace.setExportStrings (List< String > exportStrings)
Implemented in nars.storage.Memory.
setNewStamp()
void nars.storage.WorkSpace.setNewStamp (Stamp newStamp)
Implemented in nars.storage.Memory.
setNewTasks()
void nars.storage.WorkSpace.setNewTasks (List< Task > newTasks)
Implemented in nars.storage.Memory.
setTaskForgettingRate()
void nars.storage.WorkSpace.setTaskForgettingRate (AtomicInteger taskForgettingRate)
Implemented in nars.storage.Memory.
The documentation for this interface was generated from the following file:
fabric/src/main/java/nars/storage/WorkSpace.java