photon: nars.language.IntersectionExt Class Reference
nars.language.IntersectionExt Class Reference
A compound term whose extension is the intersection of the extensions of its components.
Public Member Functions
Object clone ()
Clone an object.
String operator ()
Get the operator of the term.
boolean isCommutative ()
Check if the compound is communitative.
Public Member Functions inherited from nars.language.CompoundTerm
abstract String operator ()
Abstract method to get the operator of the compound.
abstract Object clone ()
Abstract clone method.
void setName (String s)
Change the oldName of a CompoundTerm, called after variable substitution.
int getComplexity ()
syntactic complexity of the compound, the sum of those of its components plus 1
boolean isConstant ()
Whether the term names a concept.
void setConstant (boolean isConstant)
Set the constant status.
boolean isCommutative ()
Check if the order of the components matters.
int size ()
get the number of components
Term componentAt (int i)
get a component by index
List< Term > getComponents ()
list of (direct) components
List< Term > cloneComponents ()
Clone the component list.
boolean containComponent (Term t)
Check whether the compound contains a certain component.
boolean containAllComponents (Term t)
Check whether the compound contains all components of another term, or that term as a whole.
boolean containVar ()
Whether this compound term contains any variable term.
void renameVariables ()
Rename the variables in the compound.
void renameVariables (HashMap< Variable, Variable > map)
Rename the variables in the compound.
void applySubstitute (Map< Term, Term > subs)
Recursively apply a substitute to the current CompoundTerm.
List< TermLink > prepareComponentLinks ()
Build TermLink templates to constant components and subcomponents.
void setComponents (List< Term > components)
void setComplexity (short complexity)
Public Member Functions inherited from nars.language.Term
Term (String name)
Constructor with a given name.
String getName ()
Reporting the name of the current Term.
void setName (String $name$)
Object clone ()
Make a new Term with the same name.
boolean equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
int hashCode ()
Produce a hash code for the term.
boolean isConstant ()
Check whether the current Term can name a Concept.
void renameVariables ()
Blank method to be override in CompoundTerm.
int getComplexity ()
The syntactic complexity, for constant automic Term, is 1.
final int compareTo (Term that)
Check the relative order of two Terms.
final String toString ()
The same as getName by default, used in display only.
Static Public Member Functions
static Term make (Term term1, Term term2, Memory memory)
Try to make a new compound from two components.
static Term make (List< Term > argList, Memory memory)
Try to make a new IntersectionExt.
static Term make (TreeSet< Term > set, Memory memory)
Try to make a new compound from a set of components.
Static Public Member Functions inherited from nars.language.CompoundTerm
static Term make (CompoundTerm compound, List< Term > components, Memory memory)
Try to make a compound term from a template and a list of components.
static Term make (String op, List< Term > arg, Memory memory)
Try to make a compound term from an operator and a list of components.
static List< Term > cloneList (List< Term > original)
Deep clone an array list of terms.
static Term addComponents (CompoundTerm t1, Term t2, Memory memory)
Try to add a component into a compound.
static Term reduceComponents (CompoundTerm t1, Term t2, Memory memory)
Try to remove a component from a compound.
static Term setComponent (CompoundTerm compound, int index, Term t, Memory memory)
Try to replace a component in a compound at a given index by another one.
Static Public Member Functions inherited from nars.language.Term
static boolean hasOrIsTerm $par (Term root, Term... leaves)
Private Member Functions
IntersectionExt (List< Term > arg)
Constructor with partial values, called by make.
IntersectionExt (String n, List< Term > cs, boolean con, int i)
Constructor with full values, called by clone.
Static Private Member Functions
static IntersectionExt doCLone (IntersectionExt intersectionExt)
Additional Inherited Members
Protected Member Functions inherited from nars.language.CompoundTerm
CompoundTerm (String name, List< Term > components, boolean isConstant, int complexity)
Constructor called from subclasses constructors to clone the fields.
CompoundTerm ()
Default constructor.
CompoundTerm (List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
CompoundTerm (String name, List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
String makeName ()
default method to make the oldName of the current term from existing fields
Protected Member Functions inherited from nars.language.Term
Term ()
Default constructor that build an internal Term.
Static Protected Member Functions inherited from nars.language.CompoundTerm
static List< Term > argumentsToList (Term ...t2)
build a component list from two terms
static String makeCompoundName (String op, Iterable< Term > arg)
default method to make the oldName of a compound term from given fields
static String makeSetName (char opener, List< Term > arg, char closer)
make the oldName of an ExtensionSet or IntensionSet
static String makeImageName (String op, List< Term > arg, int relationIndex)
default method to make the oldName of an image term from given fields
Protected Attributes inherited from nars.language.Term
String name
A Term is identified uniquely by its name, a sequence of characters in a given alphabet (ASCII or Unicode)
Static Package Functions inherited from nars.language.CompoundTerm
static void calcComplexity (CompoundTerm compoundTerm)
The complexity of the term is the sum of those of the components plus 1.
Detailed Description
A compound term whose extension is the intersection of the extensions of its components.
Definition at line 32 of file IntersectionExt.java.
Constructor & Destructor Documentation
IntersectionExt() [1/2]
nars.language.IntersectionExt.IntersectionExt (List< Term > arg) private
Constructor with partial values, called by make.
Parameters
arg The component list of the term
Definition at line 39 of file IntersectionExt.java.
Referenced by nars.language.IntersectionExt.doCLone(), and nars.language.IntersectionExt.make().
{
         super(arg);
     }
IntersectionExt() [2/2]
nars.language.IntersectionExt.IntersectionExt (String n, List< Term > cs, boolean con, int i) private
Constructor with full values, called by clone.
Parameters
n The name of the term
cs Component list
i Syntactic complexity of the compound
Definition at line 49 of file IntersectionExt.java.
{
         super(n, cs, con, i);
     }
Member Function Documentation
clone()
Object nars.language.IntersectionExt.clone ()
Clone an object.
Returns
A new object, to be casted into a IntersectionExt
Definition at line 57 of file IntersectionExt.java.
References nars.language.IntersectionExt.doCLone().
{
         return doCLone(this);
     }
doCLone()
static IntersectionExt nars.language.IntersectionExt.doCLone (IntersectionExt intersectionExt) static private
Definition at line 62 of file IntersectionExt.java.
References nars.language.CompoundTerm.cloneList(), nars.language.CompoundTerm.getComplexity(), nars.language.CompoundTerm.getComponents(), nars.language.IntersectionExt.IntersectionExt(), nars.language.CompoundTerm.isConstant(), and nars.language.Term.name.
Referenced by nars.language.IntersectionExt.clone().
{
         return new IntersectionExt(intersectionExt.name, (List<Term>) cloneList(intersectionExt.getComponents()), intersectionExt.isConstant(), intersectionExt.getComplexity());
     }
isCommutative()
boolean nars.language.IntersectionExt.isCommutative ()
Check if the compound is communitative.
Returns
true for communitative
Definition at line 144 of file IntersectionExt.java.
{
         return true;
     }
make() [1/3]
static Term nars.language.IntersectionExt.make (Term term1, Term term2, Memory memory) static
Try to make a new compound from two components.
Called by the inference rules.
Parameters
term1 The first compoment
term2 The first compoment
memory Reference to the memory
Returns
A compound generated or a term it reduced to
Definition at line 73 of file IntersectionExt.java.
References nars.language.Term.clone(), nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.CompoundTerm(), nars.language.SetInt.make(), and nars.language.SetExt.make().
Referenced by nars.inference.CompositionalRules.composeCompound(), nars.language.IntersectionExt.make(), and nars.language.CompoundTerm.make().
{
         TreeSet<Term> set;
         if ((term1 instanceof SetInt) && (term2 instanceof SetInt)) {
             set = new TreeSet<Term>(((CompoundTerm) term1).cloneComponents());
             set.addAll(((CompoundTerm) term2).cloneComponents());        // set union
             return SetInt.make(set, memory);
         }
         if ((term1 instanceof SetExt) && (term2 instanceof SetExt)) {
             set = new TreeSet<Term>(((CompoundTerm) term1).cloneComponents());
             set.retainAll(((CompoundTerm) term2).cloneComponents());     // set intersection
             return SetExt.make(set, memory);
         }
         if (term1 instanceof IntersectionExt) {
             set = new TreeSet<Term>(((CompoundTerm) term1).cloneComponents());
             if (term2 instanceof IntersectionExt) {
                 set.addAll(((CompoundTerm) term2).cloneComponents());
             }               // (&,(&,P,Q),(&,R,S)) = (&,P,Q,R,S)
             else {
                 set.add((Term) term2.clone());
             }               // (&,(&,P,Q),R) = (&,P,Q,R)
         } else if (term2 instanceof IntersectionExt) {
             set = new TreeSet<Term>(((CompoundTerm) term2).cloneComponents());
             set.add((Term) term1.clone());    // (&,R,(&,P,Q)) = (&,P,Q,R)
         } else {
             set = new TreeSet<Term>();
             set.add((Term) term1.clone());
             set.add((Term) term2.clone());
         }
         return make(set, memory);
     }
make() [2/3]
static Term nars.language.IntersectionExt.make (List< Term > argList, Memory memory) static
Try to make a new IntersectionExt.
Called by StringParser.
Returns
the Term generated from the arguments
Parameters
argList The list of components
memory Reference to the memory
Definition at line 110 of file IntersectionExt.java.
References nars.language.IntersectionExt.make().
{
         TreeSet<Term> set = new TreeSet<Term>(argList); // sort/merge arguments
         return make(set, memory);
     }
make() [3/3]
static Term nars.language.IntersectionExt.make (TreeSet< Term > set, Memory memory) static
Try to make a new compound from a set of components.
Called by the public make methods.
Parameters
set a set of Term as compoments
memory Reference to the memory
Returns
the Term generated from the arguments
Definition at line 121 of file IntersectionExt.java.
References nars.io.Symbols.INTERSECTION_EXT_OPERATOR, nars.language.IntersectionExt.IntersectionExt(), nars.language.CompoundTerm.makeCompoundName(), nars.language.Term.name, nars.storage.Memory.nameToListedTerm(), and nars.language.CompoundTerm.size().
{
         if (set.size() == 1) {
             return set.first();
         }                         // special case: single component
         ArrayList<Term> argument = new ArrayList<Term>(set);
         String name = makeCompoundName(Symbols.INTERSECTION_EXT_OPERATOR, argument);
         Term t = Memory.nameToListedTerm(memory, name);
         return (t != null) ? t : new IntersectionExt(argument);
     }
operator()
String nars.language.IntersectionExt.operator ()
Get the operator of the term.
Returns
the operator of the term
Definition at line 135 of file IntersectionExt.java.
References nars.io.Symbols.INTERSECTION_EXT_OPERATOR.
{
         return Symbols.INTERSECTION_EXT_OPERATOR;
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/language/IntersectionExt.java