photon: nars.inference.CompositionalRules Class Reference
nars.inference.CompositionalRules Class Reference
Compound term composition and decomposition rules, with two premises.
Static Package Functions
static void composeCompound (Statement taskContent, Statement beliefContent, int index, Memory memory)
{<S ==> M>,
static void introVarInner (Statement premise1, Statement premise2, CompoundTerm oldCompound, Memory memory)
{<M --> S>, <C ==> <M --> P>>} |- <(&&, <#x --> S>, C) ==> <#x --> P>> {<M --> S>, (&&, C, <M --> P>)} |- (&&, C, <<#x --> S> ==> <#x --> P>>)
static TruthValue reduceConjunctionNeg (TruthHandle v1, TruthHandle v2)
{(–, (&&, A, (–, B))), (–, B)} |- (–, A)
static TruthValue reduceDisjunction (TruthHandle v1, TruthHandle v2)
{(||, A, B), (–, B)} |- A
Static Private Member Functions
static void processComposed (Statement statement, Term subject, Term predicate, TruthValue truth, Memory memory)
Finish composing implication term.
static void decomposeCompound (CompoundTerm compound, Term component, Term term1, int index, boolean compoundTask, Memory memory)
{<(S|P) ==> M>,
static void introVarOuter (Statement taskContent, Statement beliefContent, int index, Memory memory)
Introduce a dependent variable in an outer-layer conjunction.
static Term secondCommonTerm (Term term1, Term term2, int index)
Introduce a second independent variable into two terms with a common component.
Detailed Description
Compound term composition and decomposition rules, with two premises.
Forward inference only, except the last group (dependent variable introduction) can also be used backward.
Definition at line 37 of file CompositionalRules.java.
Member Function Documentation
composeCompound()
static void nars.inference.CompositionalRules.composeCompound (Statement taskContent, Statement beliefContent, int index, Memory memory) static package
{<S ==> M>,
<P ==> M>} |- {<(S|P) ==> M>, <(S&P) ==> M>, <(S-P) ==> M>, <(P-S) ==> M>}
Parameters
index The location of the shared term
memory Reference to the memory
Definition at line 51 of file CompositionalRules.java.
References nars.language.CompoundTerm.componentAt(), nars.inference.CompositionalRules.decomposeCompound(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.inference.TruthFunctions.intersection(), nars.inference.CompositionalRules.introVarOuter(), nars.entity.Sentence.isJudgment(), nars.entity.TruthValue.isNegative(), nars.language.IntersectionExt.make(), nars.language.IntersectionInt.make(), nars.inference.TruthFunctions.negation(), nars.inference.CompositionalRules.processComposed(), and nars.inference.TruthFunctions.union().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric().
{
         if (!memory.getCurrentTask().getSentence().isJudgment()
                 || taskContent.getClass() != beliefContent.getClass()) {
             return;
         }
         Term componentT = taskContent.componentAt(1 - index);
         Term componentB = beliefContent.componentAt(1 - index);
         Term componentCommon = taskContent.componentAt(index);
         if (componentT instanceof CompoundTerm
                 && ((CompoundTerm) componentT).containAllComponents(componentB)) {
             decomposeCompound((CompoundTerm) componentT, componentB,
                     componentCommon, index, true, memory);
             return;
         } else if (componentB instanceof CompoundTerm
                 && ((CompoundTerm) componentB).containAllComponents(componentT)) {
             decomposeCompound((CompoundTerm) componentB, componentT,
                     componentCommon, index, false, memory);
             return;
         }
         TruthValue truthT = memory.getCurrentTask().getSentence().getTruth();
         TruthValue truthB = memory.getCurrentBelief().getTruth();
         TruthValue truthOr = TruthFunctions.union(truthT, truthB);
         TruthValue truthAnd = TruthFunctions.intersection(truthT, truthB);
         Term termOr = null;
         Term termAnd = null;
         if (index == 0) {
             if (taskContent instanceof Inheritance) {
                 termOr = IntersectionInt.make(componentT, componentB, memory);
                 if (truthB.isNegative()) {
                     if (!truthT.isNegative()) {
                         termAnd = DifferenceExt.Companion.make(componentT,
                                 componentB, memory);
                         truthAnd = TruthFunctions.intersection(truthT,
                                 TruthFunctions.negation(truthB));
                     }
                 } else if (truthT.isNegative()) {
                     termAnd = DifferenceExt.Companion.make(componentB,
                             componentT, memory);
                     truthAnd = TruthFunctions.intersection(truthB,
                             TruthFunctions.negation(truthT));
                 } else {
                     termAnd = IntersectionExt.make(componentT, componentB,
                             memory);
                 }
             } else if (taskContent instanceof Implication) {
                 termOr = Disjunction.Companion.make(componentT, componentB,
                         memory);
                 termAnd = Conjunction.Companion.make(componentT, componentB,
                         memory);
             }
             processComposed(taskContent, componentCommon, termOr, truthOr,
                     memory);
             processComposed(taskContent, componentCommon, termAnd, truthAnd,
                     memory);
         } else { // index == 1
             if (taskContent instanceof Inheritance) {
                 termOr = IntersectionExt.make(componentT, componentB, memory);
                 if (truthB.isNegative()) {
                     if (!truthT.isNegative()) {
                         termAnd = DifferenceInt.Companion.make(componentT,
                                 componentB, memory);
                         truthAnd = TruthFunctions.intersection(truthT,
                                 TruthFunctions.negation(truthB));
                     }
                 } else if (truthT.isNegative()) {
                     termAnd = DifferenceInt.Companion.make(componentB,
                             componentT, memory);
                     truthAnd = TruthFunctions.intersection(truthB,
                             TruthFunctions.negation(truthT));
                 } else {
                     termAnd = IntersectionInt.make(componentT, componentB,
                             memory);
                 }
             } else if (taskContent instanceof Implication) {
                 termOr = Conjunction.Companion.make(componentT, componentB,
                         memory);
                 termAnd = Disjunction.Companion.make(componentT, componentB,
                         memory);
             }
             processComposed(taskContent, termOr, componentCommon, truthOr,
                     memory);
             processComposed(taskContent, termAnd, componentCommon, truthAnd,
                     memory);
         }
         if (taskContent instanceof Inheritance) {
             introVarOuter(taskContent, beliefContent, index, memory);// introVarImage(taskContent,
             // beliefContent,
             // index,
             // memory);
         }
     }
decomposeCompound()
static void nars.inference.CompositionalRules.decomposeCompound (CompoundTerm compound, Term component, Term term1, int index, boolean compoundTask, Memory memory) static private
{<(S|P) ==> M>,
<P ==> M>} |- <S ==> M>
Parameters
term1 The other term in the contentInd
index The location of the shared term: 0 for subject, 1 for predicate
compoundTask Whether the implication comes from the task
memory Reference to the memory
Definition at line 188 of file CompositionalRules.java.
References nars.language.CompoundTerm.componentAt(), nars.inference.BudgetFunctions.compoundForward(), nars.storage.Memory.doublePremiseTask(), nars.language.Term.equals(), nars.entity.Task.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.language.Statement.make(), nars.language.CompoundTerm.reduceComponents(), nars.inference.TruthFunctions.reduceConjunction(), nars.inference.CompositionalRules.reduceConjunctionNeg(), and nars.inference.CompositionalRules.reduceDisjunction().
Referenced by nars.inference.CompositionalRules.composeCompound().
{
         if (!(compound instanceof Statement)) {
             Term term2 = CompoundTerm.reduceComponents(compound, component,
                     memory);
             if (term2 != null) {
                 Task task = memory.getCurrentTask();
                 Sentence sentence = task.getSentence();
                 Sentence belief = memory.getCurrentBelief();
                 Statement oldContent = (Statement) task.getContent();
                 TruthValue v1, v2;
                 if (compoundTask) {
                     v1 = sentence.getTruth();
                     v2 = belief.getTruth();
                 } else {
                     v1 = belief.getTruth();
                     v2 = sentence.getTruth();
                 }
                 TruthValue truth = null;
                 Term content;
                 if (index == 0) {
                     content = Statement.make(oldContent, term1, term2, memory);
                     if (content != null && oldContent instanceof Inheritance) {
                         if (!(compound instanceof IntersectionExt)) {
                             if (!(compound instanceof IntersectionInt)) {
                                 if (!(compound instanceof SetInt)
                                         || !(component instanceof SetInt)) {
                                     if (!(compound instanceof SetExt)
                                             || !(component instanceof SetExt)) {
                                         if (!(compound instanceof DifferenceExt)) {
                                             if (!(oldContent instanceof Implication)) {
                                                 return;
                                             }
                                             if (compound instanceof Conjunction) {
                                                 truth = TruthFunctions
                                                         .reduceConjunction(v1,
                                                                 v2);
                                             } else if (compound instanceof Disjunction) {
                                                 truth = reduceDisjunction(v1,
                                                         v2);
                                             }
                                         } else {
                                             if (compound.componentAt(0).equals(
                                                     component)) {
                                                 truth = reduceDisjunction(v2,
                                                         v1);
                                             } else {
                                                 truth = reduceConjunctionNeg(
                                                         v1, v2);
                                             }
                                         }
                                     } else {
                                         truth = reduceDisjunction(v1, v2);
                                     }
                                 } else {
                                     truth = TruthFunctions.reduceConjunction(
                                             v1, v2);
                                 }
                             } else {
                                 truth = reduceDisjunction(v1, v2);
                             }
                         } else {
                             truth = TruthFunctions.reduceConjunction(v1, v2);
                         }
                     }
                 } else {
                     content = Statement.make(oldContent, term2, term1, memory);
                     if (content == null) {
                         return;
                     }
                     if (oldContent instanceof Inheritance) {
                         if (compound instanceof IntersectionInt) {
                             truth = TruthFunctions.reduceConjunction(v1, v2);
                         } else if (compound instanceof IntersectionExt) {
                             truth = reduceDisjunction(v1, v2);
                         } else if (compound instanceof SetExt
                                 && component instanceof SetExt) {
                             truth = TruthFunctions.reduceConjunction(v1, v2);
                         } else if (compound instanceof SetInt
                                 && component instanceof SetInt) {
                             truth = reduceDisjunction(v1, v2);
                         } else if (compound instanceof DifferenceInt) {
                             if (compound.componentAt(1).equals(component)) {
                                 truth = reduceDisjunction(v2, v1);
                             } else {
                                 truth = reduceConjunctionNeg(v1, v2);
                             }
                         }
                     } else if (oldContent instanceof Implication)
                         if (compound instanceof Disjunction) {
                             truth = TruthFunctions.reduceConjunction(v1, v2);
                         } else if (compound instanceof Conjunction) {
                             truth = reduceDisjunction(v1, v2);
                         }
                 }
                 if (truth != null) {
                     BudgetValue budget = BudgetFunctions.compoundForward(
                             memory, truth, content);
                     Memory.doublePremiseTask(memory, content, truth, budget);
                 }
             }
         }
     }
introVarInner()
static void nars.inference.CompositionalRules.introVarInner (Statement premise1, Statement premise2, CompoundTerm oldCompound, Memory memory) static package
{<M --> S>, <C ==> <M --> P>>} |- <(&&, <#x --> S>, C) ==> <#x --> P>> {<M --> S>, (&&, C, <M --> P>)} |- (&&, C, <<#x --> S> ==> <#x --> P>>)
     Introduce a second independent variable into two terms with a common
component
Parameters
term1 The first term
term2 The second term
index The index of the terms in their statement
oldCompound The whole contentInd of the first premise, Implication or Conjunction
memory Reference to the memory
Definition at line 440 of file CompositionalRules.java.
References nars.language.CompoundTerm.applySubstitute(), nars.language.CompoundTerm.containComponent(), nars.storage.Memory.doublePremiseTask(), nars.language.Term.equals(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.inference.TruthFunctions.induction(), nars.inference.TruthFunctions.intersection(), nars.entity.Sentence.isJudgment(), nars.language.CompoundTerm.make(), and nars.inference.CompositionalRules.secondCommonTerm().
Referenced by nars.inference.RuleTables.compoundAndStatement(), and nars.inference.RuleTables.detachmentWithVar().
{
         Task task = memory.getCurrentTask();
         Sentence taskSentence = task.getSentence();
         if (!taskSentence.isJudgment() || premise1.getClass() != premise2.getClass() || oldCompound.containComponent(premise1)) {
             return;
         }
         Term subject1 = premise1.getSubject();
         Term subject2 = premise2.getSubject();
         Term predicate1 = premise1.getPredicate();
         Term predicate2 = premise2.getPredicate();
 //        Statement stateInd1, stateInd2, stateDep1, stateDep2;
         Term commonTerm1, commonTerm2;
         if (subject1.equals(subject2)) {
             commonTerm1 = subject1;
             commonTerm2 = secondCommonTerm(predicate1, predicate2, 0);
 //            stateDep1 = Statement.make(premise1, varDep, predicate1, memory);
 //            stateDep2 = Statement.make(premise2, varDep, predicate2, memory);
 //            Term predicate1C = (Term) predicate1.clone();
 //            Term predicate2C = (Term) predicate2.clone();
 //            introVarSecond(predicate1C, predicate2C, 0);
 //            stateInd1 = Statement.make(premise1, varInd, predicate1C, memory);
 //            stateInd2 = Statement.make(premise2, varInd, predicate2C, memory);
         } else if (predicate1.equals(predicate2)) {
             commonTerm1 = predicate1;
             commonTerm2 = secondCommonTerm(subject1, subject2, 0);
 //            stateDep1 = Statement.make(premise1, subject1, varDep, memory);
 //            stateDep2 = Statement.make(premise2, subject2, varDep, memory);
 //            Term subject1C = (Term) subject1.clone();
 //            Term subject2C = (Term) subject2.clone();
 //            introVarSecond(subject1C, subject2C, 1);
 //            stateInd1 = Statement.make(premise1, subject1C, varInd, memory);
 //            stateInd2 = Statement.make(premise2, subject2C, varInd, memory);
         } else {
             return;
         }
 //        Term implication, contentInd, contentDep = null;
 //        if (oldCompound instanceof Implication) {
 //            implication = Statement.make((Statement) oldCompound, oldCompound.componentAt(0), stateInd2, memory);
 //            contentInd = Statement.make((Statement) oldCompound, stateInd1, implication, memory);
 //            if (oldCompound.equals(premise1)) {
 //                return;
 //            }
 //            contentDep = Conjunction.make(oldCompound, premise1, memory);
 //            if (contentDep == null || !(contentDep instanceof CompoundTerm)) {
 //                return;
 //            }
 //            HashMap<Term, Term> substitute = new HashMap<Term, Term>();
 //            substitute.put(memory.currentTerm, new Variable("#varDep"));
 //            ((CompoundTerm) contentDep).applySubstitute(substitute);
 //        } else if (oldCompound instanceof Conjunction) {
 //            implication = Implication.make(stateInd1, stateInd2, memory);
 //            HashMap<Term, Term> subs = new HashMap<Term, Term>();
 //            subs.put(premise2, implication);
 //            contentInd = (Term) oldCompound.clone();
 //            ((CompoundTerm) contentInd).applySubstitute(subs);
 //            contentDep = Conjunction.make(stateDep1, oldCompound, memory);
 //            subs.clear();
 //            subs.put(premise2, stateDep2);
 //            ((CompoundTerm) contentDep).applySubstitute(subs);
 //        } else {
 //            return;
 //        }
         Sentence belief = memory.getCurrentBelief();
         Map<Term, Term> substitute = new HashMap<Term, Term>();
         substitute.put(commonTerm1, new Variable("#varDep2"));
         CompoundTerm content = (CompoundTerm) Conjunction.Companion.make(premise1, oldCompound, memory);
         content.applySubstitute(substitute);
         TruthValue truth = TruthFunctions.intersection(taskSentence.getTruth(), belief.getTruth());
         BudgetValue budget = BudgetFunctions.forward(memory, truth);
         Memory.doublePremiseTask(memory, content, truth, budget, false);
         substitute.clear();
         substitute.put(commonTerm1, new Variable("$varInd1"));
         if (commonTerm2 != null) {
             substitute.put(commonTerm2, new Variable("$varInd2"));
         }
         content = Implication.Companion.make(premise1, oldCompound, memory);
         content.applySubstitute(substitute);
         if (premise1.equals(taskSentence.getContent())) {
             truth = TruthFunctions.induction(belief.getTruth(), taskSentence.getTruth());
         } else {
             truth = TruthFunctions.induction(taskSentence.getTruth(), belief.getTruth());
         }
         budget = BudgetFunctions.forward(memory, truth);
         Memory.doublePremiseTask(memory, content, truth, budget);
     }
introVarOuter()
static void nars.inference.CompositionalRules.introVarOuter (Statement taskContent, Statement beliefContent, int index, Memory memory) static private
Introduce a dependent variable in an outer-layer conjunction.
Parameters
taskContent The first premise <M --> S>
beliefContent The second premise <M --> P>
index The location of the shared term: 0 for subject, 1 for predicate
memory Reference to the memory
Definition at line 308 of file CompositionalRules.java.
References nars.inference.TruthFunctions.comparison(), nars.inference.BudgetFunctions.compoundForward(), nars.storage.Memory.doublePremiseTask(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.language.ImageInt.getTheOtherComponent(), nars.entity.Sentence.getTruth(), nars.inference.TruthFunctions.induction(), nars.inference.TruthFunctions.intersection(), and nars.language.Inheritance.make().
Referenced by nars.inference.CompositionalRules.composeCompound().
{
         TruthValue truthT = memory.getCurrentTask().getSentence().getTruth();
         TruthValue truthB = memory.getCurrentBelief().getTruth();
         Variable varInd = new Variable("$varInd1");
         Variable varInd2 = new Variable("$varInd2");
         Term term11, term12, term21, term22, commonTerm;
         Map<Term, Term> subs = new HashMap<Term, Term>();
         if (index == 0) {
             term11 = varInd;
             term21 = varInd;
             term12 = taskContent.getPredicate();
             term22 = beliefContent.getPredicate();
             if (term12 instanceof ImageExt && term22 instanceof ImageExt) {
                 commonTerm = ((ImageExt) term12).getTheOtherComponent();
                 if (commonTerm == null || !Expr4.INSTANCE.hasOrIsTerm(term22, commonTerm)) {
                     commonTerm = ((ImageExt) term22).getTheOtherComponent();
                     if (commonTerm == null || !Expr4.INSTANCE.hasOrIsTerm(term12, commonTerm)) {
                         commonTerm = null;
                     }
                 }
                 if (commonTerm != null) {
                     subs.put(commonTerm, varInd2);
                     ((CompoundTerm) term12).applySubstitute(subs);
                     ((CompoundTerm) term22).applySubstitute(subs);
                 }
             }
         } else {
             term11 = taskContent.getSubject();
             term21 = beliefContent.getSubject();
             term12 = varInd;
             term22 = varInd;
             if (term11 instanceof ImageInt && term21 instanceof ImageInt) {
                 commonTerm = ImageInt.getTheOtherComponent(((ImageInt) term11));
                 if (commonTerm == null || !Expr4.INSTANCE.hasOrIsTerm(term21, commonTerm)) {
                     commonTerm = ImageInt.getTheOtherComponent(((ImageInt) term21));
                     if (commonTerm == null || !Expr4.INSTANCE.hasOrIsTerm(term11, commonTerm)) {
                         commonTerm = null;
                     }
                 }
                 if (commonTerm != null) {
                     subs.put(commonTerm, varInd2);
                     ((CompoundTerm) term11).applySubstitute(subs);
                     ((CompoundTerm) term21).applySubstitute(subs);
                 }
             }
         }
         Statement state1 = Inheritance.make(term11, term12, memory);
         Statement state2 = Inheritance.make(term21, term22, memory);
         Term content = Implication.Companion.make(state1, state2, memory);
         TruthValue truth = TruthFunctions.induction(truthT, truthB);
         BudgetValue budget = BudgetFunctions.compoundForward(memory, truth, content);
         Memory.doublePremiseTask(memory, content, truth, budget);
         content = Implication.Companion.make(state2, state1, memory);
         truth = TruthFunctions.induction(truthB, truthT);
         budget = BudgetFunctions.compoundForward(memory, truth, content);
         Memory.doublePremiseTask(memory, content, truth, budget);
         content = Equivalence.Companion.make(state1, state2, memory);
         truth = TruthFunctions.comparison(truthT, truthB);
         budget = BudgetFunctions.compoundForward(memory, truth, content);
         Memory.doublePremiseTask(memory, content, truth, budget);
         Variable varDep = new Variable("#varDep");
         if (index == 0) {
             state1 = Inheritance.make(varDep, taskContent.getPredicate(), memory);
             state2 = Inheritance.make(varDep, beliefContent.getPredicate(), memory);
         } else {
             state1 = Inheritance.make(taskContent.getSubject(), varDep, memory);
             state2 = Inheritance.make(beliefContent.getSubject(), varDep, memory);
         }
         content = Conjunction.Companion.make(state1, state2, memory);
         truth = TruthFunctions.intersection(truthT, truthB);
         budget = BudgetFunctions.compoundForward(memory, truth, content);
         Memory.doublePremiseTask(memory, content, truth, budget, false);
     }
processComposed()
static void nars.inference.CompositionalRules.processComposed (Statement statement, Term subject, Term predicate, TruthValue truth, Memory memory) static private
Finish composing implication term.
Parameters
subject Subject of contentInd
predicate Predicate of contentInd
truth TruthValue of the contentInd
memory Reference to the memory
Definition at line 156 of file CompositionalRules.java.
References nars.inference.BudgetFunctions.compoundForward(), nars.storage.Memory.doublePremiseTask(), nars.language.Term.equals(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), and nars.language.Statement.make().
Referenced by nars.inference.CompositionalRules.composeCompound().
{
         if (subject == null || predicate == null) {
             return;
         }
         Term content = Statement.make(statement, subject, predicate, memory);
         if (content == null || content.equals(statement)
                 || content.equals(memory.getCurrentBelief().getContent())) {
             return;
         }
         BudgetValue budget = BudgetFunctions.compoundForward(memory, truth,
                 content);
         Memory.doublePremiseTask(memory, content, truth, budget);
     }
reduceConjunctionNeg()
static TruthValue nars.inference.CompositionalRules.reduceConjunctionNeg (TruthHandle v1, TruthHandle v2) static package
{(–, (&&, A, (–, B))), (–, B)} |- (–, A)
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 576 of file CompositionalRules.java.
References nars.inference.TruthFunctions.negation(), and nars.inference.TruthFunctions.reduceConjunction().
Referenced by nars.inference.CompositionalRules.decomposeCompound().
{
         return TruthFunctions
                 .reduceConjunction(v1, TruthFunctions.negation(v2));
     }
reduceDisjunction()
static TruthValue nars.inference.CompositionalRules.reduceDisjunction (TruthHandle v1, TruthHandle v2) static package
{(||, A, B), (–, B)} |- A
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 590 of file CompositionalRules.java.
References nars.inference.TruthFunctions.deduction(), nars.inference.TruthFunctions.intersection(), and nars.inference.TruthFunctions.negation().
Referenced by nars.inference.CompositionalRules.decomposeCompound().
{
         TruthValue v0 = TruthFunctions.intersection(v1,
                 TruthFunctions.negation(v2));
         return TruthFunctions.deduction(v0, 1f);
     }
secondCommonTerm()
static Term nars.inference.CompositionalRules.secondCommonTerm (Term term1, Term term2, int index) static private
Introduce a second independent variable into two terms with a common component.
Parameters
term1 The first term
term2 The second term
index The index of the terms in their statement
Definition at line 536 of file CompositionalRules.java.
References nars.language.ImageInt.getTheOtherComponent().
Referenced by nars.inference.CompositionalRules.introVarInner().
{
         Term commonTerm = null;
         if (index == 0) {
             if (term1 instanceof ImageExt && term2 instanceof ImageExt) {
                 commonTerm = ((ImageExt) term1).getTheOtherComponent();
                 if (commonTerm == null
                         || !Expr4.INSTANCE.hasOrIsTerm(term2, commonTerm)) {
                     commonTerm = ((ImageExt) term2).getTheOtherComponent();
                     if (commonTerm == null
                             || !Expr4.INSTANCE.hasOrIsTerm(term1, commonTerm)) {
                         commonTerm = null;
                     }
                 }
             }
         } else {
             if (term1 instanceof ImageInt && term2 instanceof ImageInt) {
                 commonTerm = ImageInt.getTheOtherComponent(((ImageInt) term1));
                 if (commonTerm == null
                         || !Expr4.INSTANCE.hasOrIsTerm(term2, commonTerm)) {
                     commonTerm = ImageInt
                             .getTheOtherComponent(((ImageInt) term2));
                     if (commonTerm == null
                             || !Expr4.INSTANCE.hasOrIsTerm(term1, commonTerm)) {
                         commonTerm = null;
                     }
                 }
             }
         }
         return commonTerm;
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/inference/CompositionalRules.java