photon: nars.entity.BudgetValue Class Reference
nars.entity.BudgetValue Class Reference
A triple of priority (current), durability (decay), and quality (long-term average).
Public Member Functions
BudgetValue ()
Default constructor.
BudgetValue (float p, float d, float q)
Constructor with initialization.
BudgetValue (BudgetStruct v)
Cloning constructor.
float getPriority ()
Get priority value.
void setPriority (float v)
Change priority value.
void incPriority (float v)
Increase priority value by a percentage of the remaining range.
void decPriority (float v)
Decrease priority value by a percentage of the remaining range.
float getDurability ()
Get durability value.
void setDurability (float v)
Change durability value.
void incDurability (float v)
Increase durability value by a percentage of the remaining range.
void decDurability (float v)
Decrease durability value by a percentage of the remaining range.
float getQuality ()
Get quality value.
void setQuality (float v)
Change quality value.
void incQuality (float v)
Increase quality value by a percentage of the remaining range.
void decQuality (float v)
Decrease quality value by a percentage of the remaining range.
void merge (BudgetStruct that)
Merge one BudgetValue into another.
float summary ()
To summarize a BudgetValue into a single number in [0, 1].
boolean aboveThreshold ()
Whether the budget should get any processing at all.
String toString ()
Fully display the BudgetValue.
String toStringBrief ()
Briefly display the BudgetValue.
Protected Attributes
float priority
The relative share of time resource to be allocated.
float durability
The percent of priority to be kept in a constant period; All priority values “decay” over time, though at different rates.
float quality
The overall (context-independent) evaluation.
Static Private Attributes
static final char MARK = Symbols.BUDGET_VALUE_MARK
The character that marks the two ends of a budget value.
static final char SEPARATOR = Symbols.VALUE_SEPARATOR
The character that separates the factors in a budget value.
Detailed Description
A triple of priority (current), durability (decay), and quality (long-term average).
Definition at line 32 of file BudgetValue.java.
Constructor & Destructor Documentation
BudgetValue() [1/3]
nars.entity.BudgetValue.BudgetValue ()
Default constructor.
Definition at line 53 of file BudgetValue.java.
References nars.entity.BudgetValue.durability, nars.entity.BudgetValue.priority, and nars.entity.BudgetValue.quality.
{
         priority = 0.01f;
         durability = 0.01f;
         quality = 0.01f;
     }
BudgetValue() [2/3]
nars.entity.BudgetValue.BudgetValue (float p, float d, float q)
Constructor with initialization.
Parameters
p Initial priority
d Initial durability
q Initial quality
Definition at line 65 of file BudgetValue.java.
References nars.entity.BudgetValue.durability, nars.entity.BudgetValue.priority, and nars.entity.BudgetValue.quality.
{
         priority = p;
         durability = d;
         quality = q;
     }
BudgetValue() [3/3]
nars.entity.BudgetValue.BudgetValue (BudgetStruct v)
Cloning constructor.
Parameters
v Budget value to be cloned
Definition at line 75 of file BudgetValue.java.
References nars.entity.BudgetValue.durability, nars.entity.BudgetValue.priority, and nars.entity.BudgetValue.quality.
{
         priority = v.getPriority();
         durability = v.getDurability();
         quality = v.getQuality();
     }
Member Function Documentation
aboveThreshold()
boolean nars.entity.BudgetValue.aboveThreshold ()
Whether the budget should get any processing at all.
to be revised to depend on how busy the system is
Returns
The decision on whether to process the Item
Definition at line 199 of file BudgetValue.java.
References nars.storage.Parameters.BUDGET_THRESHOLD, and nars.entity.BudgetValue.summary().
Referenced by nars.entity.Concept.buildTermLinks(), nars.storage.Memory.derivedTask(), nars.entity.Concept.directProcess(), nars.storage.Memory.inputTask(), nars.entity.Concept.linkToTask(), nars.entity.Concept.processJudgment(), and nars.inference.LocalRules.trySolution().
{
         return (summary() >= Parameters.BUDGET_THRESHOLD);
     }
decDurability()
void nars.entity.BudgetValue.decDurability (float v)
Decrease durability value by a percentage of the remaining range.
Parameters
v The decreasing percent
Definition at line 141 of file BudgetValue.java.
References nars.inference.UtilityFunctions.and(), and nars.entity.BudgetValue.durability.
Referenced by nars.entity.Item.decDurability().
{
         durability= UtilityFunctions.and(durability, v);
     }
decPriority()
void nars.entity.BudgetValue.decPriority (float v)
Decrease priority value by a percentage of the remaining range.
Parameters
v The decreasing percent
Definition at line 109 of file BudgetValue.java.
References nars.inference.UtilityFunctions.and(), and nars.entity.BudgetValue.priority.
Referenced by nars.entity.Item.decPriority(), and nars.entity.Concept.processJudgment().
{
         priority= UtilityFunctions.and(priority, v);
     }
decQuality()
void nars.entity.BudgetValue.decQuality (float v)
Decrease quality value by a percentage of the remaining range.
Parameters
v The decreasing percent
Definition at line 173 of file BudgetValue.java.
References nars.inference.UtilityFunctions.and(), and nars.entity.BudgetValue.quality.
{
         quality= UtilityFunctions.and(quality, v);
     }
getDurability()
float nars.entity.BudgetValue.getDurability ()
Get durability value.
Returns
The current durability
Definition at line 117 of file BudgetValue.java.
References nars.entity.BudgetValue.durability.
Referenced by nars.entity.Item.getDurability(), and nars.inference.BudgetFunctions.merge().
{
         return durability;
     }
getPriority()
float nars.entity.BudgetValue.getPriority ()
Get priority value.
Returns
The current priority
Definition at line 85 of file BudgetValue.java.
References nars.entity.BudgetValue.priority.
Referenced by nars.entity.Item.getPriority().
{
         return priority ;
     }
getQuality()
float nars.entity.BudgetValue.getQuality ()
Get quality value.
Returns
The current quality
Definition at line 149 of file BudgetValue.java.
References nars.entity.BudgetValue.quality.
Referenced by nars.entity.Item.getQuality(), and nars.inference.BudgetFunctions.merge().
{
         return quality ;
     }
incDurability()
void nars.entity.BudgetValue.incDurability (float v)
Increase durability value by a percentage of the remaining range.
Parameters
v The increasing percent
Definition at line 133 of file BudgetValue.java.
References nars.entity.BudgetValue.durability, and nars.inference.UtilityFunctions.or().
Referenced by nars.entity.Item.incDurability().
{
         durability= UtilityFunctions.or(durability, v);
     }
incPriority()
void nars.entity.BudgetValue.incPriority (float v)
Increase priority value by a percentage of the remaining range.
Parameters
v The increasing percent
Definition at line 101 of file BudgetValue.java.
References nars.inference.UtilityFunctions.or(), and nars.entity.BudgetValue.priority.
Referenced by nars.entity.Item.incPriority(), and nars.inference.BudgetFunctions.merge().
{
         priority= UtilityFunctions.or(priority, v);
     }
incQuality()
void nars.entity.BudgetValue.incQuality (float v)
Increase quality value by a percentage of the remaining range.
Parameters
v The increasing percent
Definition at line 165 of file BudgetValue.java.
References nars.inference.UtilityFunctions.or(), and nars.entity.BudgetValue.quality.
{
         quality= UtilityFunctions.or(quality, v);
     }
merge()
void nars.entity.BudgetValue.merge (BudgetStruct that)
Merge one BudgetValue into another.
Parameters
that The other Budget
Definition at line 181 of file BudgetValue.java.
References nars.inference.BudgetFunctions.merge().
Referenced by nars.entity.Item.merge().
{
         BudgetFunctions.merge(this, that);
     }
setDurability()
void nars.entity.BudgetValue.setDurability (float v)
Change durability value.
Parameters
v The new durability
Definition at line 125 of file BudgetValue.java.
References nars.entity.BudgetValue.durability.
Referenced by nars.inference.BudgetFunctions.merge(), and nars.entity.Item.setDurability().
{
         durability= v;
     }
setPriority()
void nars.entity.BudgetValue.setPriority (float v)
Change priority value.
Parameters
v The new priority
Definition at line 93 of file BudgetValue.java.
References nars.entity.BudgetValue.priority.
Referenced by nars.entity.Item.setPriority().
{
         priority= v;
     }
setQuality()
void nars.entity.BudgetValue.setQuality (float v)
Change quality value.
Parameters
v The new quality
Definition at line 157 of file BudgetValue.java.
References nars.entity.BudgetValue.quality.
Referenced by nars.inference.BudgetFunctions.merge(), and nars.entity.Item.setQuality().
{
         quality= v;
     }
summary()
float nars.entity.BudgetValue.summary ()
To summarize a BudgetValue into a single number in [0, 1].
Returns
The summary value
Definition at line 189 of file BudgetValue.java.
References nars.inference.UtilityFunctions.aveGeo(), nars.entity.BudgetValue.durability, nars.entity.BudgetValue.priority, and nars.entity.BudgetValue.quality.
Referenced by nars.entity.BudgetValue.aboveThreshold(), nars.storage.Memory.activatedTask(), and nars.storage.Memory.derivedTask().
{
         return UtilityFunctions.aveGeo(priority, durability, quality);
     }
toString()
String nars.entity.BudgetValue.toString ()
Fully display the BudgetValue.
Returns
String representation of the value
Definition at line 208 of file BudgetValue.java.
References nars.entity.BudgetValue.durability, nars.entity.BudgetValue.MARK, nars.entity.BudgetValue.priority, nars.entity.BudgetValue.quality, and nars.entity.BudgetValue.SEPARATOR.
{
         return ""+ MARK + priority + SEPARATOR + durability + SEPARATOR + quality  + MARK;
     }
toStringBrief()
String nars.entity.BudgetValue.toStringBrief ()
Briefly display the BudgetValue.
Returns
String representation of the value with 2-digit accuracy
Definition at line 216 of file BudgetValue.java.
References nars.entity.BudgetValue.durability, nars.entity.BudgetValue.MARK, nars.entity.BudgetValue.priority, nars.entity.BudgetValue.quality, and nars.entity.BudgetValue.SEPARATOR.
Referenced by nars.entity.Item.toStringBrief().
{
         return ""+MARK + priority  + SEPARATOR + durability  + SEPARATOR + quality + MARK;
     }
Member Data Documentation
durability
float nars.entity.BudgetValue.durability protected
The percent of priority to be kept in a constant period; All priority values “decay” over time, though at different rates.
Each item is given a “durability” factor in (0, 1) to specify the percentage of priority level left after each reevaluation
Definition at line 46 of file BudgetValue.java.
Referenced by nars.entity.BudgetValue.BudgetValue(), nars.entity.BudgetValue.decDurability(), nars.entity.BudgetValue.getDurability(), nars.entity.BudgetValue.incDurability(), nars.entity.BudgetValue.setDurability(), nars.entity.BudgetValue.summary(), nars.entity.BudgetValue.toString(), and nars.entity.BudgetValue.toStringBrief().
MARK
final char nars.entity.BudgetValue.MARK = Symbols.BUDGET_VALUE_MARK static private
The character that marks the two ends of a budget value.
Definition at line 35 of file BudgetValue.java.
Referenced by nars.entity.BudgetValue.toString(), and nars.entity.BudgetValue.toStringBrief().
priority
float nars.entity.BudgetValue.priority protected
The relative share of time resource to be allocated.
Definition at line 39 of file BudgetValue.java.
Referenced by nars.entity.BudgetValue.BudgetValue(), nars.entity.BudgetValue.decPriority(), nars.entity.BudgetValue.getPriority(), nars.entity.BudgetValue.incPriority(), nars.entity.BudgetValue.setPriority(), nars.entity.BudgetValue.summary(), nars.entity.BudgetValue.toString(), and nars.entity.BudgetValue.toStringBrief().
quality
float nars.entity.BudgetValue.quality protected
The overall (context-independent) evaluation.
Definition at line 48 of file BudgetValue.java.
Referenced by nars.entity.BudgetValue.BudgetValue(), nars.entity.BudgetValue.decQuality(), nars.entity.BudgetValue.getQuality(), nars.entity.BudgetValue.incQuality(), nars.entity.BudgetValue.setQuality(), nars.entity.BudgetValue.summary(), nars.entity.BudgetValue.toString(), and nars.entity.BudgetValue.toStringBrief().
SEPARATOR
final char nars.entity.BudgetValue.SEPARATOR = Symbols.VALUE_SEPARATOR static private
The character that separates the factors in a budget value.
Definition at line 37 of file BudgetValue.java.
Referenced by nars.entity.BudgetValue.toString(), and nars.entity.BudgetValue.toStringBrief().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/entity/BudgetValue.java