photon: nars.language.Term Class Reference
nars.language.Term Class Reference
Term is the basic component of Narsese, and the object of processing in NARS.
Public Member Functions
Term (String name)
Constructor with a given name.
String getName ()
Reporting the name of the current Term.
void setName (String $name$)
Object clone ()
Make a new Term with the same name.
boolean equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
int hashCode ()
Produce a hash code for the term.
boolean isConstant ()
Check whether the current Term can name a Concept.
void renameVariables ()
Blank method to be override in CompoundTerm.
int getComplexity ()
The syntactic complexity, for constant automic Term, is 1.
final int compareTo (Term that)
Check the relative order of two Terms.
final String toString ()
The same as getName by default, used in display only.
Static Public Member Functions
static boolean hasOrIsTerm $par (Term root, Term... leaves)
Protected Member Functions
Term ()
Default constructor that build an internal Term.
Protected Attributes
String name
A Term is identified uniquely by its name, a sequence of characters in a given alphabet (ASCII or Unicode)
Detailed Description
Term is the basic component of Narsese, and the object of processing in NARS.
A Term may have an associated Concept containing relations with other Terms. It is not linked in the Term, because a Concept may be forgot while the Term exists. Multiple objects may represent the same Term.
Definition at line 35 of file Term.java.
Constructor & Destructor Documentation
Term() [1/2]
nars.language.Term.Term () protected
Default constructor that build an internal Term.
Definition at line 46 of file Term.java.
Referenced by nars.language.Term.clone().
                      {
     }
Term() [2/2]
nars.language.Term.Term (String name)
Constructor with a given name.
Parameters
name A String as the name of the Term
Definition at line 54 of file Term.java.
References nars.language.Term.name.
{
         this.name = name;
     }
Member Function Documentation
$par()
static boolean hasOrIsTerm nars.language.Term.$par (Term root, Term... leaves) static
Definition at line 58 of file Term.java.
{
         return Arrays.stream(leaves).anyMatch(term -> Objects.equals(root, term)) || root instanceof CompoundTerm && ((CompoundTerm) root).getComponents().stream().anyMatch(t -> hasOrIsTerm$par(t, leaves));
     }
clone()
Object nars.language.Term.clone ()
Make a new Term with the same name.
Returns
The new Term
Definition at line 82 of file Term.java.
References nars.language.Term.name, and nars.language.Term.Term().
Referenced by nars.language.CompoundTerm.applySubstitute(), nars.entity.Sentence.cloneContent(), nars.language.IntersectionInt.make(), nars.language.IntersectionExt.make(), nars.inference.LocalRules.match(), nars.inference.RuleTables.reason(), and nars.inference.RuleTables.transformTask().
{
         return new Term(name);
     }
compareTo()
final int nars.language.Term.compareTo (Term that)
Check the relative order of two Terms.
Parameters
that The Term to be compared with the current Term
Returns
The same as compareTo as defined on Strings
Definition at line 137 of file Term.java.
References nars.language.Term.getName(), and nars.language.Term.name.
Referenced by nars.language.Similarity.make().
{
         return name.compareTo(that.getName());
     }
equals()
boolean nars.language.Term.equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
Parameters
that The Term to be compared with the current Term
Returns
Whether the two Terms are equal
Definition at line 93 of file Term.java.
References nars.language.Term.getName(), and nars.language.Term.name.
Referenced by nars.inference.RuleTables.asymmetricAsymmetric(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.LocalRules.convertedJudgment(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.detachmentWithVar(), nars.entity.Sentence.equals(), nars.entity.Sentence.equivalentTo(), nars.inference.CompositionalRules.introVarInner(), nars.language.Statement.invalidStatement(), nars.language.ImageExt.make(), nars.language.ImageInt.make(), nars.entity.TaskLink.novel(), nars.inference.CompositionalRules.processComposed(), nars.entity.Concept.processQuestion(), nars.language.CompoundTerm.renameVariables(), nars.inference.LocalRules.revisible(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), nars.entity.TermLink.TermLink(), and nars.inference.StructuralRules.transformProductImage().
{
         return (that instanceof Term) && name.equals(((Term) that).getName());
     }
getComplexity()
int nars.language.Term.getComplexity ()
The syntactic complexity, for constant automic Term, is 1.
Returns
The conplexity of the term, an integer
Definition at line 127 of file Term.java.
Referenced by nars.language.CompoundTerm.calcComplexity(), nars.inference.BudgetFunctions.compoundBackward(), nars.inference.BudgetFunctions.compoundBackwardWeak(), nars.inference.BudgetFunctions.compoundForward(), and nars.entity.Concept.getQuality().
{
         return 1;
     }
getName()
String nars.language.Term.getName ()
Reporting the name of the current Term.
Returns
The name of the term as a String
Definition at line 67 of file Term.java.
References nars.language.Term.name.
Referenced by nars.language.Term.compareTo(), nars.entity.Concept.Concept(), nars.inference.LocalRules.convertedJudgment(), nars.language.Term.equals(), nars.storage.Memory.getConcept(), nars.io.StringParser.parseTask(), nars.language.CompoundTerm.renameVariables(), and nars.entity.TermLink.TermLink().
{
         return name;
     }
hashCode()
int nars.language.Term.hashCode ()
Produce a hash code for the term.
Returns
An integer hash code
Definition at line 103 of file Term.java.
References nars.language.Term.name.
Referenced by nars.entity.Sentence.hashCode().
{
         return (name != null ? name.hashCode() : 7);
     }
isConstant()
boolean nars.language.Term.isConstant ()
Check whether the current Term can name a Concept.
Returns
A Term is constant by default
Definition at line 112 of file Term.java.
Referenced by nars.inference.RuleTables.detachmentWithVar(), nars.storage.Memory.getConcept(), nars.language.CompoundTerm.prepareComponentLinks(), and nars.inference.StructuralRules.structuralCompound().
{
         return true;
     }
renameVariables()
void nars.language.Term.renameVariables ()
Blank method to be override in CompoundTerm.
Definition at line 119 of file Term.java.
Referenced by nars.entity.Sentence.Sentence().
{
     }
setName()
void nars.language.Term.setName (String $name$)
Definition at line 72 of file Term.java.
References nars.language.Term.name.
{
         name = $name$;
     }
toString()
final String nars.language.Term.toString ()
The same as getName by default, used in display only.
Returns
The name of the term as a String
Definition at line 147 of file Term.java.
References nars.language.Term.name.
{
         return name;
     }
Member Data Documentation
name
String nars.language.Term.name protected
A Term is identified uniquely by its name, a sequence of characters in a given alphabet (ASCII or Unicode)
Definition at line 41 of file Term.java.
Referenced by nars.language.CompoundTerm.applySubstitute(), nars.language.Variable.clone(), nars.language.SetInt.clone(), nars.language.Inheritance.clone(), nars.language.Similarity.clone(), nars.language.Negation.clone(), nars.language.Product.clone(), nars.language.SetExt.clone(), nars.language.ImageInt.clone(), nars.language.Term.clone(), nars.language.ImageExt.clone(), nars.language.Term.compareTo(), nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.containVar(), nars.language.IntersectionInt.doCLone(), nars.language.IntersectionExt.doCLone(), nars.language.Term.equals(), nars.language.Term.getName(), nars.language.Variable.getType(), nars.language.Term.hashCode(), nars.language.Similarity.make(), nars.language.Product.make(), nars.language.Inheritance.make(), nars.language.Negation.make(), nars.language.SetInt.make(), nars.language.IntersectionExt.make(), nars.language.IntersectionInt.make(), nars.language.ImageInt.make(), nars.language.ImageExt.make(), nars.language.CompoundTerm.makeCompoundName(), nars.language.CompoundTerm.makeImageName(), nars.language.CompoundTerm.makeSetName(), nars.language.Term.setName(), nars.language.CompoundTerm.setName(), nars.language.Term.Term(), and nars.language.Term.toString().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/language/Term.java