photon: nars.storage.TermLinkBag Class Reference
nars.storage.TermLinkBag Class Reference
Contains TermLinks to relevant (compound or component) Terms.
Public Member Functions
TermLinkBag (WorkSpace memory)
Constructor.
TermLink takeOut (TaskLink taskLink, long time)
Replace default to prevent repeated inference, by checking TaskLink.
Public Member Functions inherited from nars.storage.Bag< TermLink >
void init ()
float averagePriority ()
Get the average priority of Items.
boolean contains (Type it)
Check if an item is in the bag.
Type get (String key)
Get an Item by key.
boolean putIn (Type newItem)
Add a new Item into the Bag.
boolean putBack (Type oldItem)
Put an item back into the itemTable.
Type takeOut ()
Choose an Item according to priority distribution and take it out of the Bag.
Type pickOut (String key)
Pick an item by key, then remove it from the bag.
void addBagObserver (BagObserver bagObserver, String title)
To start displaying the Bag in a BagWindow.
void play ()
Resume display.
void stop ()
Stop display.
void refresh ()
Refresh display.
String toString ()
Collect Bag content into a String for display.
String toStringLong ()
TODO bad paste from preceding.
void setShowLevel (int showLevel)
Protected Member Functions
int capacity ()
Get the (constant) capacity of TermLinkBag.
int forgetRate ()
Get the (adjustable) forget rate of TermLinkBag.
Protected Member Functions inherited from nars.storage.Bag< TermLink >
abstract int capacity ()
To get the capacity of the concrete subclass.
Bag (WorkSpace memory)
constructor, called from subclasses
abstract int forgetRate ()
Get the item decay rate, which differs in difference subclass, and can be changed in run time by the user, so not a constant.
boolean emptyLevel (int n)
Check whether a level is empty.
void outOfBase (Type oldItem)
Remove an item from itemTable, then adjust mass.
Additional Inherited Members
Protected Attributes inherited from nars.storage.Bag< TermLink >
WorkSpace memory
whether this bag has an active window
Package Functions inherited from nars.storage.Bag< TermLink >
String showSizes ()
Detailed Description
Contains TermLinks to relevant (compound or component) Terms.
Definition at line 28 of file TermLinkBag.java.
Constructor & Destructor Documentation
TermLinkBag()
nars.storage.TermLinkBag.TermLinkBag (WorkSpace memory)
Constructor.
Parameters
memory The reference of memory
Definition at line 33 of file TermLinkBag.java.
References nars.storage.Bag< TermLink >.memory.
{
         super(memory);
     }
Member Function Documentation
capacity()
int nars.storage.TermLinkBag.capacity () protected
Get the (constant) capacity of TermLinkBag.
Returns
The capacity of TermLinkBag
Definition at line 41 of file TermLinkBag.java.
References nars.storage.Parameters.TERM_LINK_BAG_SIZE.
{
         return Parameters.TERM_LINK_BAG_SIZE;
     }
forgetRate()
int nars.storage.TermLinkBag.forgetRate () protected
Get the (adjustable) forget rate of TermLinkBag.
Returns
The forget rate of TermLinkBag
Definition at line 49 of file TermLinkBag.java.
References nars.storage.WorkSpace.getBeliefForgettingRate(), and nars.storage.Bag< TermLink >.memory.
{
         return memory.getBeliefForgettingRate().get();
     }
takeOut()
TermLink nars.storage.TermLinkBag.takeOut (TaskLink taskLink, long time)
Replace default to prevent repeated inference, by checking TaskLink.
Parameters
taskLink The selected TaskLink
time The current time
Returns
The selected TermLink
Definition at line 59 of file TermLinkBag.java.
References nars.storage.Parameters.MAX_MATCHED_TERM_LINK, nars.entity.TaskLink.novel(), nars.storage.Bag< TermLink >.putBack(), and nars.storage.Bag< TermLink >.takeOut().
Referenced by nars.entity.Concept.fireFromProcessConcept().
{
         for (int i = 0; i < Parameters.MAX_MATCHED_TERM_LINK; i++) {
             TermLink termLink = takeOut();
             if (termLink == null) {
                 return null;
             }
             if (taskLink.novel(termLink, time)) {
                 return termLink;
             }
             putBack(termLink);
         }
         return null;
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/storage/TermLinkBag.java