photon: nars.inference.BudgetFunctions Class Reference
nars.inference.BudgetFunctions Class Reference
Budget functions for resources allocation.
Static Public Member Functions
static float truthToQuality (TruthHandle t)
Determine the quality of a judgment by its truth value alone.
static void activate (Concept concept, BudgetStruct budget)
Activate a concept by an incoming TaskLink.
static void forget (BudgetStruct budget, float forgetRate, float relativeThreshold)
Decrease Priority after an item is used, called in Bag.
static void merge (BudgetValue baseValue, BudgetStruct adjustValue)
Merge an item into another one in a bag, when the two are identical except in budget values.
static BudgetValue backward (WorkSpace memory, TruthHandle truth)
Backward inference result and adjustment, stronger case.
static BudgetValue backwardWeak (WorkSpace memory, TruthHandle truth)
Backward inference result and adjustment, weaker case.
static BudgetValue compoundForward (WorkSpace memory, TruthHandle truth, Term content)
Forward inference with CompoundTerm conclusion.
static BudgetValue compoundBackward (Term content, WorkSpace memory)
Backward inference with CompoundTerm conclusion, stronger case.
static BudgetValue compoundBackwardWeak (Term content, WorkSpace memory)
Backward inference with CompoundTerm conclusion, weaker case.
static float aveAri (float... arr)
A function where the output is the arithmetic average the inputs.
Static Public Member Functions inherited from nars.inference.UtilityFunctions
static float and (float... arr)
A function where the output is conjunctively determined by the inputs.
static float or (float... arr)
A function where the output is disjunctively determined by the inputs.
static float aveGeo (float... arr)
A function where the output is the geometric average the inputs.
static float w2c (float w)
A function to convert weight to confidence.
Static Package Functions
static BudgetValue update (Task task, TruthValue bTruth)
Update a belief.
static BudgetValue forward (WorkSpace memory, TruthHandle truth)
Forward inference result and adjustment.
Static Private Member Functions
static BudgetValue budgetInference (float qual, int complexity, WorkSpace memory)
Common processing for all inference step.
Detailed Description
Budget functions for resources allocation.
Definition at line 32 of file BudgetFunctions.java.
Member Function Documentation
activate()
static void nars.inference.BudgetFunctions.activate (Concept concept, BudgetStruct budget) static
Activate a concept by an incoming TaskLink.
Parameters
concept The concept
budget The budget for the new item
Definition at line 84 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.aveAri(), nars.entity.Item.getDurability(), nars.entity.Item.getPriority(), nars.entity.Concept.getQuality(), nars.inference.UtilityFunctions.or(), nars.entity.Item.setDurability(), nars.entity.Item.setPriority(), and nars.entity.Item.setQuality().
Referenced by nars.storage.Memory.activateConcept().
{
         float oldPri = concept.getPriority();
         float priority = or(oldPri, budget.getPriority());
         float durability = aveAri(concept.getDurability(),
                 budget.getDurability(), oldPri / priority);
         float quality = concept.getQuality();
         concept.setPriority(priority);
         concept.setDurability(durability);
         concept.setQuality(quality);
     }
aveAri()
static float nars.inference.BudgetFunctions.aveAri (float... arr) static
A function where the output is the arithmetic average the inputs.
Parameters
arr The inputs, each in [0, 1]
Returns
The arithmetic average the inputs
Definition at line 256 of file BudgetFunctions.java.
Referenced by nars.inference.BudgetFunctions.activate(), and nars.inference.BudgetFunctions.budgetInference().
{
         float sum = 0;
         for (float f : arr) {
             sum += f;
         }
         return sum / arr.length;
     }
backward()
static BudgetValue nars.inference.BudgetFunctions.backward (WorkSpace memory, TruthHandle truth) static
Backward inference result and adjustment, stronger case.
Parameters
memory Reference to the memory
truth The truth value of the belief deriving the conclusion
Returns
The budget value of the conclusion
Definition at line 162 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.budgetInference(), and nars.inference.BudgetFunctions.truthToQuality().
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.RuleTables.elimiVarDep(), nars.inference.RuleTables.functionBeggingToBeAsync(), and nars.inference.SyllogisticRules.resemblance().
{
         return budgetInference(truthToQuality(truth), 1, memory);
     }
backwardWeak()
static BudgetValue nars.inference.BudgetFunctions.backwardWeak (WorkSpace memory, TruthHandle truth) static
Backward inference result and adjustment, weaker case.
Parameters
memory Reference to the memory
truth The truth value of the belief deriving the conclusion
Returns
The budget value of the conclusion
Definition at line 175 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.budgetInference(), nars.inference.BudgetFunctions.truthToQuality(), and nars.inference.UtilityFunctions.w2c().
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.RuleTables.conditionalAbd(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.RuleTables.dedExe(), nars.inference.RuleTables.elimiVarDep(), and nars.inference.RuleTables.functionBeggingToBeAsync().
{
         return budgetInference(w2c(1) * truthToQuality(truth), 1, memory);
     }
budgetInference()
static BudgetValue nars.inference.BudgetFunctions.budgetInference (float qual, int complexity, WorkSpace memory) static private
Common processing for all inference step.
Parameters
qual Quality of the inference
complexity Syntactic complexity of the conclusion
memory Reference to the memory
Returns
Budget of the conclusion task
Definition at line 233 of file BudgetFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.inference.BudgetFunctions.aveAri(), nars.entity.Item.getBudget(), nars.storage.WorkSpace.getCurrentBeliefLink(), nars.storage.WorkSpace.getCurrentTask(), nars.storage.WorkSpace.getCurrentTaskLink(), nars.entity.Item.getDurability(), nars.entity.Item.getPriority(), and nars.entity.Item.incPriority().
Referenced by nars.inference.BudgetFunctions.backward(), nars.inference.BudgetFunctions.backwardWeak(), nars.inference.BudgetFunctions.compoundBackward(), nars.inference.BudgetFunctions.compoundBackwardWeak(), nars.inference.BudgetFunctions.compoundForward(), and nars.inference.BudgetFunctions.forward().
{
         Item t = memory.getCurrentTaskLink();
         if (t == null)
             t = memory.getCurrentTask();
         float priority = t.getPriority();
         float durability = t.getDurability();
         float quality = (float) (qual / Math.sqrt(complexity));
         TermLink bLink = memory.getCurrentBeliefLink();
         if (bLink != null) {
             priority = aveAri(priority, bLink.getPriority());
             durability = aveAri(durability, bLink.getDurability());
             Item.incPriority(bLink.getBudget(), quality);
         }
         return new BudgetValue(and(priority, quality),
                 and(durability, quality), quality);
     }
compoundBackward()
static BudgetValue nars.inference.BudgetFunctions.compoundBackward (Term content, WorkSpace memory) static
Backward inference with CompoundTerm conclusion, stronger case.
Parameters
content The content of the conclusion
memory Reference to the memory
Returns
The budget of the conclusion
Definition at line 205 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.budgetInference(), and nars.language.Term.getComplexity().
{
         return budgetInference(1, content.getComplexity(), memory);
     }
compoundBackwardWeak()
static BudgetValue nars.inference.BudgetFunctions.compoundBackwardWeak (Term content, WorkSpace memory) static
Backward inference with CompoundTerm conclusion, weaker case.
Parameters
content The content of the conclusion
memory Reference to the memory
Returns
The budget of the conclusion
Definition at line 218 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.budgetInference(), nars.language.Term.getComplexity(), and nars.inference.UtilityFunctions.w2c().
Referenced by nars.inference.RuleTables.contraposition(), and nars.inference.StructuralRules.structuralCompose2().
{
         return budgetInference(w2c(1), content.getComplexity(), memory);
     }
compoundForward()
static BudgetValue nars.inference.BudgetFunctions.compoundForward (WorkSpace memory, TruthHandle truth, Term content) static
Forward inference with CompoundTerm conclusion.
Parameters
memory Reference to the memory
truth The truth value of the conclusion
content The content of the conclusion
Returns
The budget of the conclusion
Definition at line 191 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.budgetInference(), nars.language.Term.getComplexity(), and nars.inference.BudgetFunctions.truthToQuality().
Referenced by nars.inference.CompositionalRules.decomposeCompound(), nars.inference.CompositionalRules.introVarOuter(), and nars.inference.CompositionalRules.processComposed().
{
         return budgetInference(truthToQuality(truth), content.getComplexity(),
                 memory);
     }
forget()
static void nars.inference.BudgetFunctions.forget (BudgetStruct budget, float forgetRate, float relativeThreshold) static
Decrease Priority after an item is used, called in Bag.
After a constant time, p should become d*p. Since in this period, the item is accessed c*p times, each time p-q should multiple d^(1/(c*p)). The intuitive meaning of the parameter "forgetRate" is: after this number of times of access, priority 1 will become d, it is a system parameter adjustable in run time.
Parameters
budget The previous budget value
forgetRate The budget for the new item
relativeThreshold The relative threshold of the bag
Definition at line 112 of file BudgetFunctions.java.
Referenced by nars.storage.Bag< Concept >.putBack().
{
         double quality = budget.getQuality() * relativeThreshold; // re-scaled
                                                                     // quality
         double p = budget.getPriority() - quality; // priority above quality
         if (p > 0) {
             quality += p
                     * Math.pow(budget.getDurability(), 1.0 / (forgetRate * p));
         } // priority Durability
         budget.setPriority((float) quality);
     }
forward()
static BudgetValue nars.inference.BudgetFunctions.forward (WorkSpace memory, TruthHandle truth) static package
Forward inference result and adjustment.
Parameters
truth The truth value of the conclusion
Returns
The budget value of the conclusion
Definition at line 149 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.budgetInference(), and nars.inference.BudgetFunctions.truthToQuality().
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.RuleTables.conditionalAbd(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.LocalRules.conversion(), nars.inference.LocalRules.convertRelation(), nars.inference.RuleTables.dedExe(), nars.inference.RuleTables.functionBeggingToBeAsync(), nars.inference.LocalRules.inferToAsym(), nars.inference.LocalRules.inferToSym(), nars.inference.CompositionalRules.introVarInner(), nars.inference.SyllogisticRules.resemblance(), and nars.inference.StructuralRules.structuralCompound().
{
         return budgetInference(truthToQuality(truth), 1, memory);
     }
merge()
static void nars.inference.BudgetFunctions.merge (BudgetValue baseValue, BudgetStruct adjustValue) static
Merge an item into another one in a bag, when the two are identical except in budget values.
Parameters
baseValue The budget value to be modified
adjustValue The budget doing the adjusting
Definition at line 133 of file BudgetFunctions.java.
References nars.entity.BudgetValue.getDurability(), nars.entity.BudgetValue.getQuality(), nars.entity.BudgetValue.incPriority(), nars.entity.BudgetValue.setDurability(), and nars.entity.BudgetValue.setQuality().
Referenced by nars.entity.BudgetValue.merge().
{
         baseValue.incPriority(adjustValue.getPriority());
         baseValue.setDurability(Math.max(baseValue.getDurability(),
                 adjustValue.getDurability()));
         baseValue.setQuality(Math.max(baseValue.getQuality(),
                 adjustValue.getQuality()));
     }
truthToQuality()
static float nars.inference.BudgetFunctions.truthToQuality (TruthHandle t) static
Determine the quality of a judgment by its truth value alone.
Mainly decided by confidence, though binary judgment is also preferred
Parameters
t The truth value of a judgment
Returns
The quality of the judgment, according to truth value only
Definition at line 44 of file BudgetFunctions.java.
References nars.inference.UtilityFunctions.aveGeo().
Referenced by nars.inference.BudgetFunctions.backward(), nars.inference.BudgetFunctions.backwardWeak(), nars.inference.BudgetFunctions.compoundForward(), nars.inference.BudgetFunctions.forward(), nars.io.StringParser.parseBudget(), nars.inference.LocalRules.revise(), nars.inference.LocalRules.solutionEval(), and nars.inference.BudgetFunctions.update().
{
         float freq = t.getFrequency();
         float conf = t.getConfidence();
         return aveGeo(conf, Math.abs(freq - 0.5f) + freq * 0.5f);
     }
update()
static BudgetValue nars.inference.BudgetFunctions.update (Task task, TruthValue bTruth) static package
Update a belief.
Parameters
task The task containing new belief
bTruth Truth value of the previous belief
Returns
Budget value of the updating task
Definition at line 64 of file BudgetFunctions.java.
References nars.entity.Item.getDurability(), nars.entity.Item.getPriority(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.entity.TruthValue.isExpDifAbs(), nars.inference.UtilityFunctions.or(), and nars.inference.BudgetFunctions.truthToQuality().
{
         TruthValue tTruth = task.getSentence().getTruth();
         float dif = tTruth.isExpDifAbs(bTruth);
         float priority = or(dif, task.getPriority());
         float durability = or(dif, task.getDurability());
         float quality = truthToQuality(bTruth);
         return new BudgetValue(priority, durability, quality);
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/inference/BudgetFunctions.java