photon: nars.language.Statement Class Reference
nars.language.Statement Class Reference abstract
A statement is a compound term, consisting of a subject, a predicate, and a relation symbol in between.
Public Member Functions
boolean invalid ()
Check the validity of a potential Statement.
Term getSubject ()
Return the first component of the statement.
Term getPredicate ()
Return the second component of the statement.
Public Member Functions inherited from nars.language.CompoundTerm
abstract String operator ()
Abstract method to get the operator of the compound.
abstract Object clone ()
Abstract clone method.
void setName (String s)
Change the oldName of a CompoundTerm, called after variable substitution.
int getComplexity ()
syntactic complexity of the compound, the sum of those of its components plus 1
boolean isConstant ()
Whether the term names a concept.
void setConstant (boolean isConstant)
Set the constant status.
boolean isCommutative ()
Check if the order of the components matters.
int size ()
get the number of components
Term componentAt (int i)
get a component by index
List< Term > getComponents ()
list of (direct) components
List< Term > cloneComponents ()
Clone the component list.
boolean containComponent (Term t)
Check whether the compound contains a certain component.
boolean containAllComponents (Term t)
Check whether the compound contains all components of another term, or that term as a whole.
boolean containVar ()
Whether this compound term contains any variable term.
void renameVariables ()
Rename the variables in the compound.
void renameVariables (HashMap< Variable, Variable > map)
Rename the variables in the compound.
void applySubstitute (Map< Term, Term > subs)
Recursively apply a substitute to the current CompoundTerm.
List< TermLink > prepareComponentLinks ()
Build TermLink templates to constant components and subcomponents.
void setComponents (List< Term > components)
void setComplexity (short complexity)
Public Member Functions inherited from nars.language.Term
Term (String name)
Constructor with a given name.
String getName ()
Reporting the name of the current Term.
void setName (String $name$)
Object clone ()
Make a new Term with the same name.
boolean equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
int hashCode ()
Produce a hash code for the term.
boolean isConstant ()
Check whether the current Term can name a Concept.
void renameVariables ()
Blank method to be override in CompoundTerm.
int getComplexity ()
The syntactic complexity, for constant automic Term, is 1.
final int compareTo (Term that)
Check the relative order of two Terms.
final String toString ()
The same as getName by default, used in display only.
Static Public Member Functions
static Statement make (String relation, Term subject, Term predicate, Memory memory)
Make a Statement from String, called by StringParser.
static Statement make (Statement statement, Term subj, Term pred, Memory memory)
Make a Statement from given components, called by the rules.
static boolean invalidStatement (Term subject, Term predicate)
Check the validity of a potential Statement.
Static Public Member Functions inherited from nars.language.CompoundTerm
static Term make (CompoundTerm compound, List< Term > components, Memory memory)
Try to make a compound term from a template and a list of components.
static Term make (String op, List< Term > arg, Memory memory)
Try to make a compound term from an operator and a list of components.
static List< Term > cloneList (List< Term > original)
Deep clone an array list of terms.
static Term addComponents (CompoundTerm t1, Term t2, Memory memory)
Try to add a component into a compound.
static Term reduceComponents (CompoundTerm t1, Term t2, Memory memory)
Try to remove a component from a compound.
static Term setComponent (CompoundTerm compound, int index, Term t, Memory memory)
Try to replace a component in a compound at a given index by another one.
Static Public Member Functions inherited from nars.language.Term
static boolean hasOrIsTerm $par (Term root, Term... leaves)
Protected Member Functions
Statement (List< Term > arg)
Constructor with partial values, called by make.
Statement ()
Default constructor.
Statement (String n, List< Term > cs, boolean con, int i)
Constructor with full values, called by clone.
String makeName ()
Override the default in making the nameStr of the current term from existing fields.
Protected Member Functions inherited from nars.language.CompoundTerm
CompoundTerm (String name, List< Term > components, boolean isConstant, int complexity)
Constructor called from subclasses constructors to clone the fields.
CompoundTerm ()
Default constructor.
CompoundTerm (List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
CompoundTerm (String name, List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
String makeName ()
default method to make the oldName of the current term from existing fields
Protected Member Functions inherited from nars.language.Term
Term ()
Default constructor that build an internal Term.
Static Protected Member Functions
static String makeStatementName (TermStruct subject, String relation, TermStruct predicate)
Default method to make the nameStr of an image term from given fields.
Static Protected Member Functions inherited from nars.language.CompoundTerm
static List< Term > argumentsToList (Term ...t2)
build a component list from two terms
static String makeCompoundName (String op, Iterable< Term > arg)
default method to make the oldName of a compound term from given fields
static String makeSetName (char opener, List< Term > arg, char closer)
make the oldName of an ExtensionSet or IntensionSet
static String makeImageName (String op, List< Term > arg, int relationIndex)
default method to make the oldName of an image term from given fields
Additional Inherited Members
Protected Attributes inherited from nars.language.Term
String name
A Term is identified uniquely by its name, a sequence of characters in a given alphabet (ASCII or Unicode)
Static Package Functions inherited from nars.language.CompoundTerm
static void calcComplexity (CompoundTerm compoundTerm)
The complexity of the term is the sum of those of the components plus 1.
Detailed Description
A statement is a compound term, consisting of a subject, a predicate, and a relation symbol in between.
It can be of either first-order or higher-order.
Definition at line 34 of file Statement.java.
Constructor & Destructor Documentation
Statement() [1/3]
nars.language.Statement.Statement (List< Term > arg) protected
Constructor with partial values, called by make.
Parameters
arg The component list of the term
Definition at line 40 of file Statement.java.
{
         super(arg);
     }
Statement() [2/3]
nars.language.Statement.Statement () protected
Default constructor.
Definition at line 47 of file Statement.java.
Referenced by nars.language.Statement.invalidStatement().
{
     }
Statement() [3/3]
nars.language.Statement.Statement (String n, List< Term > cs, boolean con, int i) protected
Constructor with full values, called by clone.
Parameters
n The nameStr of the term
cs Component list
con Constant indicator
i Syntactic complexity of the compound
Definition at line 57 of file Statement.java.
{
         super(n, cs, con, i);
     }
Member Function Documentation
getPredicate()
Term nars.language.Statement.getPredicate ()
Return the second component of the statement.
Returns
The second component
Definition at line 201 of file Statement.java.
References nars.language.CompoundTerm.getComponents().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric(), nars.inference.RuleTables.asymmetricSymmetric(), nars.inference.RuleTables.contraposition(), nars.inference.LocalRules.convertedJudgment(), nars.inference.RuleTables.detachment(), nars.inference.RuleTables.detachmentWithVar(), nars.inference.LocalRules.inferToAsym(), nars.inference.LocalRules.inferToSym(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.language.Statement.invalid(), nars.language.Statement.invalidStatement(), nars.language.Statement.makeName(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.RuleTables.symmetricSymmetric(), nars.inference.StructuralRules.transformProductImage(), and nars.inference.RuleTables.transformSetRelation().
{
         return getComponents().get(1);
     }
getSubject()
Term nars.language.Statement.getSubject ()
Return the first component of the statement.
Returns
The first component
Definition at line 193 of file Statement.java.
References nars.language.CompoundTerm.getComponents().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric(), nars.inference.RuleTables.asymmetricSymmetric(), nars.inference.RuleTables.contraposition(), nars.inference.LocalRules.convertedJudgment(), nars.inference.RuleTables.detachment(), nars.inference.RuleTables.detachmentWithVar(), nars.inference.LocalRules.inferToAsym(), nars.inference.LocalRules.inferToSym(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.language.Statement.invalid(), nars.language.Statement.invalidStatement(), nars.language.Statement.makeName(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.RuleTables.symmetricSymmetric(), nars.inference.StructuralRules.transformProductImage(), and nars.inference.RuleTables.transformSetRelation().
{
         return getComponents().get(0);
     }
invalid()
boolean nars.language.Statement.invalid ()
Check the validity of a potential Statement.
[To be refined]
Minimum requirement: the two terms cannot be the same, or containing each other as component
Returns
Whether The Statement is invalid
Definition at line 185 of file Statement.java.
References nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), and nars.language.Statement.invalidStatement().
Referenced by nars.inference.RuleTables.detachment().
{
         return invalidStatement(getSubject(), getPredicate());
     }
invalidStatement()
static boolean nars.language.Statement.invalidStatement (Term subject, Term predicate) static
Check the validity of a potential Statement.
[To be refined]
Minimum requirement: the two terms cannot be the same, or containing each other as component
Parameters
subject The first component
predicate The second component
Returns
Whether The Statement is invalid
Definition at line 155 of file Statement.java.
References nars.language.CompoundTerm.CompoundTerm(), nars.language.Term.equals(), nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), and nars.language.Statement.Statement().
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.RuleTables.dedExe(), nars.language.Statement.invalid(), nars.language.Inheritance.make(), nars.language.Similarity.make(), nars.language.Statement.make(), and nars.inference.SyllogisticRules.resemblance().
{
         if (subject.equals(predicate)) {
             return true;
         }
         if ((subject instanceof CompoundTerm) && ((CompoundTerm) subject).containComponent(predicate)) {
             return true;
         }
         if ((predicate instanceof CompoundTerm) && ((CompoundTerm) predicate).containComponent(subject)) {
             return true;
         }
         if ((subject instanceof Statement) && (predicate instanceof Statement)) {
             Statement s1 = (Statement) subject;
             Statement s2 = (Statement) predicate;
             Term t11 = s1.getSubject();
             Term t12 = s1.getPredicate();
             Term t21 = s2.getSubject();
             Term t22 = s2.getPredicate();
             if (t11.equals(t22) && t12.equals(t21)) {
                 return true;
             }
         }
         return false;
     }
make() [1/2]
static Statement nars.language.Statement.make (String relation, Term subject, Term predicate, Memory memory) static
Make a Statement from String, called by StringParser.
Parameters
relation The relation String
subject The first component
predicate The second component
memory Reference to the memeory
Returns
The Statement built
Definition at line 69 of file Statement.java.
References nars.io.Symbols.EQUIVALENCE_RELATION, nars.io.Symbols.IMPLICATION_RELATION, nars.io.Symbols.INHERITANCE_RELATION, nars.io.Symbols.INSTANCE_PROPERTY_RELATION, nars.io.Symbols.INSTANCE_RELATION, nars.language.Statement.invalidStatement(), nars.language.Instance.make(), nars.language.Property.make(), nars.language.InstanceProperty.make(), nars.language.Similarity.make(), nars.language.Inheritance.make(), nars.language.Statement.make(), nars.io.Symbols.PROPERTY_RELATION, and nars.io.Symbols.SIMILARITY_RELATION.
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.RuleTables.conditionalAbd(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.RuleTables.contraposition(), nars.inference.LocalRules.convertedJudgment(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.dedExe(), nars.inference.LocalRules.inferToAsym(), nars.language.Statement.make(), nars.io.StringParser.parseStatement(), nars.inference.CompositionalRules.processComposed(), nars.inference.SyllogisticRules.resemblance(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.StructuralRules.structuralStatement(), and nars.inference.StructuralRules.transformProductImage().
{
         if (invalidStatement(subject, predicate)) {
             return null;
         }
         if (relation.equals(Symbols.INHERITANCE_RELATION)) {
             return Inheritance.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.SIMILARITY_RELATION)) {
             return Similarity.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.INSTANCE_RELATION)) {
             return Instance.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.PROPERTY_RELATION)) {
             return Property.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.INSTANCE_PROPERTY_RELATION)) {
             return InstanceProperty.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.IMPLICATION_RELATION)) {
             return Implication.Companion.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.EQUIVALENCE_RELATION)) {
             return Equivalence.Companion.make(subject, predicate, memory);
         }
         return null;
     }
make() [2/2]
static Statement nars.language.Statement.make (Statement statement, Term subj, Term pred, Memory memory) static
Make a Statement from given components, called by the rules.
Returns
The Statement built
Parameters
subj The first component
pred The second component
statement A sample statement providing the class type
memory Reference to the memeory
Definition at line 105 of file Statement.java.
References nars.language.Inheritance.make(), and nars.language.Similarity.make().
{
         if (statement instanceof Inheritance) {
             return Inheritance.make(subj, pred, memory);
         }
         if (statement instanceof Similarity) {
             return Similarity.make(subj, pred, memory);
         }
         if (statement instanceof Implication) {
             return Implication.Companion.make(subj, pred, memory);
         }
         if (statement instanceof Equivalence) {
             return Equivalence.Companion.make(subj, pred, memory);
         }
         return null;
     }
makeName()
String nars.language.Statement.makeName () protected
Override the default in making the nameStr of the current term from existing fields.
Returns
the nameStr of the term
Definition at line 126 of file Statement.java.
References nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), and nars.language.Statement.makeStatementName().
{
         return makeStatementName(getSubject(), operator(), getPredicate());
     }
makeStatementName()
static String nars.language.Statement.makeStatementName (TermStruct subject, String relation, TermStruct predicate) static protected
Default method to make the nameStr of an image term from given fields.
Parameters
subject The first component
predicate The second component
relation The relation operator
Returns
The nameStr of the term
Definition at line 137 of file Statement.java.
References nars.io.Symbols.STATEMENT_CLOSER, and nars.io.Symbols.STATEMENT_OPENER.
Referenced by nars.language.Inheritance.make(), nars.language.Similarity.make(), and nars.language.Statement.makeName().
{
         StringBuffer nameStr = new StringBuffer();
         nameStr.append(Symbols.STATEMENT_OPENER);
         nameStr.append(subject.getName());
         nameStr.append(' ' + relation + ' ');
         nameStr.append(predicate.getName());
         nameStr.append(Symbols.STATEMENT_CLOSER);
         return nameStr.toString();
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/language/Statement.java