photon: nars.io.StringParser Class Reference
nars.io.StringParser Class Reference abstract
Parse input String into Task or Term.
Classes
class InvalidInputException
All kinds of invalid input lines.
Static Public Member Functions
static boolean isRelation (String s0)
Check Statement relation symbol, called in StringPaser.
static boolean isOperator (String s)
Check CompoundTerm operator symbol.
static Task parseTask (String s, Memory memory, long time)
Enter a new Task in String into the memory, called from InputWindow or locally.
static Term parseTerm (String s0, Memory memory)
Top-level method that parse a Term in general, which may recursively call itself.
Static Private Member Functions
static String getBudgetString (StringBuffer s) throws InvalidInputException
Return the prefex of a task string that contains a BudgetValue.
static String getTruthString (StringBuffer s) throws InvalidInputException
Return the postfix of a task string that contains a TruthValue.
static TruthValue parseTruth (String s, char type)
parse the input String into a TruthValue (or DesireValue)
static BudgetValue parseBudget (String s, char punctuation, TruthHandle truth) throws InvalidInputException
parse the input String into a BudgetValue
static void showWarning (String message)
static Term parseAtomicTerm (String s0) throws InvalidInputException
Parse a Term that has no internal structure.
static Statement parseStatement (String s0, Memory memory) throws InvalidInputException
Parse a String to create a Statement.
static Term parseCompoundTerm (String s0, Memory memory) throws InvalidInputException
Parse a String to create a CompoundTerm.
static List< Term > parseArguments (String s0, Memory memory) throws InvalidInputException
Parse a String into the argument get of a CompoundTerm.
static int nextSeparator (String s, int first)
Locate the first top-level separator in a CompoundTerm.
static int topRelation (String s)
locate the top-level relation in a statement
static boolean isOpener (String s, int i)
Check CompoundTerm opener symbol.
static boolean isCloser (String s, int i)
Check CompoundTerm closer symbol.
Additional Inherited Members
Static Public Attributes inherited from nars.io.Symbols
static final char JUDGMENT_MARK = '.'
static final char QUESTION_MARK = '?'
static final char VAR_INDEPENDENT = '$'
static final char VAR_DEPENDENT = '#'
static final char VAR_QUERY = '?'
static final char BUDGET_VALUE_MARK = '$'
static final char TRUTH_VALUE_MARK = '%'
static final char VALUE_SEPARATOR = ';'
static final char COMPOUND_TERM_OPENER = '('
static final char COMPOUND_TERM_CLOSER = ')'
static final char STATEMENT_OPENER = '<'
static final char STATEMENT_CLOSER = '>'
static final char SET_EXT_OPENER = '{'
static final char SET_EXT_CLOSER = '}'
static final char SET_INT_OPENER = '['
static final char SET_INT_CLOSER = ']'
static final char ARGUMENT_SEPARATOR = ','
static final char IMAGE_PLACE_HOLDER = '_'
static final String INTERSECTION_EXT_OPERATOR = "&"
static final String INTERSECTION_INT_OPERATOR = "|"
static final String DIFFERENCE_EXT_OPERATOR = "-"
static final String DIFFERENCE_INT_OPERATOR = "~"
static final String PRODUCT_OPERATOR = "*"
static final String IMAGE_EXT_OPERATOR = "/"
static final String IMAGE_INT_OPERATOR = "\\"
static final String NEGATION_OPERATOR = "--"
static final String DISJUNCTION_OPERATOR = "||"
static final String CONJUNCTION_OPERATOR = "&&"
static final String INHERITANCE_RELATION = "-->"
static final String SIMILARITY_RELATION = "<->"
static final String INSTANCE_RELATION = "{--"
static final String PROPERTY_RELATION = "--]"
static final String INSTANCE_PROPERTY_RELATION = "{-]"
static final String IMPLICATION_RELATION = "==>"
static final String EQUIVALENCE_RELATION = "<=>"
static final String INPUT_LINE = "IN"
static final String OUTPUT_LINE = "OUT"
static final char PREFIX_MARK = ':'
static final char RESET_MARK = '*'
static final char COMMENT_MARK = '/'
static final char STAMP_OPENER = '{'
static final char STAMP_CLOSER = '}'
static final char STAMP_SEPARATOR = ';'
static final char STAMP_STARTER = ':'
static final String TO_COMPONENT_1 = " @("
static final String TO_COMPONENT_2 = ")_ "
static final String TO_COMPOUND_1 = " _@("
static final String TO_COMPOUND_2 = ") "
Detailed Description
Parse input String into Task or Term.
Abstract class with static methods only.
Definition at line 38 of file StringParser.java.
Member Function Documentation
getBudgetString()
static String nars.io.StringParser.getBudgetString (StringBuffer s) throws InvalidInputException static private
Return the prefex of a task string that contains a BudgetValue.
Parameters
s the input in a StringBuffer
Returns
a String containing a BudgetValue
Exceptions
InvalidInputException if the input cannot be parsed into a BudgetValue
Definition at line 110 of file StringParser.java.
References nars.io.Symbols.BUDGET_VALUE_MARK.
Referenced by nars.io.StringParser.parseTask().
{
         if (Symbols.BUDGET_VALUE_MARK == s.charAt(0)) {
             int i = s.indexOf(Symbols.BUDGET_VALUE_MARK + "", 1);    // looking for the end
             assert 0 <= i : "missing budget closer";
             String budgetString = s.substring(1, i).trim();
             assert !budgetString.isEmpty() : "empty budget";
             s.delete(0, i + 1);
             return budgetString;
         }
         return null;
     }
getTruthString()
static String nars.io.StringParser.getTruthString (StringBuffer s) throws InvalidInputException static private
Return the postfix of a task string that contains a TruthValue.
Parameters
s the input in a StringBuffer
Returns
a String containing a TruthValue
Exceptions
InvalidInputException if the input cannot be parsed into a TruthValue
Definition at line 131 of file StringParser.java.
References nars.io.Symbols.TRUTH_VALUE_MARK.
Referenced by nars.io.StringParser.parseTask().
{
         int last = s.length() - 1;
         if (Symbols.TRUTH_VALUE_MARK == s.charAt(last)) {
             int first = s.indexOf(Symbols.TRUTH_VALUE_MARK + "");    // looking for the beginning
             assert first != last : "missing truth mark";
             String truthString = s.substring(first + 1, last).trim();
             assert !truthString.isEmpty() : "empty truth";
             s.delete(first, last + 1);                 // remaining input to be processed outside
             s.trimToSize();
             return truthString;
         }
         return null;
     }
isCloser()
static boolean nars.io.StringParser.isCloser (String s, int i) static private
Check CompoundTerm closer symbol.
Parameters
s The String to be checked
i The starting index
Returns
if the given String is a closer symbol
Definition at line 422 of file StringParser.java.
References nars.io.Symbols.COMPOUND_TERM_CLOSER, nars.io.StringParser.isRelation(), nars.io.Symbols.SET_EXT_CLOSER, nars.io.Symbols.SET_INT_CLOSER, and nars.io.Symbols.STATEMENT_CLOSER.
Referenced by nars.io.StringParser.nextSeparator(), and nars.io.StringParser.topRelation().
{
         char c = s.charAt(i);
         return (Symbols.COMPOUND_TERM_CLOSER == c ||
                 Symbols.SET_EXT_CLOSER == c ||
                 Symbols.SET_INT_CLOSER == c ||
                 Symbols.STATEMENT_CLOSER == c) && !(2 <= i && isRelation(s.substring(i - 2, i + 1)));
     }
isOpener()
static boolean nars.io.StringParser.isOpener (String s, int i) static private
Check CompoundTerm opener symbol.
Parameters
s The String to be checked
i The starting index
Returns
if the given String is an opener symbol
Definition at line 405 of file StringParser.java.
References nars.io.Symbols.COMPOUND_TERM_OPENER, nars.io.StringParser.isRelation(), nars.io.Symbols.SET_EXT_OPENER, nars.io.Symbols.SET_INT_OPENER, and nars.io.Symbols.STATEMENT_OPENER.
Referenced by nars.io.StringParser.nextSeparator(), and nars.io.StringParser.topRelation().
{
         char c = s.charAt(i);
         return (Symbols.COMPOUND_TERM_OPENER == c ||
                 Symbols.SET_EXT_OPENER == c ||
                 Symbols.SET_INT_OPENER == c ||
                 Symbols.STATEMENT_OPENER == c) && !(i + 3 <= s.length() && isRelation(s.substring(i, i + 3)));
     }
isOperator()
static boolean nars.io.StringParser.isOperator (String s) static
Check CompoundTerm operator symbol.
Parameters
s The String to be checked
Returns
if the given String is an operator symbol
Definition at line 57 of file StringParser.java.
References nars.io.Symbols.CONJUNCTION_OPERATOR, nars.io.Symbols.DIFFERENCE_EXT_OPERATOR, nars.io.Symbols.DIFFERENCE_INT_OPERATOR, nars.io.Symbols.DISJUNCTION_OPERATOR, nars.io.Symbols.IMAGE_EXT_OPERATOR, nars.io.Symbols.IMAGE_INT_OPERATOR, nars.io.Symbols.INTERSECTION_EXT_OPERATOR, nars.io.Symbols.INTERSECTION_INT_OPERATOR, nars.io.Symbols.NEGATION_OPERATOR, and nars.io.Symbols.PRODUCT_OPERATOR.
Referenced by nars.io.StringParser.parseCompoundTerm().
{
         return 1 == s.length()
                 && (s.equals(INTERSECTION_EXT_OPERATOR) ||
                 s.equals(INTERSECTION_INT_OPERATOR) ||
                 s.equals(DIFFERENCE_EXT_OPERATOR) ||
                 s.equals(DIFFERENCE_INT_OPERATOR) ||
                 s.equals(PRODUCT_OPERATOR) ||
                 s.equals(IMAGE_EXT_OPERATOR) ||
                 s.equals(IMAGE_INT_OPERATOR)) ||
                 1 != s.length() && 2 == s.length()
                         && (s.equals(NEGATION_OPERATOR) || s.equals(DISJUNCTION_OPERATOR) || s.equals(CONJUNCTION_OPERATOR));
     }
isRelation()
static boolean nars.io.StringParser.isRelation (String s0) static
Check Statement relation symbol, called in StringPaser.
Parameters
s0 The String to be checked
Returns
if the given String is a relation symbol
Definition at line 46 of file StringParser.java.
References nars.io.Symbols.EQUIVALENCE_RELATION, nars.io.Symbols.IMPLICATION_RELATION, nars.io.Symbols.INHERITANCE_RELATION, nars.io.Symbols.INSTANCE_PROPERTY_RELATION, nars.io.Symbols.INSTANCE_RELATION, nars.io.Symbols.PROPERTY_RELATION, and nars.io.Symbols.SIMILARITY_RELATION.
Referenced by nars.io.StringParser.isCloser(), nars.io.StringParser.isOpener(), and nars.io.StringParser.topRelation().
{
         String s;
         return (s = s0.trim()).length() == 3 && (s.equals(INHERITANCE_RELATION) || s.equals(SIMILARITY_RELATION) || s.equals(INSTANCE_RELATION) || s.equals(PROPERTY_RELATION) || s.equals(INSTANCE_PROPERTY_RELATION) || s.equals(IMPLICATION_RELATION) || s.equals(EQUIVALENCE_RELATION));
     }
nextSeparator()
static int nars.io.StringParser.nextSeparator (String s, int first) static private
Locate the first top-level separator in a CompoundTerm.
Parameters
s The String to be parsed
first The starting index
Returns
the index of the next seperator in a String
Definition at line 355 of file StringParser.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, nars.io.StringParser.isCloser(), and nars.io.StringParser.isOpener().
Referenced by nars.io.StringParser.parseArguments().
{
         int levelCounter = 0;
         int i = first;
         while (i < s.length() - 1) {
             if (isOpener(s, i)) {
                 levelCounter++;
             } else if (isCloser(s, i)) {
                 levelCounter--;
             } else if (Symbols.ARGUMENT_SEPARATOR == s.charAt(i)) {
                 if (0 == levelCounter) {
                     break;
                 }
             }
             i++;
         }
         return i;
     }
parseArguments()
static List<Term> nars.io.StringParser.parseArguments (String s0, Memory memory) throws InvalidInputException static private
Parse a String into the argument get of a CompoundTerm.
Parameters
s0 The String to be parsed
Returns
the arguments in an ArrayList
Exceptions
InvalidInputException the String cannot be parsed into an argument get
Definition at line 330 of file StringParser.java.
References nars.io.StringParser.nextSeparator(), and nars.io.StringParser.parseTerm().
Referenced by nars.io.StringParser.parseCompoundTerm(), and nars.io.StringParser.parseTerm().
{
         String s = s0.trim();
         List<Term> list = new ArrayList<Term>();
         int start = 0;
         int end = 0;
         Term t;
         while (end < s.length() - 1) {
             end = nextSeparator(s, start);
             t = parseTerm(s.substring(start, end), memory);     // recursive call
             list.add(t);
             start = end + 1;
         }
         if (list.isEmpty()) {
             throw new InvalidInputException("null argument");
         }
         return list;
     }
parseAtomicTerm()
static Term nars.io.StringParser.parseAtomicTerm (String s0) throws InvalidInputException static private
Parse a Term that has no internal structure.
The Term can be a constant or a variable.
Parameters
s0 the String to be parsed
Returns
the Term generated from the String
Exceptions
InvalidInputException the String cannot be parsed into a Term
Definition at line 271 of file StringParser.java.
References nars.language.Variable.containVar().
Referenced by nars.io.StringParser.parseTerm().
{
         String s = s0.trim();
         if (s.isEmpty()) {
             throw new InvalidInputException("missing term");
         }
         assert !s.contains(" ") : "invalid term";
         return Variable.containVar(s) ? new Variable(s) : new Term(s);
     }
parseBudget()
static BudgetValue nars.io.StringParser.parseBudget (String s, char punctuation, TruthHandle truth) throws InvalidInputException static private
parse the input String into a BudgetValue
Parameters
truth the TruthValue of the task
s input String
punctuation Task punctuation
Returns
the input BudgetValue
Exceptions
InvalidInputException If the String cannot be parsed into a BudgetValue
Definition at line 179 of file StringParser.java.
References nars.storage.Parameters.DEFAULT_JUDGMENT_DURABILITY, nars.storage.Parameters.DEFAULT_JUDGMENT_PRIORITY, nars.storage.Parameters.DEFAULT_QUESTION_DURABILITY, nars.storage.Parameters.DEFAULT_QUESTION_PRIORITY, nars.io.Symbols.JUDGMENT_MARK, nars.io.Symbols.QUESTION_MARK, nars.inference.BudgetFunctions.truthToQuality(), and nars.io.Symbols.VALUE_SEPARATOR.
Referenced by nars.io.StringParser.parseTask().
{
         float priority, durability;
         switch (punctuation) {
             case Symbols.JUDGMENT_MARK:
                 priority = Parameters.DEFAULT_JUDGMENT_PRIORITY;
                 durability = Parameters.DEFAULT_JUDGMENT_DURABILITY;
                 break;
             case Symbols.QUESTION_MARK:
                 priority = Parameters.DEFAULT_QUESTION_PRIORITY;
                 durability = Parameters.DEFAULT_QUESTION_DURABILITY;
                 break;
             default:
                 throw new InvalidInputException("unknown punctuation: '" + punctuation + "'");
         }
         if (null != s) { // overrite default
             int i = s.indexOf(Symbols.VALUE_SEPARATOR);
             if (0 > i) {        // default durability
                 priority = Float.parseFloat(s);
             } else {
                 priority = Float.parseFloat(s.substring(0, i));
                 durability = Float.parseFloat(s.substring(i + 1));
             }
         }
         float quality = null == truth ? 1 : BudgetFunctions.truthToQuality(truth);
         return new BudgetValue(priority, durability, quality);
     }
parseCompoundTerm()
static Term nars.io.StringParser.parseCompoundTerm (String s0, Memory memory) throws InvalidInputException static private
Parse a String to create a CompoundTerm.
Parameters
s0 The String to be parsed
Returns
the Term generated from the String
Exceptions
InvalidInputException the String cannot be parsed into a Term
Definition at line 308 of file StringParser.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, nars.io.StringParser.isOperator(), nars.language.CompoundTerm.make(), and nars.io.StringParser.parseArguments().
Referenced by nars.io.StringParser.parseTerm().
{
         String s = s0.trim();
         int firstSeparator = s.indexOf(Symbols.ARGUMENT_SEPARATOR);
         String op = s.substring(0, firstSeparator).trim();
         if (!isOperator(op)) {
             throw new InvalidInputException("unknown operator: " + op);
         }
         List<Term> arg = parseArguments(s.substring(firstSeparator + 1) + Symbols.ARGUMENT_SEPARATOR, memory);
         Term t = CompoundTerm.make(op, arg, memory);
         if (null == t) {
             throw new InvalidInputException("invalid compound term");
         }
         return t;
     }
parseStatement()
static Statement nars.io.StringParser.parseStatement (String s0, Memory memory) throws InvalidInputException static private
Parse a String to create a Statement.
Parameters
s0 The input String to be parsed
Returns
the Statement generated from the String
Exceptions
InvalidInputException the String cannot be parsed into a Term
Definition at line 287 of file StringParser.java.
References nars.language.Statement.make(), nars.io.StringParser.parseTerm(), and nars.io.StringParser.topRelation().
Referenced by nars.io.StringParser.parseTerm().
{
         String s = s0.trim();
         int i = topRelation(s);
         if (0 > i) {
             throw new InvalidInputException("invalid statement");
         }
         String relation = s.substring(i, i + 3);
         Term subject = parseTerm(s.substring(0, i), memory);
         Term predicate = parseTerm(s.substring(i + 3), memory);
         Statement t = Statement.make(relation, subject, predicate, memory);
         assert null != t : "invalid statement";
         return t;
     }
parseTask()
static Task nars.io.StringParser.parseTask (String s, Memory memory, long time) static
Enter a new Task in String into the memory, called from InputWindow or locally.
Parameters
s the single-line input String
memory Reference to the memory
time The current time
Returns
An experienced task
Definition at line 78 of file StringParser.java.
References nars.language.Variable.containVarDep(), nars.entity.Stamp.createStamp(), nars.io.StringParser.getBudgetString(), nars.language.Term.getName(), nars.io.StringParser.getTruthString(), nars.io.StringParser.parseBudget(), nars.io.StringParser.parseTerm(), nars.io.StringParser.parseTruth(), and nars.io.StringParser.showWarning().
Referenced by nars.storage.ReasonerBatch.parseExperience().
{
         StringBuffer buffer = new StringBuffer(s);
         Task task = null;
         try {
             String budgetString = getBudgetString(buffer);
             String truthString = getTruthString(buffer);
             String str = buffer.toString().trim();
             int last = str.length() - 1;
             char punc = str.charAt(last);
             Stamp stamp = Stamp.createStamp(time);
             TruthValue truth = parseTruth(truthString, punc);
             Term content = parseTerm(str.substring(0, last), memory);
             Sentence sentence = new Sentence(content, punc, truth, stamp);
             if (content instanceof Conjunction && Variable.containVarDep(content.getName()))
                 sentence.setRevisible(false);
             BudgetValue budget = parseBudget(budgetString, punc, truth);
             task = new Task(sentence, budget);
         } catch (InvalidInputException e) {
             String message = " !!! INVALID INPUT: parseTask: " + buffer + " --- " + e.getMessage();
             System.out.println(message);
             showWarning(message);
         }
         return task;
     }
parseTerm()
static Term nars.io.StringParser.parseTerm (String s0, Memory memory) static
Top-level method that parse a Term in general, which may recursively call itself.
There are 5 valid cases:
(Op, A1, ..., An) is a CompoundTerm if Op is a built-in operator
{A1, ..., An} is an SetExt;
[A1, ..., An] is an SetInt;
<T1 re="" t2>=""> is a Statement (including higher-order Statement);
otherwise it is a simple term.
Parameters
s0 the String to be parsed
memory Reference to the memory
Returns
the Term generated from the String
Definition at line 220 of file StringParser.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, nars.io.Symbols.COMPOUND_TERM_CLOSER, nars.io.Symbols.COMPOUND_TERM_OPENER, nars.language.SetInt.make(), nars.language.SetExt.make(), nars.storage.Memory.nameToListedTerm(), nars.io.StringParser.parseArguments(), nars.io.StringParser.parseAtomicTerm(), nars.io.StringParser.parseCompoundTerm(), nars.io.StringParser.parseStatement(), nars.io.Symbols.SET_EXT_CLOSER, nars.io.Symbols.SET_EXT_OPENER, nars.io.Symbols.SET_INT_CLOSER, nars.io.Symbols.SET_INT_OPENER, nars.io.StringParser.showWarning(), nars.io.Symbols.STATEMENT_CLOSER, and nars.io.Symbols.STATEMENT_OPENER.
Referenced by nars.io.StringParser.parseArguments(), nars.io.StringParser.parseStatement(), and nars.io.StringParser.parseTask().
{
         String s = s0.trim();
         try {
             assert !s.isEmpty() : "missing content";
             Term t = Memory.nameToListedTerm(memory, s);    // existing constant or operator
             if (null == t) {
                 int index = s.length() - 1;
                 char first = s.charAt(0);
                 char last = s.charAt(index);
                 switch (first) {
                     case Symbols.COMPOUND_TERM_OPENER:
                         assert Symbols.COMPOUND_TERM_CLOSER == last : "missing CompoundTerm closer";
                         return parseCompoundTerm(s.substring(1, index), memory);
                     case Symbols.SET_EXT_OPENER:
                         assert Symbols.SET_EXT_CLOSER == last : "missing ExtensionSet closer";
                         return SetExt.make(parseArguments(s.substring(1, index) + Symbols.ARGUMENT_SEPARATOR, memory), memory);
                     case Symbols.SET_INT_OPENER:
                         assert Symbols.SET_INT_CLOSER == last : "missing IntensionSet closer";
                         return SetInt.make(parseArguments(s.substring(1, index) + Symbols.ARGUMENT_SEPARATOR, memory), memory);
                     case Symbols.STATEMENT_OPENER:
                         assert Symbols.STATEMENT_CLOSER == last : "missing Statement closer";
                         return parseStatement(s.substring(1, index), memory);
                     default:
                         return parseAtomicTerm(s);
                 }
             }
             return t;
         } catch (InvalidInputException e) {
             String message = " !!! INVALID INPUT: parseTerm: " + s + " --- " + e.getMessage();
             System.out.println(message);
             showWarning(message);
         }
         return null;
     }
parseTruth()
static TruthValue nars.io.StringParser.parseTruth (String s, char type) static private
parse the input String into a TruthValue (or DesireValue)
Parameters
s input String
type Task type
Returns
the input TruthValue
Definition at line 152 of file StringParser.java.
References nars.storage.Parameters.DEFAULT_JUDGMENT_CONFIDENCE, nars.io.Symbols.QUESTION_MARK, and nars.io.Symbols.VALUE_SEPARATOR.
Referenced by nars.io.StringParser.parseTask().
{
         if (Symbols.QUESTION_MARK == type) {
             return null;
         }
         float frequency = 1.0f;
         float confidence = Parameters.DEFAULT_JUDGMENT_CONFIDENCE;
         if (null != s) {
             int i = s.indexOf(Symbols.VALUE_SEPARATOR);
             if (0 > i) {
                 frequency = Float.parseFloat(s);
             } else {
                 frequency = Float.parseFloat(s.substring(0, i));
                 confidence = Float.parseFloat(s.substring(i + 1));
             }
         }
         return new TruthValue(frequency, confidence);
     }
showWarning()
static void nars.io.StringParser.showWarning (String message) static private
Definition at line 257 of file StringParser.java.
Referenced by nars.io.StringParser.parseTask(), and nars.io.StringParser.parseTerm().
{
 //      new TemporaryFrame( message + "\n( the faulty line has been kept in the input window )",
 //              40000, TemporaryFrame.WARNING );
     }
topRelation()
static int nars.io.StringParser.topRelation (String s) static private
locate the top-level relation in a statement
Parameters
s The String to be parsed
Returns
the index of the top-level relation
Definition at line 381 of file StringParser.java.
References nars.io.StringParser.isCloser(), nars.io.StringParser.isOpener(), and nars.io.StringParser.isRelation().
Referenced by nars.io.StringParser.parseStatement().
                                              {      // need efficiency improvement
         int levelCounter = 0;
         int i = 0;
         while (i < s.length() - 3) {    // don't need to check the last 3 characters
             if (0 == levelCounter && isRelation(s.substring(i, i + 3))) {
                 return i;
             }
             if (isOpener(s, i)) {
                 levelCounter++;
             } else if (isCloser(s, i)) {
                 levelCounter--;
             }
             i++;
         }
         return -1;
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/io/StringParser.java