photon: nars.storage.BagObserver Interface Reference
nars.storage.BagObserver Interface Reference
Public Member Functions
void setTitle (String title)
void setBag (Bag<?> concepts)
void post (String str)
Post the bag content.
void refresh (String string)
void stop ()
Detailed Description
Definition at line 3 of file BagObserver.java.
Member Function Documentation
post()
void nars.storage.BagObserver.post (String str)
Post the bag content.
Parameters
str The text
Implemented in nars.storage.NullBagObserver< Type >.
Referenced by nars.storage.Bag< Concept >.addBagObserver(), and nars.storage.Bag< Concept >.play().
refresh()
void nars.storage.BagObserver.refresh (String string)
Implemented in nars.storage.NullBagObserver< Type >.
Referenced by nars.storage.Bag< Concept >.refresh().
setBag()
void nars.storage.BagObserver.setBag (Bag<?> concepts)
Implemented in nars.storage.NullBagObserver< Type >.
Referenced by nars.storage.Memory.conceptsStartPlay(), and nars.storage.Memory.taskBuffersStartPlay().
setTitle()
void nars.storage.BagObserver.setTitle (String title)
Implemented in nars.storage.NullBagObserver< Type >.
Referenced by nars.storage.Bag< Concept >.addBagObserver().
stop()
void nars.storage.BagObserver.stop ()
Implemented in nars.storage.NullBagObserver< Type >.
Referenced by nars.storage.Bag< Concept >.stop().
The documentation for this interface was generated from the following file:
fabric/src/main/java/nars/storage/BagObserver.java