photon: nars.storage.Parameters Class Reference
nars.storage.Parameters Class Reference
Collected system parameters.
Static Public Attributes
static final int CONCEPT_FORGETTING_CYCLE = 15
Concept decay rate in ConceptBag, in [1, 99].
static final int TASK_LINK_FORGETTING_CYCLE = 20
TaskLink decay rate in TaskLinkBag, in [1, 99].
static final int TERM_LINK_FORGETTING_CYCLE = 50
TermLink decay rate in TermLinkBag, in [1, 99].
static final int SILENT_LEVEL = 1
Silent threshold for task reporting, in [0, 100].
static final int NEW_TASK_FORGETTING_CYCLE = 1
Task decay rate in TaskBuffer, in [1, 99].
static final int MAX_MATCHED_TERM_LINK = 10
Maximum TermLinks checked for novelty for each TaskLink in TermLinkBag.
static final int MAX_REASONED_TERM_LINK = 3
Maximum TermLinks used in reasoning for each Task in Concept.
static final int HORIZON = 1
Evidential Horizon, the amount of future evidence to be considered.
static final float RELIANCE = (float) 1.0
Reliance factor, the empirical confidence of analytical truth.
static final float BUDGET_THRESHOLD = (float) 0.1
The budget threshold rate for task to be accepted.
static final float DEFAULT_CONFIRMATION_EXPECTATION = (float) 0.8
Default expectation for confirmation.
static final float DEFAULT_CREATION_EXPECTATION = (float) 0.66
Default expectation for confirmation.
static final float DEFAULT_JUDGMENT_CONFIDENCE = (float) 0.9
Default confidence of input judgment.
static final float DEFAULT_JUDGMENT_PRIORITY = (float) 0.8
Default priority of input judgment.
static final float DEFAULT_JUDGMENT_DURABILITY = (float) 0.8
Default durability of input judgment.
static final float DEFAULT_QUESTION_PRIORITY = (float) 0.9
Default priority of input question.
static final float DEFAULT_QUESTION_DURABILITY = (float) 0.7
Default durability of input question.
static final int BAG_LEVEL = 100
Level granularity in Bag, two digits.
static final int BAG_THRESHOLD = 10
Level separation in Bag, one digit, for display (run-time adjustable) and management (fixed)
static final float LOAD_FACTOR = (float) 0.5
Hashtable load factor in Bag.
static final int CONCEPT_BAG_SIZE = 1000
Size of ConceptBag.
static final int TASK_LINK_BAG_SIZE = 20
Size of TaskLinkBag.
static final int TERM_LINK_BAG_SIZE = 100
Size of TermLinkBag.
static final int TASK_BUFFER_SIZE = 20
Size of TaskBuffer.
static final int MAXIMUM_STAMP_LENGTH = 8
Maximum length of Stamp, a power of 2.
static final int TERM_LINK_RECORD_LENGTH = 10
Remember recently used TermLink on a Task.
static final int MAXIMUM_BELIEF_LENGTH = 7
Maximum number of beliefs kept in a Concept.
static final int MAXIMUM_QUESTIONS_LENGTH = 5
Maximum number of goals kept in a Concept.
Detailed Description
Collected system parameters.
To be modified before compiling.
Definition at line 6 of file Parameters.java.
Member Data Documentation
BAG_LEVEL
final int nars.storage.Parameters.BAG_LEVEL = 100 static
Level granularity in Bag, two digits.
Definition at line 55 of file Parameters.java.
BAG_THRESHOLD
final int nars.storage.Parameters.BAG_THRESHOLD = 10 static
Level separation in Bag, one digit, for display (run-time adjustable) and management (fixed)
Definition at line 60 of file Parameters.java.
BUDGET_THRESHOLD
final float nars.storage.Parameters.BUDGET_THRESHOLD = (float) 0.1 static
The budget threshold rate for task to be accepted.
Definition at line 35 of file Parameters.java.
Referenced by nars.entity.BudgetValue.aboveThreshold().
CONCEPT_BAG_SIZE
final int nars.storage.Parameters.CONCEPT_BAG_SIZE = 1000 static
Size of ConceptBag.
Definition at line 64 of file Parameters.java.
Referenced by nars.storage.ConceptBag.capacity().
CONCEPT_FORGETTING_CYCLE
final int nars.storage.Parameters.CONCEPT_FORGETTING_CYCLE = 15 static
Concept decay rate in ConceptBag, in [1, 99].
Definition at line 10 of file Parameters.java.
DEFAULT_CONFIRMATION_EXPECTATION
final float nars.storage.Parameters.DEFAULT_CONFIRMATION_EXPECTATION = (float) 0.8 static
Default expectation for confirmation.
Definition at line 39 of file Parameters.java.
DEFAULT_CREATION_EXPECTATION
final float nars.storage.Parameters.DEFAULT_CREATION_EXPECTATION = (float) 0.66 static
Default expectation for confirmation.
Definition at line 41 of file Parameters.java.
Referenced by nars.storage.Memory.processNewTask().
DEFAULT_JUDGMENT_CONFIDENCE
final float nars.storage.Parameters.DEFAULT_JUDGMENT_CONFIDENCE = (float) 0.9 static
Default confidence of input judgment.
Definition at line 43 of file Parameters.java.
Referenced by nars.io.StringParser.parseTruth().
DEFAULT_JUDGMENT_DURABILITY
final float nars.storage.Parameters.DEFAULT_JUDGMENT_DURABILITY = (float) 0.8 static
Default durability of input judgment.
Definition at line 47 of file Parameters.java.
Referenced by nars.io.StringParser.parseBudget().
DEFAULT_JUDGMENT_PRIORITY
final float nars.storage.Parameters.DEFAULT_JUDGMENT_PRIORITY = (float) 0.8 static
Default priority of input judgment.
Definition at line 45 of file Parameters.java.
Referenced by nars.io.StringParser.parseBudget().
DEFAULT_QUESTION_DURABILITY
final float nars.storage.Parameters.DEFAULT_QUESTION_DURABILITY = (float) 0.7 static
Default durability of input question.
Definition at line 51 of file Parameters.java.
Referenced by nars.io.StringParser.parseBudget().
DEFAULT_QUESTION_PRIORITY
final float nars.storage.Parameters.DEFAULT_QUESTION_PRIORITY = (float) 0.9 static
Default priority of input question.
Definition at line 49 of file Parameters.java.
Referenced by nars.io.StringParser.parseBudget().
HORIZON
final int nars.storage.Parameters.HORIZON = 1 static
Evidential Horizon, the amount of future evidence to be considered.
Definition at line 28 of file Parameters.java.
Referenced by nars.inference.TruthFunctions.c2w(), and nars.inference.UtilityFunctions.w2c().
LOAD_FACTOR
final float nars.storage.Parameters.LOAD_FACTOR = (float) 0.5 static
Hashtable load factor in Bag.
Definition at line 62 of file Parameters.java.
MAX_MATCHED_TERM_LINK
final int nars.storage.Parameters.MAX_MATCHED_TERM_LINK = 10 static
Maximum TermLinks checked for novelty for each TaskLink in TermLinkBag.
Definition at line 22 of file Parameters.java.
Referenced by nars.storage.TermLinkBag.takeOut().
MAX_REASONED_TERM_LINK
final int nars.storage.Parameters.MAX_REASONED_TERM_LINK = 3 static
Maximum TermLinks used in reasoning for each Task in Concept.
Definition at line 24 of file Parameters.java.
Referenced by nars.entity.Concept.fireFromProcessConcept().
MAXIMUM_BELIEF_LENGTH
final int nars.storage.Parameters.MAXIMUM_BELIEF_LENGTH = 7 static
Maximum number of beliefs kept in a Concept.
Definition at line 78 of file Parameters.java.
Referenced by nars.entity.Concept.processJudgment().
MAXIMUM_QUESTIONS_LENGTH
final int nars.storage.Parameters.MAXIMUM_QUESTIONS_LENGTH = 5 static
Maximum number of goals kept in a Concept.
Definition at line 80 of file Parameters.java.
Referenced by nars.entity.Concept.processQuestion().
MAXIMUM_STAMP_LENGTH
final int nars.storage.Parameters.MAXIMUM_STAMP_LENGTH = 8 static
Maximum length of Stamp, a power of 2.
Definition at line 74 of file Parameters.java.
Referenced by nars.entity.Stamp.Stamp().
NEW_TASK_FORGETTING_CYCLE
final int nars.storage.Parameters.NEW_TASK_FORGETTING_CYCLE = 1 static
Task decay rate in TaskBuffer, in [1, 99].
Definition at line 20 of file Parameters.java.
Referenced by nars.storage.NovelTaskBag.forgetRate().
RELIANCE
final float nars.storage.Parameters.RELIANCE = (float) 1.0 static
Reliance factor, the empirical confidence of analytical truth.
Definition at line 30 of file Parameters.java.
SILENT_LEVEL
final int nars.storage.Parameters.SILENT_LEVEL = 1 static
Silent threshold for task reporting, in [0, 100].
Definition at line 16 of file Parameters.java.
TASK_BUFFER_SIZE
final int nars.storage.Parameters.TASK_BUFFER_SIZE = 20 static
Size of TaskBuffer.
Definition at line 70 of file Parameters.java.
Referenced by nars.storage.NovelTaskBag.capacity().
TASK_LINK_BAG_SIZE
final int nars.storage.Parameters.TASK_LINK_BAG_SIZE = 20 static
Size of TaskLinkBag.
Definition at line 66 of file Parameters.java.
Referenced by nars.storage.TaskLinkBag.capacity().
TASK_LINK_FORGETTING_CYCLE
final int nars.storage.Parameters.TASK_LINK_FORGETTING_CYCLE = 20 static
TaskLink decay rate in TaskLinkBag, in [1, 99].
Definition at line 12 of file Parameters.java.
TERM_LINK_BAG_SIZE
final int nars.storage.Parameters.TERM_LINK_BAG_SIZE = 100 static
Size of TermLinkBag.
Definition at line 68 of file Parameters.java.
Referenced by nars.storage.TermLinkBag.capacity().
TERM_LINK_FORGETTING_CYCLE
final int nars.storage.Parameters.TERM_LINK_FORGETTING_CYCLE = 50 static
TermLink decay rate in TermLinkBag, in [1, 99].
Definition at line 14 of file Parameters.java.
TERM_LINK_RECORD_LENGTH
final int nars.storage.Parameters.TERM_LINK_RECORD_LENGTH = 10 static
Remember recently used TermLink on a Task.
Definition at line 76 of file Parameters.java.
Referenced by nars.entity.TaskLink.novel().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/storage/Parameters.java