photon: nars.storage.Memory Class Reference
nars.storage.Memory Class Reference
The memory of the system.
Public Member Functions
Memory (ReasonerBatch reasoner)
Create a new memory.
List< String > getExportStrings ()
List of Strings or Tasks to be sent to the output channels.
IInferenceRecorder getRecorder ()
Inference record text to be written into a log file.
void setRecorder (IInferenceRecorder recorder)
AtomicInteger getTaskForgettingRate ()
AtomicInteger getBeliefForgettingRate ()
AtomicInteger getConceptForgettingRate ()
ReasonerBatch getReasoner ()
Backward pointer to the reasoner.
void setReasoner (ReasonerBatch reasoner)
ConceptBag getConcepts ()
Concept bag.
void setConcepts (ConceptBag concepts)
NovelTaskBag getNovelTasks ()
New tasks with novel composed terms, for delayed and selective processing.
void setNovelTasks (NovelTaskBag novelTasks)
void setBeliefForgettingRate (AtomicInteger beliefForgettingRate)
void setTaskForgettingRate (AtomicInteger taskForgettingRate)
void setConceptForgettingRate (AtomicInteger conceptForgettingRate)
List< Task > getNewTasks ()
List of new tasks accumulated in one cycle, to be processed in the next cycle.
void setNewTasks (List< Task > newTasks)
void setExportStrings (List< String > exportStrings)
Term getCurrentTerm ()
The selected Term.
void setCurrentTerm (Term currentTerm)
Concept getCurrentConcept ()
The selected Concept.
void setCurrentConcept (Concept currentConcept)
TaskLink getCurrentTaskLink ()
The selected TaskLink.
void setCurrentTaskLink (TaskLink currentTaskLink)
Task getCurrentTask ()
The selected Task.
void setCurrentTask (Task currentTask)
TermLink getCurrentBeliefLink ()
The selected TermLink.
void setCurrentBeliefLink (TermLink currentBeliefLink)
Sentence getCurrentBelief ()
The selected belief.
void setCurrentBelief (Sentence currentBelief)
Stamp getNewStamp ()
The new Stamp.
void setNewStamp (Stamp newStamp)
Map< Term, Term > getSubstitute ()
The substitution that unify the common term in the Task and the Belief TODO unused.
void setSubstitute (Map< Term, Term > substitute)
Static Public Member Functions
static void init (Memory memory)
static long getTime (Memory memory)
static boolean noResult (WorkSpace memory)
Actually means that there are no new Tasks.
static Concept nameToConcept (Memory memory, String name)
Get an existing Concept for a given name.
static Term nameToListedTerm (Memory memory, String name)
Get a Term for a given name of a Concept or Operator.
static Concept termToConcept (Memory memory, TermStruct term)
Get an existing Concept for a given Term.
static Concept getConcept (Memory memory, Term term)
Get the Concept associated to a Term, or create it.
static void activateConcept (Memory memory, Concept c, BudgetStruct b)
Adjust the activation level of a Concept.
static void inputTask (Memory memory, Task task)
Input task processing.
static void activatedTask (Memory memory, BudgetValue budget, Sentence sentence, Sentence candidateBelief)
Activated task called in MatchingRules.trySolution and Concept.processGoal.
static void doublePremiseTask (Memory memory, Term newContent, TruthValue newTruth, BudgetValue newBudget)
Shared final operations by all double-premise rules, called from the rules except StructuralRules.
static void doublePremiseTask (Memory memory, Term newContent, TruthValue newTruth, BudgetValue newBudget, boolean revisible)
Shared final operations by all double-premise rules, called from the rules except StructuralRules.
static void singlePremiseTask (Memory memory, Term newContent, TruthValue newTruth, BudgetValue newBudget)
Shared final operations by all single-premise rules, called in StructuralRules.
static void singlePremiseTask (Memory memory, Term newContent, int punctuation, TruthValue newTruth, BudgetValue newBudget)
Shared final operations by all single-premise rules, called in StructuralRules.
static void workCycle (Memory memory, long clock)
An atomic working workCycle of the system: process new Tasks, then fireFromProcessConcept a concept.
static void conceptsStartPlay (Memory memory, BagObserver bagObserver, String s)
Display active concepts, called from MainWindow.
static void taskBuffersStartPlay (Memory memory, BagObserver bagObserver, String s)
Display new tasks, called from MainWindow.
static void report (Memory memory, Sentence sentence, boolean input)
Display input/output sentence in the output channels.
static String toString (Memory memory)
Static Private Member Functions
static void derivedTask (Memory memory, Task task)
Derived task comes from the inference rules.
static void processNewTask (Memory memory)
Process the newTasks accumulated in the previous workCycle, accept input ones and those that corresponding to existing concepts, plus one from the buffer.
static void processNovelTask (Memory memory)
Select a novel task to process.
static void processConcept (Memory memory)
Select a concept to fireFromProcessConcept.
static void immediateProcess (Memory memory, Task task)
Immediate processing of a new task, in constant time Local processing, in one concept only.
static String toStringLongIfNotNull (Bag<?> item, String title)
static String toStringLongIfNotNull (Item item, String title)
static String toStringIfNotNull (Object item, String title)
Private Attributes
ReasonerBatch reasoner
ConceptBag concepts
NovelTaskBag novelTasks
IInferenceRecorder recorder
AtomicInteger beliefForgettingRate = new AtomicInteger(Parameters.TERM_LINK_FORGETTING_CYCLE)
AtomicInteger taskForgettingRate = new AtomicInteger(Parameters.TASK_LINK_FORGETTING_CYCLE)
AtomicInteger conceptForgettingRate = new AtomicInteger(Parameters.CONCEPT_FORGETTING_CYCLE)
List< Task > newTasks
List< String > exportStrings
Term currentTerm
Concept currentConcept
TaskLink currentTaskLink
Task currentTask
TermLink currentBeliefLink
Sentence currentBelief
Stamp newStamp
Map< Term, Term > substitute
Detailed Description
The memory of the system.
Definition at line 38 of file Memory.java.
Constructor & Destructor Documentation
Memory()
nars.storage.Memory.Memory (ReasonerBatch reasoner)
Create a new memory.
Called in Reasoner.reset only
Parameters
reasoner
Definition at line 71 of file Memory.java.
References nars.storage.Memory.reasoner, nars.storage.Memory.setConcepts(), nars.storage.Memory.setExportStrings(), nars.storage.Memory.setNewTasks(), nars.storage.Memory.setNovelTasks(), nars.storage.Memory.setReasoner(), and nars.storage.Memory.setRecorder().
{
         setReasoner(reasoner);
         setRecorder(new NullInferenceRecorder());
         setConcepts(new ConceptBag(this));
         setNovelTasks(new NovelTaskBag(this));
         setNewTasks(new ArrayList<>());
         setExportStrings(new ArrayList<>());
     }
Member Function Documentation
activateConcept()
static void nars.storage.Memory.activateConcept (Memory memory, Concept c, BudgetStruct b) static
Adjust the activation level of a Concept.
called in Concept.insertTaskLink only
Parameters
memory
c the concept to be adjusted
b the new BudgetValue
Definition at line 198 of file Memory.java.
References nars.inference.BudgetFunctions.activate(), nars.storage.Memory.getConcepts(), nars.entity.Item.getKey(), nars.storage.Bag< Type extends Item >.pickOut(), and nars.storage.Bag< Type extends Item >.putBack().
Referenced by nars.entity.Concept.insertTaskLink().
{
         memory.getConcepts().pickOut(c.getKey());
         BudgetFunctions.activate(c, b);
         memory.getConcepts().putBack(c);
     }
activatedTask()
static void nars.storage.Memory.activatedTask (Memory memory, BudgetValue budget, Sentence sentence, Sentence candidateBelief) static
Activated task called in MatchingRules.trySolution and Concept.processGoal.
Parameters
memory
budget The budget value of the new Task
sentence The content of the new Task
candidateBelief The belief to be used in future inference, for forward/backward correspondence
Definition at line 238 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.entity.Item.getBudget(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getReasoner(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), nars.storage.ReasonerBatch.getSilenceValue(), nars.entity.Sentence.isQuestion(), nars.storage.Memory.report(), and nars.entity.BudgetValue.summary().
Referenced by nars.inference.LocalRules.trySolution().
{
         Task task = new Task(sentence, budget, memory.getCurrentTask(), sentence, candidateBelief);
         memory.getRecorder().append("!!! Activated: " + task + "\n");
         if (sentence.isQuestion()) {
             float s = task.getBudget().summary();
 //            float minSilent = reasoner.getMainWindow().silentW.value() / 100.0f;
             float minSilent = ReasonerBatch.getSilenceValue(memory.getReasoner().getSilenceValue()).get() / 100.0f;
             // only report significant derived Tasks
             if (s > minSilent) report(memory, task.getSentence(), false);
         }
         memory.getNewTasks().add(task);
     }
conceptsStartPlay()
static void nars.storage.Memory.conceptsStartPlay (Memory memory, BagObserver bagObserver, String s) static
Display active concepts, called from MainWindow.
we don't want to expose fields concepts and novelTasks, AND we want to separate GUI and inference, so this method has become conceptsStartPlay(BagObserver bagObserver, String s) and this method calls concepts.addBagObserver(bagObserver, s) see design for Bag and
Parameters
memory
bagObserver
s the window title
Definition at line 447 of file Memory.java.
References nars.storage.Bag< Type extends Item >.addBagObserver(), nars.storage.Memory.getConcepts(), and nars.storage.BagObserver.setBag().
{
         bagObserver.setBag(memory.getConcepts());
         memory.getConcepts().addBagObserver(bagObserver, s);
     }
derivedTask()
static void nars.storage.Memory.derivedTask (Memory memory, Task task) static private
Derived task comes from the inference rules.
Parameters
memory
task the derived task
Definition at line 257 of file Memory.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.io.IInferenceRecorder.append(), nars.entity.Item.getBudget(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getReasoner(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), nars.storage.ReasonerBatch.getSilenceValue(), nars.storage.Memory.report(), and nars.entity.BudgetValue.summary().
Referenced by nars.storage.Memory.doublePremiseTask(), and nars.storage.Memory.singlePremiseTask().
{
         if (task.getBudget().aboveThreshold()) {
             memory.getRecorder().append("!!! Derived: " + task + "\n");
             float budget = task.getBudget().summary();
 //            float minSilent = reasoner.getMainWindow().silentW.value() / 100.0f;
             float minSilent = ReasonerBatch.getSilenceValue(memory.getReasoner().getSilenceValue()).get() / 100.0f;
             if (budget > minSilent) {  // only report significant derived Tasks
                 report(memory, task.getSentence(), false);
             }
             memory.getNewTasks().add(task);
         } else {
             memory.getRecorder().append("!!! Ignored: " + task + "\n");
         }
     }
doublePremiseTask() [1/2]
static void nars.storage.Memory.doublePremiseTask (Memory memory, Term newContent, TruthValue newTruth, BudgetValue newBudget) static
Shared final operations by all double-premise rules, called from the rules except StructuralRules.
Parameters
memory
newContent The content of the sentence in task
newTruth The truth value of the sentence in task
newBudget The budget value in task
Definition at line 282 of file Memory.java.
References nars.storage.Memory.derivedTask(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getNewStamp(), nars.entity.Sentence.getPunctuation(), and nars.entity.Task.getSentence().
Referenced by nars.inference.RuleTables.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.RuleTables.conditionalAbd(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.decomposeStatement(), nars.inference.RuleTables.dedExe(), nars.inference.RuleTables.elimiVarDep(), nars.inference.RuleTables.functionBeggingToBeAsync(), nars.inference.LocalRules.inferToAsym(), nars.inference.LocalRules.inferToSym(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.inference.CompositionalRules.processComposed(), nars.inference.SyllogisticRules.resemblance(), and nars.inference.LocalRules.revision().
{
         if (null != newContent) {
             Sentence newSentence = new Sentence(newContent, memory.getCurrentTask().getSentence().getPunctuation(), newTruth, memory.getNewStamp());
             Task newTask = new Task(newSentence, newBudget, memory.getCurrentTask(), memory.getCurrentBelief());
             Memory.derivedTask(memory, newTask);
         }
     }
doublePremiseTask() [2/2]
static void nars.storage.Memory.doublePremiseTask (Memory memory, Term newContent, TruthValue newTruth, BudgetValue newBudget, boolean revisible) static
Shared final operations by all double-premise rules, called from the rules except StructuralRules.
Parameters
memory
newContent The content of the sentence in task
newTruth The truth value of the sentence in task
newBudget The budget value in task
revisible Whether the sentence is revisible
Definition at line 300 of file Memory.java.
References nars.storage.Memory.derivedTask(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getNewStamp(), nars.entity.Sentence.getPunctuation(), and nars.entity.Task.getSentence().
{
         if (null != newContent) {
             Sentence taskSentence = memory.getCurrentTask().getSentence();
             Sentence newSentence = new Sentence(newContent, taskSentence.getPunctuation(), newTruth, memory.getNewStamp(), revisible);
             Task newTask = new Task(newSentence, newBudget, memory.getCurrentTask(), memory.getCurrentBelief());
             Memory.derivedTask(memory, newTask);
         }
     }
getBeliefForgettingRate()
AtomicInteger nars.storage.Memory.getBeliefForgettingRate ()
Implements nars.storage.WorkSpace.
Definition at line 532 of file Memory.java.
References nars.storage.Memory.beliefForgettingRate.
{
         return beliefForgettingRate;
     }
getConcept()
static Concept nars.storage.Memory.getConcept (Memory memory, Term term) static
Get the Concept associated to a Term, or create it.
Parameters
memory
term indicating the concept
Returns
an existing Concept, or a new one, or null (TODO bad smell)
Definition at line 169 of file Memory.java.
References nars.storage.Bag< Type extends Item >.get(), nars.storage.Memory.getConcepts(), nars.language.Term.getName(), nars.language.Term.isConstant(), and nars.storage.Bag< Type extends Item >.putIn().
Referenced by nars.entity.Concept.buildTermLinks(), nars.storage.Memory.immediateProcess(), and nars.entity.Concept.linkToTask().
{
         Concept r=null;
         e:{
             if (term.isConstant()) {
                 Concept concept = memory.getConcepts().get(term.getName());
             if (null == concept) {
                 concept = new Concept(term, memory); // the only place to make a new Concept
                 boolean created = memory.getConcepts().putIn(concept);
                 if (created) r = concept;
                 break e;
             }
             r=concept;
         }
         }
         return r;
     }
getConceptForgettingRate()
AtomicInteger nars.storage.Memory.getConceptForgettingRate ()
Implements nars.storage.WorkSpace.
Definition at line 537 of file Memory.java.
References nars.storage.Memory.conceptForgettingRate.
{
         return conceptForgettingRate;
     }
getConcepts()
ConceptBag nars.storage.Memory.getConcepts ()
Concept bag.
Containing all Concepts of the system
Definition at line 555 of file Memory.java.
References nars.storage.Memory.concepts.
Referenced by nars.storage.Memory.activateConcept(), nars.storage.Memory.conceptsStartPlay(), nars.storage.Memory.getConcept(), nars.storage.Memory.init(), nars.storage.Memory.nameToConcept(), nars.storage.Memory.nameToListedTerm(), nars.storage.Memory.processConcept(), and nars.storage.Memory.toString().
{
         return concepts;
     }
getCurrentBelief()
Sentence nars.storage.Memory.getCurrentBelief ()
The selected belief.
Implements nars.storage.WorkSpace.
Definition at line 675 of file Memory.java.
References nars.storage.Memory.currentBelief.
Referenced by nars.inference.CompositionalRules.composeCompound(), nars.inference.RuleTables.compoundAndSelf(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.RuleTables.conditionalAbd(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.LocalRules.conversion(), nars.inference.LocalRules.convertedJudgment(), nars.inference.LocalRules.convertRelation(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.decomposeStatement(), nars.inference.RuleTables.detachmentWithVar(), nars.storage.Memory.doublePremiseTask(), nars.inference.RuleTables.elimiVarDep(), nars.inference.RuleTables.functionBeggingToBeAsync(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.inference.LocalRules.matchReverse(), nars.inference.CompositionalRules.processComposed(), nars.storage.Memory.singlePremiseTask(), nars.inference.RuleTables.syllogisms(), and nars.storage.Memory.toString().
{
         return currentBelief;
     }
getCurrentBeliefLink()
TermLink nars.storage.Memory.getCurrentBeliefLink ()
The selected TermLink.
Implements nars.storage.WorkSpace.
Definition at line 662 of file Memory.java.
References nars.storage.Memory.currentBeliefLink.
Referenced by nars.storage.Memory.toString().
{
         return currentBeliefLink;
     }
getCurrentConcept()
Concept nars.storage.Memory.getCurrentConcept ()
The selected Concept.
Definition at line 624 of file Memory.java.
References nars.storage.Memory.currentConcept.
Referenced by nars.storage.Memory.immediateProcess(), and nars.storage.Memory.processConcept().
{
         return currentConcept;
     }
getCurrentTask()
Task nars.storage.Memory.getCurrentTask ()
The selected Task.
Implements nars.storage.WorkSpace.
Definition at line 649 of file Memory.java.
References nars.storage.Memory.currentTask.
Referenced by nars.storage.Memory.activatedTask(), nars.inference.SyllogisticRules.analogy(), nars.inference.RuleTables.componentAndStatement(), nars.inference.CompositionalRules.composeCompound(), nars.inference.RuleTables.compoundAndSelf(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.RuleTables.conditionalAbd(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.RuleTables.contraposition(), nars.inference.LocalRules.convertedJudgment(), nars.inference.LocalRules.convertRelation(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.decomposeStatement(), nars.inference.RuleTables.detachmentWithVar(), nars.storage.Memory.doublePremiseTask(), nars.inference.RuleTables.elimiVarDep(), nars.inference.RuleTables.functionBeggingToBeAsync(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.inference.LocalRules.matchAsymSym(), nars.inference.LocalRules.matchReverse(), nars.inference.RuleTables.reason(), nars.storage.Memory.singlePremiseTask(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralCompound(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.StructuralRules.structuralStatement(), nars.inference.RuleTables.syllogisms(), nars.storage.Memory.toString(), nars.inference.RuleTables.transformNegation(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.StructuralRules.transformProductImage(), nars.inference.RuleTables.transformSetRelation(), nars.inference.StructuralRules.transformSubjectPI(), and nars.inference.RuleTables.transformTask().
{
         return currentTask;
     }
getCurrentTaskLink()
TaskLink nars.storage.Memory.getCurrentTaskLink ()
The selected TaskLink.
Implements nars.storage.WorkSpace.
Definition at line 636 of file Memory.java.
References nars.storage.Memory.currentTaskLink.
{
         return currentTaskLink;
     }
getCurrentTerm()
Term nars.storage.Memory.getCurrentTerm ()
The selected Term.
Implements nars.storage.WorkSpace.
Definition at line 612 of file Memory.java.
References nars.storage.Memory.currentTerm.
Referenced by nars.storage.Memory.immediateProcess(), nars.storage.Memory.processConcept(), and nars.inference.RuleTables.reason().
{
         return currentTerm;
     }
getExportStrings()
List<String> nars.storage.Memory.getExportStrings ()
List of Strings or Tasks to be sent to the output channels.
Implements nars.storage.WorkSpace.
Definition at line 94 of file Memory.java.
References nars.storage.Memory.exportStrings.
Referenced by nars.storage.ReasonerBatch.doTick(), nars.storage.Memory.init(), nars.storage.Memory.report(), and nars.storage.ReasonerBatch.textInputLine().
{
         return exportStrings;
     }
getNewStamp()
Stamp nars.storage.Memory.getNewStamp ()
The new Stamp.
Implements nars.storage.WorkSpace.
Definition at line 688 of file Memory.java.
References nars.storage.Memory.newStamp.
Referenced by nars.storage.Memory.doublePremiseTask(), nars.entity.Concept.getBelief(), nars.entity.Concept.processJudgment(), and nars.storage.Memory.singlePremiseTask().
{
         return newStamp;
     }
getNewTasks()
List<Task> nars.storage.Memory.getNewTasks ()
List of new tasks accumulated in one cycle, to be processed in the next cycle.
Implements nars.storage.WorkSpace.
Definition at line 594 of file Memory.java.
References nars.storage.Memory.newTasks.
Referenced by nars.storage.Memory.activatedTask(), nars.storage.Memory.derivedTask(), nars.storage.Memory.init(), nars.storage.Memory.inputTask(), nars.storage.Memory.processNewTask(), and nars.storage.Memory.toString().
{
         return newTasks;
     }
getNovelTasks()
NovelTaskBag nars.storage.Memory.getNovelTasks ()
New tasks with novel composed terms, for delayed and selective processing.
Definition at line 566 of file Memory.java.
References nars.storage.Memory.novelTasks.
Referenced by nars.storage.Memory.init(), nars.storage.Memory.processNewTask(), nars.storage.Memory.processNovelTask(), nars.storage.Memory.taskBuffersStartPlay(), nars.storage.Memory.toString(), and nars.storage.Memory.workCycle().
{
         return novelTasks;
     }
getReasoner()
ReasonerBatch nars.storage.Memory.getReasoner ()
Backward pointer to the reasoner.
Definition at line 544 of file Memory.java.
References nars.storage.Memory.reasoner.
Referenced by nars.storage.Memory.activatedTask(), nars.storage.Memory.derivedTask(), nars.storage.Memory.getTime(), nars.storage.Memory.init(), and nars.storage.Memory.report().
{
         return reasoner;
     }
getRecorder()
IInferenceRecorder nars.storage.Memory.getRecorder ()
Inference record text to be written into a log file.
Definition at line 101 of file Memory.java.
References nars.storage.Memory.recorder.
Referenced by nars.storage.Memory.activatedTask(), nars.storage.Memory.derivedTask(), nars.entity.Concept.fireFromProcessConcept(), nars.entity.Concept.getBelief(), nars.storage.Memory.immediateProcess(), nars.storage.Memory.init(), nars.storage.Memory.inputTask(), nars.storage.Memory.processConcept(), nars.storage.Memory.processNewTask(), and nars.storage.Memory.workCycle().
{
         return recorder;
     }
getSubstitute()
Map<Term, Term> nars.storage.Memory.getSubstitute ()
The substitution that unify the common term in the Task and the Belief TODO unused.
Definition at line 701 of file Memory.java.
References nars.storage.Memory.substitute.
{
         return substitute;
     }
getTaskForgettingRate()
AtomicInteger nars.storage.Memory.getTaskForgettingRate ()
Implements nars.storage.WorkSpace.
Definition at line 527 of file Memory.java.
References nars.storage.Memory.taskForgettingRate.
{
         return taskForgettingRate;
     }
getTime()
static long nars.storage.Memory.getTime (Memory memory) static
Definition at line 109 of file Memory.java.
References nars.storage.ReasonerBatch.getClock(), nars.storage.Memory.getReasoner(), and nars.storage.ReasonerBatch.getTime().
Referenced by nars.entity.Concept.fireFromProcessConcept(), nars.entity.Concept.getBelief(), nars.entity.Concept.processJudgment(), and nars.storage.Memory.singlePremiseTask().
{
         return ReasonerBatch.getTime(memory.getReasoner().getClock());
     }
immediateProcess()
static void nars.storage.Memory.immediateProcess (Memory memory, Task task) static private
Immediate processing of a new task, in constant time Local processing, in one concept only.
Parameters
memory
task the task to be accepted
Definition at line 423 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.entity.Concept.directProcess(), nars.storage.Memory.getConcept(), nars.entity.Task.getContent(), nars.storage.Memory.getCurrentConcept(), nars.storage.Memory.getCurrentTerm(), nars.storage.Memory.getRecorder(), nars.storage.Memory.setCurrentConcept(), nars.storage.Memory.setCurrentTask(), and nars.storage.Memory.setCurrentTerm().
Referenced by nars.storage.Memory.processNewTask(), and nars.storage.Memory.processNovelTask().
{
         memory.setCurrentTask(task); // one of the two places where this variable is set
         memory.getRecorder().append("!!! Insert: " + task + "\n");
         memory.setCurrentTerm(task.getContent());
         memory.setCurrentConcept(Memory.getConcept(memory, memory.getCurrentTerm()));
         if (null != memory.getCurrentConcept()) {
             memory.getCurrentConcept().directProcess(task);
         }
     }
init()
static void nars.storage.Memory.init (Memory memory) static
Definition at line 80 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.storage.Memory.getConcepts(), nars.storage.Memory.getExportStrings(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getNovelTasks(), nars.storage.Memory.getReasoner(), nars.storage.Memory.getRecorder(), nars.storage.Bag< Type extends Item >.init(), and nars.storage.ReasonerBatch.initTimer().
Referenced by nars.storage.ReasonerBatch.reset().
{
         memory.getConcepts().init();
         memory.getNovelTasks().init();
         memory.getNewTasks().clear();
         memory.getExportStrings().clear();
 //      reasoner.getMainWindow().initTimer();
         ReasonerBatch.initTimer(memory.getReasoner());
         memory.getRecorder().append("\n-----RESET-----\n");
     }
inputTask()
static void nars.storage.Memory.inputTask (Memory memory, Task task) static
Input task processing.
Invoked by the outside or inside environment. Outside: StringParser (input); Inside: Operator (feedback). Input tasks with low priority are ignored, and the others are put into task buffer.
Parameters
memory
task The input task
Definition at line 217 of file Memory.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.io.IInferenceRecorder.append(), nars.entity.Item.getBudget(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), and nars.storage.Memory.report().
Referenced by nars.storage.ReasonerBatch.textInputLine().
{
         if (task.getBudget().aboveThreshold()) {
             memory.getRecorder().append("!!! Perceived: " + task + "\n");
             Sentence sentence = task.getSentence();
             report(memory, sentence, true);    // report input
             memory.getNewTasks().add(task);       // wait to be processed in the next workCycle
         } else {
             memory.getRecorder().append("!!! Neglected: " + task + "\n");
         }
     }
nameToConcept()
static Concept nars.storage.Memory.nameToConcept (Memory memory, String name) static
Get an existing Concept for a given name.
called from Term and ConceptWindow.
Parameters
memory
name the name of a concept
Returns
a Concept or null
Definition at line 133 of file Memory.java.
References nars.storage.Bag< Type extends Item >.get(), and nars.storage.Memory.getConcepts().
Referenced by nars.storage.Memory.termToConcept().
{
         return memory.getConcepts().get(name);
     }
nameToListedTerm()
static Term nars.storage.Memory.nameToListedTerm (Memory memory, String name) static
Get a Term for a given name of a Concept or Operator.
called in StringParser and the make methods of compound terms.
Parameters
memory
name the name of a concept or operator
Returns
a Term or null (if no Concept/Operator has this name)
Definition at line 145 of file Memory.java.
References nars.storage.Bag< Type extends Item >.get(), nars.storage.Memory.getConcepts(), and nars.entity.Concept.getTerm().
Referenced by nars.language.Inheritance.make(), nars.language.Product.make(), nars.language.Similarity.make(), nars.language.Negation.make(), nars.language.SetInt.make(), nars.language.SetExt.make(), nars.language.IntersectionInt.make(), nars.language.IntersectionExt.make(), nars.language.ImageInt.make(), nars.language.ImageExt.make(), and nars.io.StringParser.parseTerm().
{
         Concept concept;
         concept = memory.getConcepts().get(name);
         return null != concept ? concept.getTerm() : null;
     }
noResult()
static boolean nars.storage.Memory.noResult (WorkSpace memory) static
Actually means that there are no new Tasks.
Parameters
memory
Definition at line 120 of file Memory.java.
References nars.storage.WorkSpace.getNewTasks().
Referenced by nars.entity.Concept.fireFromProcessConcept(), nars.inference.RuleTables.reason(), and nars.storage.Memory.workCycle().
{
         return memory.getNewTasks().isEmpty();
     }
processConcept()
static void nars.storage.Memory.processConcept (Memory memory) static private
Select a concept to fireFromProcessConcept.
Parameters
memory
Definition at line 405 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.entity.Concept.fireFromProcessConcept(), nars.storage.Memory.getConcepts(), nars.storage.Memory.getCurrentConcept(), nars.storage.Memory.getCurrentTerm(), nars.entity.Concept.getMemory(), nars.storage.Memory.getRecorder(), nars.entity.Concept.getTaskLinks(), nars.entity.Concept.getTerm(), nars.entity.Concept.getTermLinks(), nars.storage.Bag< Type extends Item >.putBack(), nars.storage.Memory.setCurrentConcept(), nars.storage.Memory.setCurrentTerm(), and nars.storage.Bag< Type extends Item >.takeOut().
Referenced by nars.storage.Memory.workCycle().
{
         memory.setCurrentConcept(memory.getConcepts().takeOut());
         if (null != memory.getCurrentConcept()) {
             memory.setCurrentTerm(memory.getCurrentConcept().getTerm());
             memory.getRecorder().append(" * Selected Concept: " + memory.getCurrentTerm() + "\n");
             memory.getConcepts().putBack(memory.getCurrentConcept());   // current Concept remains in the bag all the time
             Concept.fireFromProcessConcept(memory.getCurrentConcept().getMemory(), memory.getCurrentConcept().getTaskLinks(), memory.getCurrentConcept().getTermLinks());              // a working workCycle
         }
     }
processNewTask()
static void nars.storage.Memory.processNewTask (Memory memory) static private
Process the newTasks accumulated in the previous workCycle, accept input ones and those that corresponding to existing concepts, plus one from the buffer.
Parameters
memory
Definition at line 369 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.storage.Parameters.DEFAULT_CREATION_EXPECTATION, nars.entity.Task.getContent(), nars.entity.TruthValue.getExpectation(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getNovelTasks(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.storage.Memory.immediateProcess(), nars.entity.Task.isInput(), nars.entity.Sentence.isJudgment(), nars.storage.Bag< Type extends Item >.putIn(), and nars.storage.Memory.termToConcept().
Referenced by nars.storage.Memory.workCycle().
{
         Task task;
         int counter = memory.getNewTasks().size();  // don't include new tasks produced in the current workCycle
         while (0 < counter--) {
             task = memory.getNewTasks().remove(0);
             if (task.isInput() || null != termToConcept(memory, task.getContent())) { // new input or existing concept
                 immediateProcess(memory, task);
             } else {
                 Sentence  s = task.getSentence();
                 if (s.isJudgment()) {
                     double d = s.getTruth().getExpectation();
                     if (Parameters.DEFAULT_CREATION_EXPECTATION < d)
                         memory.getNovelTasks().putIn(task);    // new concept formation
                     else {
                         memory.getRecorder().append("!!! Neglected: " + task + "\n");
                     }
                 }
             }
         }
     }
processNovelTask()
static void nars.storage.Memory.processNovelTask (Memory memory) static private
Select a novel task to process.
Parameters
memory
Definition at line 394 of file Memory.java.
References nars.storage.Memory.getNovelTasks(), nars.storage.Memory.immediateProcess(), and nars.storage.Bag< Type extends Item >.takeOut().
Referenced by nars.storage.Memory.workCycle().
{
         Task task = memory.getNovelTasks().takeOut();       // select a task from novelTasks
         if (null != task) {
             immediateProcess(memory, task);
         }
     }
report()
static void nars.storage.Memory.report (Memory memory, Sentence sentence, boolean input) static
Display input/output sentence in the output channels.
The only place to add Objects into exportStrings. Currently only Strings are added, though in the future there can be outgoing Tasks; also if exportStrings is empty display the current value of timer (exportStrings is emptied in ReasonerBatch#doTick(ReasonerBatch) - TODO fragile mechanism)
Parameters
memory
sentence the sentence to be displayed
input whether the task is input
Definition at line 475 of file Memory.java.
References nars.storage.ReasonerBatch.getClock(), nars.storage.Memory.getExportStrings(), nars.storage.Memory.getReasoner(), nars.storage.ReasonerBatch.getTime(), nars.storage.ReasonerBatch.getTimer(), nars.storage.ReasonerBatch.isDEBUG(), nars.entity.Sentence.toStringBrief(), and nars.storage.ReasonerBatch.updateTimer().
Referenced by nars.storage.Memory.activatedTask(), nars.storage.Memory.derivedTask(), nars.storage.Memory.inputTask(), and nars.inference.LocalRules.trySolution().
{
         if (ReasonerBatch.isDEBUG()) {
             System.out.println("// report( clock " + ReasonerBatch.getTime(memory.getReasoner().getClock())
                     + ", input " + input
                     + ", timer " + memory.getReasoner().getTimer()
                     + ", Sentence " + sentence
                     + ", exportStrings " + memory.getExportStrings());
             System.out.flush();
         }
         if (memory.getExportStrings().isEmpty()) {
 //          long timer = reasoner.getMainWindow().updateTimer();
             long timer = ReasonerBatch.updateTimer(memory.getReasoner());
             if (0 < timer) {
                 memory.getExportStrings().add(String.valueOf(timer));
             }
         }
         String s;
         if (input) {
             s = "  IN: ";
         } else {
             s = " OUT: ";
         }
         s += Sentence.toStringBrief(sentence);
         memory.getExportStrings().add(s);
     }
setBeliefForgettingRate()
void nars.storage.Memory.setBeliefForgettingRate (AtomicInteger beliefForgettingRate)
Implements nars.storage.WorkSpace.
Definition at line 575 of file Memory.java.
References nars.storage.Memory.beliefForgettingRate.
{
         this.beliefForgettingRate = beliefForgettingRate;
     }
setConceptForgettingRate()
void nars.storage.Memory.setConceptForgettingRate (AtomicInteger conceptForgettingRate)
Implements nars.storage.WorkSpace.
Definition at line 585 of file Memory.java.
References nars.storage.Memory.conceptForgettingRate.
{
         this.conceptForgettingRate = conceptForgettingRate;
     }
setConcepts()
void nars.storage.Memory.setConcepts (ConceptBag concepts)
Definition at line 559 of file Memory.java.
References nars.storage.Memory.concepts.
Referenced by nars.storage.Memory.Memory().
{
         this.concepts = concepts;
     }
setCurrentBelief()
void nars.storage.Memory.setCurrentBelief (Sentence currentBelief)
Implements nars.storage.WorkSpace.
Definition at line 680 of file Memory.java.
References nars.storage.Memory.currentBelief.
Referenced by nars.entity.Concept.processJudgment(), and nars.inference.RuleTables.reason().
{
         this.currentBelief = currentBelief;
     }
setCurrentBeliefLink()
void nars.storage.Memory.setCurrentBeliefLink (TermLink currentBeliefLink)
Implements nars.storage.WorkSpace.
Definition at line 667 of file Memory.java.
References nars.storage.Memory.currentBeliefLink.
Referenced by nars.entity.Concept.fireFromProcessConcept().
{
         this.currentBeliefLink = currentBeliefLink;
     }
setCurrentConcept()
void nars.storage.Memory.setCurrentConcept (Concept currentConcept)
Definition at line 628 of file Memory.java.
References nars.storage.Memory.currentConcept.
Referenced by nars.storage.Memory.immediateProcess(), and nars.storage.Memory.processConcept().
{
         this.currentConcept = currentConcept;
     }
setCurrentTask()
void nars.storage.Memory.setCurrentTask (Task currentTask)
Implements nars.storage.WorkSpace.
Definition at line 654 of file Memory.java.
References nars.storage.Memory.currentTask.
Referenced by nars.entity.Concept.fireFromProcessConcept(), and nars.storage.Memory.immediateProcess().
{
         this.currentTask = currentTask;
     }
setCurrentTaskLink()
void nars.storage.Memory.setCurrentTaskLink (TaskLink currentTaskLink)
Implements nars.storage.WorkSpace.
Definition at line 641 of file Memory.java.
References nars.storage.Memory.currentTaskLink.
Referenced by nars.entity.Concept.fireFromProcessConcept().
{
         this.currentTaskLink = currentTaskLink;
     }
setCurrentTerm()
void nars.storage.Memory.setCurrentTerm (Term currentTerm)
Implements nars.storage.WorkSpace.
Definition at line 617 of file Memory.java.
References nars.storage.Memory.currentTerm.
Referenced by nars.storage.Memory.immediateProcess(), and nars.storage.Memory.processConcept().
{
         this.currentTerm = currentTerm;
     }
setExportStrings()
void nars.storage.Memory.setExportStrings (List< String > exportStrings)
Implements nars.storage.WorkSpace.
Definition at line 604 of file Memory.java.
References nars.storage.Memory.exportStrings.
Referenced by nars.storage.Memory.Memory().
{
         this.exportStrings = exportStrings;
     }
setNewStamp()
void nars.storage.Memory.setNewStamp (Stamp newStamp)
Implements nars.storage.WorkSpace.
Definition at line 693 of file Memory.java.
References nars.storage.Memory.newStamp.
Referenced by nars.entity.Concept.getBelief(), nars.entity.Concept.processJudgment(), and nars.storage.Memory.singlePremiseTask().
{
         this.newStamp = newStamp;
     }
setNewTasks()
void nars.storage.Memory.setNewTasks (List< Task > newTasks)
Implements nars.storage.WorkSpace.
Definition at line 599 of file Memory.java.
References nars.storage.Memory.newTasks.
Referenced by nars.storage.Memory.Memory().
{
         this.newTasks = newTasks;
     }
setNovelTasks()
void nars.storage.Memory.setNovelTasks (NovelTaskBag novelTasks)
Definition at line 570 of file Memory.java.
References nars.storage.Memory.novelTasks.
Referenced by nars.storage.Memory.Memory().
{
         this.novelTasks = novelTasks;
     }
setReasoner()
void nars.storage.Memory.setReasoner (ReasonerBatch reasoner)
Definition at line 548 of file Memory.java.
References nars.storage.Memory.reasoner.
Referenced by nars.storage.Memory.Memory().
{
         this.reasoner = reasoner;
     }
setRecorder()
void nars.storage.Memory.setRecorder (IInferenceRecorder recorder)
Definition at line 105 of file Memory.java.
References nars.storage.Memory.recorder.
Referenced by nars.storage.Memory.Memory().
{
         this.recorder = recorder;
     }
setSubstitute()
void nars.storage.Memory.setSubstitute (Map< Term, Term > substitute)
Definition at line 705 of file Memory.java.
References nars.storage.Memory.substitute.
{
         this.substitute = substitute;
     }
setTaskForgettingRate()
void nars.storage.Memory.setTaskForgettingRate (AtomicInteger taskForgettingRate)
Implements nars.storage.WorkSpace.
Definition at line 580 of file Memory.java.
References nars.storage.Memory.taskForgettingRate.
{
         this.taskForgettingRate = taskForgettingRate;
     }
singlePremiseTask() [1/2]
static void nars.storage.Memory.singlePremiseTask (Memory memory, Term newContent, TruthValue newTruth, BudgetValue newBudget) static
Shared final operations by all single-premise rules, called in StructuralRules.
Parameters
memory
newContent The content of the sentence in task
newTruth The truth value of the sentence in task
newBudget The budget value in task
Definition at line 318 of file Memory.java.
References nars.storage.Memory.getCurrentTask(), nars.entity.Sentence.getPunctuation(), and nars.entity.Task.getSentence().
Referenced by nars.inference.RuleTables.contraposition(), nars.inference.LocalRules.convertedJudgment(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralCompound(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.StructuralRules.structuralStatement(), nars.inference.RuleTables.transformNegation(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.StructuralRules.transformProductImage(), nars.inference.RuleTables.transformSetRelation(), and nars.inference.StructuralRules.transformSubjectPI().
{
         singlePremiseTask(memory, newContent, memory.getCurrentTask().getSentence().getPunctuation(), newTruth, newBudget);
     }
singlePremiseTask() [2/2]
static void nars.storage.Memory.singlePremiseTask (Memory memory, Term newContent, int punctuation, TruthValue newTruth, BudgetValue newBudget) static
Shared final operations by all single-premise rules, called in StructuralRules.
Parameters
memory
newContent The content of the sentence in task
punctuation The punctuation of the sentence in task
newTruth The truth value of the sentence in task
newBudget The budget value in task
Definition at line 331 of file Memory.java.
References nars.entity.Stamp.createStamp(), nars.storage.Memory.derivedTask(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getNewStamp(), nars.entity.Sentence.getRevisible(), nars.entity.Task.getSentence(), nars.entity.Sentence.getStamp(), nars.storage.Memory.getTime(), nars.entity.Sentence.isJudgment(), and nars.storage.Memory.setNewStamp().
{
         Sentence taskSentence = memory.getCurrentTask().getSentence();
         if (taskSentence.isJudgment() || null == memory.getCurrentBelief()) {
             memory.setNewStamp(Stamp.createStamp(taskSentence.getStamp(), Memory.getTime(memory)));
         } else {
             memory.setNewStamp(Stamp.createStamp(memory.getCurrentBelief().getStamp(), Memory.getTime(memory)));
         }
         Sentence newSentence = new Sentence(newContent, punctuation, newTruth, memory.getNewStamp(), taskSentence.getRevisible());
         Task newTask = new Task(newSentence, newBudget, memory.getCurrentTask(), null);
         Memory.derivedTask(memory, newTask);
     }
taskBuffersStartPlay()
static void nars.storage.Memory.taskBuffersStartPlay (Memory memory, BagObserver bagObserver, String s) static
Display new tasks, called from MainWindow.
see
Parameters
memory
bagObserver
s the window title
Definition at line 459 of file Memory.java.
References nars.storage.Bag< Type extends Item >.addBagObserver(), nars.storage.Memory.getNovelTasks(), and nars.storage.BagObserver.setBag().
{
         bagObserver.setBag(memory.getNovelTasks());
         memory.getNovelTasks().addBagObserver(bagObserver, s);
     }
termToConcept()
static Concept nars.storage.Memory.termToConcept (Memory memory, TermStruct term) static
Get an existing Concept for a given Term.
Parameters
memory
term The Term naming a concept
Returns
a Concept or null
Definition at line 158 of file Memory.java.
References nars.storage.Memory.nameToConcept().
Referenced by nars.storage.Memory.processNewTask(), and nars.inference.RuleTables.reason().
{
         return nameToConcept(memory, term.getName());
     }
toString()
static String nars.storage.Memory.toString (Memory memory) static
Definition at line 502 of file Memory.java.
References nars.storage.Memory.getConcepts(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentBeliefLink(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getNovelTasks(), nars.storage.Memory.toStringIfNotNull(), and nars.storage.Memory.toStringLongIfNotNull().
Referenced by nars.storage.ReasonerBatch.asString().
{
         return toStringLongIfNotNull(memory.getConcepts(), "concepts")
                 + toStringLongIfNotNull(memory.getNovelTasks(), "novelTasks")
                 + toStringIfNotNull(memory.getNewTasks(), "newTasks")
                 + toStringLongIfNotNull(memory.getCurrentTask(), "currentTask")
                 + toStringLongIfNotNull(memory.getCurrentBeliefLink(), "currentBeliefLink")
                 + toStringIfNotNull(memory.getCurrentBelief(), "currentBelief");
     }
toStringIfNotNull()
static String nars.storage.Memory.toStringIfNotNull (Object item, String title) static private
Definition at line 521 of file Memory.java.
Referenced by nars.storage.Memory.toString().
{
         return null == item ? "" : "\n " + title + ":\n"
                 + item;
     }
toStringLongIfNotNull() [1/2]
static String nars.storage.Memory.toStringLongIfNotNull (Bag<?> item, String title) static private
Definition at line 511 of file Memory.java.
References nars.storage.Bag< Type extends Item >.toStringLong().
Referenced by nars.storage.Memory.toString().
{
         return null == item ? "" : "\n " + title + ":\n"
                 + item.toStringLong();
     }
toStringLongIfNotNull() [2/2]
static String nars.storage.Memory.toStringLongIfNotNull (Item item, String title) static private
Definition at line 516 of file Memory.java.
References nars.entity.Item.toStringLong().
{
         return null == item ? "" : "\n " + title + ":\n"
                 + Item.toStringLong(item);
     }
workCycle()
static void nars.storage.Memory.workCycle (Memory memory, long clock) static
An atomic working workCycle of the system: process new Tasks, then fireFromProcessConcept a concept.
Called from Reasoner.tick only
Parameters
memory
clock The current time to be displayed
Definition at line 351 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.storage.Memory.getNovelTasks(), nars.storage.Memory.getRecorder(), nars.storage.Memory.noResult(), nars.storage.Memory.processConcept(), nars.storage.Memory.processNewTask(), nars.storage.Memory.processNovelTask(), and nars.storage.Bag< Type extends Item >.refresh().
Referenced by nars.storage.ReasonerBatch.doTick().
{
         memory.getRecorder().append(" --- " + clock + " ---\n");
         processNewTask(memory);
         if (noResult(memory)) {       // necessary?
             processNovelTask(memory);
         }
         if (noResult(memory)) {       // necessary?
             processConcept(memory);
         }
         memory.getNovelTasks().refresh();
     }
Member Data Documentation
beliefForgettingRate
AtomicInteger nars.storage.Memory.beliefForgettingRate = new AtomicInteger(Parameters.TERM_LINK_FORGETTING_CYCLE) private
Definition at line 46 of file Memory.java.
Referenced by nars.storage.Memory.getBeliefForgettingRate(), and nars.storage.Memory.setBeliefForgettingRate().
conceptForgettingRate
AtomicInteger nars.storage.Memory.conceptForgettingRate = new AtomicInteger(Parameters.CONCEPT_FORGETTING_CYCLE) private
Definition at line 48 of file Memory.java.
Referenced by nars.storage.Memory.getConceptForgettingRate(), and nars.storage.Memory.setConceptForgettingRate().
concepts
ConceptBag nars.storage.Memory.concepts private
Definition at line 43 of file Memory.java.
Referenced by nars.storage.Memory.getConcepts(), and nars.storage.Memory.setConcepts().
currentBelief
Sentence nars.storage.Memory.currentBelief private
Definition at line 58 of file Memory.java.
Referenced by nars.storage.Memory.getCurrentBelief(), and nars.storage.Memory.setCurrentBelief().
currentBeliefLink
TermLink nars.storage.Memory.currentBeliefLink private
Definition at line 57 of file Memory.java.
Referenced by nars.storage.Memory.getCurrentBeliefLink(), and nars.storage.Memory.setCurrentBeliefLink().
currentConcept
Concept nars.storage.Memory.currentConcept private
Definition at line 54 of file Memory.java.
Referenced by nars.storage.Memory.getCurrentConcept(), and nars.storage.Memory.setCurrentConcept().
currentTask
Task nars.storage.Memory.currentTask private
Definition at line 56 of file Memory.java.
Referenced by nars.storage.Memory.getCurrentTask(), and nars.storage.Memory.setCurrentTask().
currentTaskLink
TaskLink nars.storage.Memory.currentTaskLink private
Definition at line 55 of file Memory.java.
Referenced by nars.storage.Memory.getCurrentTaskLink(), and nars.storage.Memory.setCurrentTaskLink().
currentTerm
Term nars.storage.Memory.currentTerm private
Definition at line 53 of file Memory.java.
Referenced by nars.storage.Memory.getCurrentTerm(), and nars.storage.Memory.setCurrentTerm().
exportStrings
List<String> nars.storage.Memory.exportStrings private
Definition at line 52 of file Memory.java.
Referenced by nars.storage.Memory.getExportStrings(), and nars.storage.Memory.setExportStrings().
newStamp
Stamp nars.storage.Memory.newStamp private
Definition at line 59 of file Memory.java.
Referenced by nars.storage.Memory.getNewStamp(), and nars.storage.Memory.setNewStamp().
newTasks
List<Task> nars.storage.Memory.newTasks private
Definition at line 51 of file Memory.java.
Referenced by nars.storage.Memory.getNewTasks(), and nars.storage.Memory.setNewTasks().
novelTasks
NovelTaskBag nars.storage.Memory.novelTasks private
Definition at line 44 of file Memory.java.
Referenced by nars.storage.Memory.getNovelTasks(), and nars.storage.Memory.setNovelTasks().
reasoner
ReasonerBatch nars.storage.Memory.reasoner private
Definition at line 40 of file Memory.java.
Referenced by nars.storage.Memory.getReasoner(), nars.storage.Memory.Memory(), and nars.storage.Memory.setReasoner().
recorder
IInferenceRecorder nars.storage.Memory.recorder private
Definition at line 45 of file Memory.java.
Referenced by nars.storage.Memory.getRecorder(), and nars.storage.Memory.setRecorder().
substitute
Map<Term, Term> nars.storage.Memory.substitute private
Definition at line 62 of file Memory.java.
Referenced by nars.storage.Memory.getSubstitute(), and nars.storage.Memory.setSubstitute().
taskForgettingRate
AtomicInteger nars.storage.Memory.taskForgettingRate = new AtomicInteger(Parameters.TASK_LINK_FORGETTING_CYCLE) private
Definition at line 47 of file Memory.java.
Referenced by nars.storage.Memory.getTaskForgettingRate(), and nars.storage.Memory.setTaskForgettingRate().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/storage/Memory.java