photon: nars.language.ImageExt Class Reference
nars.language.ImageExt Class Reference
An extension image.
Public Member Functions
Object clone ()
Clone an object.
Integer getRelationIndex ()
get the index of the relation in the component list
Term getRelation ()
Get the relation term in the Image.
Term getTheOtherComponent ()
Get the other term in the Image.
String operator ()
get the operator of the term.
Public Member Functions inherited from nars.language.CompoundTerm
abstract String operator ()
Abstract method to get the operator of the compound.
abstract Object clone ()
Abstract clone method.
void setName (String s)
Change the oldName of a CompoundTerm, called after variable substitution.
int getComplexity ()
syntactic complexity of the compound, the sum of those of its components plus 1
boolean isConstant ()
Whether the term names a concept.
void setConstant (boolean isConstant)
Set the constant status.
boolean isCommutative ()
Check if the order of the components matters.
int size ()
get the number of components
Term componentAt (int i)
get a component by index
List< Term > getComponents ()
list of (direct) components
List< Term > cloneComponents ()
Clone the component list.
boolean containComponent (Term t)
Check whether the compound contains a certain component.
boolean containAllComponents (Term t)
Check whether the compound contains all components of another term, or that term as a whole.
boolean containVar ()
Whether this compound term contains any variable term.
void renameVariables ()
Rename the variables in the compound.
void renameVariables (HashMap< Variable, Variable > map)
Rename the variables in the compound.
void applySubstitute (Map< Term, Term > subs)
Recursively apply a substitute to the current CompoundTerm.
List< TermLink > prepareComponentLinks ()
Build TermLink templates to constant components and subcomponents.
void setComponents (List< Term > components)
void setComplexity (short complexity)
Public Member Functions inherited from nars.language.Term
Term (String name)
Constructor with a given name.
String getName ()
Reporting the name of the current Term.
void setName (String $name$)
Object clone ()
Make a new Term with the same name.
boolean equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
int hashCode ()
Produce a hash code for the term.
boolean isConstant ()
Check whether the current Term can name a Concept.
void renameVariables ()
Blank method to be override in CompoundTerm.
int getComplexity ()
The syntactic complexity, for constant automic Term, is 1.
final int compareTo (Term that)
Check the relative order of two Terms.
final String toString ()
The same as getName by default, used in display only.
Static Public Member Functions
static Term make (List< Term > argList, Memory memory)
Try to make a new ImageExt.
static Term make (Product product, Term relation, Integer index, Memory memory)
Try to make an Image from a Product and a relation.
static Term make (ImageExt oldImage, Term component, Integer index, Memory memory)
Try to make an Image from an existing Image and a component.
static Term make (List< Term > argument, Integer index, Memory memory)
Try to make a new compound from a set of components.
static String makeName (ImageExt imageExt)
override the default in making the name of the current term from existing fields
Static Public Member Functions inherited from nars.language.CompoundTerm
static Term make (CompoundTerm compound, List< Term > components, Memory memory)
Try to make a compound term from a template and a list of components.
static Term make (String op, List< Term > arg, Memory memory)
Try to make a compound term from an operator and a list of components.
static List< Term > cloneList (List< Term > original)
Deep clone an array list of terms.
static Term addComponents (CompoundTerm t1, Term t2, Memory memory)
Try to add a component into a compound.
static Term reduceComponents (CompoundTerm t1, Term t2, Memory memory)
Try to remove a component from a compound.
static Term setComponent (CompoundTerm compound, int index, Term t, Memory memory)
Try to replace a component in a compound at a given index by another one.
Static Public Member Functions inherited from nars.language.Term
static boolean hasOrIsTerm $par (Term root, Term... leaves)
Private Member Functions
ImageExt (String n, List< Term > arg, Integer index)
Constructor with partial values, called by make.
ImageExt (String n, List< Term > cs, boolean con, int complexity, Integer index)
Constructor with full values, called by clone.
Private Attributes
Integer relationIndex
The index of relation in the component list.
Additional Inherited Members
Protected Member Functions inherited from nars.language.CompoundTerm
CompoundTerm (String name, List< Term > components, boolean isConstant, int complexity)
Constructor called from subclasses constructors to clone the fields.
CompoundTerm ()
Default constructor.
CompoundTerm (List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
CompoundTerm (String name, List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
String makeName ()
default method to make the oldName of the current term from existing fields
Protected Member Functions inherited from nars.language.Term
Term ()
Default constructor that build an internal Term.
Static Protected Member Functions inherited from nars.language.CompoundTerm
static List< Term > argumentsToList (Term ...t2)
build a component list from two terms
static String makeCompoundName (String op, Iterable< Term > arg)
default method to make the oldName of a compound term from given fields
static String makeSetName (char opener, List< Term > arg, char closer)
make the oldName of an ExtensionSet or IntensionSet
static String makeImageName (String op, List< Term > arg, int relationIndex)
default method to make the oldName of an image term from given fields
Protected Attributes inherited from nars.language.Term
String name
A Term is identified uniquely by its name, a sequence of characters in a given alphabet (ASCII or Unicode)
Static Package Functions inherited from nars.language.CompoundTerm
static void calcComplexity (CompoundTerm compoundTerm)
The complexity of the term is the sum of those of the components plus 1.
Detailed Description
An extension image.
B --> (/,P,A,_)) iff (*,A,B) --> P
Internally, it is actually (/,A,P)_1, with an index.
Definition at line 36 of file ImageExt.java.
Constructor & Destructor Documentation
ImageExt() [1/2]
nars.language.ImageExt.ImageExt (String n, List< Term > arg, Integer index) private
Constructor with partial values, called by make.
Parameters
n The name of the term
arg The component list of the term
index The index of relation in the component list
Definition at line 50 of file ImageExt.java.
References nars.language.ImageExt.relationIndex.
Referenced by nars.language.ImageExt.clone(), and nars.language.ImageExt.make().
{
         super(n, arg);
         relationIndex = index;
     }
ImageExt() [2/2]
nars.language.ImageExt.ImageExt (String n, List< Term > cs, boolean con, int complexity, Integer index) private
Constructor with full values, called by clone.
Parameters
n The name of the term
cs Component list
complexity Syntactic complexity of the compound
index The index of relation in the component list
Definition at line 63 of file ImageExt.java.
References nars.language.CompoundTerm.complexity, and nars.language.ImageExt.relationIndex.
{
         super(n, cs, con, complexity);
         relationIndex = index;
     }
Member Function Documentation
clone()
Object nars.language.ImageExt.clone ()
Clone an object.
Returns
A new object, to be casted into an ImageExt
Definition at line 163 of file ImageExt.java.
References nars.language.CompoundTerm.cloneList(), nars.language.CompoundTerm.getComplexity(), nars.language.CompoundTerm.getComponents(), nars.language.ImageExt.ImageExt(), nars.language.CompoundTerm.isConstant(), nars.language.Term.name, and nars.language.ImageExt.relationIndex.
{
         return new ImageExt(name, (ArrayList<Term>) cloneList(getComponents()), isConstant(), getComplexity(), relationIndex);
     }
getRelation()
Term nars.language.ImageExt.getRelation ()
Get the relation term in the Image.
Returns
The term representing a relation
Definition at line 181 of file ImageExt.java.
References nars.language.CompoundTerm.getComponents(), and nars.language.ImageExt.relationIndex.
{
         return getComponents().get(relationIndex);
     }
getRelationIndex()
Integer nars.language.ImageExt.getRelationIndex ()
get the index of the relation in the component list
Returns
the index of relation
Definition at line 172 of file ImageExt.java.
References nars.language.ImageExt.relationIndex.
Referenced by nars.language.ImageExt.make(), nars.inference.StructuralRules.switchOrder(), and nars.inference.StructuralRules.transformPredicatePI().
{
         return relationIndex;
     }
getTheOtherComponent()
Term nars.language.ImageExt.getTheOtherComponent ()
Get the other term in the Image.
Returns
The term related
Definition at line 190 of file ImageExt.java.
References nars.language.CompoundTerm.getComponents(), and nars.language.ImageExt.relationIndex.
{
         return getComponents().size() != 2 ? null : (relationIndex == 0) ? getComponents().get(1) : getComponents().get(0);
     }
make() [1/4]
static Term nars.language.ImageExt.make (List< Term > argList, Memory memory) static
Try to make a new ImageExt.
Called by StringParser.
Parameters
argList The list of components
memory Reference to the memory
Returns
the Term generated from the arguments
Definition at line 75 of file ImageExt.java.
References nars.io.Symbols.IMAGE_PLACE_HOLDER.
Referenced by nars.language.ImageExt.make(), nars.language.CompoundTerm.make(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.StructuralRules.transformProductImage(), and nars.inference.StructuralRules.transformSubjectPI().
{
         Term r = null;
         if (argList.size() >= 2) {
             Term relation = argList.get(0);
             List<Term> argument = new ArrayList<Term>();
             int index = 0;
             for (int j = 1; j < argList.size(); j++) {
                 if (argList.get(j).getName().charAt(0) != Symbols.IMAGE_PLACE_HOLDER) {
                     argument.add(argList.get(j));
                 } else {
                     index = j - 1;
                     argument.add(relation);
                 }
             }
             r = make(argument, index, memory);
         }
         return r;
     }
make() [2/4]
static Term nars.language.ImageExt.make (Product product, Term relation, Integer index, Memory memory) static
Try to make an Image from a Product and a relation.
Called by the inference rules.
Parameters
product The product
relation The relation
index The index of the place-holder
Returns
A compound generated or a term it reduced to
Definition at line 102 of file ImageExt.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.componentAt(), nars.language.Term.equals(), nars.language.ImageExt.make(), and nars.language.CompoundTerm.size().
{
         Term r = null;
         e:
         {
             if (relation instanceof Product) {
                 Product p2 = (Product) relation;
                 if ((product.size() == 2) && (p2.size() == 2)) {
                     // (/,_,(*,a,b),b) is reduced to a
                     if ((index == 0) && product.componentAt(1).equals(p2.componentAt(1))) {
                         r = p2.componentAt(0);
                         break e;
                     } else // (/,(*,a,b),a,_) is reduced to b
                         if ((index == 1) && product.componentAt(0).equals(p2.componentAt(0))) {
                             r = p2.componentAt(1);
                             break e;
                         }
                 }
             }
             List<Term> argument = product.cloneComponents();
             argument.set(index, relation);
             r = make(argument, index, memory);
         }
         return r;
     }
make() [3/4]
static Term nars.language.ImageExt.make (ImageExt oldImage, Term component, Integer index, Memory memory) static
Try to make an Image from an existing Image and a component.
Called by the inference rules.
Parameters
oldImage The existing Image
component The component to be added into the component list
index The index of the place-holder in the new Image
Returns
A compound generated or a term it reduced to
Definition at line 136 of file ImageExt.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.ImageExt.getRelationIndex(), and nars.language.ImageExt.make().
{
         List<Term> argList = oldImage.cloneComponents();
         int oldIndex = oldImage.getRelationIndex();
         Term relation = argList.get(oldIndex);
         argList.set(oldIndex, component);
         argList.set(index, relation);
         return make(argList, index, memory);
     }
make() [4/4]
static Term nars.language.ImageExt.make (List< Term > argument, Integer index, Memory memory) static
Try to make a new compound from a set of components.
Called by the public make methods.
Parameters
argument The argument list
index The index of the place-holder in the new Image
Returns
the Term generated from the arguments
Definition at line 152 of file ImageExt.java.
References nars.io.Symbols.IMAGE_EXT_OPERATOR, nars.language.ImageExt.ImageExt(), nars.language.CompoundTerm.makeImageName(), nars.language.Term.name, and nars.storage.Memory.nameToListedTerm().
{
         String name = makeImageName(Symbols.IMAGE_EXT_OPERATOR, argument, index);
         Term t = Memory.nameToListedTerm(memory, name);
         return (t != null) ? t : new ImageExt(name, argument, index);
     }
makeName()
static String nars.language.ImageExt.makeName (ImageExt imageExt) static
override the default in making the name of the current term from existing fields
Returns
the name of the term
Parameters
imageExt
Definition at line 200 of file ImageExt.java.
References nars.language.CompoundTerm.getComponents(), nars.io.Symbols.IMAGE_EXT_OPERATOR, nars.language.CompoundTerm.makeImageName(), and nars.language.ImageExt.relationIndex.
{
         return makeImageName(Symbols.IMAGE_EXT_OPERATOR, imageExt.getComponents(), imageExt.relationIndex);
     }
operator()
String nars.language.ImageExt.operator ()
get the operator of the term.
Returns
the operator of the term
Definition at line 209 of file ImageExt.java.
References nars.io.Symbols.IMAGE_EXT_OPERATOR.
{
         return Symbols.IMAGE_EXT_OPERATOR;
     }
Member Data Documentation
relationIndex
Integer nars.language.ImageExt.relationIndex private
The index of relation in the component list.
Definition at line 41 of file ImageExt.java.
Referenced by nars.language.ImageExt.clone(), nars.language.ImageExt.getRelation(), nars.language.ImageExt.getRelationIndex(), nars.language.ImageExt.getTheOtherComponent(), nars.language.ImageExt.ImageExt(), and nars.language.ImageExt.makeName().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/language/ImageExt.java