photon: nars.inference.LocalRules Class Reference
nars.inference.LocalRules Class Reference
Directly process a task by a oldBelief, with only two Terms in both.
Static Public Member Functions
static void match (Task task, Sentence belief, Memory memory)
The task and belief have the same content.
static boolean revisible (Sentence s1, SentenceStruct s2)
Check whether two sentences can be used in revision.
static void revision (SentenceStruct newBelief, SentenceStruct oldBelief, boolean feedbackToLinks, Memory memory)
Belief revision.
static void trySolution (Sentence belief, Task task, Memory memory)
Check if a Sentence provide a better answer to a Question or Goal.
static float solutionQuality (SentenceStruct problem, SentenceStruct solution)
Evaluate the quality of the judgment as a solution to a problem.
static void matchReverse (Memory memory)
The task and belief match reversely.
static void matchAsymSym (Sentence asym, SentenceStruct sym, int figure, Memory memory)
Inheritance/Implication matches Similarity/Equivalence.
Static Package Functions
static BudgetValue revise (TruthValue tTruth, TruthValue bTruth, TruthValue truth, boolean feedbackToLinks, WorkSpace memory)
Evaluate the quality of a revision, then de-prioritize the premises.
static BudgetValue solutionEval (SentenceStruct problem, SentenceStruct solution, Task task, WorkSpace memory)
Evaluate the quality of a belief as a solution to a problem, then reward the belief and de-prioritize the problem.
Static Private Member Functions
static void inferToSym (Sentence judgment1, SentenceStruct judgment2, Memory memory)
{<S --> P>,
static void inferToAsym (Sentence asym, SentenceStruct sym, Memory memory)
{<S <-> P>,
static void conversion (Memory memory)
{
static void convertRelation (Memory memory)
{<S --> P>} |- <S <-> P> {<S <-> P>} |- <S --> P> Switch between Inheritance/Implication and Similarity/Equivalence
static void convertedJudgment (TruthValue newTruth, BudgetValue newBudget, Memory memory)
Convert jusgment into different relation.
Detailed Description
Directly process a task by a oldBelief, with only two Terms in both.
In matching, the new task is compared with all existing direct Tasks in that Concept, to carry out:
revision: between judgments on non-overlapping evidence; revision: between judgments; satisfy: between a Sentence and a Question/Goal; merge: between items of the same type and stamp; conversion: between different inheritance relations.
Definition at line 41 of file LocalRules.java.
Member Function Documentation
conversion()
static void nars.inference.LocalRules.conversion (Memory memory) static private
{
<P --> S>} |- <S --> P> Produce an Inheritance/Implication from a reversed Inheritance/Implication
Parameters
memory Reference to the memory
Definition at line 270 of file LocalRules.java.
References nars.inference.TruthFunctions.conversion(), nars.inference.LocalRules.convertedJudgment(), nars.inference.BudgetFunctions.forward(), nars.storage.Memory.getCurrentBelief(), and nars.entity.Sentence.getTruth().
Referenced by nars.inference.LocalRules.matchReverse().
{
         TruthValue truth = TruthFunctions.conversion(memory.getCurrentBelief()
                 .getTruth());
         BudgetValue budget = BudgetFunctions.forward(memory, truth);
         convertedJudgment(truth, budget, memory);
     }
convertedJudgment()
static void nars.inference.LocalRules.convertedJudgment (TruthValue newTruth, BudgetValue newBudget, Memory memory) static private
Convert jusgment into different relation.
called in MatchingRules
Parameters
newBudget The budget value of the new task
newTruth The truth value of the new task
memory Reference to the memory
Definition at line 307 of file LocalRules.java.
References nars.language.Variable.containVarQuery(), nars.language.Term.equals(), nars.entity.Task.getContent(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.language.Term.getName(), nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), nars.io.Symbols.JUDGMENT_MARK, nars.language.Statement.make(), and nars.storage.Memory.singlePremiseTask().
Referenced by nars.inference.LocalRules.conversion(), and nars.inference.LocalRules.convertRelation().
{
         Statement content = (Statement) memory.getCurrentTask().getContent();
         Statement beliefContent = (Statement) memory.getCurrentBelief()
                 .getContent();
         Term subjT = content.getSubject();
         Term predT = content.getPredicate();
         Term subjB = beliefContent.getSubject();
         Term predB = beliefContent.getPredicate();
         Term otherTerm;
         if (Variable.containVarQuery(subjT.getName())) {
             otherTerm = (predT.equals(subjB)) ? predB : subjB;
             content = Statement.make(content, otherTerm, predT, memory);
         }
         if (Variable.containVarQuery(predT.getName())) {
             otherTerm = (subjT.equals(subjB)) ? predB : subjB;
             content = Statement.make(content, subjT, otherTerm, memory);
         }
         Memory.singlePremiseTask(memory, content, Symbols.JUDGMENT_MARK,
                 newTruth, newBudget);
     }
convertRelation()
static void nars.inference.LocalRules.convertRelation (Memory memory) static private
{<S --> P>} |- <S <-> P> {<S <-> P>} |- <S --> P> Switch between Inheritance/Implication and Similarity/Equivalence
Parameters
memory Reference to the memory
Definition at line 284 of file LocalRules.java.
References nars.inference.TruthFunctions.abduction(), nars.inference.LocalRules.convertedJudgment(), nars.inference.TruthFunctions.deduction(), nars.inference.BudgetFunctions.forward(), nars.entity.Task.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), and nars.entity.Sentence.getTruth().
Referenced by nars.inference.LocalRules.matchAsymSym().
{
         TruthValue truth = memory.getCurrentBelief().getTruth();
         if (((Statement) memory.getCurrentTask().getContent()).isCommutative()) {
             truth = TruthFunctions.abduction(truth, 1.0f);
         } else {
             truth = TruthFunctions.deduction(truth, 1.0f);
         }
         BudgetValue budget = BudgetFunctions.forward(memory, truth);
         convertedJudgment(truth, budget, memory);
     }
inferToAsym()
static void nars.inference.LocalRules.inferToAsym (Sentence asym, SentenceStruct sym, Memory memory) static private
{<S <-> P>,
<P --> S>} |- <S --> P> Produce an Inheritance/Implication from a Similarity/Equivalence and a reversed Inheritance/Implication
Parameters
asym The asymmetric premise
sym The symmetric premise
memory Reference to the memory
Definition at line 248 of file LocalRules.java.
References nars.storage.Memory.doublePremiseTask(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.language.Statement.make(), and nars.inference.TruthFunctions.reduceConjunction().
Referenced by nars.inference.LocalRules.matchAsymSym().
{
         Statement statement = (Statement) asym.getContent();
         Term sub = statement.getPredicate();
         Term pre = statement.getSubject();
         Statement content = Statement.make(statement, sub, pre, memory);
         TruthValue truth = TruthFunctions.reduceConjunction(sym.getTruth(),
                 asym.getTruth());
         BudgetValue budget = BudgetFunctions.forward(memory, truth);
         Memory.doublePremiseTask(memory, content, truth, budget);
     }
inferToSym()
static void nars.inference.LocalRules.inferToSym (Sentence judgment1, SentenceStruct judgment2, Memory memory) static private
{<S --> P>,
<P --> S} |- <S <-> p> Produce Similarity/Equivalence from a pair of reversed Inheritance/Implication
Parameters
judgment1 The first premise
judgment2 The second premise
memory Reference to the memory
Definition at line 217 of file LocalRules.java.
References nars.storage.Memory.doublePremiseTask(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.inference.TruthFunctions.intersection(), and nars.language.Similarity.make().
Referenced by nars.inference.LocalRules.matchReverse().
{
         Statement s1 = (Statement) judgment1.getContent();
         Term t1 = s1.getSubject();
         Term t2 = s1.getPredicate();
         Term content;
         if (s1 instanceof Inheritance) {
             content = Similarity.make(t1, t2, memory);
         } else {
             content = Equivalence.Companion.make(t1, t2, memory);
         }
         TruthValue value1 = judgment1.getTruth();
         TruthHandle value2 = judgment2.getTruth();
         TruthValue truth = TruthFunctions.intersection(value1, value2);
         BudgetValue budget = BudgetFunctions.forward(memory, truth);
         Memory.doublePremiseTask(memory, content, truth, budget);
     }
match()
static void nars.inference.LocalRules.match (Task task, Sentence belief, Memory memory) static
The task and belief have the same content.
called in RuleTables.reason
Parameters
task The task
belief The belief
memory Reference to the memory
Definition at line 56 of file LocalRules.java.
References nars.language.Term.clone(), nars.entity.Sentence.clone(), nars.entity.Sentence.getContent(), nars.entity.Task.getSentence(), nars.entity.Sentence.isJudgment(), nars.inference.LocalRules.revisible(), nars.inference.LocalRules.revision(), nars.inference.LocalRules.trySolution(), nars.language.Variable.unify(), and nars.io.Symbols.VAR_QUERY.
Referenced by nars.inference.RuleTables.reason().
{
         Sentence sentence = (Sentence) task.getSentence().clone();
         if (sentence.isJudgment()) {
             if (revisible(sentence, belief)) {
                 revision(sentence, belief, true, memory);
             }
         } else if (Variable.unify(Symbols.VAR_QUERY, sentence.getContent(),
                 (Term) belief.getContent().clone())) {
             // trySolution(sentence, belief, task, memory);
             trySolution(belief, task, memory);
         }
     }
matchAsymSym()
static void nars.inference.LocalRules.matchAsymSym (Sentence asym, SentenceStruct sym, int figure, Memory memory) static
Inheritance/Implication matches Similarity/Equivalence.
Parameters
asym A Inheritance/Implication sentence
sym A Similarity/Equivalence sentence
figure location of the shared term
memory
Definition at line 194 of file LocalRules.java.
References nars.inference.LocalRules.convertRelation(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.inference.LocalRules.inferToAsym(), and nars.entity.Sentence.isJudgment().
Referenced by nars.inference.RuleTables.asymmetricSymmetric().
{
         if (memory.getCurrentTask().getSentence().isJudgment()) {
             inferToAsym(asym, sym, memory);
         } else {
             convertRelation(memory);
         }
     }
matchReverse()
static void nars.inference.LocalRules.matchReverse (Memory memory) static
The task and belief match reversely.
Parameters
memory Reference to the memory
Definition at line 172 of file LocalRules.java.
References nars.inference.LocalRules.conversion(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.inference.LocalRules.inferToSym(), and nars.entity.Sentence.isJudgment().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric().
{
         Task task = memory.getCurrentTask();
         Sentence belief = memory.getCurrentBelief();
         Sentence sentence = task.getSentence();
         if (sentence.isJudgment()) {
             inferToSym(sentence, belief, memory);
         } else {
             conversion(memory);
         }
     }
revise()
static BudgetValue nars.inference.LocalRules.revise (TruthValue tTruth, TruthValue bTruth, TruthValue truth, boolean feedbackToLinks, WorkSpace memory) static package
Evaluate the quality of a revision, then de-prioritize the premises.
Parameters
tTruth The truth value of the judgment in the task
bTruth The truth value of the belief
truth The truth value of the conclusion of revision
Returns
The budget for the new task
Definition at line 340 of file LocalRules.java.
References nars.entity.Item.decDurability(), nars.entity.Item.decPriority(), nars.entity.Item.getBudget(), nars.entity.TruthValue.getConfidence(), nars.storage.WorkSpace.getCurrentBeliefLink(), nars.storage.WorkSpace.getCurrentTask(), nars.storage.WorkSpace.getCurrentTaskLink(), nars.entity.Item.getDurability(), nars.entity.Item.getPriority(), nars.entity.TruthValue.isExpDifAbs(), nars.inference.UtilityFunctions.or(), and nars.inference.BudgetFunctions.truthToQuality().
Referenced by nars.inference.LocalRules.revision().
{
         float difT = truth.isExpDifAbs(tTruth);
         Task task = memory.getCurrentTask();
         Item.decPriority(task.getBudget(), 1 - difT);
         Item.decDurability(task.getBudget(), 1 - difT);
         if (feedbackToLinks) {
             TaskLink tLink = memory.getCurrentTaskLink();
             Item.decPriority(tLink.getBudget(), 1 - difT);
             Item.decDurability(tLink.getBudget(), 1 - difT);
             TermLink bLink = memory.getCurrentBeliefLink();
             float difB = truth.isExpDifAbs(bTruth);
             Item.decPriority(bLink.getBudget(), 1 - difB);
             Item.decDurability(bLink.getBudget(), 1 - difB);
         }
         float dif = truth.getConfidence()
                 - Math.max(tTruth.getConfidence(), bTruth.getConfidence());
         float priority = UtilityFunctions.or(dif, task.getPriority());
         float durability = UtilityFunctions.or(dif, task.getDurability());
         float quality = BudgetFunctions.truthToQuality(truth);
         return new BudgetValue(priority, durability, quality);
     }
revisible()
static boolean nars.inference.LocalRules.revisible (Sentence s1, SentenceStruct s2) static
Check whether two sentences can be used in revision.
Parameters
s1 The first sentence
s2 The second sentence
Returns
If revision is possible between the two sentences
Definition at line 78 of file LocalRules.java.
References nars.language.Term.equals(), nars.entity.Sentence.getContent(), and nars.entity.Sentence.getRevisible().
Referenced by nars.inference.LocalRules.match(), and nars.entity.Concept.processJudgment().
{
         return (s1.getContent().equals(s2.getContent()) && s1.getRevisible());
     }
revision()
static void nars.inference.LocalRules.revision (SentenceStruct newBelief, SentenceStruct oldBelief, boolean feedbackToLinks, Memory memory) static
Belief revision.
called from Concept.reviseTable and match
Parameters
newBelief The new belief in task
oldBelief The previous belief with the same content
feedbackToLinks Whether to send feedback to the links
memory
Definition at line 95 of file LocalRules.java.
References nars.storage.Memory.doublePremiseTask(), nars.inference.LocalRules.revise(), and nars.inference.TruthFunctions.revision().
Referenced by nars.inference.LocalRules.match(), and nars.entity.Concept.processJudgment().
{
         TruthValue newTruth = (TruthValue) newBelief.getTruth();
         TruthValue oldTruth = (TruthValue) oldBelief.getTruth();
         TruthValue truth = TruthFunctions.revision(newTruth, oldTruth);
         BudgetValue budget = revise(newTruth, oldTruth, truth, feedbackToLinks,
                 memory);
         Term content = (Term) newBelief.getContent();
         Memory.doublePremiseTask(memory, content, truth, budget);
     }
solutionEval()
static BudgetValue nars.inference.LocalRules.solutionEval (SentenceStruct problem, SentenceStruct solution, Task task, WorkSpace memory) static package
Evaluate the quality of a belief as a solution to a problem, then reward the belief and de-prioritize the problem.
Parameters
problem The problem (question or goal) to be solved
solution The belief as solution
task The task to be immediatedly processed, or null for continued process
Returns
The budget for the new task which is the belief activated, if necessary
Definition at line 377 of file LocalRules.java.
References nars.entity.Item.getBudget(), nars.storage.WorkSpace.getCurrentBeliefLink(), nars.storage.WorkSpace.getCurrentTask(), nars.storage.WorkSpace.getCurrentTaskLink(), nars.entity.Item.getDurability(), nars.entity.Item.getPriority(), nars.entity.Task.getSentence(), nars.entity.Item.incPriority(), nars.entity.Sentence.isJudgment(), nars.entity.Item.setPriority(), nars.inference.LocalRules.solutionQuality(), and nars.inference.BudgetFunctions.truthToQuality().
Referenced by nars.inference.LocalRules.trySolution().
{
         BudgetValue budget = null;
         boolean feedbackToLinks = false;
         if (task == null) { // called in continued processing
             task = memory.getCurrentTask();
             feedbackToLinks = true;
         }
         boolean judgmentTask = task.getSentence().isJudgment();
         float quality = solutionQuality(problem, solution);
         if (judgmentTask) {
             Item.incPriority(task.getBudget(), quality);
         } else {
             task.setPriority(Math.min(1 - quality, task.getPriority()));
             budget = new BudgetValue(quality, task.getDurability(),
                     BudgetFunctions.truthToQuality(solution.getTruth()));
         }
         if (feedbackToLinks) {
             TaskLink tLink = memory.getCurrentTaskLink();
             tLink.setPriority(Math.min(1 - quality, tLink.getPriority()));
             TermLink bLink = memory.getCurrentBeliefLink();
             Item.incPriority(bLink.getBudget(), quality);
         }
         return budget;
     }
solutionQuality()
static float nars.inference.LocalRules.solutionQuality (SentenceStruct problem, SentenceStruct solution) static
Evaluate the quality of the judgment as a solution to a problem.
Parameters
problem A goal or question
solution The solution to be evaluated
Returns
The quality of the judgment as the solution
Definition at line 147 of file LocalRules.java.
References nars.entity.Sentence.containQueryVar(), nars.entity.TruthValue.getConfidence(), and nars.entity.TruthValue.getExpectation().
Referenced by nars.entity.Concept.evaluation(), nars.inference.LocalRules.solutionEval(), and nars.inference.LocalRules.trySolution().
{
         TruthValue truth1 = (TruthValue) solution.getTruth();
         if (problem == null) {
             return (truth1).getExpectation();
         }
         TruthValue truth = (TruthValue) truth1;
         if (Sentence.containQueryVar(problem)) { // "yes/no" question
             return truth.getExpectation()
                     / ((Term) solution.getContent()).getComplexity();
         } else { // "what" question or goal
             return truth.getConfidence();
         }
     }
trySolution()
static void nars.inference.LocalRules.trySolution (Sentence belief, Task task, Memory memory) static
Check if a Sentence provide a better answer to a Question or Goal.
Parameters
belief The proposed answer
task The task to be processed
memory Reference to the memory
Definition at line 118 of file LocalRules.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.storage.Memory.activatedTask(), nars.entity.Task.getBestSolution(), nars.entity.Task.getParentBelief(), nars.entity.Task.getSentence(), nars.entity.Task.isInput(), nars.storage.Memory.report(), nars.entity.Task.setBestSolution(), nars.inference.LocalRules.solutionEval(), and nars.inference.LocalRules.solutionQuality().
Referenced by nars.inference.LocalRules.match(), nars.entity.Concept.processJudgment(), and nars.entity.Concept.processQuestion().
{
         Sentence problem = task.getSentence();
         Sentence oldBest = task.getBestSolution();
         float newQ = solutionQuality(problem, belief);
         if (oldBest != null) {
             float oldQ = solutionQuality(problem, oldBest);
             if (oldQ >= newQ) {
                 return;
             }
         }
         task.setBestSolution(belief);
         if (task.isInput()) { // moved from Sentence
             Memory.report(memory, belief, false);
         }
         BudgetValue budget = solutionEval(problem, belief, task, memory);
         if ((budget != null) && budget.aboveThreshold()) {
             Memory.activatedTask(memory, budget, belief, task.getParentBelief());
         }
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/inference/LocalRules.java