photon: nars.inference.SyllogisticRules Class Reference
nars.inference.SyllogisticRules Class Reference
Syllogisms: Inference rules based on the transitivity of the relation.
Static Package Functions
static void analogy (Term term1, Term term2, Sentence asym, SentenceStruct sym, int figure, Memory memory)
{<S ==> P>, <M <=> P>} |- <S ==> P>
static void resemblance (Term term1, Term term2, Sentence belief, SentenceStruct sentence, int figure, Memory memory)
{<S <=> M>, <M <=> P>} |- <S <=> P>
Detailed Description
Syllogisms: Inference rules based on the transitivity of the relation.
Definition at line 31 of file SyllogisticRules.java.
Member Function Documentation
analogy()
static void nars.inference.SyllogisticRules.analogy (Term term1, Term term2, Sentence asym, SentenceStruct sym, int figure, Memory memory) static package
{<S ==> P>, <M <=> P>} |- <S ==> P>
Parameters
term1 Subject of the new task
term2 Predicate of the new task
asym The asymmetric premise
sym The symmetric premise
figure Locations of the shared term in premises
memory
Definition at line 53 of file SyllogisticRules.java.
References nars.inference.TruthFunctions.analogy(), nars.inference.BudgetFunctions.backward(), nars.inference.BudgetFunctions.backwardWeak(), nars.storage.Memory.doublePremiseTask(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.language.Statement.invalidStatement(), nars.language.CompoundTerm.isCommutative(), nars.entity.Sentence.isQuestion(), and nars.language.Statement.make().
Referenced by nars.inference.RuleTables.asymmetricSymmetric().
{
         if (Statement.invalidStatement(term1, term2)) {
             return;
         }
         Statement asymSt = (Statement) asym.getContent();
         // Statement symSt = (Statement) sym.getContent();
         TruthValue truth = null;
         BudgetValue budget;
         Sentence sentence = memory.getCurrentTask().getSentence();
         CompoundTerm taskTerm = (CompoundTerm) sentence.getContent();
         if (sentence.isQuestion()) {
             if (taskTerm.isCommutative()) {
                 budget = BudgetFunctions.backwardWeak(memory, asym.getTruth());
             } else {
                 budget = BudgetFunctions.backward(memory, sym.getTruth());
             }
         } else {
             truth = TruthFunctions.analogy(asym.getTruth(), sym.getTruth());
             budget = BudgetFunctions.forward(memory, truth);
         }
         Term content = Statement.make(asymSt, term1, term2, memory);
         Memory.doublePremiseTask(memory, content, truth, budget);
     }
resemblance()
static void nars.inference.SyllogisticRules.resemblance (Term term1, Term term2, Sentence belief, SentenceStruct sentence, int figure, Memory memory) static package
{<S <=> M>, <M <=> P>} |- <S <=> P>
Parameters
term1 Subject of the new task
term2 Predicate of the new task
belief The first premise
sentence The second premise
figure Locations of the shared term in premises
memory
Definition at line 93 of file SyllogisticRules.java.
References nars.inference.BudgetFunctions.backward(), nars.storage.Memory.doublePremiseTask(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.entity.Sentence.getTruth(), nars.language.Statement.invalidStatement(), nars.language.Statement.make(), and nars.inference.TruthFunctions.resemblance().
Referenced by nars.inference.RuleTables.symmetricSymmetric().
{
         if (Statement.invalidStatement(term1, term2)) {
             return;
         }
         Statement st1 = (Statement) belief.getContent();
         // Statement st2 = (Statement) sentence.getContent();
         TruthValue truth = null;
         BudgetValue budget;
         if (sentence.isQuestion()) {
             budget = BudgetFunctions.backward(memory, belief.getTruth());
         } else {
             truth = TruthFunctions.resemblance(belief.getTruth(),
                     sentence.getTruth());
             budget = BudgetFunctions.forward(memory, truth);
         }
         Term statement = Statement.make(st1, term1, term2, memory);
         Memory.doublePremiseTask(memory, statement, truth, budget);
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/inference/SyllogisticRules.java