photon: nars.entity.EntityObserver Interface Reference
nars.entity.EntityObserver Interface Reference
Public Member Functions
abstract void post (String str)
Display the content of the concept.
abstract BagObserver createBagObserver ()
abstract void startPlay (Concept concept, boolean showLinks)
abstract void stop ()
void refresh (String message)
Detailed Description
Definition at line 5 of file EntityObserver.java.
Member Function Documentation
createBagObserver()
abstract BagObserver nars.entity.EntityObserver.createBagObserver () abstract
Implemented in nars.entity.Concept.NullEntityObserver.
Referenced by nars.entity.Concept.startPlay().
post()
abstract void nars.entity.EntityObserver.post (String str) abstract
Display the content of the concept.
Parameters
str The text to be displayed
Implemented in nars.entity.Concept.NullEntityObserver.
Referenced by nars.entity.Concept.play(), and nars.entity.Concept.startPlay().
refresh()
void nars.entity.EntityObserver.refresh (String message)
Implemented in nars.entity.Concept.NullEntityObserver.
Referenced by nars.entity.Concept.directProcess().
startPlay()
abstract void nars.entity.EntityObserver.startPlay (Concept concept, boolean showLinks) abstract
Implemented in nars.entity.Concept.NullEntityObserver.
Referenced by nars.entity.Concept.startPlay().
stop()
abstract void nars.entity.EntityObserver.stop () abstract
Implemented in nars.entity.Concept.NullEntityObserver.
Referenced by nars.entity.Concept.stop().
The documentation for this interface was generated from the following file:
fabric/src/main/java/nars/entity/EntityObserver.java