photon: nars.language.Variable Class Reference
nars.language.Variable Class Reference
A variable term, which does not correspond to a concept.
Public Member Functions
Variable (String s)
Constructor, from a given variable name.
Object clone ()
Clone a Variable.
char getType ()
Get the type of the variable.
boolean isConstant ()
A variable is not constant.
Public Member Functions inherited from nars.language.Term
Term (String name)
Constructor with a given name.
String getName ()
Reporting the name of the current Term.
void setName (String $name$)
Object clone ()
Make a new Term with the same name.
boolean equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
int hashCode ()
Produce a hash code for the term.
boolean isConstant ()
Check whether the current Term can name a Concept.
void renameVariables ()
Blank method to be override in CompoundTerm.
int getComplexity ()
The syntactic complexity, for constant automic Term, is 1.
final int compareTo (Term that)
Check the relative order of two Terms.
final String toString ()
The same as getName by default, used in display only.
Static Public Member Functions
static boolean containVarIndep (String n)
Check whether a string represent a name of a term that contains an independent variable.
static boolean containVarDep (String n)
Check whether a string represent a name of a term that contains a dependent variable.
static boolean containVarQuery (String n)
Check whether a string represent a name of a term that contains a query variable.
static boolean containVar (String n)
Check whether a string represent a name of a term that contains a variable.
static boolean unify (char type, Term t1, TermStruct t2)
To unify two terms.
static boolean unify (char type, TermStruct t1, TermStruct t2, Term compound1, TermStruct compound2)
To unify two terms.
Static Public Member Functions inherited from nars.language.Term
static boolean hasOrIsTerm $par (Term root, Term... leaves)
Additional Inherited Members
Protected Member Functions inherited from nars.language.Term
Term ()
Default constructor that build an internal Term.
Protected Attributes inherited from nars.language.Term
String name
A Term is identified uniquely by its name, a sequence of characters in a given alphabet (ASCII or Unicode)
Detailed Description
A variable term, which does not correspond to a concept.
Definition at line 32 of file Variable.java.
Constructor & Destructor Documentation
Variable()
nars.language.Variable.Variable (String s)
Constructor, from a given variable name.
Parameters
s A String read from input
Definition at line 38 of file Variable.java.
Referenced by nars.language.Variable.clone().
{
         super(s);
     }
Member Function Documentation
clone()
Object nars.language.Variable.clone ()
Clone a Variable.
Returns
The cloned Variable
Definition at line 47 of file Variable.java.
References nars.language.Term.name, and nars.language.Variable.Variable().
{
         return new Variable(name);
     }
containVar()
static boolean nars.language.Variable.containVar (String n) static
Check whether a string represent a name of a term that contains a variable.
Parameters
n The string name to be checked
Returns
Whether the name contains a variable
Definition at line 100 of file Variable.java.
References nars.language.Variable.containVarDep(), nars.language.Variable.containVarIndep(), and nars.language.Variable.containVarQuery().
Referenced by nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.containVar(), and nars.io.StringParser.parseAtomicTerm().
{
         return containVarIndep(n) || containVarDep(n) || containVarQuery(n);
     }
containVarDep()
static boolean nars.language.Variable.containVarDep (String n) static
Check whether a string represent a name of a term that contains a dependent variable.
Parameters
n The string name to be checked
Returns
Whether the name contains a dependent variable
Definition at line 82 of file Variable.java.
References nars.io.Symbols.VAR_DEPENDENT.
Referenced by nars.language.Variable.containVar(), and nars.io.StringParser.parseTask().
{
         return n.indexOf(Symbols.VAR_DEPENDENT) >= 0;
     }
containVarIndep()
static boolean nars.language.Variable.containVarIndep (String n) static
Check whether a string represent a name of a term that contains an independent variable.
Parameters
n The string name to be checked
Returns
Whether the name contains an independent variable
Definition at line 73 of file Variable.java.
References nars.io.Symbols.VAR_INDEPENDENT.
Referenced by nars.language.Variable.containVar().
{
         return n.indexOf(Symbols.VAR_INDEPENDENT) >= 0;
     }
containVarQuery()
static boolean nars.language.Variable.containVarQuery (String n) static
Check whether a string represent a name of a term that contains a query variable.
Parameters
n The string name to be checked
Returns
Whether the name contains a query variable
Definition at line 91 of file Variable.java.
References nars.io.Symbols.VAR_QUERY.
Referenced by nars.language.Variable.containVar(), and nars.inference.LocalRules.convertedJudgment().
{
         return n.indexOf(Symbols.VAR_QUERY) >= 0;
     }
getType()
char nars.language.Variable.getType ()
Get the type of the variable.
Returns
The variable type
Definition at line 55 of file Variable.java.
References nars.language.Term.name.
{
         return name.charAt(0);
     }
isConstant()
boolean nars.language.Variable.isConstant ()
A variable is not constant.
Returns
false
Definition at line 64 of file Variable.java.
{
         return false;
     }
unify() [1/2]
static boolean nars.language.Variable.unify (char type, Term t1, TermStruct t2) static
To unify two terms.
Parameters
type The type of variable that can be substituted
t1 The first term
t2 The second term
Returns
Whether the unification is possible
Definition at line 111 of file Variable.java.
Referenced by nars.inference.RuleTables.asymmetricAsymmetric(), nars.inference.RuleTables.asymmetricSymmetric(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.RuleTables.conditionalAna(), nars.inference.RuleTables.conditionalDedInd(), nars.inference.RuleTables.conditionalDedIndWithVar(), nars.inference.RuleTables.detachmentWithVar(), nars.inference.LocalRules.match(), and nars.inference.RuleTables.symmetricSymmetric().
{
         return unify(type, t1, t2, t1, t2);
     }
unify() [2/2]
static boolean nars.language.Variable.unify (char type, TermStruct t1, TermStruct t2, Term compound1, TermStruct compound2) static
To unify two terms.
Parameters
type The type of variable that can be substituted
t1 The first term to be unified
t2 The second term to be unified
compound1 The compound contermaining the first term
compound2 The compound contermaining the second term
Returns
Whether the unification is possible
Definition at line 124 of file Variable.java.
{
          Map<Term, Term> map1 = new HashMap<>();
          Map<Term, Term> map2 = new HashMap<>();
         boolean hasSubs = Expr3.INSTANCE.findSubstitute(type, t1, t2, map1, map2); // find substitution
         if (hasSubs) {
             if (!map1.isEmpty()) {
                 ((CompoundTerm) compound1).applySubstitute(map1);
             }
             if (!map2.isEmpty()) {
                 ((CompoundTerm) compound2).applySubstitute(map2);
             }
         }
         return hasSubs;
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/language/Variable.java