photon: nars.entity.TermLink Class Reference
nars.entity.TermLink Class Reference
A link between a compound term and a component term.
Public Member Functions
TermLink (Term term, short typ, IntStream indices)
Constructor for TermLink template.
TermLink (Term t, TermLink template, BudgetValue v)
Constructor to make actual TermLink from a template.
TermLink (Term t2, short transform, int... j)
Term getTerm ()
The linked Term.
void setTerm (Term term)
The type of link, one of the above.
void setTerm (TermStruct $term$)
int getType ()
Get the link type.
void setType (int type)
Integer getIndex (int i)
Get one index by level.
List< Integer > getIndex ()
The index of the component in the component list of the compound, may have up to 4 levels.
void setIndex (List< Integer > index)
Public Member Functions inherited from nars.entity.Item
String getKey ()
The key of the Item, unique in a Bag.
BudgetValue getBudget ()
The budget of the Item, consisting of 3 numbers.
float getPriority ()
Get priority value.
void setPriority (float v)
Set priority value.
float getDurability ()
Get durability value.
void setDurability (float v)
Set durability value.
float getQuality ()
Get quality value.
void setQuality (float v)
Set quality value.
String toString ()
Return a String representation of the Item.
void setKey (String key)
Static Public Attributes
static final short SELF = 0
At C, point to C; TaskLink only.
static final short COMPONENT = 1
At (&&, A, C), point to C.
static final short COMPOUND = 2
At C, point to (&&, A, C)
static final short COMPONENT_STATEMENT = 3
At <C --> A>, point to C.
static final short COMPOUND_STATEMENT = 4
At C, point to <C --> A>
static final short COMPONENT_CONDITION = 5
At <(&&, C, B) ==> A>, point to C.
static final short COMPOUND_CONDITION = 6
At C, point to <(&&, C, B) ==> A>
static final short TRANSFORM = 8
At C, point to <(*, C, B) --> A>; TaskLink only.
Protected Member Functions
TermLink (String s, BudgetValue v)
called from TaskLink
void setKey ()
Set the key of the link.
Protected Member Functions inherited from nars.entity.Item
Item ()
The default constructor.
Item (String key)
Constructor with default budget.
Item (String key, BudgetValue budget)
Constructor with initial budget.
void setBudget (BudgetValue budget)
Constructor with initial budget.
Private Attributes
Term term
int type
List< Integer > index
Additional Inherited Members
Static Public Member Functions inherited from nars.entity.Item
static void incPriority (BudgetValue budget, float v)
Increase priority value.
static void decPriority (BudgetValue budget, float v)
Decrease priority value.
static void incDurability (BudgetValue budget, float v)
Increase durability value.
static void decDurability (BudgetValue budget, float v)
Decrease durability value.
static void merge (BudgetValue budget, Item that)
Merge with another Item with identical key.
static String toStringBrief (BudgetValue budget, String key)
Return a String representation of the Item after simplification.
static String toStringLong (Item item)
Detailed Description
A link between a compound term and a component term.
A TermLink links the current Term to a term Term, which is either a component of, or compound made from, the current term.
Neither of the two terms contain variable shared with other terms.
The index value(s) indicates the location of the component in the compound.
This class is mainly used in inference.RuleTable to dispatch premises to inference rules
Definition at line 45 of file TermLink.java.
Constructor & Destructor Documentation
TermLink() [1/4]
nars.entity.TermLink.TermLink (Term term, short typ, IntStream indices)
Constructor for TermLink template.
called in CompoundTerm.prepareComponentLinks only
Parameters
term Target Term
typ Link type
indices Component indices in compound, may be 1 to 4
Definition at line 91 of file TermLink.java.
References nars.entity.TermLink.COMPOUND_CONDITION, nars.entity.TermLink.index, nars.entity.TermLink.setIndex(), nars.entity.TermLink.setTerm(), nars.entity.TermLink.setType(), nars.entity.TermLink.term, and nars.entity.TermLink.type.
{
         setTerm(term);
         setType(typ);
         assert type % 2 == 0; // template types all point to compound, though the term is component
         setIndex(new CopyOnWriteArrayList<>());
         if (type == COMPOUND_CONDITION) {  // the first index is 0 by default
             index.add(0);
         }
         if (null != indices) indices.forEachOrdered(a -> {
             index.add(a);
         });
     }
TermLink() [2/4]
nars.entity.TermLink.TermLink (String s, BudgetValue v) protected
called from TaskLink
Parameters
s The key of the TaskLink
v The budget value of the TaskLink
Definition at line 111 of file TermLink.java.
{
         super(s, v);
     }
TermLink() [3/4]
nars.entity.TermLink.TermLink (Term t, TermLink template, BudgetValue v)
Constructor to make actual TermLink from a template.
called in Concept.buildTermLinks only
Parameters
t Target Term
template TermLink template previously prepared
v Budget value of the link
Definition at line 124 of file TermLink.java.
References nars.language.Term.equals(), nars.entity.TermLink.getIndex(), nars.language.Term.getName(), nars.entity.TermLink.setIndex(), nars.entity.TermLink.setKey(), nars.entity.TermLink.setTerm(), nars.entity.TermLink.setType(), nars.entity.TermLink.term, and nars.entity.TermLink.type.
{
         super(t.getName(), v);
         setTerm(t);
         setType(template.type);
         if (template.term.equals(t)) {
             setType(type - 1);     // point to component
         }
         setIndex(template.getIndex());
         setKey();
     }
TermLink() [4/4]
nars.entity.TermLink.TermLink (Term t2, short transform, int... j)
Definition at line 135 of file TermLink.java.
{
         this(t2, transform, Arrays.stream(j));
     }
Member Function Documentation
getIndex() [1/2]
Integer nars.entity.TermLink.getIndex (int i)
Get one index by level.
Parameters
i The index level
Returns
The index value
Definition at line 210 of file TermLink.java.
References nars.entity.TermLink.index.
Referenced by nars.inference.RuleTables.indexToFigure(), nars.inference.RuleTables.reason(), and nars.inference.RuleTables.syllogisms().
{
         if (index != null && i < index.size()) {
             return index.get(i);
         } else {
             return -1;
         }
     }
getIndex() [2/2]
List<Integer> nars.entity.TermLink.getIndex ()
The index of the component in the component list of the compound, may have up to 4 levels.
Definition at line 222 of file TermLink.java.
References nars.entity.TermLink.index.
Referenced by nars.entity.TaskLink.TaskLink(), and nars.entity.TermLink.TermLink().
{
         return index;
     }
getTerm()
Term nars.entity.TermLink.getTerm ()
The linked Term.
Get the term of the link
Returns
The Term pointed by the link
Definition at line 170 of file TermLink.java.
References nars.entity.TermLink.term.
Referenced by nars.entity.TaskLink.novel(), and nars.inference.RuleTables.reason().
{
         return term;
     }
getType()
int nars.entity.TermLink.getType ()
Get the link type.
Returns
Type of the link
Definition at line 193 of file TermLink.java.
References nars.entity.TermLink.type.
Referenced by nars.entity.Concept.fireFromProcessConcept(), nars.inference.RuleTables.reason(), and nars.entity.TaskLink.TaskLink().
{
         return type;
     }
setIndex()
void nars.entity.TermLink.setIndex (List< Integer > index)
Definition at line 227 of file TermLink.java.
References nars.entity.TermLink.index.
Referenced by nars.entity.TaskLink.TaskLink(), and nars.entity.TermLink.TermLink().
{
         this.index = index;
     }
setKey()
void nars.entity.TermLink.setKey () protected
Set the key of the link.
Definition at line 142 of file TermLink.java.
References nars.entity.Item.getKey(), nars.entity.TermLink.index, nars.entity.TermLink.term, nars.io.Symbols.TO_COMPONENT_1, nars.io.Symbols.TO_COMPONENT_2, nars.io.Symbols.TO_COMPOUND_1, nars.io.Symbols.TO_COMPOUND_2, and nars.entity.TermLink.type.
Referenced by nars.entity.TaskLink.TaskLink(), and nars.entity.TermLink.TermLink().
{
         String at1, at2;
         if (type % 2 == 1) {  // to component
             at1 = Symbols.TO_COMPONENT_1;
             at2 = Symbols.TO_COMPONENT_2;
         } else {                // to compound
             at1 = Symbols.TO_COMPOUND_1;
             at2 = Symbols.TO_COMPOUND_2;
         }
         String in = "T" + type;
         if (index != null) {
             for (int i = 0; i < index.size(); i++) {
                 in += "-" + (index.get(i) + 1);
             }
         }
         setKey(at1 + in + at2);
         if (term != null) {
             setKey(getKey() + term);
         }
     }
setTerm() [1/2]
void nars.entity.TermLink.setTerm (Term term)
The type of link, one of the above.
Definition at line 178 of file TermLink.java.
References nars.entity.TermLink.term.
Referenced by nars.entity.TermLink.TermLink().
{
         this.term = term;
     }
setTerm() [2/2]
void nars.entity.TermLink.setTerm (TermStruct $term$)
Definition at line 183 of file TermLink.java.
References nars.entity.TermLink.term.
{
         term = (Term) $term$;
     }
setType()
void nars.entity.TermLink.setType (int type)
Definition at line 198 of file TermLink.java.
References nars.entity.TermLink.type.
Referenced by nars.entity.TaskLink.TaskLink(), and nars.entity.TermLink.TermLink().
{
         this.type = type;
     }
Member Data Documentation
COMPONENT
final short nars.entity.TermLink.COMPONENT = 1 static
At (&&, A, C), point to C.
Definition at line 53 of file TermLink.java.
Referenced by nars.inference.RuleTables.reason().
COMPONENT_CONDITION
final short nars.entity.TermLink.COMPONENT_CONDITION = 5 static
At <(&&, C, B) ==> A>, point to C.
Definition at line 69 of file TermLink.java.
Referenced by nars.inference.RuleTables.reason().
COMPONENT_STATEMENT
final short nars.entity.TermLink.COMPONENT_STATEMENT = 3 static
At <C --> A>, point to C.
Definition at line 61 of file TermLink.java.
Referenced by nars.inference.RuleTables.reason().
COMPOUND
final short nars.entity.TermLink.COMPOUND = 2 static
At C, point to (&&, A, C)
Definition at line 57 of file TermLink.java.
Referenced by nars.language.CompoundTerm.prepareComponentLinks(), and nars.inference.RuleTables.reason().
COMPOUND_CONDITION
final short nars.entity.TermLink.COMPOUND_CONDITION = 6 static
At C, point to <(&&, C, B) ==> A>
Definition at line 73 of file TermLink.java.
Referenced by nars.language.CompoundTerm.prepareComponentLinks(), nars.inference.RuleTables.reason(), and nars.entity.TermLink.TermLink().
COMPOUND_STATEMENT
final short nars.entity.TermLink.COMPOUND_STATEMENT = 4 static
At C, point to <C --> A>
Definition at line 65 of file TermLink.java.
Referenced by nars.language.CompoundTerm.prepareComponentLinks(), and nars.inference.RuleTables.reason().
index
List<Integer> nars.entity.TermLink.index private
Definition at line 80 of file TermLink.java.
Referenced by nars.entity.TermLink.getIndex(), nars.entity.TermLink.setIndex(), nars.entity.TermLink.setKey(), and nars.entity.TermLink.TermLink().
SELF
final short nars.entity.TermLink.SELF = 0 static
At C, point to C; TaskLink only.
Definition at line 49 of file TermLink.java.
Referenced by nars.inference.RuleTables.reason(), and nars.entity.TaskLink.TaskLink().
term
Term nars.entity.TermLink.term private
Definition at line 78 of file TermLink.java.
Referenced by nars.entity.TermLink.getTerm(), nars.entity.TermLink.setKey(), nars.entity.TermLink.setTerm(), and nars.entity.TermLink.TermLink().
TRANSFORM
final short nars.entity.TermLink.TRANSFORM = 8 static
At C, point to <(*, C, B) --> A>; TaskLink only.
Definition at line 77 of file TermLink.java.
Referenced by nars.entity.Concept.buildTermLinks(), nars.entity.Concept.fireFromProcessConcept(), and nars.language.CompoundTerm.prepareComponentLinks().
type
int nars.entity.TermLink.type private
Definition at line 79 of file TermLink.java.
Referenced by nars.entity.TermLink.getType(), nars.entity.TermLink.setKey(), nars.entity.TermLink.setType(), and nars.entity.TermLink.TermLink().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/entity/TermLink.java