photon: nars.entity.TruthValue Class Reference
nars.entity.TruthValue Class Reference
Frequency and confidence.
Public Member Functions
TruthValue (float f, float c)
Constructor with two ShortFloats.
TruthValue (TruthHandle v)
Constructor with a TruthValue to clone.
float getFrequency ()
Get the frequency value.
float getConfidence ()
The confidence factor of the truth value.
float getExpectation ()
Calculate the expectation value of the truth value.
float isExpDifAbs (TruthValue t)
Calculate the absolute difference of the expectation value and that of a given truth value.
boolean isNegative ()
Check if the truth value is negative.
boolean equals (Object that)
Compare two truth values.
int hashCode ()
The hash code of a TruthValue.
Object clone ()
String toString ()
The String representation of a TruthValue.
String toStringBrief ()
A simplified String representation of a TruthValue, where each factor is accruate to 1%.
void setFrequency (float frequency)
void setConfidence (float confidence)
Private Attributes
float frequency
float confidence
Static Private Attributes
static final char DELIMITER = Symbols.TRUTH_VALUE_MARK
The charactor that marks the two ends of a truth value.
static final char SEPARATOR = Symbols.VALUE_SEPARATOR
The charactor that separates the factors in a truth value.
Detailed Description
Frequency and confidence.
Definition at line 29 of file TruthValue.java.
Constructor & Destructor Documentation
TruthValue() [1/2]
nars.entity.TruthValue.TruthValue (float f, float c)
Constructor with two ShortFloats.
Parameters
f The frequency value
c The confidence value
Definition at line 42 of file TruthValue.java.
References nars.entity.TruthValue.setConfidence(), and nars.entity.TruthValue.setFrequency().
Referenced by nars.entity.TruthValue.clone().
{
         setFrequency(f);
         setConfidence((c < 1) ?  (c) :  (0.9999f));
     }
TruthValue() [2/2]
nars.entity.TruthValue.TruthValue (TruthHandle v)
Constructor with a TruthValue to clone.
Parameters
v The truth value to be cloned
Definition at line 51 of file TruthValue.java.
References nars.entity.TruthValue.setConfidence(), and nars.entity.TruthValue.setFrequency().
{
         setFrequency(v.getFrequency());
         setConfidence(v.getConfidence());
     }
Member Function Documentation
clone()
Object nars.entity.TruthValue.clone ()
Definition at line 123 of file TruthValue.java.
References nars.entity.TruthValue.getConfidence(), nars.entity.TruthValue.getFrequency(), and nars.entity.TruthValue.TruthValue().
{
         return new TruthValue(getFrequency(), getConfidence());
     }
equals()
boolean nars.entity.TruthValue.equals (Object that)
Compare two truth values.
Parameters
that The other TruthValue
Returns
Whether the two are equivalent
Definition at line 107 of file TruthValue.java.
References nars.entity.TruthValue.getConfidence(), and nars.entity.TruthValue.getFrequency().
Referenced by nars.entity.Sentence.equals(), and nars.entity.Sentence.equivalentTo().
{
         return ((that instanceof TruthValue)
                 && (getFrequency() == ((TruthValue) that).getFrequency())
                 && (getConfidence() == ((TruthValue) that).getConfidence()));
     }
getConfidence()
float nars.entity.TruthValue.getConfidence ()
The confidence factor of the truth value.
Get the confidence value
Returns
The confidence value
Definition at line 70 of file TruthValue.java.
References nars.entity.TruthValue.confidence.
Referenced by nars.entity.TruthValue.clone(), nars.entity.TruthValue.equals(), nars.entity.TruthValue.getExpectation(), nars.inference.LocalRules.revise(), nars.inference.LocalRules.solutionQuality(), nars.entity.TruthValue.toString(), and nars.entity.TruthValue.toStringBrief().
{
         return confidence ;
     }
getExpectation()
float nars.entity.TruthValue.getExpectation ()
Calculate the expectation value of the truth value.
Returns
The expectation value
Definition at line 78 of file TruthValue.java.
References nars.entity.TruthValue.getConfidence(), and nars.entity.TruthValue.getFrequency().
Referenced by nars.entity.TruthValue.hashCode(), nars.entity.TruthValue.isExpDifAbs(), nars.storage.Memory.processNewTask(), nars.entity.Concept.processQuestion(), and nars.inference.LocalRules.solutionQuality().
{
         return (float) (getConfidence() * (getFrequency() - 0.5) + 0.5);
     }
getFrequency()
float nars.entity.TruthValue.getFrequency ()
Get the frequency value.
Returns
The frequency value
Definition at line 61 of file TruthValue.java.
References nars.entity.TruthValue.frequency.
Referenced by nars.inference.TruthFunctions.abduction(), nars.inference.TruthFunctions.analogy(), nars.inference.RuleTables.anonymousAnalogy(), nars.entity.TruthValue.clone(), nars.inference.TruthFunctions.comparison(), nars.inference.RuleTables.contraposition(), nars.inference.TruthFunctions.conversion(), nars.inference.TruthFunctions.deduction(), nars.inference.TruthFunctions.desireDed(), nars.inference.TruthFunctions.desireInd(), nars.inference.TruthFunctions.desireStrong(), nars.inference.TruthFunctions.desireWeak(), nars.entity.TruthValue.equals(), nars.inference.RuleTables.exemplification(), nars.entity.TruthValue.getExpectation(), nars.inference.TruthFunctions.intersection(), nars.entity.TruthValue.isNegative(), nars.inference.TruthFunctions.negation(), nars.inference.TruthFunctions.resemblance(), nars.inference.TruthFunctions.revision(), nars.entity.TruthValue.toString(), nars.entity.TruthValue.toStringBrief(), and nars.inference.TruthFunctions.union().
{
         return frequency ;
     }
hashCode()
int nars.entity.TruthValue.hashCode ()
The hash code of a TruthValue.
Returns
The hash code
Definition at line 118 of file TruthValue.java.
References nars.entity.TruthValue.getExpectation().
Referenced by nars.entity.Sentence.hashCode().
{
         return (int) (getExpectation() * 37);
     }
isExpDifAbs()
float nars.entity.TruthValue.isExpDifAbs (TruthValue t)
Calculate the absolute difference of the expectation value and that of a given truth value.
Parameters
t The given value
Returns
The absolute difference
Definition at line 89 of file TruthValue.java.
References nars.entity.TruthValue.getExpectation().
Referenced by nars.inference.LocalRules.revise(), and nars.inference.BudgetFunctions.update().
{
         return Math.abs(getExpectation() - t.getExpectation());
     }
isNegative()
boolean nars.entity.TruthValue.isNegative ()
Check if the truth value is negative.
Returns
True if the frequence is less than 1/2
Definition at line 97 of file TruthValue.java.
References nars.entity.TruthValue.getFrequency().
Referenced by nars.inference.CompositionalRules.composeCompound().
{
         return getFrequency() < 0.5;
     }
setConfidence()
void nars.entity.TruthValue.setConfidence (float confidence)
Definition at line 152 of file TruthValue.java.
References nars.entity.TruthValue.confidence.
Referenced by nars.entity.TruthValue.TruthValue().
{
         this.confidence = confidence;
     }
setFrequency()
void nars.entity.TruthValue.setFrequency (float frequency)
Definition at line 147 of file TruthValue.java.
References nars.entity.TruthValue.frequency.
Referenced by nars.entity.TruthValue.TruthValue().
{
         this.frequency = frequency;
     }
toString()
String nars.entity.TruthValue.toString ()
The String representation of a TruthValue.
Returns
The String
Definition at line 132 of file TruthValue.java.
References nars.entity.TruthValue.DELIMITER, nars.entity.TruthValue.getConfidence(), nars.entity.TruthValue.getFrequency(), and nars.entity.TruthValue.SEPARATOR.
{
         return ""+DELIMITER + getFrequency() + SEPARATOR + getConfidence() + DELIMITER;
     }
toStringBrief()
String nars.entity.TruthValue.toStringBrief ()
A simplified String representation of a TruthValue, where each factor is accruate to 1%.
Returns
The String
Definition at line 140 of file TruthValue.java.
References nars.entity.TruthValue.DELIMITER, nars.entity.TruthValue.getConfidence(), nars.entity.TruthValue.getFrequency(), and nars.entity.TruthValue.SEPARATOR.
Referenced by nars.entity.Sentence.toKey().
{
         String s1 = "" +DELIMITER + getFrequency() + SEPARATOR;
         Float s2 = getConfidence();
         return s2 == (1.0f) ? s1 + "0.99" + DELIMITER : s1 + s2 + DELIMITER;
     }
Member Data Documentation
confidence
float nars.entity.TruthValue.confidence private
Definition at line 35 of file TruthValue.java.
Referenced by nars.entity.TruthValue.getConfidence(), and nars.entity.TruthValue.setConfidence().
DELIMITER
final char nars.entity.TruthValue.DELIMITER = Symbols.TRUTH_VALUE_MARK static private
The charactor that marks the two ends of a truth value.
Definition at line 31 of file TruthValue.java.
Referenced by nars.entity.TruthValue.toString(), and nars.entity.TruthValue.toStringBrief().
frequency
float nars.entity.TruthValue.frequency private
Definition at line 34 of file TruthValue.java.
Referenced by nars.entity.TruthValue.getFrequency(), and nars.entity.TruthValue.setFrequency().
SEPARATOR
final char nars.entity.TruthValue.SEPARATOR = Symbols.VALUE_SEPARATOR static private
The charactor that separates the factors in a truth value.
Definition at line 33 of file TruthValue.java.
Referenced by nars.entity.TruthValue.toString(), and nars.entity.TruthValue.toStringBrief().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/entity/TruthValue.java