photon: nars.language.Product Class Reference
nars.language.Product Class Reference
A Product is a sequence of terms.
Public Member Functions
Object clone ()
Clone a Product.
String operator ()
Get the operator of the term.
Public Member Functions inherited from nars.language.CompoundTerm
abstract String operator ()
Abstract method to get the operator of the compound.
abstract Object clone ()
Abstract clone method.
void setName (String s)
Change the oldName of a CompoundTerm, called after variable substitution.
int getComplexity ()
syntactic complexity of the compound, the sum of those of its components plus 1
boolean isConstant ()
Whether the term names a concept.
void setConstant (boolean isConstant)
Set the constant status.
boolean isCommutative ()
Check if the order of the components matters.
int size ()
get the number of components
Term componentAt (int i)
get a component by index
List< Term > getComponents ()
list of (direct) components
List< Term > cloneComponents ()
Clone the component list.
boolean containComponent (Term t)
Check whether the compound contains a certain component.
boolean containAllComponents (Term t)
Check whether the compound contains all components of another term, or that term as a whole.
boolean containVar ()
Whether this compound term contains any variable term.
void renameVariables ()
Rename the variables in the compound.
void renameVariables (HashMap< Variable, Variable > map)
Rename the variables in the compound.
void applySubstitute (Map< Term, Term > subs)
Recursively apply a substitute to the current CompoundTerm.
List< TermLink > prepareComponentLinks ()
Build TermLink templates to constant components and subcomponents.
void setComponents (List< Term > components)
void setComplexity (short complexity)
Public Member Functions inherited from nars.language.Term
Term (String name)
Constructor with a given name.
String getName ()
Reporting the name of the current Term.
void setName (String $name$)
Object clone ()
Make a new Term with the same name.
boolean equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
int hashCode ()
Produce a hash code for the term.
boolean isConstant ()
Check whether the current Term can name a Concept.
void renameVariables ()
Blank method to be override in CompoundTerm.
int getComplexity ()
The syntactic complexity, for constant automic Term, is 1.
final int compareTo (Term that)
Check the relative order of two Terms.
final String toString ()
The same as getName by default, used in display only.
Static Public Member Functions
static Term make (List< Term > argument, Memory memory)
Try to make a new compound.
static Term make (CompoundTerm image, Term component, int index, Memory memory)
Try to make a Product from an ImageExt/ImageInt and a component.
Static Public Member Functions inherited from nars.language.CompoundTerm
static Term make (CompoundTerm compound, List< Term > components, Memory memory)
Try to make a compound term from a template and a list of components.
static Term make (String op, List< Term > arg, Memory memory)
Try to make a compound term from an operator and a list of components.
static List< Term > cloneList (List< Term > original)
Deep clone an array list of terms.
static Term addComponents (CompoundTerm t1, Term t2, Memory memory)
Try to add a component into a compound.
static Term reduceComponents (CompoundTerm t1, Term t2, Memory memory)
Try to remove a component from a compound.
static Term setComponent (CompoundTerm compound, int index, Term t, Memory memory)
Try to replace a component in a compound at a given index by another one.
Static Public Member Functions inherited from nars.language.Term
static boolean hasOrIsTerm $par (Term root, Term... leaves)
Private Member Functions
Product (List< Term > arg)
Constructor with partial values, called by make.
Product (String n, List< Term > cs, boolean con, int complexity)
Constructor with full values, called by clone.
Additional Inherited Members
Protected Member Functions inherited from nars.language.CompoundTerm
CompoundTerm (String name, List< Term > components, boolean isConstant, int complexity)
Constructor called from subclasses constructors to clone the fields.
CompoundTerm ()
Default constructor.
CompoundTerm (List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
CompoundTerm (String name, List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
String makeName ()
default method to make the oldName of the current term from existing fields
Protected Member Functions inherited from nars.language.Term
Term ()
Default constructor that build an internal Term.
Static Protected Member Functions inherited from nars.language.CompoundTerm
static List< Term > argumentsToList (Term ...t2)
build a component list from two terms
static String makeCompoundName (String op, Iterable< Term > arg)
default method to make the oldName of a compound term from given fields
static String makeSetName (char opener, List< Term > arg, char closer)
make the oldName of an ExtensionSet or IntensionSet
static String makeImageName (String op, List< Term > arg, int relationIndex)
default method to make the oldName of an image term from given fields
Protected Attributes inherited from nars.language.Term
String name
A Term is identified uniquely by its name, a sequence of characters in a given alphabet (ASCII or Unicode)
Static Package Functions inherited from nars.language.CompoundTerm
static void calcComplexity (CompoundTerm compoundTerm)
The complexity of the term is the sum of those of the components plus 1.
Detailed Description
A Product is a sequence of terms.
Definition at line 33 of file Product.java.
Constructor & Destructor Documentation
Product() [1/2]
nars.language.Product.Product (List< Term > arg) private
Constructor with partial values, called by make.
Parameters
arg The component list of the term
Definition at line 39 of file Product.java.
Referenced by nars.language.Product.clone(), and nars.language.Product.make().
{
         super(arg);
     }
Product() [2/2]
nars.language.Product.Product (String n, List< Term > cs, boolean con, int complexity) private
Constructor with full values, called by clone.
Parameters
n The name of the term
cs Component list
complexity Syntactic complexity of the compound
Definition at line 49 of file Product.java.
References nars.language.CompoundTerm.complexity.
{
         super(n, cs, con, complexity);
     }
Member Function Documentation
clone()
Object nars.language.Product.clone ()
Clone a Product.
Returns
A new object, to be casted into an ImageExt
Definition at line 57 of file Product.java.
References nars.language.CompoundTerm.cloneList(), nars.language.CompoundTerm.getComplexity(), nars.language.CompoundTerm.getComponents(), nars.language.CompoundTerm.isConstant(), nars.language.Term.name, and nars.language.Product.Product().
{
         return new Product(name, (ArrayList<Term>) cloneList(getComponents()), isConstant(), getComplexity());
     }
make() [1/2]
static Term nars.language.Product.make (List< Term > argument, Memory memory) static
Try to make a new compound.
Called by StringParser.
Returns
the Term generated from the arguments
Parameters
argument The list of components
memory Reference to the memeory
Definition at line 67 of file Product.java.
References nars.language.CompoundTerm.makeCompoundName(), nars.language.Term.name, nars.storage.Memory.nameToListedTerm(), nars.language.Product.Product(), and nars.io.Symbols.PRODUCT_OPERATOR.
Referenced by nars.language.Product.make(), nars.language.CompoundTerm.make(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.StructuralRules.transformProductImage(), and nars.inference.StructuralRules.transformSubjectPI().
{
         String name = makeCompoundName(Symbols.PRODUCT_OPERATOR, argument);
         Term t = Memory.nameToListedTerm(memory, name);
         return (t != null) ? t : new Product(argument);
     }
make() [2/2]
static Term nars.language.Product.make (CompoundTerm image, Term component, int index, Memory memory) static
Try to make a Product from an ImageExt/ImageInt and a component.
Called by the inference rules.
Parameters
image The existing Image
component The component to be added into the component list
index The index of the place-holder in the new Image – optional parameter
memory Reference to the memeory
Returns
A compound generated or a term it reduced to
Definition at line 81 of file Product.java.
References nars.language.CompoundTerm.cloneComponents(), and nars.language.Product.make().
{
         List<Term> argument = image.cloneComponents();
         argument.set(index, component);
         return make(argument, memory);
     }
operator()
String nars.language.Product.operator ()
Get the operator of the term.
Returns
the operator of the term
Definition at line 91 of file Product.java.
References nars.io.Symbols.PRODUCT_OPERATOR.
{
         return Symbols.PRODUCT_OPERATOR;
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/language/Product.java