photon: nars.entity.Stamp Class Reference
nars.entity.Stamp Class Reference
Each Sentence has a time stamp, consisting the following components: (1) The creation time of the sentence, (2) A evidentialBase of serial numbers of sentence, from which the sentence is derived.
Classes
class LongArrayList
temporary
Public Member Functions
Object clone ()
Clone a stamp.
boolean equals (Object that)
Check if two stamps contains the same content.
int hashCode ()
The hash code of Stamp.
long getCreationTime ()
creation time of the stamp
void setCreationTime (long creationTime)
String toString ()
Get a String form of the Stamp for display Format: {creationTime [: eventTime] : evidentialBase}.
int getBaseLength ()
evidentialBase baseLength
List< Long > getEvidentialBase ()
serial numbers
void setEvidentialBase (List< Long > evidentialBase)
Static Public Member Functions
static Stamp make (Stamp first, Stamp second, long time)
Try to merge two Stamps, return null if have overlap.
static void init ()
Initialize the stamp mechanism of the system, called in Reasoner.
static Stamp createStamp (long time)
static Stamp createStamp (Stamp old, long time)
static long getCurrentSerial ()
serial number, for the whole system TODO : should it really be static? or a Stamp be a field in ReasonerBatch ?
static void setCurrentSerial (long currentSerial)
Package Functions
long get (int i)
Get a number from the evidentialBase by index, called in this class only.
Private Member Functions
Stamp (long time)
Generate a new stamp, with a new serial number, for a new Task.
Stamp (Stamp old)
Generate a new stamp identical with a given one.
Stamp (Stamp old, long time)
Generate a new stamp from an existing one, with the same evidentialBase but different creation time.
Stamp (Stamp first, Stamp second, long time)
Generate a new stamp for derived sentence by merging the two from parents the first one is no shorter than the second.
List< Long > getBase ()
Get the evidentialBase, called in this class only.
Collection< Long > toSet ()
Convert the evidentialBase into a set.
Private Attributes
final int baseLength
List< Long > evidentialBase =new CopyOnWriteArrayList<>()
long creationTime
Static Private Attributes
static long currentSerial
Detailed Description
Each Sentence has a time stamp, consisting the following components: (1) The creation time of the sentence, (2) A evidentialBase of serial numbers of sentence, from which the sentence is derived.
Each input sentence gets a unique serial number, though the creation time may be not unique. The derived sentences inherits serial numbers from its parents, cut at the baseLength limit.
Definition at line 39 of file Stamp.java.
Constructor & Destructor Documentation
Stamp() [1/4]
nars.entity.Stamp.Stamp (long time) private
Generate a new stamp, with a new serial number, for a new Task.
Parameters
time Creation time of the stamp
Definition at line 51 of file Stamp.java.
References nars.entity.Stamp.baseLength, nars.entity.Stamp.creationTime, nars.entity.Stamp.getCurrentSerial(), nars.entity.Stamp.getEvidentialBase(), and nars.entity.Stamp.setCurrentSerial().
Referenced by nars.entity.Stamp.clone(), nars.entity.Stamp.createStamp(), nars.entity.Stamp.equals(), and nars.entity.Stamp.make().
{
         setCurrentSerial(getCurrentSerial() + 1);
         baseLength = 1;
         getEvidentialBase().add(0, getCurrentSerial());
         creationTime = time;
     }
Stamp() [2/4]
nars.entity.Stamp.Stamp (Stamp old) private
Generate a new stamp identical with a given one.
Parameters
old The stamp to be cloned
Definition at line 64 of file Stamp.java.
References nars.entity.Stamp.baseLength, nars.entity.Stamp.creationTime, nars.entity.Stamp.getBase(), nars.entity.Stamp.getBaseLength(), nars.entity.Stamp.getCreationTime(), and nars.entity.Stamp.setEvidentialBase().
{
         baseLength = old.getBaseLength();
         setEvidentialBase(old.getBase());
         creationTime = old.getCreationTime();
     }
Stamp() [3/4]
nars.entity.Stamp.Stamp (Stamp old, long time) private
Generate a new stamp from an existing one, with the same evidentialBase but different creation time.
For single-premise rules
Parameters
old The stamp of the single premise
time The current time
Definition at line 78 of file Stamp.java.
References nars.entity.Stamp.baseLength, nars.entity.Stamp.creationTime, nars.entity.Stamp.getBase(), nars.entity.Stamp.getBaseLength(), and nars.entity.Stamp.setEvidentialBase().
{
         baseLength = old.getBaseLength();
         setEvidentialBase(old.getBase());
         creationTime = time;
     }
Stamp() [4/4]
nars.entity.Stamp.Stamp (Stamp first, Stamp second, long time) private
Generate a new stamp for derived sentence by merging the two from parents the first one is no shorter than the second.
Parameters
first The first Stamp
second The second Stamp
Definition at line 91 of file Stamp.java.
References nars.entity.Stamp.baseLength, nars.entity.Stamp.creationTime, nars.entity.Stamp.get(), nars.entity.Stamp.getBaseLength(), nars.entity.Stamp.getEvidentialBase(), and nars.storage.Parameters.MAXIMUM_STAMP_LENGTH.
{
         int i1, i2, j;
         i1 = i2 = j = 0;
         baseLength = Math.min(first.getBaseLength() + second.getBaseLength(), Parameters.MAXIMUM_STAMP_LENGTH);
         getEvidentialBase().clear();
         while (i2 < second.getBaseLength() && j < getBaseLength()) {
             getEvidentialBase().add( first.get(i1));
             i1++;
             j++;
             getEvidentialBase().add( second.get(i2));
             i2++;
             j++;
         }
         while (i1 < first.getBaseLength() && j < getBaseLength()) {
             getEvidentialBase().add(first.get(i1));
             i1++;
             j++;
         }
         creationTime = time;
     }
Member Function Documentation
clone()
Object nars.entity.Stamp.clone ()
Clone a stamp.
Returns
The cloned stamp
Definition at line 175 of file Stamp.java.
References nars.entity.Stamp.Stamp().
{
         return new Stamp(this);
     }
createStamp() [1/2]
static Stamp nars.entity.Stamp.createStamp (long time) static
Definition at line 148 of file Stamp.java.
References nars.entity.Stamp.Stamp().
Referenced by nars.io.StringParser.parseTask(), and nars.storage.Memory.singlePremiseTask().
{
         return new Stamp(time);
     }
createStamp() [2/2]
static Stamp nars.entity.Stamp.createStamp (Stamp old, long time) static
Definition at line 152 of file Stamp.java.
References nars.entity.Stamp.Stamp().
{
         return new Stamp(old, time);
     }
equals()
boolean nars.entity.Stamp.equals (Object that)
Check if two stamps contains the same content.
Parameters
that The Stamp to be compared
Returns
Whether the two have contain the same elements
Definition at line 218 of file Stamp.java.
References nars.entity.Stamp.Stamp(), and nars.entity.Stamp.toSet().
Referenced by nars.entity.Sentence.equals(), nars.entity.Sentence.equivalentTo(), and nars.entity.Concept.processJudgment().
{
         if (!(that instanceof StampStruct)) {
             return false;
         }
         Collection<Long> set1 = toSet();
         Collection<Long> set2 = ((Stamp) that).toSet();
         return set1.containsAll(set2) && set2.containsAll(set1);
     }
get()
long nars.entity.Stamp.get (int i) package
Get a number from the evidentialBase by index, called in this class only.
Parameters
i The index
Returns
The number at the index
Definition at line 185 of file Stamp.java.
References nars.entity.Stamp.getEvidentialBase().
Referenced by nars.entity.Stamp.make(), and nars.entity.Stamp.Stamp().
                     {
         return getEvidentialBase().get(i);
     }
getBase()
List<Long> nars.entity.Stamp.getBase () private
Get the evidentialBase, called in this class only.
Returns
The evidentialBase of numbers
Definition at line 194 of file Stamp.java.
References nars.entity.Stamp.getEvidentialBase().
Referenced by nars.entity.Stamp.Stamp().
{
         return getEvidentialBase();
     }
getBaseLength()
int nars.entity.Stamp.getBaseLength ()
evidentialBase baseLength
Definition at line 278 of file Stamp.java.
References nars.entity.Stamp.baseLength.
Referenced by nars.entity.Stamp.make(), nars.entity.Stamp.Stamp(), nars.entity.Stamp.toSet(), and nars.entity.Stamp.toString().
{
         return baseLength;
     }
getCreationTime()
long nars.entity.Stamp.getCreationTime ()
creation time of the stamp
Get the creationTime of the truth-value
Returns
The creation time
Definition at line 245 of file Stamp.java.
References nars.entity.Stamp.creationTime.
Referenced by nars.entity.Task.getCreationTime(), nars.entity.Stamp.Stamp(), and nars.entity.Stamp.toString().
{
         return creationTime;
     }
getCurrentSerial()
static long nars.entity.Stamp.getCurrentSerial () static
serial number, for the whole system TODO : should it really be static? or a Stamp be a field in ReasonerBatch ?
Definition at line 161 of file Stamp.java.
References nars.entity.Stamp.currentSerial.
Referenced by nars.entity.Stamp.Stamp().
{
         return currentSerial;
     }
getEvidentialBase()
List<Long> nars.entity.Stamp.getEvidentialBase ()
serial numbers
Definition at line 286 of file Stamp.java.
References nars.entity.Stamp.evidentialBase.
Referenced by nars.entity.Stamp.get(), nars.entity.Stamp.getBase(), nars.entity.Stamp.Stamp(), nars.entity.Stamp.toSet(), and nars.entity.Stamp.toString().
{
         return evidentialBase;
     }
hashCode()
int nars.entity.Stamp.hashCode ()
The hash code of Stamp.
Returns
The hash code
Definition at line 233 of file Stamp.java.
References nars.entity.Stamp.toString().
Referenced by nars.entity.Sentence.hashCode().
{
         return toString().hashCode();
     }
init()
static void nars.entity.Stamp.init () static
Initialize the stamp mechanism of the system, called in Reasoner.
Definition at line 144 of file Stamp.java.
References nars.entity.Stamp.setCurrentSerial().
Referenced by nars.storage.ReasonerBatch.reset().
{
         setCurrentSerial(0);
     }
make()
static Stamp nars.entity.Stamp.make (Stamp first, Stamp second, long time) static
Try to merge two Stamps, return null if have overlap.
By default, the event time of the first stamp is used in the result
Parameters
first The first Stamp
second The second Stamp
time The new creation time
Returns
The merged Stamp, or null
Definition at line 122 of file Stamp.java.
References nars.entity.Stamp.get(), nars.entity.Stamp.getBaseLength(), and nars.entity.Stamp.Stamp().
Referenced by nars.entity.Concept.getBelief(), and nars.entity.Concept.processJudgment().
{
         Stamp r = null;
         e:
         {
             for (int i = 0; i < first.getBaseLength(); i++) {
                 for (int j = 0; j < second.getBaseLength(); j++) {
                     if (first.get(i) == second.get(j)) {
                         break e;
                     }
                 }
             }
             r = first.getBaseLength() > second.getBaseLength() ? new Stamp(first, second, time) : new Stamp(second, first, time);
         }
         return r;
     }
setCreationTime()
void nars.entity.Stamp.setCreationTime (long creationTime)
Definition at line 250 of file Stamp.java.
References nars.entity.Stamp.creationTime.
{
         this.creationTime = creationTime;
     }
setCurrentSerial()
static void nars.entity.Stamp.setCurrentSerial (long currentSerial) static
Definition at line 165 of file Stamp.java.
References nars.entity.Stamp.currentSerial.
Referenced by nars.entity.Stamp.init(), and nars.entity.Stamp.Stamp().
{
         Stamp.currentSerial = currentSerial;
     }
setEvidentialBase()
void nars.entity.Stamp.setEvidentialBase (List< Long > evidentialBase)
Definition at line 290 of file Stamp.java.
References nars.entity.Stamp.evidentialBase.
Referenced by nars.entity.Stamp.Stamp().
{
         this.evidentialBase = evidentialBase;
     }
toSet()
Collection<Long> nars.entity.Stamp.toSet () private
Convert the evidentialBase into a set.
Returns
The TreeSet representation of the evidential base
Definition at line 203 of file Stamp.java.
References nars.entity.Stamp.getBaseLength(), and nars.entity.Stamp.getEvidentialBase().
Referenced by nars.entity.Stamp.equals().
{
         Collection<Long> set = new TreeSet<Long>();
         for (int i = 0; i < getBaseLength(); i++) {
             set.add(getEvidentialBase().get(i));
         }
         return set;
     }
toString()
String nars.entity.Stamp.toString ()
Get a String form of the Stamp for display Format: {creationTime [: eventTime] : evidentialBase}.
Returns
The Stamp as a String
Definition at line 261 of file Stamp.java.
References nars.entity.Stamp.getBaseLength(), nars.entity.Stamp.getCreationTime(), nars.entity.Stamp.getEvidentialBase(), nars.io.Symbols.STAMP_CLOSER, nars.io.Symbols.STAMP_OPENER, nars.io.Symbols.STAMP_SEPARATOR, and nars.io.Symbols.STAMP_STARTER.
Referenced by nars.entity.Stamp.hashCode().
{
         StringBuffer buffer = new StringBuffer(" " + Symbols.STAMP_OPENER + getCreationTime());
         buffer.append(" " + Symbols.STAMP_STARTER + " ");
         for (int i = 0; i < getBaseLength(); i++) {
             buffer.append(Long.toString(getEvidentialBase().get(i)));
             if (i < getBaseLength() - 1) {
                 buffer.append(Symbols.STAMP_SEPARATOR);
             } else {
                 buffer.append(Symbols.STAMP_CLOSER + " ");
             }
         }
         return buffer.toString();
     }
Member Data Documentation
baseLength
final int nars.entity.Stamp.baseLength private
Definition at line 42 of file Stamp.java.
Referenced by nars.entity.Stamp.getBaseLength(), nars.entity.Stamp.LongArrayList.LongArrayList(), and nars.entity.Stamp.Stamp().
creationTime
long nars.entity.Stamp.creationTime private
Definition at line 44 of file Stamp.java.
Referenced by nars.entity.Stamp.getCreationTime(), nars.entity.Stamp.setCreationTime(), and nars.entity.Stamp.Stamp().
currentSerial
long nars.entity.Stamp.currentSerial static private
Definition at line 41 of file Stamp.java.
Referenced by nars.entity.Stamp.getCurrentSerial(), and nars.entity.Stamp.setCurrentSerial().
evidentialBase
List<Long> nars.entity.Stamp.evidentialBase =new CopyOnWriteArrayList<>() private
Definition at line 43 of file Stamp.java.
Referenced by nars.entity.Stamp.getEvidentialBase(), and nars.entity.Stamp.setEvidentialBase().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/entity/Stamp.java