photon: nars.entity.TaskLink Class Reference
nars.entity.TaskLink Class Reference
Reference to a Task.
Public Member Functions
TaskLink (Task t, TermLinkStruct template, BudgetValue v)
Constructor.
Task getTargetTask ()
The Task linked.
boolean novel (TermLink termLink, long currentTime)
To check whether a TaskLink should use a TermLink, return false if they interacted recently.
String toString ()
void setTargetTask (TaskStruct targetTask)
List< String > getRecordedLinks ()
Remember the TermLinks that has been used recently with this TaskLink.
void setRecordedLinks (List< String > recordedLinks)
List< Long > getRecordingTime ()
Remember the time when each TermLink is used with this TaskLink.
void setRecordingTime (List< Long > recordingTime)
int getCounter ()
The number of TermLinks remembered.
void setCounter (int counter)
Public Member Functions inherited from nars.entity.TermLink
TermLink (Term term, short typ, IntStream indices)
Constructor for TermLink template.
TermLink (Term t, TermLink template, BudgetValue v)
Constructor to make actual TermLink from a template.
TermLink (Term t2, short transform, int... j)
Term getTerm ()
The linked Term.
void setTerm (Term term)
The type of link, one of the above.
void setTerm (TermStruct $term$)
int getType ()
Get the link type.
void setType (int type)
Integer getIndex (int i)
Get one index by level.
List< Integer > getIndex ()
The index of the component in the component list of the compound, may have up to 4 levels.
void setIndex (List< Integer > index)
Public Member Functions inherited from nars.entity.Item
String getKey ()
The key of the Item, unique in a Bag.
BudgetValue getBudget ()
The budget of the Item, consisting of 3 numbers.
float getPriority ()
Get priority value.
void setPriority (float v)
Set priority value.
float getDurability ()
Get durability value.
void setDurability (float v)
Set durability value.
float getQuality ()
Get quality value.
void setQuality (float v)
Set quality value.
String toString ()
Return a String representation of the Item.
void setKey (String key)
Private Attributes
int counter
Task targetTask
List< Long > recordingTime
List< String > recordedLinks =new CopyOnWriteArrayList<>()
Additional Inherited Members
Static Public Member Functions inherited from nars.entity.Item
static void incPriority (BudgetValue budget, float v)
Increase priority value.
static void decPriority (BudgetValue budget, float v)
Decrease priority value.
static void incDurability (BudgetValue budget, float v)
Increase durability value.
static void decDurability (BudgetValue budget, float v)
Decrease durability value.
static void merge (BudgetValue budget, Item that)
Merge with another Item with identical key.
static String toStringBrief (BudgetValue budget, String key)
Return a String representation of the Item after simplification.
static String toStringLong (Item item)
Static Public Attributes inherited from nars.entity.TermLink
static final short SELF = 0
At C, point to C; TaskLink only.
static final short COMPONENT = 1
At (&&, A, C), point to C.
static final short COMPOUND = 2
At C, point to (&&, A, C)
static final short COMPONENT_STATEMENT = 3
At <C --> A>, point to C.
static final short COMPOUND_STATEMENT = 4
At C, point to <C --> A>
static final short COMPONENT_CONDITION = 5
At <(&&, C, B) ==> A>, point to C.
static final short COMPOUND_CONDITION = 6
At C, point to <(&&, C, B) ==> A>
static final short TRANSFORM = 8
At C, point to <(*, C, B) --> A>; TaskLink only.
Protected Member Functions inherited from nars.entity.TermLink
TermLink (String s, BudgetValue v)
called from TaskLink
void setKey ()
Set the key of the link.
Protected Member Functions inherited from nars.entity.Item
Item ()
The default constructor.
Item (String key)
Constructor with default budget.
Item (String key, BudgetValue budget)
Constructor with initial budget.
void setBudget (BudgetValue budget)
Constructor with initial budget.
Detailed Description
Reference to a Task.
The reason to separate a Task and a TaskLink is that the same Task can be linked from multiple Concepts, with different BudgetValue.
Definition at line 38 of file TaskLink.java.
Constructor & Destructor Documentation
TaskLink()
nars.entity.TaskLink.TaskLink (Task t, TermLinkStruct template, BudgetValue v)
Constructor.
only called in Memory.continuedProcess
Parameters
t The target Task
template The TermLink template
v The budget
Definition at line 53 of file TaskLink.java.
References nars.entity.TermLink.getIndex(), nars.entity.Item.getKey(), nars.entity.TermLink.getType(), nars.entity.TermLink.SELF, nars.entity.TaskLink.setCounter(), nars.entity.TermLink.setIndex(), nars.entity.TermLink.setKey(), nars.entity.TaskLink.setRecordingTime(), nars.entity.TaskLink.setTargetTask(), and nars.entity.TermLink.setType().
{
         super("", v);
         setTargetTask(t);
         if (template == null) {
             setType(TermLink.SELF);
             setIndex(null);
         } else {
             setType(template.getType());
             setIndex(template.getIndex());
         }
         setRecordingTime(new CopyOnWriteArrayList<>());
         setCounter(0);
         setKey();   // as defined in TermLink
         setKey(getKey() + t.getKey());
     }
Member Function Documentation
getCounter()
int nars.entity.TaskLink.getCounter ()
The number of TermLinks remembered.
Definition at line 151 of file TaskLink.java.
References nars.entity.TaskLink.counter.
Referenced by nars.entity.TaskLink.novel().
{
         return counter;
     }
getRecordedLinks()
List<String> nars.entity.TaskLink.getRecordedLinks ()
Remember the TermLinks that has been used recently with this TaskLink.
Definition at line 129 of file TaskLink.java.
References nars.entity.TaskLink.recordedLinks.
Referenced by nars.entity.TaskLink.novel().
{
         return recordedLinks;
     }
getRecordingTime()
List<Long> nars.entity.TaskLink.getRecordingTime ()
Remember the time when each TermLink is used with this TaskLink.
Definition at line 140 of file TaskLink.java.
References nars.entity.TaskLink.recordingTime.
Referenced by nars.entity.TaskLink.novel().
{
         return recordingTime;
     }
getTargetTask()
Task nars.entity.TaskLink.getTargetTask ()
The Task linked.
The "target" field in TermLink is not used here. Get the target Task
Returns
The linked Task
Definition at line 74 of file TaskLink.java.
References nars.entity.TaskLink.targetTask.
Referenced by nars.entity.Concept.fireFromProcessConcept(), nars.entity.TaskLink.novel(), and nars.entity.TaskLink.toString().
{
         return targetTask;
     }
novel()
boolean nars.entity.TaskLink.novel (TermLink termLink, long currentTime)
To check whether a TaskLink should use a TermLink, return false if they interacted recently.
called in TermLinkBag only
Parameters
termLink The TermLink to be checked
currentTime The current time
Returns
Whether they are novel to each other
Definition at line 88 of file TaskLink.java.
References nars.language.Term.equals(), nars.entity.TaskLink.getCounter(), nars.entity.Item.getKey(), nars.entity.TaskLink.getRecordedLinks(), nars.entity.TaskLink.getRecordingTime(), nars.entity.TaskLink.getTargetTask(), nars.entity.TermLink.getTerm(), nars.entity.TaskLink.setCounter(), and nars.storage.Parameters.TERM_LINK_RECORD_LENGTH.
Referenced by nars.storage.TermLinkBag.takeOut().
{
         Term bTerm = termLink.getTerm();
         if (bTerm.equals(getTargetTask().getSentence().getContent())) {
             return false;
         }
         String linkKey = termLink.getKey();
         int next = 0;
         int i;
         for (i = 0; i < getCounter(); i++) {
             next = i % Parameters.TERM_LINK_RECORD_LENGTH;
             if (linkKey.equals(this.getRecordedLinks().get(next))) {
                 if (currentTime < getRecordingTime().get(next) + Parameters.TERM_LINK_RECORD_LENGTH) {
                     return false;
                 } else {
                     getRecordingTime().set(next, currentTime);
                     return true;
                 }
             }
         }
         next = i % Parameters.TERM_LINK_RECORD_LENGTH;
         getRecordedLinks().add(next, linkKey);       // add knowledge reference to recordedLinks
         getRecordingTime().add(next, currentTime);
         if (getCounter() < Parameters.TERM_LINK_RECORD_LENGTH) { // keep a constant length
             setCounter(getCounter() + 1);
         }
         return true;
     }
setCounter()
void nars.entity.TaskLink.setCounter (int counter)
Definition at line 156 of file TaskLink.java.
References nars.entity.TaskLink.counter.
Referenced by nars.entity.TaskLink.novel(), and nars.entity.TaskLink.TaskLink().
{
         this.counter = counter;
     }
setRecordedLinks()
void nars.entity.TaskLink.setRecordedLinks (List< String > recordedLinks)
Definition at line 134 of file TaskLink.java.
References nars.entity.TaskLink.recordedLinks.
{
         this.recordedLinks = recordedLinks;
     }
setRecordingTime()
void nars.entity.TaskLink.setRecordingTime (List< Long > recordingTime)
Definition at line 145 of file TaskLink.java.
References nars.entity.TaskLink.recordingTime.
Referenced by nars.entity.TaskLink.TaskLink().
{
         this.recordingTime = recordingTime;
     }
setTargetTask()
void nars.entity.TaskLink.setTargetTask (TaskStruct targetTask)
Definition at line 123 of file TaskLink.java.
References nars.entity.TaskLink.targetTask.
Referenced by nars.entity.TaskLink.TaskLink().
{
         this.targetTask = (Task) targetTask;
     }
toString()
String nars.entity.TaskLink.toString ()
Definition at line 118 of file TaskLink.java.
References nars.entity.Task.getSentence(), nars.entity.Sentence.getStamp(), and nars.entity.TaskLink.getTargetTask().
{
         return super.toString() + " " + getTargetTask().getSentence().getStamp();
     }
Member Data Documentation
counter
int nars.entity.TaskLink.counter private
Definition at line 40 of file TaskLink.java.
Referenced by nars.entity.TaskLink.getCounter(), and nars.entity.TaskLink.setCounter().
recordedLinks
List<String> nars.entity.TaskLink.recordedLinks =new CopyOnWriteArrayList<>() private
Definition at line 43 of file TaskLink.java.
Referenced by nars.entity.TaskLink.getRecordedLinks(), and nars.entity.TaskLink.setRecordedLinks().
recordingTime
List<Long> nars.entity.TaskLink.recordingTime private
Definition at line 42 of file TaskLink.java.
Referenced by nars.entity.TaskLink.getRecordingTime(), and nars.entity.TaskLink.setRecordingTime().
targetTask
Task nars.entity.TaskLink.targetTask private
Definition at line 41 of file TaskLink.java.
Referenced by nars.entity.TaskLink.getTargetTask(), and nars.entity.TaskLink.setTargetTask().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/entity/TaskLink.java