photon: nars.language.Similarity Class Reference
nars.language.Similarity Class Reference
A Statement about a Similarity relation.
Public Member Functions
Object clone ()
Clone an object.
String operator ()
Get the operator of the term.
boolean isCommutative ()
Check if the compound is communitative.
Public Member Functions inherited from nars.language.Statement
boolean invalid ()
Check the validity of a potential Statement.
Term getSubject ()
Return the first component of the statement.
Term getPredicate ()
Return the second component of the statement.
Public Member Functions inherited from nars.language.CompoundTerm
abstract String operator ()
Abstract method to get the operator of the compound.
abstract Object clone ()
Abstract clone method.
void setName (String s)
Change the oldName of a CompoundTerm, called after variable substitution.
int getComplexity ()
syntactic complexity of the compound, the sum of those of its components plus 1
boolean isConstant ()
Whether the term names a concept.
void setConstant (boolean isConstant)
Set the constant status.
boolean isCommutative ()
Check if the order of the components matters.
int size ()
get the number of components
Term componentAt (int i)
get a component by index
List< Term > getComponents ()
list of (direct) components
List< Term > cloneComponents ()
Clone the component list.
boolean containComponent (Term t)
Check whether the compound contains a certain component.
boolean containAllComponents (Term t)
Check whether the compound contains all components of another term, or that term as a whole.
boolean containVar ()
Whether this compound term contains any variable term.
void renameVariables ()
Rename the variables in the compound.
void renameVariables (HashMap< Variable, Variable > map)
Rename the variables in the compound.
void applySubstitute (Map< Term, Term > subs)
Recursively apply a substitute to the current CompoundTerm.
List< TermLink > prepareComponentLinks ()
Build TermLink templates to constant components and subcomponents.
void setComponents (List< Term > components)
void setComplexity (short complexity)
Public Member Functions inherited from nars.language.Term
Term (String name)
Constructor with a given name.
String getName ()
Reporting the name of the current Term.
void setName (String $name$)
Object clone ()
Make a new Term with the same name.
boolean equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
int hashCode ()
Produce a hash code for the term.
boolean isConstant ()
Check whether the current Term can name a Concept.
void renameVariables ()
Blank method to be override in CompoundTerm.
int getComplexity ()
The syntactic complexity, for constant automic Term, is 1.
final int compareTo (Term that)
Check the relative order of two Terms.
final String toString ()
The same as getName by default, used in display only.
Static Public Member Functions
static Similarity make (Term subject, Term predicate, Memory memory)
Try to make a new compound from two components.
Static Public Member Functions inherited from nars.language.Statement
static Statement make (String relation, Term subject, Term predicate, Memory memory)
Make a Statement from String, called by StringParser.
static Statement make (Statement statement, Term subj, Term pred, Memory memory)
Make a Statement from given components, called by the rules.
static boolean invalidStatement (Term subject, Term predicate)
Check the validity of a potential Statement.
Static Public Member Functions inherited from nars.language.CompoundTerm
static Term make (CompoundTerm compound, List< Term > components, Memory memory)
Try to make a compound term from a template and a list of components.
static Term make (String op, List< Term > arg, Memory memory)
Try to make a compound term from an operator and a list of components.
static List< Term > cloneList (List< Term > original)
Deep clone an array list of terms.
static Term addComponents (CompoundTerm t1, Term t2, Memory memory)
Try to add a component into a compound.
static Term reduceComponents (CompoundTerm t1, Term t2, Memory memory)
Try to remove a component from a compound.
static Term setComponent (CompoundTerm compound, int index, Term t, Memory memory)
Try to replace a component in a compound at a given index by another one.
Static Public Member Functions inherited from nars.language.Term
static boolean hasOrIsTerm $par (Term root, Term... leaves)
Private Member Functions
Similarity (List< Term > arg)
Constructor with partial values, called by make.
Similarity (String n, List< Term > cs, boolean con, int i)
Constructor with full values, called by clone.
Additional Inherited Members
Protected Member Functions inherited from nars.language.Statement
Statement (List< Term > arg)
Constructor with partial values, called by make.
Statement ()
Default constructor.
Statement (String n, List< Term > cs, boolean con, int i)
Constructor with full values, called by clone.
String makeName ()
Override the default in making the nameStr of the current term from existing fields.
Protected Member Functions inherited from nars.language.CompoundTerm
CompoundTerm (String name, List< Term > components, boolean isConstant, int complexity)
Constructor called from subclasses constructors to clone the fields.
CompoundTerm ()
Default constructor.
CompoundTerm (List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
CompoundTerm (String name, List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
String makeName ()
default method to make the oldName of the current term from existing fields
Protected Member Functions inherited from nars.language.Term
Term ()
Default constructor that build an internal Term.
Static Protected Member Functions inherited from nars.language.Statement
static String makeStatementName (TermStruct subject, String relation, TermStruct predicate)
Default method to make the nameStr of an image term from given fields.
Static Protected Member Functions inherited from nars.language.CompoundTerm
static List< Term > argumentsToList (Term ...t2)
build a component list from two terms
static String makeCompoundName (String op, Iterable< Term > arg)
default method to make the oldName of a compound term from given fields
static String makeSetName (char opener, List< Term > arg, char closer)
make the oldName of an ExtensionSet or IntensionSet
static String makeImageName (String op, List< Term > arg, int relationIndex)
default method to make the oldName of an image term from given fields
Protected Attributes inherited from nars.language.Term
String name
A Term is identified uniquely by its name, a sequence of characters in a given alphabet (ASCII or Unicode)
Static Package Functions inherited from nars.language.CompoundTerm
static void calcComplexity (CompoundTerm compoundTerm)
The complexity of the term is the sum of those of the components plus 1.
Detailed Description
A Statement about a Similarity relation.
Definition at line 32 of file Similarity.java.
Constructor & Destructor Documentation
Similarity() [1/2]
nars.language.Similarity.Similarity (List< Term > arg) private
Constructor with partial values, called by make.
Parameters
arg The component list of the term
Definition at line 38 of file Similarity.java.
Referenced by nars.language.Similarity.clone(), and nars.language.Similarity.make().
{
         super(arg);
     }
Similarity() [2/2]
nars.language.Similarity.Similarity (String n, List< Term > cs, boolean con, int i) private
Constructor with full values, called by clone.
Parameters
n The name of the term
cs Component list
i Syntactic complexity of the compound
Definition at line 48 of file Similarity.java.
{
         super(n, cs, con, i);
     }
Member Function Documentation
clone()
Object nars.language.Similarity.clone ()
Clone an object.
Returns
A new object, to be casted into a Similarity
Definition at line 56 of file Similarity.java.
References nars.language.CompoundTerm.cloneList(), nars.language.CompoundTerm.getComplexity(), nars.language.CompoundTerm.getComponents(), nars.language.CompoundTerm.isConstant(), nars.language.Term.name, and nars.language.Similarity.Similarity().
{
         return new Similarity(name, (ArrayList<Term>) cloneList(getComponents()), isConstant(), getComplexity());
     }
isCommutative()
boolean nars.language.Similarity.isCommutative ()
Check if the compound is communitative.
Returns
true for communitative
Definition at line 97 of file Similarity.java.
{
         return true;
     }
make()
static Similarity nars.language.Similarity.make (Term subject, Term predicate, Memory memory) static
Try to make a new compound from two components.
Called by the inference rules.
Parameters
subject The first compoment
predicate The second compoment
memory Reference to the memeory
Returns
A compound generated or null
Definition at line 67 of file Similarity.java.
References nars.language.CompoundTerm.argumentsToList(), nars.language.Term.compareTo(), nars.language.Statement.invalidStatement(), nars.language.Statement.makeStatementName(), nars.language.Term.name, nars.storage.Memory.nameToListedTerm(), nars.language.Similarity.Similarity(), and nars.io.Symbols.SIMILARITY_RELATION.
Referenced by nars.inference.LocalRules.inferToSym(), nars.language.Statement.make(), nars.inference.RuleTables.makeSym(), and nars.inference.RuleTables.transformSetRelation().
{
         if (!invalidStatement(subject, predicate)) {
             if (subject.compareTo(predicate) <= 0) {
                 String name = makeStatementName(subject, Symbols.SIMILARITY_RELATION, predicate);
                 Term t = Memory.nameToListedTerm(memory, name);
                 if (t == null) {
                     return new Similarity(argumentsToList(subject, predicate));
                 }
                 return (Similarity) t;
             } else {
                 return make(predicate, subject, memory);
             }
         } else {
             return null;
         }
     }
operator()
String nars.language.Similarity.operator ()
Get the operator of the term.
Returns
the operator of the term
Definition at line 88 of file Similarity.java.
References nars.io.Symbols.SIMILARITY_RELATION.
{
         return Symbols.SIMILARITY_RELATION;
     }
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/language/Similarity.java