photon: nars.io.IInferenceRecorder Interface Reference
nars.io.IInferenceRecorder Interface Reference
Public Member Functions
abstract void init ()
Initialize the window and the file.
abstract void show ()
Show the window.
abstract void play ()
Begin the display.
abstract void stop ()
Stop the display.
abstract void append (String s)
Add new text to display.
abstract void openLogFile ()
Open the log file.
abstract void closeLogFile ()
Close the log file.
abstract boolean isLogging ()
Check file logging.
Detailed Description
Definition at line 3 of file IInferenceRecorder.java.
Member Function Documentation
append()
abstract void nars.io.IInferenceRecorder.append (String s) abstract
Add new text to display.
Parameters
s The line to be displayed
Implemented in nars.storage.NullInferenceRecorder.
Referenced by nars.storage.Memory.activatedTask(), nars.storage.Memory.derivedTask(), nars.entity.Concept.fireFromProcessConcept(), nars.entity.Concept.getBelief(), nars.storage.Memory.immediateProcess(), nars.storage.Memory.init(), nars.storage.Memory.inputTask(), nars.storage.Memory.processConcept(), nars.storage.Memory.processNewTask(), and nars.storage.Memory.workCycle().
closeLogFile()
abstract void nars.io.IInferenceRecorder.closeLogFile () abstract
Close the log file.
Implemented in nars.storage.NullInferenceRecorder.
init()
abstract void nars.io.IInferenceRecorder.init () abstract
Initialize the window and the file.
Implemented in nars.storage.NullInferenceRecorder.
isLogging()
abstract boolean nars.io.IInferenceRecorder.isLogging () abstract
Check file logging.
Returns
If the file logging is going on
Implemented in nars.storage.NullInferenceRecorder.
openLogFile()
abstract void nars.io.IInferenceRecorder.openLogFile () abstract
Open the log file.
Implemented in nars.storage.NullInferenceRecorder.
play()
abstract void nars.io.IInferenceRecorder.play () abstract
Begin the display.
Implemented in nars.storage.NullInferenceRecorder.
show()
abstract void nars.io.IInferenceRecorder.show () abstract
Show the window.
Implemented in nars.storage.NullInferenceRecorder.
stop()
abstract void nars.io.IInferenceRecorder.stop () abstract
Stop the display.
Implemented in nars.storage.NullInferenceRecorder.
The documentation for this interface was generated from the following file:
fabric/src/main/java/nars/io/IInferenceRecorder.java