photon: nars.entity.Concept Class Reference
nars.entity.Concept Class Reference
A concept contains information associated with a term, including directly and indirectly related tasks and beliefs.
Classes
class NullEntityObserver
Public Member Functions
Concept (Term tm, Memory memory)
Constructor, called in Memory.getConcept only.
void directProcess (Task task)
Directly process a new task.
float processQuestion (Task task)
To answer a question by existing beliefs.
void insertTaskLink (TaskLink taskLink)
Insert a TaskLink into the TaskLink bag.
void buildTermLinks (BudgetStruct taskBudget)
Recursively build TermLinks between a compound and its components.
void insertTermLink (TermLink termLink)
Insert a TermLink into the TermLink bag.
Term getTerm ()
The term is the unique ID of the concept.
String toString ()
Return a string representation of the concept, called in ConceptBag only.
String toStringLong ()
called from NARSBatch
float getQuality ()
Recalculate the quality of the concept [to be refined to show extension/intension balance].
Collection< TermLink > getTermLinkTemplates ()
Link templates of TermLink, only in concepts with CompoundTerm jmv TODO explain more.
Sentence getBelief (Task task)
Select a isBelief to interact with the given task in inference.
void startPlay (EntityObserver entityObserver, boolean showLinks)
Start displaying contents and links, called from ConceptWindow, TermWindow or Memory.processTask only.
void play ()
Resume display, called from ConceptWindow only.
void stop ()
Stop display, called from ConceptWindow only.
String displayContent ()
Collect direct isBelief, questions, and goals for display.
Memory getMemory ()
Reference to the memory.
void setMemory (Memory memory)
void setTerm (Term term)
TaskLinkBag getTaskLinks ()
Task links for indirect processing.
void setTaskLinks (TaskLinkBag taskLinks)
TermLinkBag getTermLinks ()
Term links between the term and its components and compounds.
void setTermLinks (TermLinkBag termLinks)
void setTermLinkTemplates (List< TermLink > termLinkTemplates)
List< Task > getQuestions ()
Question directly asked about the term.
void setQuestions (List< Task > questions)
List< Sentence > getBeliefs ()
Sentences directly made about the term, with non-future tense.
void setBeliefs (List< Sentence > beliefs)
EntityObserver getEntityObserver ()
The display window.
void setEntityObserver (EntityObserver entityObserver)
Public Member Functions inherited from nars.entity.Item
String getKey ()
The key of the Item, unique in a Bag.
BudgetValue getBudget ()
The budget of the Item, consisting of 3 numbers.
float getPriority ()
Get priority value.
void setPriority (float v)
Set priority value.
float getDurability ()
Get durability value.
void setDurability (float v)
Set durability value.
float getQuality ()
Get quality value.
void setQuality (float v)
Set quality value.
String toString ()
Return a String representation of the Item.
void setKey (String key)
Static Public Member Functions
static BudgetValue distributeAmongLinks (BudgetStruct b, int n)
Distribute the budget of a task among the links to it.
static float rankBelief (SentenceStruct judg)
Determine the rank of a judgment by its confidence and originality (stamp length)
static void fireFromProcessConcept (Memory memory, TaskLinkBag taskLinks, TermLinkBag termLinks)
An atomic step in a concept, only called in Memory# processConcept.
Static Public Member Functions inherited from nars.entity.Item
static void incPriority (BudgetValue budget, float v)
Increase priority value.
static void decPriority (BudgetValue budget, float v)
Decrease priority value.
static void incDurability (BudgetValue budget, float v)
Increase durability value.
static void decDurability (BudgetValue budget, float v)
Decrease durability value.
static void merge (BudgetValue budget, Item that)
Merge with another Item with identical key.
static String toStringBrief (BudgetValue budget, String key)
Return a String representation of the Item after simplification.
static String toStringLong (Item item)
Private Member Functions
void processJudgment (Task task)
To accept a new judgment as isBelief, and check for revisions and solutions.
void linkToTask (Task task)
Link to a new task from all relevant concepts for continued processing in the near future for unspecified time.
Static Private Member Functions
static void addToTable (Sentence newSentence, List< Sentence > table, int capacity)
Add a new belief (or goal) into the table Sort the beliefs/goals by rank, and remove redundant or low rank one.
static Sentence evaluation (SentenceStruct query, Iterable< Sentence > list)
Evaluate a query against beliefs (and desires in the future)
static String toStringIfNotNull (Object item, String title)
Private Attributes
Memory memory
Term term
TaskLinkBag taskLinks
TermLinkBag termLinks
List< TermLink > termLinkTemplates
List< Task > questions
List< Sentence > beliefs
EntityObserver entityObserver = new NullEntityObserver()
Additional Inherited Members
Protected Member Functions inherited from nars.entity.Item
Item ()
The default constructor.
Item (String key)
Constructor with default budget.
Item (String key, BudgetValue budget)
Constructor with initial budget.
void setBudget (BudgetValue budget)
Constructor with initial budget.
Detailed Description
A concept contains information associated with a term, including directly and indirectly related tasks and beliefs.
To make sure the space will be released, the only allowed reference to a concept are those in a ConceptBag. All other access go through the Term that names the concept.
Definition at line 43 of file Concept.java.
Constructor & Destructor Documentation
Concept()
nars.entity.Concept.Concept (Term tm, Memory memory)
Constructor, called in Memory.getConcept only.
Parameters
tm A term corresponding to the concept
memory A reference to the memory
Definition at line 63 of file Concept.java.
References nars.language.Term.getName(), nars.entity.Concept.memory, nars.entity.Concept.setBeliefs(), nars.entity.Concept.setMemory(), nars.entity.Concept.setQuestions(), nars.entity.Concept.setTaskLinks(), nars.entity.Concept.setTerm(), nars.entity.Concept.setTermLinks(), and nars.entity.Concept.setTermLinkTemplates().
{
         super(tm.getName());
         setTerm(tm);
         this.setMemory(memory);
         setQuestions(new ArrayList<Task>());
         setBeliefs(new ArrayList<Sentence>());
         setTaskLinks(new TaskLinkBag(memory));
         setTermLinks(new TermLinkBag(memory));
         if (tm instanceof CompoundTerm) {
             setTermLinkTemplates(((CompoundTerm) tm).prepareComponentLinks());
         }
     }
Member Function Documentation
addToTable()
static void nars.entity.Concept.addToTable (Sentence newSentence, List< Sentence > table, int capacity) static private
Add a new belief (or goal) into the table Sort the beliefs/goals by rank, and remove redundant or low rank one.
Parameters
newSentence The judgment to be processed
table The table to be revised
capacity The capacity of the table
Definition at line 236 of file Concept.java.
References nars.entity.Sentence.equivalentTo(), and nars.entity.Concept.rankBelief().
Referenced by nars.entity.Concept.processJudgment().
{
         float rank1 = rankBelief(newSentence);    // for the new isBelief
         Sentence judgment2;
         float rank2;
         int i;
         for (i = 0; i < table.size(); i++) {
             judgment2 = table.get(i);
             rank2 = rankBelief(judgment2);
             if (rank1 >= rank2) {
                 if (newSentence.equivalentTo(judgment2)) {
                     return;
                 }
                 table.add(i, newSentence);
                 break;
             }
         }
         if (table.size() >= capacity) {
             while (table.size() > capacity) {
                 table.remove(table.size() - 1);
             }
         } else if (i == table.size()) {
             table.add(newSentence);
         }
     }
buildTermLinks()
void nars.entity.Concept.buildTermLinks (BudgetStruct taskBudget)
Recursively build TermLinks between a compound and its components.
called only from Memory.continuedProcess
Parameters
taskBudget The BudgetValue of the task
Definition at line 307 of file Concept.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.entity.Concept.buildTermLinks(), nars.entity.Concept.distributeAmongLinks(), nars.storage.Memory.getConcept(), nars.entity.Concept.getMemory(), nars.entity.Concept.getTerm(), nars.entity.Concept.getTermLinkTemplates(), nars.entity.Concept.insertTermLink(), and nars.entity.TermLink.TRANSFORM.
Referenced by nars.entity.Concept.buildTermLinks(), and nars.entity.Concept.linkToTask().
{
         Term t;
         Concept concept;
         TermLink termLink1, termLink2;
         if (getTermLinkTemplates().size() > 0) {
             BudgetValue subBudget = distributeAmongLinks(taskBudget, getTermLinkTemplates().size());
             if (subBudget.aboveThreshold()) {
                 for (TermLink template : getTermLinkTemplates()) {
                     if (template.getType() != TermLink.TRANSFORM) {
                         t = template.getTerm();
                         concept = Memory.getConcept(getMemory(), t);
                         if (concept != null) {
                             termLink1 = new TermLink(t, template, subBudget);
                             insertTermLink(termLink1);   // this termLink to that
                             termLink2 = new TermLink(getTerm(), template, subBudget);
                             concept.insertTermLink(termLink2);   // that termLink to this
                             if (t instanceof CompoundTerm) {
                                 concept.buildTermLinks(subBudget);
                             }
                         }
                     }
                 }
             }
         }
     }
directProcess()
void nars.entity.Concept.directProcess (Task task)
Directly process a new task.
Called exactly once on each task. Using local information and finishing in a constant time. Provide feedback in the taskBudget value of the task.
called in Memory.immediateProcess only
Parameters
task The task to be processed
Definition at line 115 of file Concept.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.entity.Concept.displayContent(), nars.entity.Item.getBudget(), nars.entity.Concept.getEntityObserver(), nars.entity.Task.getSentence(), nars.entity.Sentence.isJudgment(), nars.entity.Concept.linkToTask(), nars.entity.Concept.processJudgment(), nars.entity.Concept.processQuestion(), and nars.entity.EntityObserver.refresh().
Referenced by nars.storage.Memory.immediateProcess().
{
         if (task.getSentence().isJudgment()) {
             processJudgment(task);
         } else {
             processQuestion(task);
         }
         if (task.getBudget().aboveThreshold()) {    // still need to be processed
             linkToTask(task);
         }
         getEntityObserver().refresh(displayContent());
     }
displayContent()
String nars.entity.Concept.displayContent ()
Collect direct isBelief, questions, and goals for display.
Returns
String representation of direct content
Definition at line 513 of file Concept.java.
References nars.entity.Concept.getBeliefs(), and nars.entity.Concept.getQuestions().
Referenced by nars.entity.Concept.directProcess(), nars.entity.Concept.play(), and nars.entity.Concept.startPlay().
{
         StringBuilder buffer = new StringBuilder();
         if (getBeliefs().size() > 0) {
             buffer.append("\n  Beliefs:\n");
             for (Sentence s : getBeliefs()) {
                 buffer.append(s).append("\n");
             }
         }
         if (getQuestions().size() > 0) {
             buffer.append("\n  Question:\n");
             for (Task t : getQuestions()) {
                 buffer.append(t).append("\n");
             }
         }
         return buffer.toString();
     }
distributeAmongLinks()
static BudgetValue nars.entity.Concept.distributeAmongLinks (BudgetStruct b, int n) static
Distribute the budget of a task among the links to it.
Parameters
b The original budget
n Number of links
Returns
Budget value for each link
Definition at line 85 of file Concept.java.
Referenced by nars.entity.Concept.buildTermLinks(), and nars.entity.Concept.linkToTask().
{
         float priority = (float) (b.getPriority() / Math.sqrt(n));
         return new BudgetValue(priority, b.getDurability(), b.getQuality());
     }
evaluation()
static Sentence nars.entity.Concept.evaluation (SentenceStruct query, Iterable< Sentence > list) static private
Evaluate a query against beliefs (and desires in the future)
Parameters
query The question to be processed
list The list of beliefs to be used
Returns
The best candidate belief selected
Definition at line 268 of file Concept.java.
References nars.inference.LocalRules.solutionQuality().
Referenced by nars.entity.Concept.processJudgment(), and nars.entity.Concept.processQuestion().
{
         if (list == null) {
             return null;
         }
         float currentBest = 0;
         float beliefQuality;
         Sentence candidate = null;
         for (Sentence judg : list) {
             beliefQuality = LocalRules.solutionQuality(query, judg);
             if (beliefQuality > currentBest) {
                 currentBest = beliefQuality;
                 candidate = judg;
             }
         }
         return candidate;
     }
fireFromProcessConcept()
static void nars.entity.Concept.fireFromProcessConcept (Memory memory, TaskLinkBag taskLinks, TermLinkBag termLinks) static
An atomic step in a concept, only called in Memory# processConcept.
Parameters
memory
taskLinks
termLinks
Definition at line 446 of file Concept.java.
References nars.io.IInferenceRecorder.append(), nars.storage.Memory.getRecorder(), nars.entity.TaskLink.getTargetTask(), nars.storage.Memory.getTime(), nars.entity.TermLink.getType(), nars.storage.Parameters.MAX_REASONED_TERM_LINK, nars.entity.Concept.memory, nars.storage.Memory.noResult(), nars.storage.Bag< Type extends Item >.putBack(), nars.inference.RuleTables.reason(), nars.storage.Memory.setCurrentBeliefLink(), nars.storage.Memory.setCurrentTask(), nars.storage.Memory.setCurrentTaskLink(), nars.storage.TermLinkBag.takeOut(), nars.storage.Bag< Type extends Item >.takeOut(), nars.entity.Concept.taskLinks, nars.entity.Concept.termLinks, nars.entity.TermLink.TRANSFORM, and nars.inference.RuleTables.transformTask().
Referenced by nars.storage.Memory.processConcept().
{
         TaskLink currentTaskLink = taskLinks.takeOut();
         if (currentTaskLink != null) {
             memory.setCurrentTaskLink(currentTaskLink);
             memory.setCurrentBeliefLink(null);
             memory.getRecorder().append(" * Selected TaskLink: " + currentTaskLink + "\n");
             Task task = currentTaskLink.getTargetTask();
             memory.setCurrentTask(task);  // one of the two places where this variable is set
             if (currentTaskLink.getType() == TermLink.TRANSFORM) {
                 RuleTables.transformTask(currentTaskLink, memory);  // to turn this into structural inference as below?
             }
             int termLinkCount = Parameters.MAX_REASONED_TERM_LINK;
             while (Memory.noResult(memory) && (termLinkCount > 0)) {
                 TermLink termLink = termLinks.takeOut(currentTaskLink, Memory.getTime(memory));
                 if (termLink != null) {
                     memory.getRecorder().append(" * Selected TermLink: " + termLink + "\n");
                     memory.setCurrentBeliefLink(termLink);
                     RuleTables.reason(currentTaskLink, termLink, memory);
                     termLinks.putBack(termLink);
                     termLinkCount--;
                 } else {
                     termLinkCount = 0;
                 }
             }
             taskLinks.putBack(currentTaskLink);
         }
     }
getBelief()
Sentence nars.entity.Concept.getBelief (Task task)
Select a isBelief to interact with the given task in inference.
get the first qualified one
only called in RuleTables.reason
Parameters
task The selected task
Returns
The selected isBelief
Definition at line 424 of file Concept.java.
References nars.io.IInferenceRecorder.append(), nars.entity.Sentence.clone(), nars.entity.Concept.getBeliefs(), nars.entity.Concept.getMemory(), nars.storage.Memory.getNewStamp(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), nars.entity.Sentence.getStamp(), nars.storage.Memory.getTime(), nars.entity.Stamp.make(), and nars.storage.Memory.setNewStamp().
Referenced by nars.inference.RuleTables.reason().
{
         Sentence taskSentence = task.getSentence();
         Sentence r = null;
         for (Sentence belief1 : getBeliefs()) {
             getMemory().getRecorder().append(" * Selected Belief: " + belief1 + "\n");
             getMemory().setNewStamp(Stamp.make((Stamp) taskSentence.getStamp(), belief1.getStamp(), Memory.getTime(getMemory())));
             if (getMemory().getNewStamp() != null) {
                 r = (Sentence) belief1.clone();
                 break;
             }
         }
         return r;
     }
getBeliefs()
List<Sentence> nars.entity.Concept.getBeliefs ()
Sentences directly made about the term, with non-future tense.
Definition at line 585 of file Concept.java.
References nars.entity.Concept.beliefs.
Referenced by nars.entity.Concept.displayContent(), nars.entity.Concept.getBelief(), nars.entity.Concept.processJudgment(), and nars.entity.Concept.processQuestion().
{
         return beliefs;
     }
getEntityObserver()
EntityObserver nars.entity.Concept.getEntityObserver ()
The display window.
Definition at line 596 of file Concept.java.
References nars.entity.Concept.entityObserver.
Referenced by nars.entity.Concept.directProcess(), nars.entity.Concept.play(), and nars.entity.Concept.stop().
{
         return entityObserver;
     }
getMemory()
Memory nars.entity.Concept.getMemory ()
Reference to the memory.
Definition at line 533 of file Concept.java.
References nars.entity.Concept.memory.
Referenced by nars.entity.Concept.buildTermLinks(), nars.entity.Concept.getBelief(), nars.entity.Concept.insertTaskLink(), nars.entity.Concept.linkToTask(), nars.storage.Memory.processConcept(), nars.entity.Concept.processJudgment(), and nars.entity.Concept.processQuestion().
{
         return memory;
     }
getQuality()
float nars.entity.Concept.getQuality ()
Recalculate the quality of the concept [to be refined to show extension/intension balance].
Returns
The quality value
Definition at line 396 of file Concept.java.
References nars.storage.Bag< Type extends Item >.averagePriority(), nars.language.Term.getComplexity(), nars.entity.Concept.getTerm(), nars.entity.Concept.getTermLinks(), and nars.inference.UtilityFunctions.or().
Referenced by nars.inference.BudgetFunctions.activate().
{
         float linkPriority = getTermLinks().averagePriority();
         float termComplexityFactor = 1.0f / getTerm().getComplexity();
         return UtilityFunctions.or(linkPriority, termComplexityFactor);
     }
getQuestions()
List<Task> nars.entity.Concept.getQuestions ()
Question directly asked about the term.
Definition at line 574 of file Concept.java.
References nars.entity.Concept.questions.
Referenced by nars.entity.Concept.displayContent(), nars.entity.Concept.processJudgment(), nars.entity.Concept.processQuestion(), and nars.entity.Concept.toStringLong().
{
         return questions;
     }
getTaskLinks()
TaskLinkBag nars.entity.Concept.getTaskLinks ()
Task links for indirect processing.
Definition at line 548 of file Concept.java.
References nars.entity.Concept.taskLinks.
Referenced by nars.entity.Concept.insertTaskLink(), nars.storage.Memory.processConcept(), nars.entity.Concept.startPlay(), and nars.entity.Concept.toStringLong().
{
         return taskLinks;
     }
getTerm()
Term nars.entity.Concept.getTerm ()
The term is the unique ID of the concept.
Return the associated term, called from Memory only
Returns
The associated term
Definition at line 353 of file Concept.java.
References nars.entity.Concept.term.
Referenced by nars.entity.Concept.buildTermLinks(), nars.entity.Concept.getQuality(), nars.entity.Concept.linkToTask(), nars.storage.Memory.nameToListedTerm(), nars.storage.Memory.processConcept(), and nars.entity.Concept.startPlay().
{
         return term;
     }
getTermLinks()
TermLinkBag nars.entity.Concept.getTermLinks ()
Term links between the term and its components and compounds.
Definition at line 559 of file Concept.java.
References nars.entity.Concept.termLinks.
Referenced by nars.entity.Concept.getQuality(), nars.entity.Concept.insertTermLink(), nars.storage.Memory.processConcept(), nars.entity.Concept.startPlay(), and nars.entity.Concept.toStringLong().
{
         return termLinks;
     }
getTermLinkTemplates()
Collection<TermLink> nars.entity.Concept.getTermLinkTemplates ()
Link templates of TermLink, only in concepts with CompoundTerm jmv TODO explain more.
Return the templates for TermLinks, only called in Memory.continuedProcess
Returns
The template get
Definition at line 410 of file Concept.java.
References nars.entity.Concept.termLinkTemplates.
Referenced by nars.entity.Concept.buildTermLinks(), and nars.entity.Concept.linkToTask().
{
         return termLinkTemplates;
     }
insertTaskLink()
void nars.entity.Concept.insertTaskLink (TaskLink taskLink)
Insert a TaskLink into the TaskLink bag.
called only from Memory.continuedProcess
Parameters
taskLink The termLink to be inserted
Definition at line 294 of file Concept.java.
References nars.storage.Memory.activateConcept(), nars.entity.Item.getBudget(), nars.entity.Concept.getMemory(), nars.entity.Concept.getTaskLinks(), and nars.storage.Bag< Type extends Item >.putIn().
Referenced by nars.entity.Concept.linkToTask().
{
         BudgetValue taskBudget = taskLink.getBudget();
         getTaskLinks().putIn(taskLink);
         Memory.activateConcept(getMemory(), this, taskBudget);
     }
insertTermLink()
void nars.entity.Concept.insertTermLink (TermLink termLink)
Insert a TermLink into the TermLink bag.
called from buildTermLinks only
Parameters
termLink The termLink to be inserted
Definition at line 340 of file Concept.java.
References nars.entity.Concept.getTermLinks(), and nars.storage.Bag< Type extends Item >.putIn().
Referenced by nars.entity.Concept.buildTermLinks().
{
         getTermLinks().putIn(termLink);
     }
linkToTask()
void nars.entity.Concept.linkToTask (Task task) private
Link to a new task from all relevant concepts for continued processing in the near future for unspecified time.
The only method that calls the TaskLink constructor.
Parameters
task The task to be linked
Definition at line 202 of file Concept.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.entity.Concept.buildTermLinks(), nars.entity.Concept.distributeAmongLinks(), nars.entity.Item.getBudget(), nars.storage.Memory.getConcept(), nars.entity.Concept.getMemory(), nars.entity.Concept.getTerm(), nars.entity.Concept.getTermLinkTemplates(), and nars.entity.Concept.insertTaskLink().
Referenced by nars.entity.Concept.directProcess().
{
         BudgetValue taskBudget = task.getBudget();
         TaskLink taskLink = new TaskLink(task, null, taskBudget);   // link type: SELF
         insertTaskLink(taskLink);
         if (getTerm() instanceof CompoundTerm) {
             if (getTermLinkTemplates().size() > 0) {
                 BudgetValue subBudget = distributeAmongLinks(taskBudget, getTermLinkTemplates().size());
                 if (subBudget.aboveThreshold()) {
                     Term componentTerm;
                     Concept componentConcept;
                     for (TermLink termLink : getTermLinkTemplates()) {
 //                        if (!(task.isStructural() && (termLink.getType() == TermLink.TRANSFORM))) { // avoid circular transform
                         taskLink = new TaskLink(task, termLink, subBudget);
                         componentTerm = termLink.getTerm();
                         componentConcept = Memory.getConcept(getMemory(), componentTerm);
                         if (componentConcept != null) {
                             componentConcept.insertTaskLink(taskLink);
                         }
 //                        }
                     }
                     buildTermLinks(taskBudget);  // recursively insert TermLink
                 }
             }
         }
     }
play()
void nars.entity.Concept.play ()
Resume display, called from ConceptWindow only.
Definition at line 497 of file Concept.java.
References nars.entity.Concept.displayContent(), nars.entity.Concept.getEntityObserver(), and nars.entity.EntityObserver.post().
{
         getEntityObserver().post(displayContent());
     }
processJudgment()
void nars.entity.Concept.processJudgment (Task task) private
To accept a new judgment as isBelief, and check for revisions and solutions.
Parameters
task The task to be processed
Returns
Whether to continue the processing of the task
Definition at line 133 of file Concept.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.entity.Concept.addToTable(), nars.entity.BudgetValue.decPriority(), nars.entity.Stamp.equals(), nars.entity.Concept.evaluation(), nars.entity.Concept.getBeliefs(), nars.entity.Item.getBudget(), nars.entity.Concept.getMemory(), nars.storage.Memory.getNewStamp(), nars.entity.Concept.getQuestions(), nars.entity.Task.getSentence(), nars.entity.Sentence.getStamp(), nars.storage.Memory.getTime(), nars.entity.Stamp.make(), nars.storage.Parameters.MAXIMUM_BELIEF_LENGTH, nars.inference.LocalRules.revisible(), nars.inference.LocalRules.revision(), nars.storage.Memory.setCurrentBelief(), nars.storage.Memory.setNewStamp(), and nars.inference.LocalRules.trySolution().
Referenced by nars.entity.Concept.directProcess().
{
         Sentence judg = task.getSentence();
         Sentence oldBelief = evaluation(judg, getBeliefs());
         if (oldBelief != null) {
             Stamp newStamp = judg.getStamp(), oldStamp = oldBelief.getStamp();
             if (newStamp.equals(oldStamp)) {
                 task.getBudget().decPriority(0);    // duplicated task
                 return;
             } else if (LocalRules.revisible(judg, oldBelief)) {
                 getMemory().setNewStamp(Stamp.make(newStamp, oldStamp, Memory.getTime(getMemory())));
                 if (getMemory().getNewStamp() != null) {
                     getMemory().setCurrentBelief(oldBelief);
                     LocalRules.revision(judg, oldBelief, false, getMemory());
                 }
             }
         }
         if (task.getBudget().aboveThreshold()) {
             for (Task ques : getQuestions()) {
 //                LocalRules.trySolution(ques.getSentence(), judg, ques, memory);
                 LocalRules.trySolution(judg, ques, getMemory());
             }
             addToTable(judg, getBeliefs(), Parameters.MAXIMUM_BELIEF_LENGTH);
         }
     }
processQuestion()
float nars.entity.Concept.processQuestion (Task task)
To answer a question by existing beliefs.
Parameters
task The task to be processed
Returns
Whether to continue the processing of the task
Definition at line 164 of file Concept.java.
References nars.language.Term.equals(), nars.entity.Concept.evaluation(), nars.entity.Concept.getBeliefs(), nars.entity.Sentence.getContent(), nars.entity.TruthValue.getExpectation(), nars.entity.Concept.getMemory(), nars.entity.Concept.getQuestions(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.storage.Parameters.MAXIMUM_QUESTIONS_LENGTH, and nars.inference.LocalRules.trySolution().
Referenced by nars.entity.Concept.directProcess().
{
         Sentence ques = task.getSentence();
         boolean newQuestion = true;
         if (getQuestions() != null) {
             for (Task t : getQuestions()) {
                 Sentence q = t.getSentence();
                 if (q.getContent().equals(ques.getContent())) {
                     ques = q;
                     newQuestion = false;
                     break;
                 }
             }
             if (newQuestion) {
                 getQuestions().add(task);
             }
             if (getQuestions().size() > Parameters.MAXIMUM_QUESTIONS_LENGTH) {
                 getQuestions().remove(0);    // FIFO
             }
             Sentence newAnswer = evaluation(ques, getBeliefs());
             if (newAnswer != null) {
 //            LocalRules.trySolution(ques, newAnswer, task, memory);
                 LocalRules.trySolution(newAnswer, task, getMemory());
                 return newAnswer.getTruth().getExpectation();
             } else {
                 return 0.5f;
             }
         }
         throw new Error("this state was not reachable from previous code");
     }
rankBelief()
static float nars.entity.Concept.rankBelief (SentenceStruct judg) static
Determine the rank of a judgment by its confidence and originality (stamp length)
Parameters
judg The judgment to be ranked
Returns
The rank of the judgment, according to truth value only
Definition at line 98 of file Concept.java.
References nars.inference.UtilityFunctions.or().
Referenced by nars.entity.Concept.addToTable().
{
         float confidence = judg.getTruth().getConfidence();
         float originality = 1.0f / (judg.getStamp().getEvidentialBase().size() + 1);
         return UtilityFunctions.or(confidence, originality);
     }
setBeliefs()
void nars.entity.Concept.setBeliefs (List< Sentence > beliefs)
Definition at line 589 of file Concept.java.
References nars.entity.Concept.beliefs.
Referenced by nars.entity.Concept.Concept().
{
         this.beliefs = beliefs;
     }
setEntityObserver()
void nars.entity.Concept.setEntityObserver (EntityObserver entityObserver)
Definition at line 600 of file Concept.java.
References nars.entity.Concept.entityObserver.
Referenced by nars.entity.Concept.startPlay().
{
         this.entityObserver = entityObserver;
     }
setMemory()
void nars.entity.Concept.setMemory (Memory memory)
Definition at line 537 of file Concept.java.
References nars.entity.Concept.memory.
Referenced by nars.entity.Concept.Concept().
{
         this.memory = memory;
     }
setQuestions()
void nars.entity.Concept.setQuestions (List< Task > questions)
Definition at line 578 of file Concept.java.
References nars.entity.Concept.questions.
Referenced by nars.entity.Concept.Concept().
{
         this.questions = questions;
     }
setTaskLinks()
void nars.entity.Concept.setTaskLinks (TaskLinkBag taskLinks)
Definition at line 552 of file Concept.java.
References nars.entity.Concept.taskLinks.
Referenced by nars.entity.Concept.Concept().
{
         this.taskLinks = taskLinks;
     }
setTerm()
void nars.entity.Concept.setTerm (Term term)
Definition at line 541 of file Concept.java.
References nars.entity.Concept.term.
Referenced by nars.entity.Concept.Concept().
{
         this.term = term;
     }
setTermLinks()
void nars.entity.Concept.setTermLinks (TermLinkBag termLinks)
Definition at line 563 of file Concept.java.
References nars.entity.Concept.termLinks.
Referenced by nars.entity.Concept.Concept().
{
         this.termLinks = termLinks;
     }
setTermLinkTemplates()
void nars.entity.Concept.setTermLinkTemplates (List< TermLink > termLinkTemplates)
Definition at line 567 of file Concept.java.
References nars.entity.Concept.termLinkTemplates.
Referenced by nars.entity.Concept.Concept().
{
         this.termLinkTemplates = termLinkTemplates;
     }
startPlay()
void nars.entity.Concept.startPlay (EntityObserver entityObserver, boolean showLinks)
Start displaying contents and links, called from ConceptWindow, TermWindow or Memory.processTask only.
Parameters
entityObserver TODO make it a real observer pattern (i.e. with a plurality of observers)
showLinks Whether to display the task links
Definition at line 484 of file Concept.java.
References nars.storage.Bag< Type extends Item >.addBagObserver(), nars.entity.EntityObserver.createBagObserver(), nars.entity.Concept.displayContent(), nars.entity.Concept.entityObserver, nars.entity.Concept.getTaskLinks(), nars.entity.Concept.getTerm(), nars.entity.Concept.getTermLinks(), nars.entity.EntityObserver.post(), nars.entity.Concept.setEntityObserver(), and nars.entity.EntityObserver.startPlay().
{
         this.setEntityObserver(entityObserver);
         entityObserver.startPlay(this, showLinks);
         entityObserver.post(displayContent());
         if (showLinks) {
             getTaskLinks().addBagObserver(entityObserver.createBagObserver(), "Task Links in " + getTerm());
             getTermLinks().addBagObserver(entityObserver.createBagObserver(), "Term Links in " + getTerm());
         }
     }
stop()
void nars.entity.Concept.stop ()
Stop display, called from ConceptWindow only.
Definition at line 504 of file Concept.java.
References nars.entity.Concept.getEntityObserver(), and nars.entity.EntityObserver.stop().
{
         getEntityObserver().stop();
     }
toString()
String nars.entity.Concept.toString ()
Return a string representation of the concept, called in ConceptBag only.
Returns
The concept name, with taskBudget in the full version
Definition at line 363 of file Concept.java.
References nars.entity.Item.getBudget(), nars.entity.Item.getKey(), and nars.storage.NARSBatch.isStandAlone().
                              {  // called from concept bag
         if (NARSBatch.isStandAlone()) {
             return (super.toStringBrief(getBudget(), getKey()) + " " + getKey());
         } else {
             return getKey();
         }
     }
toStringIfNotNull()
static String nars.entity.Concept.toStringIfNotNull (Object item, String title) static private
Definition at line 386 of file Concept.java.
Referenced by nars.entity.Concept.toStringLong().
{
         return item == null ? "" : "\n " + title + ":" + item.toString();
     }
toStringLong()
String nars.entity.Concept.toStringLong ()
called from NARSBatch
Definition at line 374 of file Concept.java.
References nars.entity.Item.getBudget(), nars.entity.Item.getKey(), nars.entity.Concept.getQuestions(), nars.entity.Concept.getTaskLinks(), nars.entity.Concept.getTermLinks(), nars.entity.Item.toStringBrief(), and nars.entity.Concept.toStringIfNotNull().
{
         String res = toStringBrief(getBudget(), getKey()) + " " + getKey()
                 + toStringIfNotNull(getTermLinks(), "termLinks")
                 + toStringIfNotNull(getTaskLinks(), "taskLinks");
         res += toStringIfNotNull(null, "questions");
         for (Task t : getQuestions()) {
             res += t.toString();
         }
         // TODO other details?
         return res;
     }
Member Data Documentation
beliefs
List<Sentence> nars.entity.Concept.beliefs private
Definition at line 51 of file Concept.java.
Referenced by nars.entity.Concept.getBeliefs(), and nars.entity.Concept.setBeliefs().
entityObserver
EntityObserver nars.entity.Concept.entityObserver = new NullEntityObserver() private
Definition at line 52 of file Concept.java.
Referenced by nars.entity.Concept.getEntityObserver(), nars.entity.Concept.setEntityObserver(), and nars.entity.Concept.startPlay().
memory
Memory nars.entity.Concept.memory private
Definition at line 45 of file Concept.java.
Referenced by nars.entity.Concept.Concept(), nars.entity.Concept.fireFromProcessConcept(), nars.entity.Concept.getMemory(), and nars.entity.Concept.setMemory().
questions
List<Task> nars.entity.Concept.questions private
Definition at line 50 of file Concept.java.
Referenced by nars.entity.Concept.getQuestions(), and nars.entity.Concept.setQuestions().
taskLinks
TaskLinkBag nars.entity.Concept.taskLinks private
Definition at line 47 of file Concept.java.
Referenced by nars.entity.Concept.fireFromProcessConcept(), nars.entity.Concept.getTaskLinks(), and nars.entity.Concept.setTaskLinks().
term
Term nars.entity.Concept.term private
Definition at line 46 of file Concept.java.
Referenced by nars.entity.Concept.getTerm(), and nars.entity.Concept.setTerm().
termLinks
TermLinkBag nars.entity.Concept.termLinks private
Definition at line 48 of file Concept.java.
Referenced by nars.entity.Concept.fireFromProcessConcept(), nars.entity.Concept.getTermLinks(), and nars.entity.Concept.setTermLinks().
termLinkTemplates
List<TermLink> nars.entity.Concept.termLinkTemplates private
Definition at line 49 of file Concept.java.
Referenced by nars.entity.Concept.getTermLinkTemplates(), and nars.entity.Concept.setTermLinkTemplates().
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/entity/Concept.java