photon: nars.language.CompoundTerm Class Reference
nars.language.CompoundTerm Class Reference abstract
A CompoundTerm is a Term with internal (syntactic) structure.
Public Member Functions
abstract String operator ()
Abstract method to get the operator of the compound.
abstract Object clone ()
Abstract clone method.
void setName (String s)
Change the oldName of a CompoundTerm, called after variable substitution.
int getComplexity ()
syntactic complexity of the compound, the sum of those of its components plus 1
boolean isConstant ()
Whether the term names a concept.
void setConstant (boolean isConstant)
Set the constant status.
boolean isCommutative ()
Check if the order of the components matters.
int size ()
get the number of components
Term componentAt (int i)
get a component by index
List< Term > getComponents ()
list of (direct) components
List< Term > cloneComponents ()
Clone the component list.
boolean containComponent (Term t)
Check whether the compound contains a certain component.
boolean containAllComponents (Term t)
Check whether the compound contains all components of another term, or that term as a whole.
boolean containVar ()
Whether this compound term contains any variable term.
void renameVariables ()
Rename the variables in the compound.
void renameVariables (HashMap< Variable, Variable > map)
Rename the variables in the compound.
void applySubstitute (Map< Term, Term > subs)
Recursively apply a substitute to the current CompoundTerm.
List< TermLink > prepareComponentLinks ()
Build TermLink templates to constant components and subcomponents.
void setComponents (List< Term > components)
void setComplexity (short complexity)
Public Member Functions inherited from nars.language.Term
Term (String name)
Constructor with a given name.
String getName ()
Reporting the name of the current Term.
void setName (String $name$)
Object clone ()
Make a new Term with the same name.
boolean equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
int hashCode ()
Produce a hash code for the term.
boolean isConstant ()
Check whether the current Term can name a Concept.
void renameVariables ()
Blank method to be override in CompoundTerm.
int getComplexity ()
The syntactic complexity, for constant automic Term, is 1.
final int compareTo (Term that)
Check the relative order of two Terms.
final String toString ()
The same as getName by default, used in display only.
Static Public Member Functions
static Term make (CompoundTerm compound, List< Term > components, Memory memory)
Try to make a compound term from a template and a list of components.
static Term make (String op, List< Term > arg, Memory memory)
Try to make a compound term from an operator and a list of components.
static List< Term > cloneList (List< Term > original)
Deep clone an array list of terms.
static Term addComponents (CompoundTerm t1, Term t2, Memory memory)
Try to add a component into a compound.
static Term reduceComponents (CompoundTerm t1, Term t2, Memory memory)
Try to remove a component from a compound.
static Term setComponent (CompoundTerm compound, int index, Term t, Memory memory)
Try to replace a component in a compound at a given index by another one.
Static Public Member Functions inherited from nars.language.Term
static boolean hasOrIsTerm $par (Term root, Term... leaves)
Protected Member Functions
CompoundTerm (String name, List< Term > components, boolean isConstant, int complexity)
Constructor called from subclasses constructors to clone the fields.
CompoundTerm ()
Default constructor.
CompoundTerm (List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
CompoundTerm (String name, List< Term > components)
Constructor called from subclasses constructors to initialize the fields.
String makeName ()
default method to make the oldName of the current term from existing fields
Protected Member Functions inherited from nars.language.Term
Term ()
Default constructor that build an internal Term.
Static Protected Member Functions
static List< Term > argumentsToList (Term ...t2)
build a component list from two terms
static String makeCompoundName (String op, Iterable< Term > arg)
default method to make the oldName of a compound term from given fields
static String makeSetName (char opener, List< Term > arg, char closer)
make the oldName of an ExtensionSet or IntensionSet
static String makeImageName (String op, List< Term > arg, int relationIndex)
default method to make the oldName of an image term from given fields
Static Package Functions
static void calcComplexity (CompoundTerm compoundTerm)
The complexity of the term is the sum of those of the components plus 1.
Private Member Functions
void prepareComponentLinks (ArrayList< TermLink > componentLinks, short type, CompoundTerm term)
Collect TermLink templates into a list, go down one level except in special cases.
Private Attributes
List< Term > components
int complexity
boolean isConstant = true
Additional Inherited Members
Protected Attributes inherited from nars.language.Term
String name
A Term is identified uniquely by its name, a sequence of characters in a given alphabet (ASCII or Unicode)
Detailed Description
A CompoundTerm is a Term with internal (syntactic) structure.
A CompoundTerm consists of a term operator with one or more component Terms.
This abstract class contains default methods for all CompoundTerms.
Definition at line 37 of file CompoundTerm.java.
Constructor & Destructor Documentation
CompoundTerm() [1/4]
nars.language.CompoundTerm.CompoundTerm (String name, List< Term > components, boolean isConstant, int complexity) protected
Constructor called from subclasses constructors to clone the fields.
Parameters
name Name
components Component list
isConstant Whether the term refers to a concept
complexity Complexity of the compound term
Definition at line 66 of file CompoundTerm.java.
References nars.language.CompoundTerm.complexity, nars.language.CompoundTerm.components, nars.language.CompoundTerm.isConstant(), and nars.language.Term.name.
{
         super(name);
         this.components = components;
         this.isConstant = isConstant;
         this.complexity = complexity;
     }
CompoundTerm() [2/4]
nars.language.CompoundTerm.CompoundTerm () protected
Default constructor.
Definition at line 76 of file CompoundTerm.java.
Referenced by nars.language.CompoundTerm.applySubstitute(), nars.language.Statement.invalidStatement(), nars.language.IntersectionInt.make(), nars.language.IntersectionExt.make(), nars.language.CompoundTerm.makeCompoundName(), nars.language.CompoundTerm.prepareComponentLinks(), nars.language.CompoundTerm.renameVariables(), and nars.language.CompoundTerm.setComponent().
{
     }
CompoundTerm() [3/4]
nars.language.CompoundTerm.CompoundTerm (List< Term > components) protected
Constructor called from subclasses constructors to initialize the fields.
Parameters
components Component list
Definition at line 83 of file CompoundTerm.java.
References nars.language.CompoundTerm.calcComplexity(), nars.language.CompoundTerm.components, nars.language.Variable.containVar(), nars.language.CompoundTerm.isConstant(), nars.language.CompoundTerm.makeName(), and nars.language.Term.name.
{
         this.components = components;
         calcComplexity(this);
         name = makeName();
         isConstant = !Variable.containVar(name);
     }
CompoundTerm() [4/4]
nars.language.CompoundTerm.CompoundTerm (String name, List< Term > components) protected
Constructor called from subclasses constructors to initialize the fields.
Parameters
name Name of the compound
components Component list
Definition at line 95 of file CompoundTerm.java.
References nars.language.CompoundTerm.calcComplexity(), nars.language.CompoundTerm.components, nars.language.Variable.containVar(), nars.language.CompoundTerm.isConstant(), and nars.language.Term.name.
{
         super(name);
         isConstant = !Variable.containVar(name);
         this.components = components;
         calcComplexity(this);
     }
Member Function Documentation
addComponents()
static Term nars.language.CompoundTerm.addComponents (CompoundTerm t1, Term t2, Memory memory) static
Try to add a component into a compound.
Parameters
t1 The compound
t2 The component
memory Reference to the memory
Returns
The new compound
Definition at line 395 of file CompoundTerm.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.getComponents(), and nars.language.CompoundTerm.make().
{
         if (null == t2) {
             return t1;
         }
         boolean success;
         List<Term> list = t1.cloneComponents();
         if (t1.getClass() == t2.getClass()) {
             success = list.addAll(((CompoundTerm) t2).getComponents());
         } else {
             success = list.add(t2);
         }
         return (success ? make(t1, list, memory) : null);
     }
applySubstitute()
void nars.language.CompoundTerm.applySubstitute (Map< Term, Term > subs)
Recursively apply a substitute to the current CompoundTerm.
Parameters
subs
Definition at line 506 of file CompoundTerm.java.
References nars.language.Term.clone(), nars.language.CompoundTerm.componentAt(), nars.language.CompoundTerm.components, nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.isCommutative(), nars.language.CompoundTerm.makeName(), nars.language.Term.name, and nars.language.CompoundTerm.size().
Referenced by nars.inference.CompositionalRules.introVarInner().
{
         Term t1, t2;
         for (int i = 0; i < size(); i++) {
             t1 = componentAt(i);
 //            if (t1 instanceof Variable) {
             t2 = subs.get(t1);
             if (null != t2) {
                 components.set(i, (Term) t2.clone());
 //                }
             } else if (t1 instanceof CompoundTerm) {
                 ((CompoundTerm) t1).applySubstitute(subs);
             }
         }
         if (this.isCommutative()) {         // re-order
             TreeSet<Term> s = new TreeSet<Term>(components);
             components = new ArrayList<>(s);
         }
         name = makeName();
     }
argumentsToList()
static List<Term> nars.language.CompoundTerm.argumentsToList (Term ... t2) static protected
build a component list from two terms
Parameters
t1 the first component
t2 the second component
Returns
the component list
Definition at line 198 of file CompoundTerm.java.
Referenced by nars.language.Inheritance.make(), nars.language.Similarity.make(), and nars.language.SetExt.make().
{
         return new CopyOnWriteArrayList<>(t2);
      }
calcComplexity()
static void nars.language.CompoundTerm.calcComplexity (CompoundTerm compoundTerm) static package
The complexity of the term is the sum of those of the components plus 1.
Parameters
compoundTerm
Definition at line 114 of file CompoundTerm.java.
References nars.language.CompoundTerm.complexity, nars.language.CompoundTerm.components, and nars.language.Term.getComplexity().
Referenced by nars.language.CompoundTerm.CompoundTerm().
{
         compoundTerm.complexity = 1;
         for (Term t : compoundTerm.components) {
             compoundTerm.complexity += t.getComplexity();
         }
     }
clone()
abstract Object nars.language.CompoundTerm.clone () abstract
Abstract clone method.
Returns
A clone of the compound term
Referenced by nars.language.CompoundTerm.cloneList().
cloneComponents()
List<Term> nars.language.CompoundTerm.cloneComponents ()
Clone the component list.
Returns
The cloned component list
Definition at line 346 of file CompoundTerm.java.
References nars.language.CompoundTerm.cloneList(), and nars.language.CompoundTerm.components.
Referenced by nars.language.CompoundTerm.addComponents(), nars.language.IntersectionExt.make(), nars.language.IntersectionInt.make(), nars.language.Product.make(), nars.language.ImageExt.make(), nars.language.ImageInt.make(), nars.language.CompoundTerm.reduceComponents(), nars.language.CompoundTerm.setComponent(), nars.inference.StructuralRules.structuralCompose2(), and nars.inference.StructuralRules.transformProductImage().
{
         return cloneList(components);
     }
cloneList()
static List<Term> nars.language.CompoundTerm.cloneList (List< Term > original) static
Deep clone an array list of terms.
Parameters
original The original component list
Returns
an identical and separate copy of the list
Definition at line 355 of file CompoundTerm.java.
References nars.language.CompoundTerm.clone().
Referenced by nars.language.SetInt.clone(), nars.language.Inheritance.clone(), nars.language.Similarity.clone(), nars.language.Product.clone(), nars.language.Negation.clone(), nars.language.SetExt.clone(), nars.language.ImageInt.clone(), nars.language.ImageExt.clone(), nars.language.CompoundTerm.cloneComponents(), nars.language.IntersectionExt.doCLone(), and nars.language.IntersectionInt.doCLone().
{
         if (null == original) {
             return null;
         }
         List<Term> arr = new ArrayList<Term>(original.size());
         for (int i = 0; i < original.size(); i++) {
             arr.add((Term) ((Term) original.get(i)).clone());
         }
         return arr;
     }
componentAt()
Term nars.language.CompoundTerm.componentAt (int i)
get a component by index
Parameters
i index of the component
Returns
the component
Definition at line 330 of file CompoundTerm.java.
References nars.language.CompoundTerm.components.
Referenced by nars.language.CompoundTerm.applySubstitute(), nars.inference.CompositionalRules.composeCompound(), nars.inference.RuleTables.compoundAndSelf(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.RuleTables.conditionalDedIndWithVar(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.detachmentWithVar(), nars.language.ImageExt.make(), nars.language.ImageInt.make(), nars.language.CompoundTerm.prepareComponentLinks(), nars.language.CompoundTerm.renameVariables(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.StructuralRules.transformProductImage(), nars.inference.StructuralRules.transformSubjectPI(), and nars.inference.RuleTables.transformTask().
{
         return components.get(i);
     }
containAllComponents()
boolean nars.language.CompoundTerm.containAllComponents (Term t)
Check whether the compound contains all components of another term, or that term as a whole.
Parameters
t The other term
Returns
Whether the components are all in the compound
Definition at line 380 of file CompoundTerm.java.
References nars.language.CompoundTerm.components, and nars.language.CompoundTerm.getComponents().
{
         if (getClass() == t.getClass()) {
             return components.containsAll(((CompoundTerm) t).getComponents());
         } else {
             return components.contains(t);
         }
     }
containComponent()
boolean nars.language.CompoundTerm.containComponent (Term t)
Check whether the compound contains a certain component.
Parameters
t The component to be checked
Returns
Whether the component is in the compound
Definition at line 371 of file CompoundTerm.java.
References nars.language.CompoundTerm.components.
Referenced by nars.inference.RuleTables.compoundAndSelf(), and nars.inference.CompositionalRules.introVarInner().
{
         return components.contains(t);
     }
containVar()
boolean nars.language.CompoundTerm.containVar ()
Whether this compound term contains any variable term.
Returns
Whether the name contains a variable
Definition at line 456 of file CompoundTerm.java.
References nars.language.Variable.containVar(), and nars.language.Term.name.
Referenced by nars.language.CompoundTerm.renameVariables().
{
         return Variable.containVar(name);
     }
getComplexity()
int nars.language.CompoundTerm.getComplexity ()
syntactic complexity of the compound, the sum of those of its components plus 1
report the term's syntactic complexity
Returns
the complexity value
Definition at line 283 of file CompoundTerm.java.
References nars.language.CompoundTerm.complexity.
Referenced by nars.language.SetInt.clone(), nars.language.Inheritance.clone(), nars.language.Similarity.clone(), nars.language.Negation.clone(), nars.language.Product.clone(), nars.language.SetExt.clone(), nars.language.ImageInt.clone(), nars.language.ImageExt.clone(), nars.language.IntersectionInt.doCLone(), and nars.language.IntersectionExt.doCLone().
{
         return complexity;
     }
getComponents()
List<Term> nars.language.CompoundTerm.getComponents ()
list of (direct) components
Get the component list
Returns
The component list
Definition at line 338 of file CompoundTerm.java.
References nars.language.CompoundTerm.components.
Referenced by nars.language.CompoundTerm.addComponents(), nars.language.SetInt.clone(), nars.language.Similarity.clone(), nars.language.Inheritance.clone(), nars.language.Product.clone(), nars.language.Negation.clone(), nars.language.SetExt.clone(), nars.language.ImageInt.clone(), nars.language.ImageExt.clone(), nars.language.CompoundTerm.containAllComponents(), nars.language.IntersectionExt.doCLone(), nars.language.IntersectionInt.doCLone(), nars.language.Statement.getPredicate(), nars.language.ImageInt.getRelation(), nars.language.ImageExt.getRelation(), nars.language.Statement.getSubject(), nars.language.ImageInt.getTheOtherComponent(), nars.language.ImageExt.getTheOtherComponent(), nars.language.SetInt.makeName(), nars.language.ImageInt.makeName(), nars.language.ImageExt.makeName(), and nars.language.CompoundTerm.reduceComponents().
{
         return components;
     }
isCommutative()
boolean nars.language.CompoundTerm.isCommutative ()
Check if the order of the components matters.
commutative CompoundTerms: Sets, Intersections Commutative Statements: Similarity, Equivalence (except the one with a temporal order) Commutative CompoundStatements: Disjunction, Conjunction (except the one with a temporal order)
Returns
The default value is false
Definition at line 312 of file CompoundTerm.java.
Referenced by nars.inference.SyllogisticRules.analogy(), and nars.language.CompoundTerm.applySubstitute().
{
         return false;
     }
isConstant()
boolean nars.language.CompoundTerm.isConstant ()
Whether the term names a concept.
check if the term contains free variable
Returns
if the term is a constant
Definition at line 292 of file CompoundTerm.java.
Referenced by nars.language.SetInt.clone(), nars.language.Inheritance.clone(), nars.language.Similarity.clone(), nars.language.Product.clone(), nars.language.Negation.clone(), nars.language.SetExt.clone(), nars.language.ImageInt.clone(), nars.language.ImageExt.clone(), nars.language.CompoundTerm.CompoundTerm(), nars.language.IntersectionExt.doCLone(), nars.language.IntersectionInt.doCLone(), and nars.language.CompoundTerm.setConstant().
{
         return isConstant;
     }
make() [1/2]
static Term nars.language.CompoundTerm.make (CompoundTerm compound, List< Term > components, Memory memory) static
Try to make a compound term from a template and a list of components.
Parameters
compound The template
components The components
memory Reference to the memory
Returns
A compound term or null
Definition at line 129 of file CompoundTerm.java.
References nars.language.CompoundTerm.components, nars.language.ImageExt.make(), nars.language.ImageInt.make(), and nars.language.CompoundTerm.operator().
Referenced by nars.language.CompoundTerm.addComponents(), nars.inference.CompositionalRules.introVarInner(), nars.io.StringParser.parseCompoundTerm(), nars.language.CompoundTerm.reduceComponents(), nars.language.CompoundTerm.setComponent(), nars.inference.StructuralRules.structuralCompose2(), and nars.inference.StructuralRules.transformProductImage().
{
         if (compound instanceof ImageExt) {
             return ImageExt.make(components, ((ImageExt) compound).getRelationIndex(), memory);
         } else if (compound instanceof ImageInt) {
             return ImageInt.make(components, ((ImageInt) compound).getRelationIndex(), memory);
         } else {
             return make(compound.operator(), components, memory);
         }
     }
make() [2/2]
static Term nars.language.CompoundTerm.make (String op, List< Term > arg, Memory memory) static
Try to make a compound term from an operator and a list of components.
Called from StringParser
Parameters
op Term operator
arg Component list
memory Reference to the memory
Returns
A compound term or null
Definition at line 148 of file CompoundTerm.java.
References nars.io.Symbols.CONJUNCTION_OPERATOR, nars.io.Symbols.DIFFERENCE_EXT_OPERATOR, nars.io.Symbols.DIFFERENCE_INT_OPERATOR, nars.io.Symbols.DISJUNCTION_OPERATOR, nars.io.Symbols.IMAGE_EXT_OPERATOR, nars.io.Symbols.IMAGE_INT_OPERATOR, nars.io.Symbols.INTERSECTION_EXT_OPERATOR, nars.io.Symbols.INTERSECTION_INT_OPERATOR, nars.language.SetInt.make(), nars.language.Negation.make(), nars.language.Product.make(), nars.language.SetExt.make(), nars.language.IntersectionInt.make(), nars.language.IntersectionExt.make(), nars.language.ImageExt.make(), nars.language.ImageInt.make(), nars.io.Symbols.NEGATION_OPERATOR, nars.io.Symbols.PRODUCT_OPERATOR, nars.io.Symbols.SET_EXT_OPENER, and nars.io.Symbols.SET_INT_OPENER.
{
         if (1 == op.length()) {
             if (Symbols.SET_EXT_OPENER == op.charAt(0)) {
                 return SetExt.make(arg, memory);
             }
             if (Symbols.SET_INT_OPENER == op.charAt(0)) {
                 return SetInt.make(arg, memory);
             }
             if (op.equals(Symbols.INTERSECTION_EXT_OPERATOR)) {
                 return IntersectionExt.make(arg, memory);
             }
             if (op.equals(Symbols.INTERSECTION_INT_OPERATOR)) {
                 return IntersectionInt.make(arg, memory);
             }
             if (op.equals(Symbols.DIFFERENCE_EXT_OPERATOR)) {
                 return DifferenceExt.Companion.make(arg, memory);
             }
             if (op.equals(Symbols.DIFFERENCE_INT_OPERATOR)) {
                 return DifferenceInt.Companion.make(arg, memory);
             }
             if (op.equals(Symbols.PRODUCT_OPERATOR)) {
                 return Product.make(arg, memory);
             }
             if (op.equals(Symbols.IMAGE_EXT_OPERATOR)) {
                 return ImageExt.make(arg, memory);
             }
             if (op.equals(Symbols.IMAGE_INT_OPERATOR)) {
                 return ImageInt.make(arg, memory);
             }
         }
         if (2 == op.length()) {
             if (op.equals(Symbols.NEGATION_OPERATOR)) {
                 return Negation.make(arg, memory);
             }
             if (op.equals(Symbols.DISJUNCTION_OPERATOR)) {
                 return Disjunction.Companion.make(arg, memory);
             }
             if (op.equals(Symbols.CONJUNCTION_OPERATOR)) {
                 return Conjunction.Companion.make(arg, memory);
             }
         }
         return null;
     }
makeCompoundName()
static String nars.language.CompoundTerm.makeCompoundName (String op, Iterable< Term > arg) static protected
default method to make the oldName of a compound term from given fields
Parameters
op the term operator
arg the list of components
Returns
the oldName of the term
Definition at line 218 of file CompoundTerm.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, nars.io.Symbols.COMPOUND_TERM_CLOSER, nars.io.Symbols.COMPOUND_TERM_OPENER, nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.makeName(), and nars.language.Term.name.
Referenced by nars.language.Product.make(), nars.language.Negation.make(), nars.language.IntersectionExt.make(), nars.language.IntersectionInt.make(), and nars.language.CompoundTerm.makeName().
{
         StringBuffer name = new StringBuffer();
         name.append(Symbols.COMPOUND_TERM_OPENER);
         name.append(op);
         for (Term t : arg) {
             name.append(Symbols.ARGUMENT_SEPARATOR);
             if (t instanceof CompoundTerm) {
                 ((CompoundTerm) t).setName(((CompoundTerm) t).makeName());
             }
             name.append(t.getName());
         }
         name.append(Symbols.COMPOUND_TERM_CLOSER);
         return name.toString();
     }
makeImageName()
static String nars.language.CompoundTerm.makeImageName (String op, List< Term > arg, int relationIndex) static protected
default method to make the oldName of an image term from given fields
Parameters
op the term operator
arg the list of components
relationIndex the location of the place holder
Returns
the oldName of the term
Definition at line 259 of file CompoundTerm.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, nars.io.Symbols.COMPOUND_TERM_CLOSER, nars.io.Symbols.COMPOUND_TERM_OPENER, nars.io.Symbols.IMAGE_PLACE_HOLDER, and nars.language.Term.name.
Referenced by nars.language.ImageInt.make(), nars.language.ImageExt.make(), nars.language.ImageInt.makeName(), and nars.language.ImageExt.makeName().
{
         StringBuffer name = new StringBuffer();
         name.append(Symbols.COMPOUND_TERM_OPENER);
         name.append(op);
         name.append(Symbols.ARGUMENT_SEPARATOR);
         name.append(arg.get(relationIndex).getName());
         for (int i = 0; i < arg.size(); i++) {
             name.append(Symbols.ARGUMENT_SEPARATOR);
             if (i == relationIndex) {
                 name.append(Symbols.IMAGE_PLACE_HOLDER);
             } else {
                 name.append(arg.get(i).getName());
             }
         }
         name.append(Symbols.COMPOUND_TERM_CLOSER);
         return name.toString();
     }
makeName()
String nars.language.CompoundTerm.makeName () protected
default method to make the oldName of the current term from existing fields
Returns
the oldName of the term
Definition at line 208 of file CompoundTerm.java.
References nars.language.CompoundTerm.components, and nars.language.CompoundTerm.makeCompoundName().
Referenced by nars.language.CompoundTerm.applySubstitute(), nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.makeCompoundName(), and nars.language.CompoundTerm.renameVariables().
{
         return makeCompoundName(operator(), components);
     }
makeSetName()
static String nars.language.CompoundTerm.makeSetName (char opener, List< Term > arg, char closer) static protected
make the oldName of an ExtensionSet or IntensionSet
Parameters
opener the set opener
closer the set closer
arg the list of components
Returns
the oldName of the term
Definition at line 240 of file CompoundTerm.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, and nars.language.Term.name.
Referenced by nars.language.SetInt.make(), nars.language.SetExt.make(), nars.language.SetInt.makeName(), and nars.language.SetExt.makeName().
{
         StringBuffer name = new StringBuffer();
         name.append(opener);
         name.append(arg.get(0).getName());
         for (int i = 1; i < arg.size(); i++) {
             name.append(Symbols.ARGUMENT_SEPARATOR);
             name.append(arg.get(i).getName());
         }
         name.append(closer);
         return name.toString();
     }
operator()
abstract String nars.language.CompoundTerm.operator () abstract
Abstract method to get the operator of the compound.
Returns
The operator in a String
Referenced by nars.language.CompoundTerm.make().
prepareComponentLinks() [1/2]
List<TermLink> nars.language.CompoundTerm.prepareComponentLinks ()
Build TermLink templates to constant components and subcomponents.
The compound type determines the link type; the component type determines whether to build the link.
Returns
A list of TermLink templates
Definition at line 533 of file CompoundTerm.java.
References nars.entity.TermLink.COMPOUND, and nars.entity.TermLink.COMPOUND_STATEMENT.
{
         ArrayList<TermLink> componentLinks = new ArrayList<TermLink>();
         short type = (this instanceof Statement) ? TermLink.COMPOUND_STATEMENT : TermLink.COMPOUND;   // default
         prepareComponentLinks(componentLinks, type, this);
         return componentLinks;
     }
prepareComponentLinks() [2/2]
void nars.language.CompoundTerm.prepareComponentLinks (ArrayList< TermLink > componentLinks, short type, CompoundTerm term) private
Collect TermLink templates into a list, go down one level except in special cases.
Parameters
componentLinks The list of TermLink templates built so far
type The type of TermLink to be built
term The CompoundTerm for which the links are built
Definition at line 547 of file CompoundTerm.java.
References nars.language.CompoundTerm.componentAt(), nars.entity.TermLink.COMPOUND_CONDITION, nars.language.CompoundTerm.CompoundTerm(), nars.language.Term.isConstant(), nars.language.CompoundTerm.size(), and nars.entity.TermLink.TRANSFORM.
{
         Term t1, t2, t3;                    // components at different levels
         for (int i = 0; i < term.size(); i++) {     // first level components
             t1 = term.componentAt(i);
             if (t1.isConstant()) {
                 componentLinks.add(new TermLink(t1, type, i));
             }
             if ((t1 instanceof Conjunction) && ((this instanceof Equivalence) || ((this instanceof Implication) && (0 == i)))) {
                 ((CompoundTerm) t1).prepareComponentLinks(componentLinks, TermLink.COMPOUND_CONDITION, (CompoundTerm) t1);
             } else if (t1 instanceof CompoundTerm) {
                 for (int j = 0; j < ((CompoundTerm) t1).size(); j++) {  // second level components
                     t2 = ((CompoundTerm) t1).componentAt(j);
                     if (t2.isConstant()) {
                         if ((t1 instanceof Product) || (t1 instanceof ImageExt) || (t1 instanceof ImageInt)) {
                             if (TermLink.COMPOUND_CONDITION == type) {
                                 componentLinks.add(new TermLink(t2, TermLink.TRANSFORM, 0, i, j));
                             } else {
                                 componentLinks.add(new TermLink(t2, TermLink.TRANSFORM, i, j));
                             }
                         } else {
                             componentLinks.add(new TermLink(t2, type, i, j));
                         }
                     }
                     if ((t2 instanceof Product) || (t2 instanceof ImageExt) || (t2 instanceof ImageInt)) {
                         for (int k = 0; k < ((CompoundTerm) t2).size(); k++) {
                             t3 = ((CompoundTerm) t2).componentAt(k);
                             if (t3.isConstant()) {                           // third level
                                 if (TermLink.COMPOUND_CONDITION == type) {
                                     componentLinks.add(new TermLink(t3, TermLink.TRANSFORM, 0, i, j, k));
                                 } else {
                                     componentLinks.add(new TermLink(t3, TermLink.TRANSFORM, i, j, k));
                                 }
                             }
                         }
                     }
                 }
             }
         }
     }
reduceComponents()
static Term nars.language.CompoundTerm.reduceComponents (CompoundTerm t1, Term t2, Memory memory) static
Try to remove a component from a compound.
Parameters
t1 The compound
t2 The component
memory Reference to the memory
Returns
The new compound
Definition at line 416 of file CompoundTerm.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.getComponents(), and nars.language.CompoundTerm.make().
Referenced by nars.inference.RuleTables.conditionalAbd(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.RuleTables.decomposeStatement(), and nars.inference.RuleTables.elimiVarDep().
{
         boolean success;
         List<Term> list = t1.cloneComponents();
         if (t1.getClass() == t2.getClass()) {
             success = list.removeAll(((CompoundTerm) t2).getComponents());
         } else {
             success = list.remove(t2);
         }
         return (success ? make(t1, list, memory) : null);
     }
renameVariables() [1/2]
void nars.language.CompoundTerm.renameVariables ()
Rename the variables in the compound.
Definition at line 464 of file CompoundTerm.java.
References nars.language.CompoundTerm.containVar(), nars.language.CompoundTerm.makeName(), nars.language.CompoundTerm.setConstant(), and nars.language.CompoundTerm.setName().
{
         if (containVar()) {
             renameVariables(new HashMap<Variable, Variable>());
         }
         setConstant(true);
         setName(makeName());
     }
renameVariables() [2/2]
void nars.language.CompoundTerm.renameVariables (HashMap< Variable, Variable > map)
Rename the variables in the compound.
Parameters
map The substitution established so far
Definition at line 476 of file CompoundTerm.java.
References nars.language.CompoundTerm.componentAt(), nars.language.CompoundTerm.components, nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.containVar(), nars.language.Term.equals(), nars.language.Term.getName(), and nars.language.CompoundTerm.makeName().
{
         if (containVar()) {
             for (int i = 0; i < components.size(); i++) {
                 Term term = componentAt(i);
                 if (term instanceof Variable) {
                     Variable var;
                     if (1 == term.getName().length()) { // anonymous variable from input
                         var = new Variable(term.getName().charAt(0) + "" + (map.size() + 1));
                     } else {
                         var = map.get(term);
                         if (null == var) {
                             var = new Variable(term.getName().charAt(0) + "" + (map.size() + 1));
                         }
                     }
                     if (!term.equals(var)) {
                         components.set(i, var);
                     }
                     map.put((Variable) term, var);
                 } else if (term instanceof CompoundTerm) {
                     ((CompoundTerm) term).renameVariables(map);
                     term.setName(((CompoundTerm) term).makeName());
                 }
             }
         }
     }
setComplexity()
void nars.language.CompoundTerm.setComplexity (short complexity)
Definition at line 591 of file CompoundTerm.java.
References nars.language.CompoundTerm.complexity.
{
         this.complexity = complexity;
     }
setComponent()
static Term nars.language.CompoundTerm.setComponent (CompoundTerm compound, int index, Term t, Memory memory) static
Try to replace a component in a compound at a given index by another one.
Parameters
compound The compound
index The location of replacement
t The new component
memory Reference to the memory
Returns
The new compound
Definition at line 435 of file CompoundTerm.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.CompoundTerm(), and nars.language.CompoundTerm.make().
Referenced by nars.inference.RuleTables.conditionalAna(), and nars.inference.RuleTables.conditionalDedInd().
{
         List<Term> list = compound.cloneComponents();
         list.remove(index);
         if (null != t) {
             if (compound.getClass() != t.getClass()) {
                 list.add(index, t);
             } else {
                 List<Term> list2 = ((CompoundTerm) t).cloneComponents();
                 for (int i = 0; i < list2.size(); i++) {
                     list.add(index + i, list2.get(i));
                 }
             }
         }
         return make(compound, list, memory);
     }
setComponents()
void nars.language.CompoundTerm.setComponents (List< Term > components)
Definition at line 587 of file CompoundTerm.java.
References nars.language.CompoundTerm.components.
{
         this.components = components;
     }
setConstant()
void nars.language.CompoundTerm.setConstant (boolean isConstant)
Set the constant status.
Parameters
isConstant
Definition at line 300 of file CompoundTerm.java.
References nars.language.CompoundTerm.isConstant().
Referenced by nars.language.CompoundTerm.renameVariables().
{
         this.isConstant = isConstant;
     }
setName()
void nars.language.CompoundTerm.setName (String s)
Change the oldName of a CompoundTerm, called after variable substitution.
Parameters
s The new oldName
Definition at line 106 of file CompoundTerm.java.
References nars.language.Term.name.
Referenced by nars.language.CompoundTerm.renameVariables().
{
         name = s;
     }
size()
int nars.language.CompoundTerm.size ()
get the number of components
Returns
the size of the component list
Definition at line 321 of file CompoundTerm.java.
References nars.language.CompoundTerm.components.
Referenced by nars.language.CompoundTerm.applySubstitute(), nars.inference.RuleTables.compoundAndCompound(), nars.language.SetExt.make(), nars.language.ImageExt.make(), nars.language.ImageInt.make(), nars.language.IntersectionExt.make(), nars.language.IntersectionInt.make(), nars.language.CompoundTerm.prepareComponentLinks(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.RuleTables.transformSetRelation(), and nars.inference.StructuralRules.transformSubjectPI().
                       {
         return components.size();
     }
Member Data Documentation
complexity
int nars.language.CompoundTerm.complexity private
Definition at line 40 of file CompoundTerm.java.
Referenced by nars.language.CompoundTerm.calcComplexity(), nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.getComplexity(), nars.language.ImageExt.ImageExt(), nars.language.ImageInt.ImageInt(), nars.language.Product.Product(), and nars.language.CompoundTerm.setComplexity().
components
List<Term> nars.language.CompoundTerm.components private
Definition at line 39 of file CompoundTerm.java.
Referenced by nars.language.CompoundTerm.applySubstitute(), nars.language.CompoundTerm.calcComplexity(), nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.componentAt(), nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.containAllComponents(), nars.language.CompoundTerm.containComponent(), nars.language.CompoundTerm.getComponents(), nars.language.CompoundTerm.make(), nars.language.CompoundTerm.makeName(), nars.language.CompoundTerm.renameVariables(), nars.language.CompoundTerm.setComponents(), and nars.language.CompoundTerm.size().
isConstant
boolean nars.language.CompoundTerm.isConstant = true private
Definition at line 41 of file CompoundTerm.java.
The documentation for this class was generated from the following file:
fabric/src/main/java/nars/language/CompoundTerm.java